### ISSUE TITLE
QueueException: queuecmd_count_beans not found in TaskRegistry

### ISSUE THREAD

**Issue by sheeshmohsin** [coleifer/huey#101]
Hey, I am getting this error, while setting up huey. 
http://ur1.ca/mwqkl

Is it really a bug or just its my fault, please guide me
FYI - I am using huey with django.

**Comment by sheeshmohsin** [comment]
It works using --verbosity but i am not able to call the tasks function asynchronously in django. if i call the function it stucks at that and after completion it process further.

**Comment by sheeshmohsin** [comment]
Fixed, changed setting always_eager from true to false

**Comment by sheeshmohsin** [comment]
The same error happening, it seems fixed to me because i setted always_eager to true.

This is the error - http://ur1.ca/mwqkl

**Comment by coleifer** [comment]
Probably an error in the organization of the code or how you're running it. Try the suggestions in http://huey.readthedocs.org/en/latest/troubleshooting.html
