### ISSUE TITLE
Question: How can I determine when an item was put into queue?

### ISSUE THREAD

**Issue by dmr** [coleifer/huey#104]
I'm using huey for periodic tasks and sometime the consumer crashes.
I can live with that but once it is back up my other application already queued up a few "send email notification" tasks. --> The consumer is executing all the tasks and people get angry because they receive the sama email many times.

--> Is there a way to check when the item was put into queue?

Something that would allow me to write something like this:

```
@periodic_task(crontab(minute='*', hour='*'))
def send_notification(put_to_queue_timing):
    if datetime.timedelta(now() - put_to_queue_timing) > 100:
        return
    do_things...()
```

I'm not sure if other queue systems offer something like this. For celery I found a discard_all (http://celery.readthedocs.org/en/latest/reference/celery.app.control.html#celery.app.control.Control.discard_all) but there are tasks that I still need.

My current solution is to go into redis delete all the items I don't like but over the weekend there were a few hundreds stacked...

Thanks,
Daniel

**Comment by coleifer** [comment]
I think the real issue is the consumer crashing... can you provide any info about that?

**Comment by coleifer** [comment]
To somewhat answer your question, there is an `EventEmitter` API which is poorly documented, but can be used to capture various events. You'll need to check the source code and tests for examples, unfortunately.

I'm closing this for now, but please comment if you can provide info on the consumer crashes. That would be extremely helpful for me.

**Comment by dmr** [comment]
I'll post an update here once I can reproduce it but the huey worker is working really well sending thousands of mails and doing search index updates and other things every day and after many months it crashes once, so it's really not that big of a deal, huey is running really well, thanks for building it :)

So after this crash I'll add some more debugging info to hopefully catch the issue next time.

Thanks for the EventEmitter hint, I'll look into that.
