### ISSUE TITLE
race condition in RedisSchedule:

### ISSUE THREAD

**Issue by 72squared** [coleifer/huey#105]
https://github.com/coleifer/huey/blob/ddbe0fe1dc3d9d7a62d923761188893102b4a109/huey/backends/redis_backend.py#L96-L98

Between the read and the write, another process could add to the redis sorted set in that time interval and then the item would disappear. Or another consumer process could read the same set of tasks, and then the tasks might be executed twice.

**Comment by 72squared** [comment]
The only way I can think of to solve it is to use a LUA script to read the values and then remove them if any are found and return them.

**Comment by 72squared** [comment]
in the past I've used a lua script something like this to solve it:

pop_lua = """
local res = redis.call('zrangebyscore', KEYS[1], '-inf', ARGV[1], 'LIMIT', 0, 1)
for i = 1, #res do
    if redis.call('zrem', KEYS[1], res[i]) == 1 then
        return res[i]
    end
end
"""

task = self.conn.eval(pop_lua, 1, self.key, unix_ts)

**Comment by coleifer** [comment]
Alternatively I suppose Huey could use a lock of some sort. Has this come up in practice?

**Comment by 72squared** [comment]
A lock won't work well if you have many consumer processes on different servers using the same redis queue. Besides I prefer non blocking solutions when possible. As for whether it has come up, I think this problem would be very hard to spot.

**Comment by 72squared** [comment]
The nice thing about the Lua script idea is that it is only one network round trip and the operation is pretty much atomic.

**Comment by coleifer** [comment]
Yeah, I agree, the Lua idea is definitely the best option. Do you think you could put together a PR?

**Comment by 72squared** [comment]
Yeah, will do.

**Comment by 72squared** [comment]
patch submitted! #107

**Comment by 72squared** [comment]
patch #107 was accepted. Issue resolved.
