### ISSUE TITLE
Define a task to work on only one worker

### ISSUE THREAD

**Issue by evaldobratti** [coleifer/huey#115]
Is there a way to accomplish this?

I'm defining some tasks and want them to be consumed by only one worker.
For example: I have a worker to check a json api periodically (like every 3s), but if I define it as periodic task, after sometime all available workers will be working on this task.

Today I'm using a simple task, with an "while True:" inside and starting it through a script, but I'm wondering if there is a better way.

Sorry for my bad English and thank you!
Nice job :)

**Comment by coleifer** [comment]
> but if I define it as periodic task, after sometime all available workers will be working on this task.

You need to use some kind of locking. That, to me, seems like the correct approach.
