### ISSUE TITLE
using entry points and a function for huey_consumer.py

### ISSUE THREAD

**Issue by oz123** [coleifer/huey#116]
Hi, 

I was wondering if you will accept a PR for modifying huey_consumer.py a bit. I would like to pack everything in under 
```
if __name__ == '__main__':
    parser = get_option_parser()
    ...
```
In a function called `main()`, this will enable other people to easily reuse this code.  

You can than change the installer also to use the new setuptools mechanism for creating scripts:
```
setup(
 name='huey',
 entry_points='''
        [console_scripts]
        huey_consumer=huey.bin.huey_consumer:main
     '''
)
```

**Comment by coleifer** [comment]
I would definitely accept that PR.

**Comment by coleifer** [comment]
Although I think the `entry_points` would be:

```python
entry_points={
    'console_scripts': ['huey_consumer = huey.bin.huey_consumer:main']
}
```

**Comment by oz123** [comment]
@coleifer thank your for the quick respond! I created the tiny PR. The test suite currently fails 
on both master an my own branch, I hope it's not much of a problem ...
