### ISSUE TITLE
Periodic tasks with periods less than a minute

### ISSUE THREAD

**Issue by wldcordeiro** [coleifer/huey#118]
I'm working on a Django project currently where we need a task queueing system to get info from a separate system to store in our database. We want to get this info every five seconds, but it seems Huey is limited to a minute as its lowest period of time. Would adding this be possible?

**Comment by coleifer** [comment]
See #33. Basically, I don't have plans to modify this.

**Comment by wldcordeiro** [comment]
Is there a technical reason why not? Does the system fail with intervals less than a minute?

**Comment by coleifer** [comment]
Yeah, the way the periodic task runner works I'd be concerned that tasks that are supposed to run every minute would run 60x a minute.

**Comment by coleifer** [comment]
It may be an easy fix, though...

**Comment by wldcordeiro** [comment]
I'm interested in helping add the ability to use seconds, Celery is too heavyweight for my use case and I like your API. I noticed that obviously the crontab function would need changes, but if you could tell me which parts of the library are affected I'll take a look at making a PR

**Comment by wldcordeiro** [comment]
Also if that's the case I'd reopen this issue or #33

**Comment by coleifer** [comment]
@wldcordeiro -- if all of your tasks that run every minute also specify a second, you could simply set the `--periodic-task-interval` (or `-P`) to `1` when running the consumer.

This would ensure that the periodic task scheduler runs every second as opposed to the default of every 60 seconds. The hitch would be crontab tasks that execute at a particular minute. Because the periodic task scheduler will "think" the task is valid for 60 ticks during that given minute, it will be enqueued 60 times. Obviously not correct. The solution is to have all tasks that run on a particular minute also specify a particular second.

**Comment by coleifer** [comment]
I think this can be closed.

**Comment by viperfx** [comment]
@wldcordeiro did you find a solution to your database based scheduling?

**Comment by coleifer** [comment]
Just to update as my comments are not quite correct anymore --

You **can** run tasks at intervals of 1 second. **However**, the `crontab` helper function that is typically used with the `periodic_task` decorator only supports a granularity of a minute, so you'll need to define your own validation function for sub-minute tasks.

**Comment by paunovic** [comment]
I have been trying tonight to make this work, and have come up with something like this:

```
def crontab_seconds(seconds=1):
    def validate_date(timestamp):
        return timestamp.second % seconds == 0

    return validate_date


@huey.periodic_task(crontab_seconds(10))
def search_indexing_task() -> None:
    logger.info(f'Hey!')
```

However, when I run huey worker, it seems that scheduler executes only once per minute, despite it saying this in the logs:

```
*** Scheduler runs every 1 second(s).
```

I may be missing something obvious, any advice on how to make periodic task run every 10 seconds? I am using it to optimize indexing of database changes to ElasticSearch, by having another redis queue which this periodic task would pick up every 10 seconds and reindex necessary rows at once.

**Comment by coleifer** [comment]
Periodic tasks *always* and *only* run once every 60 seconds.

**Comment by coleifer** [comment]
The scheduler may run at arbitrary intervals, which reduces latency when scheduling tasks for execution in the future, but periodic tasks have a maximum frequency of once-per-minute (just like cron).

**Comment by paunovic** [comment]
> You **can** run tasks at intervals of 1 second. **However**, the `crontab` helper function that is typically used with the `periodic_task` decorator only supports a granularity of a minute, so you'll need to define your own validation function for sub-minute tasks.

I'm sorry, but can you clarify this comment then?

**Comment by coleifer** [comment]
The scheduler takes care of tasks that are scheduled to run at some time in the future relative to when the task was dequeued. So you might spawn a task to execute in 61 seconds. If the scheduler only ran once a minute and you were unlucky, you could be waiting 120s for that task to run.

The scheduler also enqueued periodic tasks, but regardless of the scheduler interval, periodic tasks are only enqueued once a minute.

The code in scheduler.loop() is quite clear if you're still confused.

**Comment by coleifer** [comment]
Regarding what you quoted, that is no longer the case.

**Comment by paunovic** [comment]
I don't quite understand reasoning behind this limitation in Huey, since it is often needed to run periodic tasks in sub-minute intervals, and not having such feature is rather bizarre.

**Comment by coleifer** [comment]
Its really a shame that Huey isn't open source and permissively licensed.

**Comment by tanrax** [comment]
My solution to running a task every second is to run the task every minute, and then inside it play with a `sleep`.

```python
from huey.contrib.djhuey import periodic_task, lock_task
import time

@periodic_task(crontab(minute="*"))
@lock_task("send_summary_lock")
def send_summary():
	for second in range(0, 60):
		time.sleep(1)
```
