### ISSUE TITLE
New release of Huey on PyPI?

### ISSUE THREAD

**Issue by antoviaque** [coleifer/huey#119]
Would it be possible to get a new release out & pushed to PyPI? 0.4.8 was released in May, and [there has been a few PRs merged](https://github.com/coleifer/huey/pulls?q=is%3Apr+is%3Aclosed) since then. That would allow me to get rid to the github requirement for silencing the Django 1.8 warning, which is out for a while too now. Thanks!

**Comment by coleifer** [comment]
Released 0.4.9

**Comment by antoviaque** [comment]
@coleifer Thank you! : )
