### ISSUE TITLE
Can't get the return of tasks

### ISSUE THREAD

**Issue by cyanqing** [coleifer/huey#121]
Hi,

I'm having trouble getting the return of tasks when using huey with django.
I can get the return in a few cases, but most often I get nothing.
 
Here are my HUEY settings

        HUEY = {
            'backend': 'huey.backends.redis_backend',  # required.
            'name': 'unique name',
            'connection': {'host': 'localhost', 'port': 6379},
            'always_eager': False,  # Defaults to False when running via manage.py run_huey

            # Options for configuring a result store -- *recommended*
            'result_store': 'huey.backends.redis_backend.RedisDataStore',
            'result_store_name': 'dh-results',
            'result_store_connection': {'host': 'localhost', 'port': 6379},

            # Options to pass into the consumer when running ``manage.py run_huey``
            'consumer_options': {'workers': 4},
        }

Here are my HUEY tasks:

        from huey.djhuey import task
        
        @task()
        def count_beans(number):
            print '-- counted %s beans --' % number
            return 'Counted %s beans' % number

Here are my main.py:

        res = count_beans(9)
        print res
        print res.get()

I use the run_huey to run the consumer and I can see the task's print, but the `res.get()` is none.Could you tell me where the problem is?

Thanks.

**Comment by coleifer** [comment]
It probably depends on how soon after firing your task you are calling `.get()`. You probably need to call `.get(blocking=True)` if you want the call to block until there is a result value.

http://huey.readthedocs.org/en/latest/api.html#AsyncData.get

**Comment by cyanqing** [comment]
Thank you ! It works now.
