### ISSUE TITLE
Revoke all tasks

### ISSUE THREAD

**Issue by camilonova** [coleifer/huey#122]
I can't find how in the docs. There is any way from the command line to revoke all tasks?

**Comment by coleifer** [comment]
Hmm, you could try the queue.flush() method.

**Comment by coleifer** [comment]
And also you'll want to call schedule.flush().

**Comment by camilonova** [comment]
Just for documenting how you should do:

```
from huey.contrib.djhuey import HUEY
HUEY.flush()
```

Thanks.

**Comment by coleifer** [comment]
That actually doesn't revoke tasks, it just removes everything that's currently in Redis. If you enqueue tasks subsequent to the FLUSH, they will get executed.
