### ISSUE TITLE
Restricting task to single worker

### ISSUE THREAD

**Issue by vrakesh** [coleifer/huey#123]
Hi,
  I have a setup where, I am running multiple pexpect scripts using the task queue. When a task is invoked the workers, are  creating two threads( 2 workers) for the same operation. This may lead to some undesired behavior. Is there any way to limit a task to just run on one worker?

**Comment by vrakesh** [comment]
On further investigation , I found that this happens only when using sqlite backend. but redis backend does not create two instances (threads) of the same task. Which is ideal. But while using sqlite backend. Two workers grab the same task and run it.

**Comment by coleifer** [comment]
I think there's a race condition due to improperly implemented locking during the read.

**Comment by coleifer** [comment]
The [snippet](http://flask.pocoo.org/snippets/88/) the implementer of this backend references appears to do the right thing while reading, which is acquire a `RESERVED` lock. I think the author mistook the sqlite3 `isolation_level` parameter for meaning the same thing as explicitly executing `BEGIN IMMEDIATE`.

I'll look into reworking the code.

**Comment by vrakesh** [comment]
@coleifer Thanks looking forward to the patch. All your projects are great :) Learning a lot from them.

**Comment by coleifer** [comment]
I ended up killing off the SQLite backend in the 1.0.0 release of Huey, so this issue is no longer valid.
