### ISSUE TITLE
Question: huey in production

### ISSUE THREAD

**Issue by dmr** [coleifer/huey#124]
Hello everyone,

we are using huey in production for a while now and we love it, thank you @coleifer.

As our services grow the need to monitor what is happening grows so I was wondering if anybody built anything like flower for celery (http://flower.readthedocs.org/en/latest/) for huey?

What are you using to monitor huey, redis cli?

**Comment by coleifer** [comment]
Huey emits events as it processes items (enqueued, scheduled, revoked, task started, task finished, task error, etc. These are poorly documented so perhaps that's a first step?

**Comment by dmr** [comment]
Ok, I'll look into the events next time, thank you :)

I was just curious if anybody is listening here and maybe already did some of the work.
