### ISSUE TITLE
django support document is missing

### ISSUE THREAD

**Issue by lucemia** [coleifer/huey#128]
Will huey continually support django in the future?

I use `huey` a lot for my django project, really appreciate.
Since recently the document of django supported is dropped, is there any roadmap about future huey could be share?

**Comment by coleifer** [comment]
For the moment, you can find them here: http://huey.readthedocs.org/en/0.4.9/

I am doing some rewriting of the consuming APIs for the 1.0 release and so things are a bit in flux right now.
