### ISSUE TITLE
monitor huey

### ISSUE THREAD

**Issue by cresg820** [coleifer/huey#129]
Hi,
how can I monitor status of huey and check what tasks are in queue, what tasks are running, etc?

**Comment by coleifer** [comment]
In `master` there are new methods:

* http://huey.readthedocs.org/en/latest/api.html#Huey.pending
* http://huey.readthedocs.org/en/latest/api.html#Huey.scheduled
* http://huey.readthedocs.org/en/latest/api.html#Huey.all_results
