### ISSUE TITLE
How to do mocking/monkey patching in huey tasks?

### ISSUE THREAD

**Issue by laike9m** [coleifer/huey#134]
I want to test a huey task, and need to patch `requests.get`. 

```python
# huey_tasks.py
@huey.task()
def function():
    import requests
    print(requests.get('http://www.google.com'))
```

```python
import huey_tasks

@patch('requests.get')
def call_patched(fake_get):
    fake_get.return_value = '1'
    huey_tasks.function()
```
Launch huey_consumer: `huey_tasks.huey -w 10 -l logs/huey.log`
Run test, however patching didn't have any effect.
```
[2016-01-24 17:01:12,053] INFO:requests.packages.urllib3.connectionpool:Worker-1:Starting new HTTP connection (1): www.google.com
[2016-01-24 17:01:12,562] INFO:requests.packages.urllib3.connectionpool:Worker-1:Starting new HTTP connection (1): www.google.com.sg
<Response [200]>
```
If I remove the `@huey.task()` decorator, patching works and `1` gets printed.

So how should I test huey tasks? After all, I can't remove the decorator every time, has to be a better way.

**Comment by coleifer** [comment]
Well, the monkey-patch needs to occur in the task instance loaded into RAM by your test. If you're running the consumer in a separate process, the patch needs to be applied there.

**Comment by laike9m** [comment]
@coleifer So what should I do? How to people usually test these code?

**Comment by laike9m** [comment]
OK, finally found a way to test
```
# huey_tasks.py

def _function():
    import requests
    print(requests.get('http://www.google.com'))

function = huey.task()(_function)
```
```
import huey_tasks

@patch('requests.get')
def call_patched(fake_get):
    fake_get.return_value = '1'
    huey_tasks._function()
```
Then directly run test code without launching `huey_consumer`.

**Comment by coleifer** [comment]
You know about always_eager, right? If not check the docs. I think that's
what you are looking for.

**Comment by laike9m** [comment]
I know there's `always_eager`, but you can't test a function which is already decorated with `@task` and monkey patch it at the same time. The above solution is the only way I can think of.

**Comment by jedie** [comment]
I have a similar problem: I try to use https://pypi.org/project/requests-mock/ to mock requests calls. But this doesn't work in huey immediate mode. Think the mock doesn't catch the call.

Work-a-round: I use **call_local()** as described here: https://huey.readthedocs.io/en/latest/guide.html#tips-and-tricks

Any idea to better combine requests-mock with huey in tests?
