### ISSUE TITLE
Run huey task from view

### ISSUE THREAD

**Issue by dmcmulle** [coleifer/huey#137]
Hi.  Really sorry to write here, but I don't know where else to ask for some help.  Someone recommended huey to me on /r/django and it looks to be exactly what I need.

I've installed redis and have setup huey in my project settings file as follows:
```
HUEY = {
    'name': 'my-app',
    'connection': {'host': 'localhost', 'port': 6379},
    'consumer': {'workers': 4, 'worker_type': 'thread'},
}
```

I have added huey.contrib.djhuey to INSTALLED_APPS.

I created an app called 'main' and created a file called 'tasks.py'.  Tasks.py looks like this:

```
from huey.contrib.djhuey import crontab, periodic_task, task
import time

@task()
def long_running_task():
    print 'starting task'
    time.sleep(10)
    print 'ending task'
```

In views.py I have:

```
from django.http import *
import tasks

def add_task(request):
    print 'test1'
    tasks.long_running_task()
    return HttpResponse("Task added")`
```

When I run this, instead of the `tasks.long_running_task()` call in my view sending the task into redis and being run with a consumer, the view simply hangs and waits 10 seconds.  

I'm very sorry for such a poor description of my problem, I'm a junior web developer and this is my first encounter using a message broker/consumer system.  

What am I doing wrong?  Any help is appreciated.  Thanks so much.

**Comment by coleifer** [comment]
If you're running in debug mode, huey by default will assume you want to run tasks "in-process" for easier debugging. Since typically you are not using a separate queue process when developing.

**Comment by coleifer** [comment]
Just update your huey settings dict to have `always_eager=False`.

**Comment by dmcmulle** [comment]
Ah, I'm an idiot.  Thank you my friend!  All is well now :)

**Comment by JoseTomasTocino** [comment]
Is this documented anywhere? I've run into the same problem and was about to open an issue. Looks like the line that provokes this behavior is this one https://github.com/coleifer/huey/blob/master/huey/contrib/djhuey/__init__.py#L79
