### ISSUE TITLE
utc=False and wrong schedule date

### ISSUE THREAD

**Issue by mskrzypek** [coleifer/huey#139]
There is no possibility to properly set `eta` parameter when `utc=False`.

No matter what date I set as an `eta` argument, ie.
```
- 2016-02-24 19:08:42
- 2016-02-24 19:08:42+01:00
- 2016-02-24 19:08:42+00:00
```
I receive below consumer log:
`[2016-02-24 18:53:49,154] Executing queuecmd_announcement_enqueue: 459[...]96b @2016-02-24 18:08:42`

And in the result the command is being executed one hour before the specified time.

**Comment by coleifer** [comment]
Can you provide more information? How are you enqueueing your task? What parameters are you passing to the consumer?

**Comment by mskrzypek** [comment]
I have django project, settings: **USE_TZ=True**, **HUEY['consumer']['utc']=False**
I have model with datefield (value = **2016-02-24 19:23:42+01:00**)
Let's assume the datetime on the server is: **2016-02-24 19:08:42+01:00**

I want to schedule task on date from datefield: **2016-02-24 19:23:42+01:00**

So let's try:
```
dates = [
    mymodel.datefield,
    localtime(mymodel.datefield),
    mymodel.datefield.replace(tzinfo=None),
    mymodel.datefield.replace(tzinfo=utc)
]
for date in dates:
    mytask.schedule(args=(...), eta=date)
```

Result is always like this:

`[2016-02-24 19:08:42,154] Executing queuecmd_mytask: 459[...]96b @2016-02-24 18:23:42`

So the task executes immediatelly, because of one hour shift. How can I schedule task on 19:23 and not 18:23?

**Comment by coleifer** [comment]
So, behind the scenes, huey converts local timestamps into UTC. The `utils.local_to_utc` function does this:

```python
def local_to_utc(dt):
    return datetime.datetime(*time.gmtime(time.mktime(dt.timetuple()))[:6])
```

It may not be correctly accounting for timezones, I'm not really sure as I'm not very familiar with Python's timezone implementation.

**Comment by mskrzypek** [comment]
For all below python datetimes:
```
2016-02-28 17:26:31+01:00
2016-02-28 17:26:31+00:00
2016-02-28 17:26:31
```
`local_to_utc` function returns:

`2016-02-28 16:26:31`

Should this function convert localtime to utc, despite of "utc=False" setting?

**Comment by coleifer** [comment]
OK, so by default, Huey consumer treats date-times as UTC. When you call `task.schedule()` it will automatically convert the timestamp, which it assumes to be localtime, to UTC.

So if you're running your consumer with ``--utc=False``, then when you call `.schedule()` you should pass in `convert_utc=False`:

```python
my_task.schedule(delay=10, convert_utc=False)
```

**Comment by mskrzypek** [comment]
Ok, I haven't noticed it in docs.
When I set this parameter to False, I get this error:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/ms/.virtualenvs/vmf/local/lib/python2.7/site-packages/huey/consumer.py", line 359, in _run
>     consumer_process.loop()
>   File "/home/ms/.virtualenvs/vmf/local/lib/python2.7/site-packages/huey/consumer.py", line 110, in loop
>     self.handle_task(task, now or self.get_now())
>   File "/home/ms/.virtualenvs/vmf/local/lib/python2.7/site-packages/huey/consumer.py", line 123, in handle_task
>     if not self.huey.ready_to_run(task, ts):
>   File "/home/ms/.virtualenvs/vmf/local/lib/python2.7/site-packages/huey/api.py", line 327, in ready_to_run
>     return cmd.execute_time is None or cmd.execute_time <= dt
> TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by coleifer** [comment]
Yeah, peewee compares things to the current time (or current UTC time if the consumer is running without --localtime), and these do not have a timezone.

Where are your timestamps coming from? Is there a way you can convert them to naive before sending them to Peewee?
