### ISSUE TITLE
Serialization error in error handler when task is passed to the job

### ISSUE THREAD

**Issue by deathowl** [coleifer/huey#140]
The following errors appear on pubsub every time a task raises an exception:
Can't pickle <class 'utils.image_helpers.queuecmd_save_thumbnail_task'> attribute lookup queuecmd_save_thumbnail_task on utils.image_helpers failed

I'm about to fix it. Expect the PR later on today.

**Comment by deathowl** [comment]
https://github.com/coleifer/huey/pull/141 This PR Solves this issue.

**Comment by deathowl** [comment]
Hey @coleifer i know it's not nice to ask for releases, but could you release a new version to pip please?

**Comment by coleifer** [comment]
Released 1.1.1
