### ISSUE TITLE
Huey causing trouble in django-admin

### ISSUE THREAD

**Issue by samirotiv** [coleifer/huey#142]
When Huey is running, saving models from Django admin erratically fails. I unfortunately can't paste the actual code here, but I can tell you anything you like about it.

I'm using Django Signals to listen for events like save and save_m2m, and am doing certain operations when they're being saved. When I terminate Huey, it perfectly works, but if I start Huey (python manage.py run_huey), then models refuse to get saved.

I am still using Django's builtin server. Is this the reason for the problem?

**Comment by coleifer** [comment]
I have no clue, but this sounds very much like a configuration issue as opposed to a bug in huey.
