### ISSUE TITLE
Can't configure port - connection refused

### ISSUE THREAD

**Issue by atavory** [coleifer/huey#144]
Hello,

  Many thanks for this package - it's excellent!

  Whenever I try to set the port:

    huey = RedisHuey('foo', host='localhost', port=20000)

I get

    ScheduleReadException: ConnectionError: Error 111 connecting to localhost:20000. Connection refused.

How can this be done?

Many thanks!

**Comment by coleifer** [comment]
This would lead me to believe that redis isn't running on port 20000.
