### ISSUE TITLE
Specifying configuration for the consumer

### ISSUE THREAD

**Issue by hyperknot** [coleifer/huey#145]
In most if not all web-app scenarios, you have different configuration for deployment, production etc. I found no information in the docs about what is the recommended way to pass some additional information to `huey_consumer`.

Is the best idea to come up with a unique command line argument (like `--ini=development.ini`) and try to parse it out of sys.argv?

Unfortunately it doesn't work, as it terminates with:
```
huey_consumer: error: no such option: --ini
```

**Comment by coleifer** [comment]
Huey supports a number of config options for running the consumer:

http://huey.readthedocs.org/en/latest/consumer.html#options-for-the-consumer

Anything else would be beyond the scope of running the consumer, and should be handled by the application. If you have some very specific use-case in mind I can try to respond more specifically.

**Comment by hyperknot** [comment]
But none of those options can pass a parameter to the script. I need to
pass if the config is using development.ini or production.ini.

At the moment, I solved it using using environment variables.

**Comment by coleifer** [comment]
+1 for not reinventing the wheel
