### ISSUE TITLE
db_task with unit tests and/or nested tests

### ISSUE THREAD

**Issue by iivvoo** [coleifer/huey#146]
I understand that the db_task / db_periodic_task make sure the database connection has closed (on Djang0. However, I'm using nested task (calling one task from another) which means the nested task no longer has a usable connection.

Additionally this makes it hard to unit test the task. This could be solved by separating the task and task-logic and only testing the login, but again with nested tasks this becomes hard.

Are there any known solutions to this? How do people deal with nested tasks on django?

**Comment by iivvoo** [comment]
Actually I now realize that nested tasks isn't a problem (except in testing cases) since each task will run isolated with its own connection (at least that's my assumption)

So the only problem that remains is not closing the connection in test setups. Or more specifically in 'always_eager' situations.

Would, in that case,

```

from huey.contrib.djhuey import HUEY

def close_db(fn):
    """Decorator to be used with tasks that may operate on the database."""
    @wraps(fn)
    def inner(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        finally:
            if not HUEY.always_eager:
                connection.close()
    return inner
```

work? It seems to work for me.

**Comment by iivvoo** [comment]
Lastly, periodic tasks are never eager, they're always fired through run_huey which means they *should* close the connection:

```
def close_db(fn, iscron=False):
    """Decorator to be used with tasks that may operate on the database."""
    @wraps(fn)
    def inner(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        finally:
            if not iscron and not HUEY.always_eager:
                connection.close()
    return inner


def db_task(*args, **kwargs):
    def decorator(fn):
        return task(*args, **kwargs)(close_db(fn))
    return decorator


def db_periodic_task(*args, **kwargs):
    def decorator(fn):
        return periodic_task(*args, **kwargs)(close_db(fn, iscron=True))
    return decorator
```

**Comment by coleifer** [comment]
> Additionally this makes it hard to unit test the task.

Separate your task logic from your task-decorated functions.

I've merged a fix that will not close the db conn for always_eager=True. Thanks for the suggestion, I think it's spot-on. I am going to pass on merging the periodic special-casing, as I think it could be interpreted either way and it is easier to reason about without a special case.
