### ISSUE TITLE
No obvious way to retrieve task result given event parsing

### ISSUE THREAD

**Issue by blakev** [coleifer/huey#148]
The only obvious way to get results "easily" from the Redis data store is to call them, and then use the `.get()` method on the `AsyncResults` object. However, this doesn't work well if you are listening for events that completed via:

```python
from bumble.config import hue

storage = hue.get_storage()

for event in storage:
    event_id = event.get('id', None)

    if event_id:
        # ...get-results-from-redis-by-id...
```

Since the tasks are truely asynchronous it would make sense that there should be an easy / obvious way to obtain those results from Redis as soon as they've been emitted.  If the consumer and the task commissioner are running in two processes, this is harder than it needs to be.

**Comment by blakev** [comment]
Maybe something like this in `RedisStorage`

```python
    def data(self, key, deserialize=None):
        if self.has_data_for_key(key) and key is not None:
            val = self.conn.hget(self.result_key, key)
            if val:
                if deserialize is None:
                    deserialize = pickle.loads
                return deserialize(val)
```

**Comment by coleifer** [comment]
Commit 653f0b1 adds a new method to the ``Huey`` object, ``Huey.result``. You can now do something like:

```python
from huey.consumer import EVENT_FINISHED

for event in huey.storage:
    if event['status'] == EVENT_FINISHED:
        result = huey.result(event['id'])
        process_result(result)
```

**Comment by coleifer** [comment]
I should add that the data is deserialized by the `result` method. Additionally, the `result` method supports all the same arguments as `AsyncData.get()` (so it can block, etc).

**Comment by coleifer** [comment]
https://github.com/coleifer/huey/blob/master/CHANGELOG#L4-L15

**Comment by blakev** [comment]
I looked over your code, it's great!

Thanks!
