### ISSUE TITLE
Asyncio Support

### ISSUE THREAD

**Issue by zbyte64** [coleifer/huey#151]
Huey should support coroutines. This would mean having an asyncio event loop and detecting if a task is a coroutine. Also if a task returns a future that should be waited on before marking the task complete and it should use future.result() as the task response.

```
@task
@asyncio.coroutine
def cleanup(container_id):
    client = create_docker_client()
    yield from client.containers.container(container_id).remove(form=True)
```

**Comment by coleifer** [comment]
Hmm...peewee supports haven't, what about that? I'm not in love with the way the asyncio APIs require completely different syntax from the rest of Python and am not sure how to implement it in a compatible way. Any ideas?

**Comment by zbyte64** [comment]
Not really a fan of asyncio either but there may be times the task runner has to execute an asyncio function. The main crux of the problem is that you do not want to run the event loop inside the task loop itself but rather by task runner. 

You don't have to require asyncio in order to support asyncio. You can detect if a task returns a coroutine and do special handling when that happens.

**Comment by coleifer** [comment]
@zbyte64 -- could you put together a bit of sample code I can look at? or maybe point me to prior art in something like celery project, etc?

**Comment by xucian** [comment]
guess this didn't make it into the lib, right?
