### ISSUE TITLE
Documentation for supplying own redis connection

### ISSUE THREAD

**Issue by canni** [coleifer/huey#154]
If you're using Redis also for eg. session storage, you probably want to use single redis connection/connection pool for both, session & tasks & others..

Currently AFAIK the only way to supply you're own conn, is to subclass `Huey`, and override `get_storage` method.

Probably not the best API for that, but if it needs to stay like this, a bit of docs showing how to do that might be helpful for others

**Comment by canni** [comment]
NVMD, I missed the `**storage_kwargs` on base `Huey` class, but documenting that might be handy anyway.

**Comment by coleifer** [comment]
Link: http://huey.readthedocs.io/en/latest/api.html#Huey

No problem I've had a to-do item to rewrite and reorganize the Huey docs for some time. Thanks for updating and letting me know you found the fix.

**Comment by Matt-Deacalion** [comment]
I came across this today. I want to use the same connection pool for Huey and the Django cache backend. It wasn't that obvious from the docs how to do this, as Django needs to be fully initialised before you can retrieve it's connection pool - which rules out instantiating `Huey` in the Django settings.

For future searchers, this is how I wired it up with [django-redis](https://github.com/jazzband/django-redis).

**_config/huey.py_**
```python
from django_redis import get_redis_connection
from huey import RedisHuey


class DjangoHuey(RedisHuey):
    """
    Subclassed to use the existing connection pool from the Django
    cache backend, when using `django-redis`.
    """
    def __init__(self, *args, **kwargs):
        connection = get_redis_connection()
        kwargs['connection_pool'] = connection.connection_pool

        super().__init__(*args, **kwargs)
```

**_settings.py_**
```python
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL'),
        'OPTIONS': {
            # this connection pool is also used for Huey
            'CONNECTION_POOL_KWARGS': {'max_connections': 100},
        },
    }
}

HUEY = {'huey_class': 'config.huey.DjangoHuey'}
```
