### ISSUE TITLE
Timeout - feature request

### ISSUE THREAD

**Issue by hegga** [coleifer/huey#159]
Hi,

Would it be possible to add a timeout argument to the huey.task decorator? Where a task will be killed
if the run time exceeds the time specified in the timeout argument.

This could for example look like:

```python
@huey.task(timeout=60)
def add_numbers(a, b)
    return a + b
```

**Comment by coleifer** [comment]
That's a pretty cool idea. By the way, I edited your comment to include code formatting. PLEASE format your code when you submit a ticket. It takes literally 5 seconds and communicates to the project maintainer that you actually care. When I see an issue without code formatting it sends a very bad message, in other words.

OK, anyways,

Yes that's a cool idea. There are some potential pitfalls, though. Gevent relies on cooperative multi-tasking. If your misbehaving Python task is chugging along without yielding for I/O, then Gevent's event loop hsa no way of pre-empting the misbehaving task. So, for people using the gevent worker model, task timeouts will work but with a big freakin caveat.

For threaded tasks this should be straightforward.

For multi-process I imagine it should be as well, but I'm less familiar with the multiprocessing module so I'll need to read up on how this might be implemented.

Do you have any suggestions on how it might work?

**Comment by hegga** [comment]
Sorry about the missing code formatting, collaboration through github is quite new to me.

I'm afraid this feature would be a bit over my python level, but I'll try to look at the source code of 
huey during the weekend to see if I can come up with some suggestions. Initially I were mostly wondering if this was something that you had thought of, or would like to add at all. 

By the way, I really like the simplicity of huey, it's a great piece of software, thanks for making it open source.

**Comment by coleifer** [comment]
Thanks for the kind words about the project! No worries i just wanted to ask if that any thoughts about the implementation.

I think it should be straightforward as a decorator that wraps your task functions (and hence is executed in the consumer).

```python

@huey.task()
@huey.timeout(600)
def my_task():
    ...


```

**Comment by hegga** [comment]
Wow! I think that would be a very nice and clever way to implement this functionality.

**Comment by coleifer** [comment]
So, for threads, it is actually not at all straightforward. Python *highly* discourages you from killing a thread that's actively working from another thread. Gevent and multiprocessing should both be easy to implement timeouts on tasks, but with threading I don't see any viable options.

Going to close this for now, may revisit it in the future.
