### ISSUE TITLE
Exception running scheduler

### ISSUE THREAD

**Issue by cmanallen** [coleifer/huey#161]
Hi, I'm getting errors running the scheduler.  Can you help me troubleshoot this bug?

Executing huey with: `huey_consumer bac.tasks.huey -s 10 ` raises the below errors.

```
Exception in thread Scheduler:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/huey/consumer.py", line 359, in _run
    consumer_process.loop()
  File "/usr/local/lib/python2.7/site-packages/huey/consumer.py", line 226, in loop
    for task in self.huey.read_schedule(now):
  File "/usr/local/lib/python2.7/site-packages/huey/api.py", line 322, in read_schedule
    for m in self._read_schedule(ts)]
  File "/usr/local/lib/python2.7/site-packages/huey/api.py", line 164, in inner
    wrap_exception(exc_class)
  File "/usr/local/lib/python2.7/site-packages/huey/utils.py", line 18, in wrap_exception
    raise new_exc_class('%s: %s' % (exc_class.__name__, exc))
ScheduleReadException: TypeError: int() argument must be a string or a number, not 'NoneType'
```
```
Exception in thread Worker-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/huey/consumer.py", line 359, in _run
    consumer_process.loop()
  File "/usr/local/lib/python2.7/site-packages/huey/consumer.py", line 95, in loop
    self.huey.emit_task(EVENT_ERROR_DEQUEUEING, task, error=True)
  File "/usr/local/lib/python2.7/site-packages/huey/api.py", line 260, in emit_task
    metadata = self._get_task_metadata(task, error)
  File "/usr/local/lib/python2.7/site-packages/huey/api.py", line 236, in _get_task_metadata
    'id': task.task_id,
AttributeError: 'NoneType' object has no attribute 'task_id'
```

**Comment by coleifer** [comment]
I'm not sure what might be going on.

What version are you using? How are you instantiating your `huey` object? How are you instantiating the storage backend (if you are, if not don't worry about it)?

Are you calling your tasks with a delay, or are these cron tasks that seem to be failing (if you can tell)? My guess is that you've got a busted task and the real errors are masked, but I'm not positive.

**Comment by cmanallen** [comment]
@coleifer Version `1.1.2`.  I'm not using storage (to my knowledge - I'm not doing anything explicit).

Huey is instantiated like:

```python
class Scheduler(object):
    _connection = None

    def connection(self):
        if self._connection is None:
            app = application.app.app_context()
            app.push()

            self._connection = RedisHuey(
                'scheduler', host=current_app.config.get('REDIS_HOST'),
                port=current_app.config.get('REDIS_PORT'))

            app.pop()
        return self._connection


huey = Scheduler().connection()
```

---

So basically my `bac.tasks` module looks like this.

```python
from common.scheduler import huey
from tasks.whatever import task

if __name__ == '__main__':
    task()
```

Running the script causes the error in the OP.  But if I comment everything but the `huey` import out it still fails with the error.

Full disclosure I'm running this script in an Ubuntu docker-machine (if it matters).

**Comment by coleifer** [comment]
Man...I have no idea. What I can tell you, though, is that I don't believe there's a fundamental bug in the scheduler code...I have to assume something funky going on in your app.

You might try pulling down the huey repository and checking out the example app.

**Comment by coleifer** [comment]
Also, if you haven't tried it already, you might just try specifying "always_eager=True" when instantiating your Huey instance. This will cause tasks to bypass the consumer/scheduler APIs and run in the calling thread.

**Comment by cmanallen** [comment]
@coleifer Okay thanks for the `always_eager`.  I've been doing some debugging and I think the problem lies in how huey is being instantiated.  Once I figure out the error I'll let you know.

**Comment by cmanallen** [comment]
@coleifer Hah, found the error.  The redis host was being passed as `None`.  Manually specifying it to my redis hostname fixed the issue.

Kind of sucks that it fails so hard.  It may be worth raising an exception like `ValueError: NoneType can not be redis hostname`.
