### ISSUE TITLE
get task_id and the status of task by task_id

### ISSUE THREAD

**Issue by hmleo** [coleifer/huey#162]
Hi Coleifer：
   When i started a task,i need to display the progressbar of the task's status and update the progressbar depend on the status of the task.
   So i need to get the task_id when starting the task and then get the status of the task by task_id.
   So how can i complish this  in  huey? I didn't find good way to deal with it.I will be appreciate for give me good advice.
   Thanks!

**Comment by coleifer** [comment]
You will get the task's ID via the `TaskResultWrapper` object returned by a task.

To update the status, I'd suggest having your task push updates to a shared resource, and have your dashboard or whatever poll for updates from the task.

It's a common pattern but one that depends entirely on your application.
