### ISSUE TITLE
Failed deque() in Worker.loop() causes AttributeError in _get_task_metadata()

### ISSUE THREAD

**Issue by martinmo** [coleifer/huey#164]
Hi, first of all thanks for all your effort! During tests with Huey I encountered a minor bug. In my case it was triggered by shutting down Redis before shutting down the Huey workers. This should result in a cascade of `ConnectionError`s being logged but instead it also raises an AttributeError.

From https://github.com/coleifer/huey/blob/master/huey/consumer.py#L89:

```python
    def loop(self, now=None):
        task = None
        exc_raised = True
        try:
            task = self.huey.dequeue()
        except QueueReadException as exc:
            self.huey.emit_task(EVENT_ERROR_DEQUEUEING, task, error=True)  # task is None
            self._logger.exception('Error reading from queue')
        # [...] several other invocations of emit_task() with task=None [...]
```

`emit_task()` then calls `_get_task_metadata()`, which tries to access attributes of the `task` of type `NoneType`.

**Comment by coleifer** [comment]
4306c3f6a89d4e98775ed56d308a176659789304

**Comment by coleifer** [comment]
Thanks!
