### ISSUE TITLE
stats add extra network roundtrips when queuing

### ISSUE THREAD

**Issue by 72squared** [coleifer/huey#166]
I noticed in using this newer version of huey that supports metadata, it adds extra round trips to redis to increment counters. With a little careful refactoring, performance could be dramatically improved by incrementing counters with the queueing of the task so it only needs 1 network roundtrip. 

Another acceptable alternative is a config option to disable the metadata tracking for those who don't use it. I personally have other mechanisms for tracking these things.

**Comment by coleifer** [comment]
Thanks for the input. This was an experiment I was trying out and I agree actually that it's got some issues (performance, clunky API, usefulness). I'm planning to scrap it in the next release :)

**Comment by coleifer** [comment]
Feature removed and 1.2.0 release tagged and pushed to pypi. Thanks for getting me motivated to fix this one!

**Comment by 72squared** [comment]
+1
