### ISSUE TITLE
refactor dequeuing operations to pipeline

### ISSUE THREAD

**Issue by 72squared** [coleifer/huey#167]
Encouraged by your perf optimization of yanking metadata. Think you could think through how to make fewer network requests on dequeueing to make it more efficient. for example:

https://github.com/coleifer/huey/blob/master/huey/storage.py#L190-L194

This section could be rewritten as:

```
    def pop_data(self, key):
        pipe = self.conn.pipeline(transaction=False)
        pipe.hexists(self.result_key, key)
        pipe.hget(self.result_key, key)
        pipe.hdel(self.result_key, key)
        exists, val, del = pipe.execute()
        if not exists:
            return EmptyData
        return val
```

**Comment by coleifer** [comment]
Are you running your Redis instance on a separate server from your consumer?

**Comment by 72squared** [comment]
Actually, in my current design, no. I am running the consumer on the same server as redis. But I still feel it should be as efficient as possible.

**Comment by 72squared** [comment]
Another easier way to improve efficiency is to look for ways to avoid making calls altogether. I sit and watch the redis monitor on a test setup and then queue a job and watch the consumer work. In my case, I have the result store disabled, but the consumer still does:

```
"HEXISTS" "huey.results.mpfq" "r:b7e7473a-da89-4e31-af46-0e9ac8772c66"
```

I don't know the code super well, but think this is because the TaskWrapper still is checking the result store even though it is disabled, here:

https://github.com/coleifer/huey/blob/master/huey/api.py#L414-L428

Thoughts?

**Comment by coleifer** [comment]
```
"HEXISTS" "huey.results.mpfq" "r:b7e7473a-da89-4e31-af46-0e9ac8772c66"
```

So if you look at that key, you'll see it begins with "r:" -- this indicates that this is the key used to indicate that a task has been revoked. When you enqueue something and the consumer determines it is not scheduled for some time in the future, it will check to see if the user has "revoked" the task before actually executing it. Revoking a task is equivalent to saying "if you see this task, don't run it as long as the revoke flag is in place".

So that is why you see a `HEXISTS` before your task runs.

**Comment by 72squared** [comment]
But if I don't have result_store enabled, there's no way for me to revoke it, right? So it's an unnecessary check.

**Comment by coleifer** [comment]
The storage of task results is now treated differently from revoking and scheduling as of the big changes in 1.1.0. Basically, you always have the option to schedule and revoke, as it's part of the core storage api as opposed to an individual component you need to install.
