### ISSUE TITLE
Check if last retry

### ISSUE THREAD

**Issue by mke21** [coleifer/huey#168]
Hi,

Is it possible to detect the the retry iteration and see if it is the last iteration?
I would like to do something different at the last retry, something like:

```python
@huey.task(retries=3, delay=10)
def mytask(myparam):
    try:
        do_something(myparam)
    except:
        if retry<retries:
            raise
        else:
            sendemail(myparam)
```

I know this is possible with celery, but don't know how to do that in huey.

For the rest, this is a great little task queue you made.

**Comment by coleifer** [comment]
http://huey.readthedocs.io/en/latest/api.html#Huey.task

Specifically scroll down to the description of `retries_as_argument`
