### ISSUE TITLE
Replace a dead process in Consumer.worker_threads

### ISSUE THREAD

**Issue by dmitryduev** [coleifer/huey#169]
Hi,

If one of the processes in Consumer.worker_threads is killed (for whatever reason), huey does not catch that. I tried killing (with kill -9) all processes in worker_threads (on mac os) and huey_consumer.py simply hangs. How about replacing a dead process with a new one? A workaround in Consumer.run() could look like this (tested, works):
```

def run(self):
    self.start()
    while True:
        try:
            # replace a dead process:
            for i in range(self.workers):
                if not self.worker_threads[i].is_alive():
                    worker = self._create_runnable(self._create_worker())
                    self.worker_threads[i] = self.environment.create_process(
                        worker, 'Worker-{:d}'.format(i + 1))
                    self.worker_threads[i].start()
            is_set = self.stop_flag.wait(timeout=0.1)
            time.sleep(0.1)
        except KeyboardInterrupt:
            self.stop()
        except:
            self._logger.exception('Error in consumer.')
            self.stop()
        else:
            if self._received_signal:
                self.stop()
            if self.stop_flag.is_set():
                break
    self._logger.info('Consumer exiting.')
```

But probably you could think of a better way to implement this functionality.

**Comment by coleifer** [comment]
Out of curiosity, why would the worker get killed? I guess oom...and of course if the user kills it...hmm.  yeah, I agree, though that a new one needs to be created. Thank you for bringing this to my attention!

**Comment by dmitryduev** [comment]
In my case, the system where I'm running huey operates without human supervision, and there's a 'supervisor' process that looks after the system that may kill a misbehaving (for whatever reason) process. So it's just an additional level of protection.
