### ISSUE TITLE
djhuey run_huey consumer settings not documented

### ISSUE THREAD

**Issue by iivvoo** [coleifer/huey#170]
I had to dive into the code to find out how to make run_huey log properly. The logfile setting is pretty obvious but loglevel is rather tricky since it doesn't take logging.DEBUG or "DEBUG" as argument.

Turns out the valid values are

    None - INFO
    0 - ERROR
    1 - DEBUG

If not set properly, huey will default to DEBUG which can get rather noisy :)

**Comment by coleifer** [comment]
The `loglevel` is especially weird because of the way Django uses "verbosity" as a default argument/

**Comment by coleifer** [comment]
But yes, this can definitely be improved.

**Comment by coleifer** [comment]
I don't like to complain, but there is an unbelievable stench coming from Django's management command API, which is compounded by `argparse` and it's fappy as fuck and annoying as all hell refusal to let me just. remove. a. damn. option.

**Comment by coleifer** [comment]
Sorry. I spent the last hour digging through the code of Django 1.8, 1.9 and argparse trying to figure out a way that doesn't completely suck to get rid of the "--verbosity"/"-v" option. Turns out it was a herculean task beyond my abilities. So I renamed the huey option.
