### ISSUE TITLE
PicklingError: Can't pickle

### ISSUE THREAD

**Issue by rahul3103** [coleifer/huey#172]
```
[2016-08-02 15:18:53,973] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/Users/rahul/.virtualenvs/search/lib/python3.5/site-packages/huey/consumer.py", line 144, in process_task
    self.huey.execute(task)
  File "/Users/rahul/.virtualenvs/search/lib/python3.5/site-packages/huey/api.py", line 291, in execute
    self._put_data(task.task_id, pickle.dumps(result))
_pickle.PicklingError: Can't pickle <class 'tasks.queuecmd_add_article_to_index'>: attribute lookup queuecmd_add_article_to_index on tasks failed
```

**Comment by coleifer** [comment]
Thanks for bringing this to my attention, I'll push a fix soon.

**Comment by coleifer** [comment]
It looks like you're using version 1.1.2, have you tried upgrading to the latest version 1.2.0? I think there's a possibility this one's been fixed.

Also:

* What does this task return?
* Is this a regular task or a periodic task?

**Comment by coleifer** [comment]
@rahul3103 -- :bell: can you please get back to me regarding the questions I've asked?

**Comment by rahul3103** [comment]
Yeah, I am on version 1.1.2. It adds articles to whoosh index.

**Comment by rahul3103** [comment]
Sorry, for the delay.

**Comment by coleifer** [comment]
Can you try upgrading to 1.2.0 and letting me know if that fixes it? And is this a regular or periodic task?

**Comment by rahul3103** [comment]
Its a regular continuous thing, whenever new article created its added to whoosh index.

`[2016-08-05 19:29:23,106] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_add_or_update_index: 57e74549-dece-4d1f-b0aa-a405722622b9
1
[2016-08-05 19:29:23,110] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/Users/rahul/.virtualenvs/search/lib/python3.5/site-packages/huey/consumer.py", line 141, in process_task
    self.huey.execute(task)
  File "/Users/rahul/.virtualenvs/search/lib/python3.5/site-packages/huey/api.py", line 279, in execute
    self._put_data(task.task_id, pickle.dumps(result))
_pickle.PicklingError: Can't pickle <function StrictRedis.<lambda> at 0x105b079d8>: attribute lookup StrictRedis.<lambda> on redis.client failed`

**Comment by coleifer** [comment]
Is the above traceback after upgrading?

**Comment by rahul3103** [comment]
Yes its coming after upgrade to 1.2.0

**Comment by coleifer** [comment]
Can you tell me what, if anything, is returned by this task function? i.e. does the task have a `return` statement anywhere? And what are you returning?

**Comment by rahul3103** [comment]
This is the function

```
@queue.task()
def add_article_to_index(_id=None):
    '''Add a newly published article to index.'''
    if not _id:
        return False
    article = get_article(_id)
    if not article:
        logger.error('Article ID: %s was not added to index.' % _id)
        return False
    writer = get_index_writer()
    add_to_index(writer=writer, article=article, update=False)
    writer.commit(merge=True)
    return True
```

Error:

```
[2016-08-06 00:42:07,114] ERROR:huey.consumer.Worker:Worker-1:Unhandled exception in worker thread
Traceback (most recent call last):
  File "/Users/rahul/.virtualenvs/search/lib/python3.5/site-packages/huey/consumer.py", line 141, in process_task
    self.huey.execute(task)
  File "/Users/rahul/.virtualenvs/search/lib/python3.5/site-packages/huey/api.py", line 279, in execute
    self._put_data(task.task_id, pickle.dumps(result))
TypeError: can't pickle _thread.lock objects
```

**Comment by coleifer** [comment]
Are you sure that is the exact code?? I was able to reproduce the first error by returning the task itself from the task-decorated function.

And how is it that you first submitted this issue where the problem was Python could not pickle a task instance. Then you posted that the problem was `<function StrictRedis.<lambda> at 0x105b079d8>`. Lastly the issue was `Lock`.

The only place `threading.Lock` is used is in a test of the consumer.

I believe this has very much to do with problems in your code and that you are not being forthright about what code you are running.

Please update this ticket if you have a reproducible example, otherwise I'm considering this closed.
