### ISSUE TITLE
How to use a unix socket?

### ISSUE THREAD

**Issue by camilonova** [coleifer/huey#174]
Instead of a host and a port to connect to redis.

**Comment by coleifer** [comment]
When you are using the `RedisHuey` object, the argument signature of the constructor looks like this:

```python
class RedisStorage(BaseStorage):
    def __init__(self, name='huey', blocking=False, read_timeout=1,
                 max_errors=1000, connection_pool=None, **connection_params):
```

If a connection pool is not specified, then the parameters in `**connection_params**` will be used to set up a new connection pool.

So you have two options. If you already have a Redis `ConnectionPool` that uses unix domain sockets, you can pass that to `RedisHuey`.

```python
my_pool = ConnectionPool(
    connection_class=UnixDomainSocketConnection, 
    path='/tmp/my_redis.sock')
huey = RedisHuey(connection_pool=my_pool)
```

Alternatively, you can pass in the parameters needed to create a new connection pool:


```python
huey = RedisHuey(
    connection_class=UnixDomainSocketConnection, 
    path='/tmp/my_redis.sock')
```

**Comment by camilonova** [comment]
#163 is what I was looking for. Thanks.

**Comment by coleifer** [comment]
Oh, I'm glad I spent all that time typing up an answer to your question.
