### ISSUE TITLE
How to start Huey service automatically with Django?

### ISSUE THREAD

**Issue by ranihorev** [coleifer/huey#177]
Hi,

It's not exactly a bug but I hope you could help me.
I'm running Huey with Django and I would like to start Huey immediately with Django (and without holding the console).
Is it possible?

Thanks

Edit: more specifically - I'm trying to run it using dockerfile but because it holding the console it doesn't work (sorry for the bad explanation). 
This is the command:  gunicorn -c gunicorn_conf.py djangoApp.wsgi:application && python manage.py run_huey. 
If I'm switching the order of the commands the server won't start.

**Comment by ranihorev** [comment]
Fixed the problem - just ran 2 docker separately - one for Gunicorn and one for Huey.

**Comment by sillycube** [comment]
I find it not working with docker as well. Whether running python manage.py run_huey && python manage.py runserver 0.0.0.0:8000 or the reverse order, it's the same. Either Huey or django can be run but not both. I try to separate the line into 2 but have no luck

**Comment by coleifer** [comment]
I think you have a fundamental misunderstanding of what docker is supposed to do, @sillycube. If you insist on trying to run both processes in a single docker container then you'll need to background one of them.

**Comment by sillycube** [comment]
Ok, thanks for prompt reply. I was using 2 containers to run celery and django for another project. Just trying to see if I can do it without separating them
