### ISSUE TITLE
clear tasks by id

### ISSUE THREAD

**Issue by kittles** [coleifer/huey#180]
is there a way to clear outstanding tasks that have been enqueued and are in some stage of retying by task id? also- is there a way to just clear everything so when i kill the consumer while it still has stuff enqueued, i can restart it without those things coming back?

**Comment by coleifer** [comment]
To clear everything, call `huey.flush()`

To revoke a task given only it's id, do something like this:

```python
from huey import QueueTask

huey.revoke(QueueTask(task_id=mytaskid))
```

If you  have the return value wrapper from calling the task, just use its revoke method.

I may, for simple, add a `revoke_by_id` method to huey,...

**Comment by kittles** [comment]
thanks. im queueing a bunch of tasks, then keeping track of their ids and listening to events to know when all have finished- is this the best way to handle this? figured id ask in case i missed something in the api and docs. 
`
pending_task_ids = []
results = []
for job in jobs:
    result = run_task(job) # run task is a huey task
    pending_task_ids.append(result.task.task_id)

# track all tasks invoked, wait until they are all done
for event in huey.storage:

    # is there a good way to timeout of this loop if it goes on for too long?

    # handle finished events
    if event['status'] == EVENT_FINISHED:
        # move the id to completed array
        if event['id'] in pending_task_ids:
            pending_task_ids.remove(event['id'])
            results.append(huey.result(event['id']))
        # check to see if all jobs are done
        if len(pending_task_ids) == 0:
            break

`

**Comment by coleifer** [comment]
At the moment, there's no real way to group a bunch of tasks and make sure they're all done... the best idea I have would be a meta-task:

```python
@huey.task()
def metatask():
    r1 = subtask1()
    r2 = subtask2()
    r3 = subtask3()
    return (
        r1.get(blocking=True),
        r2.get(blocking=True),
        r3.get(blocking=True),
    )

@huey.task()
def subtask1():
    ...
```

**Comment by coleifer** [comment]
BTW I did add methods to revoke a task and restore a task using just an id: `revoke_by_id` and `restore_by_id`.

**Comment by ivancarrancho** [comment]
from huey.contrib.djhuey import HUEY
HUEY.flush()
