### ISSUE TITLE
How can test code into the conditional of retries?

### ISSUE THREAD

**Issue by felipe3dfx** [coleifer/huey#181]
I need test a task, where it ask for the current retry, if it is the latest, make something
```

if kwargs['retries'] == 0:
    print('last retry') <-- Need test it!
```
How can create a test using the retry how 0? with the goal of enter into the conditional of retries.

**Comment by coleifer** [comment]
In the task decorator, you'll want to set the `retries_as_argument` to true.

http://huey.readthedocs.io/en/latest/api.html#Huey.task

**Comment by felipe3dfx** [comment]
the task has:
`@task(retries=3, retry_delay=(60*5), retries_as_argument=True)`
When i try to create a functional test, it broken because the task raises exception for add a new retry, I need that the task run all retries and execute the code into the conditional.

Any ideas?

**Comment by coleifer** [comment]
I'd try stackoverflow
