### ISSUE TITLE
Can't revoke Django tasks 

### ISSUE THREAD

**Issue by ranihorev** [coleifer/huey#182]
Hi,

I'm adding (successfully) tasks to send email on a specific date and time.
The task is called upon new item creation signal in Django and I save the task_id.
e.g.
`@receiver(post_save, sender=Newsletter)
def on_create(sender, instance, created, **kwargs):
    send_newsletter_email.schedule(args=(instance,), eta=instance.scheduled_date)`

I would like to revoke the task if the object is deleted but it doesn't work.
I tried to revoke it using this code, but the task is still there afterwards...
`for event in HUEY.scheduled():
            if event.task_id == instance.task_id:
                HUEY.revoke(event)`

What's wrong?

Thanks!

**Comment by coleifer** [comment]
Can you provide any additional information? Best would be a chunk of your huey log file showing the task being scheduled by the app, the call to revoke it, and the task being run in spite of this.

How much time is there between scheduling the task and actually sending it, typically?

When you say that it doesn't work, what do you mean? Is there an error?

Are you sure you're actually matching tasks based on their IDs and calling revoke?

Help me help you by including useful details.

**Comment by ranihorev** [comment]
Hi,

Sorry but I gave up on doing that, so I can't send you the logs...

Thanks!

**Comment by coleifer** [comment]
Let me know if you want to pick this back up. Thanks for the response
