### ISSUE TITLE
Scheduled tasks take longer to start

### ISSUE THREAD

**Issue by amitt001** [coleifer/huey#185]
A simple test script

```
import time
from tasks import count_beans

start = time.time()
res = count_beans.schedule(args=(100,), delay=59)
while res() is None:
	pass
print(time.time() - start)
```

Does not execute on correct time. It diverts from somewhere like 1 sec to 9 sec
Note: I think, scheduling starts on right time but the task execution takes longer
See:

```
[2016-10-06 00:06:40,166] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_count_beans: 7b05df51-0a0d-4acf-aa7f-77343cb21853 @2016-10-05 18:36:40 for execution
[2016-10-06 00:06:48,702] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_count_beans: 7b05df51-0a0d-4acf-aa7f-77343cb21853 @2016-10-05 18:36:40
```

**A difference of 8 seconds.**

**Comment by coleifer** [comment]
This appears to be happening with the example application that ships with Huey. The example is configured to run with a scheduler delay of 10 seconds. If you look here, you can see that the consumer is being run with `-s 10`:

https://github.com/coleifer/huey/blob/master/examples/simple/cons.sh#L8

The default value is 1 second, so as long as you are not overriding this setting, tasks should always execute within 1 second of being scheduled so long as there is an available worker to take the task.

**Comment by coleifer** [comment]
Another option is to run huey in "blocking" mode, which is kind of like long-polling if you're familiar with that from web development. If you're running huey in "blocking" mode, then you should see tasks executing without delay. To use blocking mode, add `blocking=True` when you declare your huey instance:

```python
huey = Huey(..., blocking=True, ...)
```

**Comment by amitt001** [comment]
I am not running huey with the example cron.sh script. I am using `huey_consumer main.huey` command.

**Comment by coleifer** [comment]
It's not "cron.sh", it's "cons.sh" ... anyways.

How are you instantiating huey, and what arguments are you passing the consumer on the command line? It looks to me as if you are using the same ones the example app uses.

**Comment by amitt001** [comment]
Not passing any command and instantiating by this command- `huey_consumer main.huey`
