### ISSUE TITLE
periodic_task and utc time

### ISSUE THREAD

**Issue by mskrzypek** [coleifer/huey#187]
`@db_periodic_task(crontab(hour='0', minute='0'))`

With above decorator and `utc=False` option in consumer settings, the task runs at 2:00 am - it is my local time. I think that setting `utc` to `False` should effect in treating all datetimes as my local time (identical with operating system settings).

**Comment by coleifer** [comment]
Hmm...yeah, I would think that if you are absolutely 100% sure you're running the consumer in local-time mode, then it sounds like there's a bug.

**Comment by coleifer** [comment]
The thing is, the logic is quite straightforward in the code... The Scheduler has a `get_now()` method which returns `datetime.datetime.now()` if the consumer was initialized with `utc=False`. That datetime is passed around and used by the function that evaluates whether the periodic task should execute or not.

Can you tell me how you're running the consumer? If you're using Django, what options are you passing in?

**Comment by mskrzypek** [comment]
Yes, I'm using Django.

```
# settings.py
HUEY = {
    'name': 'xxx',
    'always_eager': False,
    'consumer': {
        'loglevel': logging.DEBUG,
        'workers': 4,
        'worker_type': 'thread',
        'utc': False,
    },
}
```

Consumer runs without additional options:

`/www/.virtualenvs/xxx/bin/python manage.py run_huey`

**Comment by mskrzypek** [comment]
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import datetime
>>> datetime.datetime.utcnow()
datetime.datetime(2016, 10, 14, 13, 19, 16, 817603)
>>> datetime.datetime.now()
datetime.datetime(2016, 10, 14, 15, 19, 21, 430033)
```

**Comment by mskrzypek** [comment]
Django==1.10.2
huey==1.2.1

**Comment by coleifer** [comment]
Are you comfortable adding some additional logging code to your copy of huey? If so, I'd love if you could add something to the `consumer.py` module in the consumer's `__init__` method that printed the value of `utc`.

Something like:

```python

class Consumer(object):
    def __init__(self, ...):
        self._logger = ...
        # then towards the end of the method:
        self._logger.info('UTC is initialized to: %s', utc)
```

Then restart the consumer and share the logfiles with me. That'd be great!

**Comment by mskrzypek** [comment]
Yes, sure.

```
[2016-10-25 20:38:59,283] UTC is initialized to: True
[2016-10-25 20:38:59,283] Huey consumer started with 1 thread, PID 16310
[2016-10-25 20:38:59,284] Scheduler runs every 1 seconds.
[2016-10-25 20:38:59,284] Periodic tasks are enabled.
```

**Comment by coleifer** [comment]
I think that between 8e704b3 and 7d7566d this should be fixed.

**Comment by coleifer** [comment]
Well, maybe not...Ugh.

**Comment by mskrzypek** [comment]
Unfortunately, it has not been fixed yet.

**Comment by camilonova** [comment]
I just worked on a fix for this, please check #202

**Comment by camilonova** [comment]
@mskrzypek Please test the PR and let us know if it works for you too.

**Comment by Antwan86** [comment]
The reason for this whole #202 #187 #190 etc is simple : The `OptionParserHandler` shouldn't be initialised with default values at all. When you run a consumer, it is instanciated with default options as per the `ConsumerOption` class settings. Having additional default options on top of it is redundant, and causes issues with DjHuey config being ignored.

See [consumer_options.py](https://github.com/coleifer/huey/blob/master/huey/consumer_options.py) files, all settings are defaulted twice, this definitely not good.

**Comment by coleifer** [comment]
:+1:

**Comment by camilonova** [comment]
This issue can be closed now. @coleifer Could you please release a new version?

**Comment by coleifer** [comment]
1.3.0

**Comment by camilonova** [comment]
@coleifer 🍻  Thanks

**Comment by coleifer** [comment]
Thanks to you and @Antwan86 for the fixes and for the excellent job reporting the issue.

**Comment by srj55** [comment]
This fix isn't working for me.  in my Django settings, the 'utc' option has no effect.  When I run 'run_huey', the only way to set utc is on the command line.   If I don't set it in the command line (--utc), then utc will always be False.

**Comment by Antwan86** [comment]
`utc` option has no effect because it's the default.

@coleifer Can you please review #215
