### ISSUE TITLE
djhuey management command is ignoring consumer config

### ISSUE THREAD

**Issue by Antwan86** [coleifer/huey#190]
When launching the consumer through djhuey, the task is ignoring the HUEY consumer parameters in django configuration even if no arguments are provided to the command line.

This is due to the new optionparser introduced in the version 1.2.1.

Example 1 :

**📄 settings.py**

```
HUEY = {
    'consumer': {'workers': 2, 'worker_type': 'process'}
}
```

**💻 CLI**

```
$ ./manage. py run_huey
Huey consumer started with 1 thread, PID 8964
```

Example 2 :

**📄 settings.py**

```
HUEY = {
    'consumer': {'workers': 8, 'worker_type': 'greenlet'}
}
```

**💻 CLI**

```
$ ./manage. py run_huey -w 2
Huey consumer started with 2 thread, PID 8964
```

etc.

**Comment by coleifer** [comment]
I think that between 8e704b3563914ee59ca7ce2778c099ca5980991c and 7d7566d49a82ffaf6d039e5a484fc9cc374dbb94 this should be fixed. Could you pull down the latest code and verify that it's working for you? In my testing it seemed to be working.

**Comment by camilonova** [comment]
@coleifer I can confirm the bug is real and it is fixed at the current master. Could you release a new version?
