### ISSUE TITLE
Arguments for crontab task

### ISSUE THREAD

**Issue by lockie** [coleifer/huey#192]
Hi and thanks for an awesome library!
Is there currently a possibility to set arguments for a function being crontab task? (Not that I desperately need this, but it would be helpful.)

**Comment by coleifer** [comment]
What would this even look like, or how would this work?  The function is called (with no arguments) by the huey consumer at the appropriate interval, so no arguments are ever passed to it.

Am I misunderstanding what you're asking?

**Comment by lockie** [comment]
This would be usable in scenario when you are processing large quantities of some items, which take long time. Then you can add two crontab jobs: one that processes only the latest few and called e.g. hourly, and one that tries to process all of them and called, say, weekly. The obvious method for this would be adding `count` parameter to the job function. Of course, you could refactor it to common function and call it from two distinct job functions, so the question is only matter of convenience.

**Comment by coleifer** [comment]
There's no way to pass a parameter in to a cron-type function is what I was trying to say. Refactoring into two tasks is the correct way.
