### ISSUE TITLE
Get result by task_id

### ISSUE THREAD

**Issue by winkidney** [coleifer/huey#193]
Hi Charles Leifer,

I'm winkidney, a python developer from china.

Thanks for your great works first, this task-queue system really helps me a lot.

I'd like to contribute a PullRequest for a problem I meet.

The problem is : what if we want to get the task result if we miss the `TaskResultWrapper`?
Now I want to run an docker container and I don't want to wait until the docker ends its work.
I will save a `task_id` then query the result periodly, `huey` has no API for this feature.

Any idea?

**Comment by coleifer** [comment]
You can just call `Huey.result(task_id)`.

http://huey.readthedocs.io/en/latest/api.html#Huey.result

**Comment by winkidney** [comment]
Sorry for my mistake, thanks a lot:)

**Comment by coleifer** [comment]
No problem at all, it's a new API and kind of buried amidst the other methods.
