### ISSUE TITLE
only one instance of task at a time

### ISSUE THREAD

**Issue by cmorgan** [coleifer/huey#198]
Does Huey support this? 
I have previously used celery_once extension https://github.com/TrackMaven/celery-once

Also, is Windows supported?
Thanks

**Comment by coleifer** [comment]
You'll need to implement some kind of locking outside of Huey itself. It'd be very easy to do -- just create a new task decorator that wraps the `huey.task` method and have it perform the locking there.

**Comment by coleifer** [comment]
Windows is supported provided redis and python both work on windows.

**Comment by whoiswes** [comment]
FYI, in case anyone is googling this like I did, here's how I accomplished a decorator-based locking method in a somewhat generic way.  Has not been exhaustively tested, no warranty, not responsible for global thermonuclear war, etc.

Constructive feedback welcome if anyone has a better way.

```
def lock(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        # Put KV object with key as wrapped func name + timestamp
        lock = huey.storage.put_if_empty('{}-{}'.format(fn.__name__, datetime.datetime.utcnow().replace(second=0, microsecond=0).isoformat()), None)
        if not lock:
            return
        return fn(*args, **kwargs)
    return inner
```

**Comment by coleifer** [comment]
Huey actually has the ability to lock tasks, via `lock_task()`:

https://huey.readthedocs.io/en/latest/getting-started.html#locking-tasks

https://huey.readthedocs.io/en/latest/api.html#Huey.lock_task

**Comment by whoiswes** [comment]
@coleifer - I was aware of the lock_task decorator, but that doesn't work with scheduled tasks when you have multiple instances of the consumer running, correct?

I have a n+1 node application where each node is running a full app stack for redundancy/failover purposes (so, wsgi + huey processes).  Adding lock_task doesn't seem to prevent multiple scheduled task invocations, so if I have three nodes active, I get three scheduled task invocations.  I haven't exhaustively tested normal tasks as my use case is all about cron-style jobs.

I might be missing something obvious, and apologize if I am, but in other, similar issues, you've stated to perform any task locking outside of huey, which is what I attempted to do above (and it seems to work, for my use case(s), at least).
