### ISSUE TITLE
huey consumer dies !!

### ISSUE THREAD

**Issue by nikhil1910** [coleifer/huey#199]
Hi,

I tried to solve this problem myself and looked it on the internet also. After so much googling and not finding anything as result and decided to create an issue . Apologies if this isn't the right place for this.

I used huey as an celery alternative with python/django for a project. I do a lot heavy background processing and as mentioned huey is a lightweight alternative for celery. I find it very interesting and hence used it. But now i'm having problem with huey. I start huey in nohup mode so it won't hangup when i'm done working on server but now it's worker are dying. Please help as i need it so much!!!
For your reference i'm attaching the screenshots with the issue

Thanks in advanced.
![screenshot 10](https://cloud.githubusercontent.com/assets/23717156/22146803/f419ebcc-df2b-11e6-9bae-375808877230.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/23717156/22146804/f41db400-df2b-11e6-94f3-4611c4552c8f.png)

**Comment by coleifer** [comment]
I have no idea why the worker processes are dying in your application, but I don't believe the problem is in Huey...perhaps you're running out of memory and the OS is killing the processes?  Does the issue happen when running with threads or greenlets?  Huey's unit tests should cover this behavior, and anecdotally I haven't experienced issues running multiprocess huey consumers on my own system.

**Comment by nikhil1910** [comment]
Thanks for the reply. As you stated my server was out of memory and hence the workers were killed by the OS. But also this issue happened when i was working with processes and not threads or greenlets. But huey is really and i hope you make it more better. And my problem is solved and hence i'm closing this issues.
Thank you very much!!!

**Comment by Ak12166** [comment]
Facing the similar issue as stated above by nikhil1901 @nikhil1910 how did you resolved it?

**Comment by coleifer** [comment]
Your tasks are using up all your system memory and the system is killing them.

**Comment by Ak12166** [comment]
Yeah you right ....Huey tasks are consuming ram , but when the task is executed completed that memory is not being released, what might be causing this

**Comment by coleifer** [comment]
Your code, presumably.
