### ISSUE TITLE
Setting up a Huey task to always be running

### ISSUE THREAD

**Issue by dmcmulle** [coleifer/huey#206]
Hello.  I have Huey with Django setup.  I didn't see a clear way to have a task that is always running.  Is there something set up for this or could it be a feature I could add?

Thanks.

**Comment by coleifer** [comment]
What do you mean "always running"? Why would you need huey to do this?

**Comment by dmcmulle** [comment]
Always running as in, a task that checks if something needs to be done.  If it doesn't, it sleeps, then checks again.  The problem is, I run my apps on heroku and sometimes the servers randomly restart for maintenance etc, which would kill the thread spawned into Huey.

I guess similar to the @reboot cron command

**Comment by coleifer** [comment]
Ah, you want a periodic task. http://huey.readthedocs.io/en/latest/api.html#Huey.periodic_task

You'll of course need to ensure your Huey consumer starts up whenever your web application process starts. But periodic tasks run according to a cron-like schedule which you can specify, that should suffice I hope.
