### ISSUE TITLE
Best way to run ever 30 seconds

### ISSUE THREAD

**Issue by sloweclair** [coleifer/huey#207]
What is the best way to run a task every 30 seconds?
What I have is run it every minute with the cron decorater then do what I need to do as soon as the task starts then it sleeps for 30 seconds and runs it again. 
Is that the best way to go about this?

Thanks!
Spencer

**Comment by coleifer** [comment]
The most granular resolution supported currently by the crontab decorator is once/minute. You can write your own validation function to run more frequently.

The function accepts a datetime and returns True or False indicating whether the task should run.

This isn't how I'd go about it, but just to give you an idea:

```
def validate_30s(dt):
    return dt.seconds % 30 == 0
```

**Comment by coleifer** [comment]
The information presented here is outdated, the scheduler now runs once-per-minute.
