### ISSUE TITLE
High memory usage in Django

### ISSUE THREAD

**Issue by eyemyth** [coleifer/huey#209]
I'm using Huey for a Django project, and it seems to never release objects from memory.

Here's the task that's causing problems for me:

https://github.com/WGBH/FixIt/blob/master/mla_game/apps/transcript/tasks.py#L126

The method it eventually calls is https://github.com/WGBH/FixIt/blob/master/mla_game/apps/transcript/models.py#L189

When I start huey via the `run_huey` Django command, the task starts running and behaves like I expect it to. I'm watching memory usage with `ps aux | awk '{print $6/1024 " MB\t\t" $11}'  | sort -n | tail` and I see the Python process allocate a little over 1GB of memory, but the tasks finish and the memory allocation doesn't go back down. It will run another batch of jobs after a minute elapses and allocate more memory, over and over until Huey crashes due to running out of memory.

If I do the same function as a Django admin command, I can do the same task on a queryset of 10,000 objects using a little of 2GB of memory.

Relevant software versions:
CentOS 7.3.1611
Python 3.5.3
Django 1.9.12
Huey 1.2.3

**Comment by coleifer** [comment]
That's definitely odd, but I'm not sure what huey has to do with it.
