### ISSUE TITLE
Add PID file option

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/huey#210]
Would it be possible to add `--pid <file>` option to consumer?

It would help monitoring the process (in supervisor etc.).

**Comment by coleifer** [comment]
I'll probably pass on this.

**Comment by tuukkamustonen** [comment]
Alright, it's a good feature per se, but there's a workaround that I'm using at the moment (works on bash at least):

    huey_consumer & echo $! > /var/run/huey.pid

That may not suit more complicated scenarios, but it works for my needs now.
