### ISSUE TITLE
Passing a connection object as an argument using the test example function: count_beans(number)

### ISSUE THREAD

**Issue by mctinetti** [coleifer/huey#211]
Hi,
I'm testing huey with Django. The example works fine, but now I want to run a real task.
I have tasks which run using the subprocess (python module), I called .exe files which make a connection to some databases. 

I want to pass as an argument the conecction to the database so I tried count_beans(conn_database, 500 ) but the web app is showing an error:  **TypeError: can't pickle Connection objects**

 Can you please tell me how to fix this?
Cristina.
![21-03-2017 2-34-17 pm](https://cloud.githubusercontent.com/assets/21248667/24169618/cd523412-0e43-11e7-925b-ccf3cf79d348.png)

**Comment by coleifer** [comment]
Unfortunately you cannot pass a connection object around like that. Many objects can be pickled (serialized and then deserialized into python objects later) but things with context-specific state like a db connection don't make sense for pickling. Instead, what you would probably do is pass in the database name and arguments required to create a connection, then in the huey task create a new connection using the parameters passed in.

**Comment by mctinetti** [comment]
I will take your advice :+1: 
Thank you for your quick answer!
