### ISSUE TITLE
Documentation about greenlets with djhuey

### ISSUE THREAD

**Issue by Antwan86** [coleifer/huey#212]
Hi,

When trying to make use of greenlets workers, the consumer task just doesn't work.
I tried to monkey patch using gevent, but it seems the worker thread is not able to connect to DB.

Settings
```
HUEY = {
    'connection': {'host': self.HUEY_HOST, 'port': self.HUEY_PORT},
}
```

Additional `run_huey_greenlet` management command :
```
from huey.contrib.djhuey.management.commands.run_huey import Command as RunHueyCommand
from django.conf import settings


class Command(RunHueyCommand):

    def __init__(self, *args, **kwargs):
        if settings.HUEY.get('consumer', {}).get('worker_type') == 'greenlet':
            from gevent import monkey
            monkey.patch_all()
        super(Command, self).__init__(*args, **kwargs)

```

CLI
```
./manage.py run_huey_greenlet

DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 139937579968256 and this is thread id 139937120251248.
```

**Comment by coleifer** [comment]
You need to apply the monkey-patch *before* anything else, even import statements.

```python
# run_huey_greenlet.py
from gevent import monkey
monkey.patch_all()

from huey.contrib...
from django.conf ...

class Command(...)
    etc
```

Could you try that and follow-up with whether that helps?

**Comment by Antwan86** [comment]
It worked when patching the `manage.py` bootstrap script, as this is where the internal DB connection are made. Patching the actual command file doesn't work as it's too late.

```
#!/usr/bin/env python
import os
import sys

if 'run_huey' in sys.argv:
    from gevent import monkey
    monkey.patch_all()

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "conf")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)
```

I think it's worth mentioning that in the doc + troubleshooting, because :

1. It's not optional as stated, it's a mandatory thing to do.
2. Most of the people use djhuey and there is no mention anywhere about how to do it properly using django.

**Comment by coleifer** [comment]
ouch... man, Django sucks! Thanks for sharing what you found.

**Comment by achidlow** [comment]
Just got bitten by this. It'd be nice if the documentation mentioned this explicitly in the [Django section](http://huey.readthedocs.io/en/latest/contrib.html#configuration-examples). The examples all use 'greenlet' as the worker type, but no mention is made that `run_huey` requires patching to work. It's even more confusing that the failure is totally silent.

(And thanks for the awesome project.)

**Comment by coleifer** [comment]
Added docs: http://huey.readthedocs.io/en/latest/contrib.html#using-gevent
