### ISSUE TITLE
Support graceful shutdown

### ISSUE THREAD

**Issue by tuukkamustonen** [coleifer/huey#213]
The docs state:

> When the consumer is shut-down cleanly (SIGTERM), any workers still involved in the execution of a task will be interrupted mid-task.

But in an old issue it is stated that `SIGTERM` would actually wait for workers to finish: https://github.com/coleifer/huey/issues/88#issuecomment-73888728

As the ticket is 2 years old or so, I assume the docs are correct and workers are killed instantly even if they are still consuming a task.

Is there a way to do graceful shutdown?

**Comment by coleifer** [comment]
There currently is not. I suppose I could add a SIGINT handler and wire that up to allow graceful shutdown, though...

**Comment by coleifer** [comment]
Added support for graceful shutdown via SIGINT: 25bf307e46ec055699d653560bd15db7f9aae276

Docs: 625cf1abd07d2cd2fb0e070bb06c1a2053cf19a7

**Comment by tuukkamustonen** [comment]
Thanks, I don't know much about linux signals, but I've seen `TERM` and `INT` used in different ways. For example [gunicorn](http://docs.gunicorn.org/en/stable/signals.html) uses `TERM` for graceful shutdown and `INT` for forceful shutdown. Recommendations seem to vary?

I wonder what signals OS sends on shutdown. Matching so that on shutdown a graceful shutdown is first attempted, and only then forced, would be a good goal.

**Comment by tuukkamustonen** [comment]
At least http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/shutdown.html states that:

> At the specified time all processes are first notified that the system is going down by the signal SIGTERM. After an interval (see -t) all processes shall be sent the signal SIGKILL

**Comment by coleifer** [comment]
From https://www.quora.com/What-is-the-difference-between-the-SIGINT-and-SIGTERM-signals-in-Linux

> SIGINT is the interrupt signal. The terminal sends it to the foreground process when the user presses ctrl-c. The default behavior is to terminate the process, but it can be caught or ignored. The intention is to provide a mechanism for an orderly, graceful shutdown.
>
> SIGTERM is the termination signal. The default behavior is to terminate the process, but it also can be caught or ignored. The intention is to kill the process, gracefully or not, but to first allow it a chance to cleanup.

So I believe the huey implementation has the correct semantics.

**Comment by tuukkamustonen** [comment]
Yeah, I read the same source. But I fear that's one just interpretation. Normally when you `Ctrl-C` something, it gets force killed. And on the other hand, even that source says that `TERM` _may_ be gracefully handled.

Anyway, I also ran the script given in https://askubuntu.com/a/819768 on my Ubuntu 12.04 LTS vm (I added catching of `SIGINT` and `SIGQUIT` signals to script). The result for `shutdown -h now`:

```
running
running
running
running
running
ignoring signal 1  # this is HUP
running
running
running
running
caught SIGTERM                                                                                                                                                                                                                                              
0.0000s after stop                                                                                                                                                                                                                                          
0.1024s after stop                                                                                                                                                                                                                                          
0.2026s after stop                                                                                                                                                                                                                                          
0.3031s after stop                                                                                                                                                                                                                                          
...<SNIP>...
10.2122s after stop
10.3134s after stop
10.4138s after stop
10.5141s after stop
<log ends here so I guess it got SIGKILLed>
```

There was no `SIGINT` given. I think with current implementation (be it semantically correct or not), at shutdown huey will get force killed.
