### ISSUE TITLE
preserve = True is not saving the result

### ISSUE THREAD

**Issue by mctinetti** [coleifer/huey#214]
Hi there,
I'm using Django with the code:
`HUEY.result( task_id , preserve = True, blocking = True ) `
But when I want to see the task result later with `HUEY.all_results( )` the task was not saved.

If I removed the blocking parameter:` HUEY.result( task_id , preserve = True) ` then I can see the task with `HUEY.all_results( )`

In settings.py I have:

```
HUEY = {
    'name': 'test-django',  # Use db name for huey.
    'result_store': True,   # Store return values of tasks.
    'store_none': True,     # False: If a task returns None, do not save to results.
    'always_eager': False,  # If False, run asynchronously
    'consumer': {
        'loglevel': logging.DEBUG,
        'workers': 2,
        'scheduler_interval': 5,
    },
}
```

Any idea?
Thanks!

**Comment by coleifer** [comment]
Thanks, fixed in master.
