### ISSUE TITLE
contrab import path

### ISSUE THREAD

**Issue by camilonova** [coleifer/huey#218]
Since this import was removed https://github.com/coleifer/huey/commit/d64faebcdcc45b607c93f4112632ec52e0ddefb9#diff-0bc89e038d6de609d32591d4d984283fL7

Now you can't use `from huey.contrib.djhuey import crontab` you should use `from huey import crontab` instead.

Should I update docs? This is going to be a breaking change from the current version.

**Comment by coleifer** [comment]
214f3e7d5e4c5302dc5f14c4b1df82e1b4796b03
