### ISSUE TITLE
Is it possible for a worker to get to the task-id?

### ISSUE THREAD

**Issue by ricosuave73** [coleifer/huey#221]
I'm writing some code in Flask that uses Huey as a queue for out-of-process tasks (long running tasks). I'm looking for a way to link the currently executing task to the process/user that put the task in the queue.

I know Huey returns a resultwrapper, and the resultwrapper has a task.task_id. The calling code can get to this id. Could the code executed by the worker process also get to this same task-id? I'd like to use this so that I can (for example) log from within the worker using the task-id, so I can see for what task we are logging.

I also have a state stored in my database. If I can link the user executing the task to the task itself, I can have the running task log for which user it is executing. The task-id would be a means to do so.

**Comment by coleifer** [comment]
Yes, when decorating a task you typically would write something like:

```python
huey = RedisHuey(...)

@huey.task()
def my_task(foo, bar):
   return foo + bar
```

It is possible, however, to have the huey consumer call your task function **passing in the task as the first parameter**:

```python
@huey.task(include_task=True)
def my_task(foo, bar, task=None):
    print task.task_id
    return foo + bar
```
