### ISSUE TITLE
Is there a way to discard scheduled tasks executed after ETA?

### ISSUE THREAD

**Issue by john-bonachon** [coleifer/huey#226]
So my consumer can be stopped. When it restarts again, it tries to executed all pending scheduled tasks even if ETA has already passed, which can be fine in some situations, but not in others.
Is there a way (from Huey task params) to discard scheduled tasks executed after ETA? Sorry to be lazy, haven't revised the code yet, but haven't found this feature on documentation (if it makes sense).

**Comment by coleifer** [comment]
Unfortunately not. So I understand the issue correctly, what happens is:

1. Schedule a task to run at 1:05
2. Shut down consumer at 1:03 -- task has not run yet.
3. Restart consumer at 1:07 -- it runs the task from 1:05.

And at step 3 you would prefer to discard the task from 1:05? Here's one idea:

Declare you task as `include_task=True` and try something like this:

```python
@huey.task(include_task=True)
def my_task(task):
    delay = task.execute_time - datetime.datetime.utcnow()
    if delay.total_seconds() > 60:
         # This task is being run more than 1 minute after it was scheduled.
         return
```

**Comment by john-bonachon** [comment]
Good idea
