### ISSUE TITLE
Specify cons.sh in Getting Started

### ISSUE THREAD

**Issue by hargup** [coleifer/huey#228]
The screen shots in [Getting Started guide](https://huey.readthedocs.io/en/latest/getting-started.html) shows `cons.sh` script running in the top right corner, but the guide itself doesn't specify `cons.sh`.

**Comment by coleifer** [comment]
What?

**Comment by hargup** [comment]
![huey](https://user-images.githubusercontent.com/2477788/27324542-2e230016-55c3-11e7-809e-f7baf857e663.png)

Here is the screenshot, `cons.sh` is highlighted in red. (Sorry, there were typos in the issue description, I have fixed it now.)

**Comment by coleifer** [comment]
I'm still not clear what the issue is.
