### ISSUE TITLE
No module named peewee

### ISSUE THREAD

**Issue by alexsilva** [coleifer/huey#229]
huey `1.3.1`

The error occurs using the alternate setting
https://huey.readthedocs.io/en/latest/sqlite.html#sqlite

**Comment by coleifer** [comment]
Yes, the SQLite storage backend has a dependency on `peewee`. You can read about the library here: http://docs.peewee-orm.com/en/latest/ -- I've updated the docs c593df5919400bcab6056b6b8230a3784ce5123f
