### ISSUE TITLE
Periodic tasks with several huey instances

### ISSUE THREAD

**Issue by Sebubu** [coleifer/huey#232]
Heey guys

Just found a bug. If you use several huey instances and several periodic tasks, all periodic tasks are executed if you start consuming on one huey instance (even the one which where decorated with the periodic task of another huey instance).

I've done an example here https://github.com/Sebubu/hueybug_taskregister.

Do you know if there is a place in the code where we can quick fix this problem or do we have to rewrite the whole TaskRegistry?

Best regards

Severin

**Comment by coleifer** [comment]
If you're running multiple consumers, you can do a couple things.

1) Since Huey relies on import-time side-effects to register tasks, ensure that the modules imported by the various consumer instances only contain the tasks you wish those consumers to run.
2) Run all but one huey instance with `-n` or `--no-periodic`, which will prevent multiple instances of a periodic task getting spawned.

**Comment by coleifer** [comment]
Although, perhaps it makes sense to attach a `TaskRegistry` to a particular `huey` instance? That's another possibility, but the above options should work in the meantime.

**Comment by Sebubu** [comment]
> Although, perhaps it makes sense to attach a TaskRegistry to a particular huey instance? That's another possibility, but the above options should work in the meantime.

I thought about something like that. The periodic task decorator is already integrated into the huey instance. Why not move the `TaskRegistry` to there?

Im going to use the `--no-periodic` as a short term solution. I hope I will find time to move the `TaskRegistry`. Unfortunately, it looks like a bigger refactoring.

**Comment by coleifer** [comment]
ee4cd0f6d9c4b153c512e8d28aa3c4fee5fe0ea6

With this patch, if you instantiate your  `Huey` object with `global_registry=False`, then I believe you'll see the behavior you're expecting -- tasks are registered to the Huey instance they were decorated with.
