### ISSUE TITLE
Issues starting and importing huey from different folder

### ISSUE THREAD

**Issue by vaskokj** [coleifer/huey#233]
I have this folder structure.

huey_test
   __init__.py
   main.py 
huey_test/config
   __init__.py
   config.py
huey_test/tasks
   __init__.py
   tasks.py

I modified main.py to import like the following...

```
from config.config import huey
from tasks.tasks import count_beans
```

I would expect this to work but I get "ImportError: cannot import name 'huey'" when running huey_consumer.exe main.huey.

If I leave the config.py in the same folder as the main but move tasks it works by doing...

```
from config import huey
from tasks.tasks import count_beans
```

How can I import everything appropriately in a different folder structure?

**Comment by winkidney** [comment]
To resolve your problem, You should search google using  "python package system" or "python absolute import", etc.

**Comment by vaskokj** [comment]
I don't think its how I'm doing the import on my side but how huey specifically the huey_consumer.py is dealing with importing the information.

huey_test/hueytest
    main.py
    __init__.py
huey_test/hueytest/conf
    test.py
    __init__.py

main.py:

```
from hueytest.conf.test import testval

if __name__ = '__main__':
    print (testval)
```

test.py:

`testval = 234`

In a command prompt relative to the huey_test folder...
   C:\Users\<username>Documents\dev\huey_test> python hueytest\main.py 
   234


Huey (huey_consumer.py) seems to want things in the same directory or relative to its own "path". For example the same pattern above does not work. 

huey_test/hueytest
    main.py
    __init__.py
huey_test/hueytest/conf
    test.py
    __init__.py


main.py:

```
from hueytest.conf.config import huey

if __name__ == '__main__':
     print (huey)
```


config.py:

```
from huey import RedisHuey

huey = RedisHuey('simple.test')
```

In a command prompt relative to the huey_test folder...(same as above)
   C:\Users\<username>Documents\dev\huey_test> python "C:\Program Files\Anaconda3\Scripts\huey_consumer.py" hueytest\main.py 

```
[91mError importing hueytest\main.huey[0m
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\huey_consumer.py", line 51, in <module>
    consumer_main()
  File "C:\Program Files\Anaconda3\Scripts\huey_consumer.py", line 43, in consumer_main
    huey_instance = load_huey(args[0])
  File "C:\Program Files\Anaconda3\Scripts\huey_consumer.py", line 18, in load_huey
    return load_class(path)
  File "C:\Program Files\Anaconda3\lib\site-packages\huey\utils.py", line 44, in load_class
    __import__(path)
ImportError: No module named 'hueytest\\main'
```

**Comment by coleifer** [comment]
I'm sorry but this isn't the best place to ask this type of question. Try StackOverflow. The huey docs are pretty clear on how to set things up: http://huey.readthedocs.io/en/latest/imports.html

And at the end of the day it's just Python and the way the `import` statement works...

**Comment by vaskokj** [comment]
I apologize. I see what I did wrong. Nothing was wrong with my imports in the actual python code, but what was being sent to huey_consumer.py as the parameters. 

I had:

`C:\Users<username>Documents\dev\huey_test> python "C:\Program Files\Anaconda3\Scripts\huey_consumer.py" **hueytest\main.huey**`

I thought you were looking for an actual PATH to the object and not the object itself. So instead of `hueytest\main.huey ` I should have sent `hueytest.main.huey` as the parameters. 

This is for anyone else that runs into the same problem.

**Comment by pBogey** [comment]
> I'm sorry but this isn't the best place to ask this type of question. Try StackOverflow. The huey docs are pretty clear on how to set things up: http://huey.readthedocs.io/en/latest/imports.html
> 
> And at the end of the day it's just Python and the way the `import` statement works...

I'm a beginner and I came here being tired of trying to configure celery with Django. I'm having a hard time understanding how to run a simple taks with Huey also, so I'm either too dumb, or the documentation is not clear enough.
