### ISSUE TITLE
Any solution for chaining

### ISSUE THREAD

**Issue by zenwalker** [coleifer/huey#234]
Hello! I need any solution for running few tasks as a chain. I read the documentation but didn't find any mention about callbacks or task dependencies. My use case:

1. Download file from S3
2. Transform this file to another format
3. Then upload converted file back to S3

Every item should be separated task because the first and third task is I/O operation and should run in separate queue. They can also fail (in theory) and needs retries, while the second is not. Any ideas? :)

**Comment by coleifer** [comment]
You can call a task from inside another task brobeans.
