### ISSUE TITLE
Is it possible to have schedules read from a database?

### ISSUE THREAD

**Issue by viperfx** [coleifer/huey#236]
Hi, 

I would like to switch from Celery to huey. I am really in need of a scheduler that look at the database and runs tasks. 

Similar to the project, django-celery-beat.

Is this currently possible with huey?

Cheers,

**Comment by coleifer** [comment]
I have no idea what "django-celery-beat" is, but I *can* tell you that Huey supports:

* Running tasks asynchronously (duh)
* Running tasks at a scheduled time (i.e., if a user signs up for an account, schedule an event to run in one week that sends them a welcome email).
* Running tasks at regular intervals (like a crontab)
* Pausing individual tasks (i.e., temporarily disable this cron job)
* Cancelling scheduled tasks (i.e., this user deleted their account, cancel the welcome email event).

It's all in the docs.

**Comment by viperfx** [comment]
Yes, it supports crontab which is perfect for my use case. I see that you can specify the task at run time using the tasks file. But I am wondering its possible to periodically check a db for crontab values, and have the worker execute at those times. 

I think the answer is that - this is currently not supported?

So if I was to fork the project, what parts of the code would be the right places to look at for attempting a solution to this?

**Comment by coleifer** [comment]
That's not supported by Huey because there's no actual need for huey to support that. You can build that on top of Huey incredibly easily. For example, you could have a cron task that runs every minute and all it does is check your DB config to see what other tasks should run and then run them:

```python
@huey.periodic_task(crontab(minute='*'))
def conditionally_run_other_tasks():
    # query database and see if some tasks should be run.
    # call the tasks in here and they will be enqueued and executed
```

**Comment by viperfx** [comment]
Ah,  I see! Okay. I will attempt this approach. Does huey have methods to check current time against crontab? I am currently storing crontab expressions in the db. If you could point to some useful functions/lines, that would be great.

**Comment by viperfx** [comment]
I was just browsing the source code and it seems, the crontab method in api.py can validate again a datetime. I will start there.

**Comment by coleifer** [comment]
Yes, `crontab` returns a function that, for a given datetime, returns whether or not it matches the pattern specified in the crontab.
