### ISSUE TITLE
Task not being scheduled correctly.

### ISSUE THREAD

**Issue by ajurna** [coleifer/huey#237]
Here is the huey config.

    HUEY = {
        'name': DATABASES['default']['NAME'],  # Use db name for huey.
        'result_store': True,  # Store return values of tasks.
        'events': True,  # Consumer emits events allowing real-time monitoring.
        'store_none': False,
        'always_eager': False,  # If DEBUG=True, run synchronously.
        'store_errors': True,  # Store error info if task throws exception.
        'blocking': False,  # Poll the queue rather than do blocking pop.
        'connection': {
            'connection_pool': ConnectionPool(host='127.0.0.1', port=6379, max_connections=100),
            'read_timeout': 1,  # If not polling (blocking pop), use timeout.
            'max_errors': 1000,  # Only store the 1000 most recent errors.
        },
        'consumer': {
            'workers': 8,
            'worker_type': 'thread',
            'initial_delay': 0.1,  # Smallest polling interval, same as -d.
            'backoff': 1.15,  # Exponential backoff using this rate, -b.
            'max_delay': 10.0,  # Max possible polling interval, -m.
            'utc': True,  # Treat ETAs and schedules as UTC datetimes.
            'scheduler_interval': 1,  # Check schedule every second, -s.
            'periodic': True,  # Enable crontab feature.
            'check_worker_health': True,  # Enable worker health checks.
            'health_check_interval': 1,  # Check worker health every second.
        },
    }

here is the task i'm trying to run.

    @db_periodic_task(lambda x: True, name='monitor_huey')
    def monitor_huey():
        print('\n\n\n', timezone.now(), '\n\n\n')
        message = PUBSUB.get_message()
        while message:
            print(timezone.now(), message)
            message = PUBSUB.get_message()

in this example it should run whenever it is inspected.
It seems to only run once a minute or so.

This is in Django and using the run_huey command.

**Comment by ajurna** [comment]
i was under the impression from #207 that i could just change the validator function and this would allow me to run a task at an arbitrary time in seconds.

But it appears the scheduler is designed to only run periodic tasks once a minute.

i'm looking into this to see if it is a trivial fix to allow per second scheduling

**Comment by ajurna** [comment]
created a PR #238 with the fix i applied.

**Comment by coleifer** [comment]
Hey, yes, the information is misleading in #207 and is no longer correct. The fact is that the finest granularity you can achieve using periodic tasks is once per minute. The reason per-second isn't supported is because to do that we'd need to enforce that the scheduler runs once per second and I just don't think that's always realistic -- especially if your huey instance is talking to a Redis server across the internet or has a large number of tasks to read/write.

**Comment by coleifer** [comment]
You *can* run the scheduler at once per second and, inside a periodic task, schedule tasks at sub-minute intervals, but that's more a hack than anything else.

**Comment by ajurna** [comment]
after thinking about what you said and looking at issues with the scheduler locking up i came up with a better solution.

if you need tasks at a sub minute interval make a governer task that queues up hte next minutes work.
It will not be 100% precise but it will allow you to approximate sub minute times. example below.
This works close to 15 seconds but it can be off by ~2 seconds either way.

    @periodic_task(crontab(minute='*'), name='monitor_huey')
    def monitor_huey():
        do_monitor_work.schedule(delay=15)
        do_monitor_work.schedule(delay=30)
        do_monitor_work.schedule(delay=45)
        do_monitor_work.schedule(delay=60)

**Comment by tehfink** [comment]
@ajurna : Have you worked out an efficient way for scheduling such tasks with a delay longer than 60s?

**Comment by ajurna** [comment]
Nope. I ended up writing a separate service to handle that functionality.

**Comment by coleifer** [comment]
> Have you worked out an efficient way for scheduling such tasks with a delay longer than 60s?

What do you mean "with a delay longer than 60s"? This ticket is about running periodic tasks at intervals lower than 60seconds...it has nothing to do with "delays".

**Comment by tehfink** [comment]
@coleifer : ajurna's code suggestion uses various values for `delay`, e.g.:
>     do_monitor_work.schedule(delay=60)

**Comment by coleifer** [comment]
@tehfink -- you can specify an arbitrary delay -- any amount of time you like.

**Comment by tehfink** [comment]
@coleifer: thanks for the reply. By asking about a ‘delay’ larger than 60s, I was referring to how to simulate dynamic periodic tasks (like in celery-beat), since it doesn’t seem that Huey natively supports this?

@ajurna: would you mind sharing your config, if possible?

**Comment by ajurna** [comment]
@tehfink unfortunately i don't have a config. after doing some testing i ran into lots of issues with by the second scheduling that ended up in abandoning this. as i said i rewrote the part that i wanted to update this often as a service.

**Comment by coleifer** [comment]
Periodic tasks take a callable as their first parameter. It accepts a
datetime and returns true or false if the task should run. The crontab
function generates a callable but you can supply your own.

**Comment by tehfink** [comment]
@coleifer: thanks for the reply. Could you give examples of working code? Because I tried your suggestions [here](https://github.com/coleifer/huey/issues/277#issuecomment-373903902), but they resulted in errors…
