### ISSUE TITLE
Re-trying tasks lost in execution

### ISSUE THREAD

**Issue by dmcmulle** [coleifer/huey#239]
Is there any way we can add functionality to retry tasks that were interrupted via SIGTERM?  Or does this need to be something handled outside of Huey?

I have a job queue where every job must be completed, but if it's in progress and the server shutdown etc, the job is lost in the abyss.

I know idempotent tasks may go against what generally people are using huey for.  Obviously, I wouldn't want to send an email list out that was interrupted twice.  But, in my situation here, I have some tasks that need to finish, where they crash or work doesn't matter, but being interrupted by server maintenance/auto-scaling seems impossible to detect at the moment with huey.

Thanks

**Comment by coleifer** [comment]
Check out the docs on consumer shutdown: http://huey.readthedocs.io/en/latest/consumer.html#consumer-shutdown

Huey supports graceful shutdown via `SIGINT`. If you want to stop the consumer but allow the workers to finish any tasks they are currently executing, use `SIGINT`.

By contrast, `SIGTERM` will stop the consumer and workers regardless of whether they are working on a task.

**Comment by dmcmulle** [comment]
Hi @coleifer,

I did take a look at the consumer shutdown, but this doesn't satisfy my needs as I am not in control of the servers and cannot issue a SIGINT.  I am using heroku, which from what I've seen seems to want you to design your applications to be 'crash resistant'.

Furthermore, I'd like to post my solution to this problem using your library.  Just in case others need a solution to this problem.  I have tested this solution in production for 7 days now with no issues.

Please note I am using Django 1.11 and huey 1.2.3 and Python 3.6.1

```
@db_task(include_task=True)
def the_task_that_must_complete(task: QueueTask):

    def ack(_job_uuid):
        """
        Every 30 seconds, update the database entry.  If this thread dies, then the worker has died, and we need to re queue the job with the periodic 'heal' task
        :param _job_uuid:
        :return:
        """
        ack_report = TheTaskThatMustBeCompleted.objects.get(uuid=_job_uuid)

        # While the task that must be completed status is not 'done'
        while ack_report.status != TheTaskThatMustBeCompleted._STATUS_DONE_:
            # update it
            # ack sent
            try:
                ack_report.updated_on = timezone.now()
                ack_report.save()
                time.sleep(30)
                # Update the report with what's in the database
                ack_report = TheTaskThatMustBeCompleted.objects.get(uuid=_job_uuid)
            except:
                print("Ack interrupted with error")
                break

        print("%s ack done." % _job_uuid)

    ack_thread = threading.Thread(target=ack, args=(task.task_id,)).start()

    try:
        # Do some long work that must be completed...
        job.status = TheTaskThatMustBeCompleted._STATUS_DONE_
        job.save()
    except:
        print("The exception")

@db_periodic_task(crontab(minute="*/1"))
def heal():
    """
    Re queues jobs that failed
    :return:
    """
    print("Healing Queue...")

    list_of_jobs_that_probably_failed = TheTaskThatMustBeCompleted.objects.filter(
        updated_on__lt=timezone.now()-timezone.timedelta(minutes=10)
    ).exclude(
        Q(status=TheTaskThatMustBeCompleted._STATUS_DONE_) | Q(status=TheTaskThatMustBeCompleted._STATUS_QUEUED_)
    )

    for j in list_of_jobs_that_probably_failed:
        # Re-schedule job
        event = the_task_that_must_complete.schedule(delay=30)

        # Point new UUID to task in DB
        j.uuid = event.task.task_id
        j.save()
        print("Task %s was found to be broken, task attempted and sent back to queue" % event.task.task_id)`

```
If the 'ack' thread dies during execution, then we know that the job failed and needs to be re-queued via the 'heal'.
