### ISSUE TITLE
Add multiprocessing support (redux)

### ISSUE THREAD

**Issue by apendleton** [coleifer/huey#24]
Per your comment, here's an issue to discuss adding multiprocessing support.

The main limitations that became obvious when trying to do this last time were around the fact that pretty much all inter-worker communication using the Python multiprocessing stack takes place via Pickle (e.g., when you push something onto a shared queue, it gets pickled, and reconstructed on the way out of the queue when a child process retrieves it).  This had/has a couple of concrete ramifications:
* Everything that gets shared has to be picklable.
* Care has to be taken to keep object graphs from getting out of control, since you can end up inadvertently pickling a *lot* of stuff if your objects have attributes that have attributes that have attributes, ad infinitum, that all have to be pickled -- and the first point makes it worse, since all of that has to be picklable.  I was able to work around some of these issues by hiding some stuff from pickle and papering over it via property decorators, but it ended up feeling pretty hacky.  Particular example: one of the objects that needed to be shared in the implementation held a reference to the command queue, which in turn, when using the redis backend, held a connection to the redis connection, which wasn't picklable.
* You can't rely on the master and the workers operating on the same copy of a data structure, since it gets copied during pickling/unpickling.  As an example, this caused weirdness within the consumer code with tracking retries of commands, because retries were stored as a property on the command object, so child workers' decrements of this value weren't seen by the parent process.

**Comment by coleifer** [comment]
Master contains some changes to add multiprocessing and greenlet worker classes. Still working out the kinks, but that's the direction huey is headed.
