### ISSUE TITLE
Force sheduled task to be executed or change its execute_time

### ISSUE THREAD

**Issue by zzzuzik** [coleifer/huey#240]
HI @coleifer 

Is there a way to force a scheduled task to run or to change its execute_time.
I can see a workaround - revoke and schedule it again; however, I don't have tasks args on my hand at that time, and wasn't able to find an example how to get them from the existing task

Thank you

**Comment by coleifer** [comment]
At present, you'll need to revoke the task and then run it again with the new execution time.

I can see possibly adding a convenience method to the `TaskResultWrapper`, `TaskResultWrapper.reschedule`, but am not sure how feasible that would be without looking into the code some.

**Comment by zzzuzik** [comment]
Is possible to get the args of the revoked task to pass them into the new scheduled one?

**Comment by coleifer** [comment]
Yep, it's possible, the short version is:

```python

@huey.task()
def some_function(a, b):
    pass

task_result_1 = some_function(3, b=4)
print task_result_1.task.data
# ((3,), {'b': 4})
print task_result_1.task.execute_time is None
# True

task_result_2 = some_function.schedule(args=(1, 2), delay=3600)
print task_result_2.task.data
# ((1, 2), {})
print task_result_2.task.execute_time
# datetime.datetime(2017, 7, 31, 23, 46, 59, 460309)
```

**Comment by zzzuzik** [comment]
That makes total sense. 

The story behind it is that I schedule one task with different args with `eta = now()+1 year` to have a queue. Next, in a different task I go through that queue and see that I have resources to execute them. There is a lot of blows and whistles around that including priority, ownership, resources availability, etc. When I have a proper condition I want to execute the scheduled task (with unknown to me args).

You know, I plowed through the docs/github to find a way to get a revoked task args. Went through the `HUEY `and `QueueTask `code to find a method. Internally, I stored only `taks_id` of a scheduled task and next revoke it by id. Will I be able to get the args based on a `task_id` only.

**Comment by coleifer** [comment]
> Will I be able to get the args based on a task_id only?

Theoretically yes. You can call the `huey` instance's `pending()` and `scheduled()` methods to get the lists of tasks that are waiting in the queue to be processed or sitting on the schedule waiting til their specified execution time (respectively). Those methods will return `task` objects and you should be able to access the `data` attribute to get the args/kwargs.

**Comment by coleifer** [comment]
Like I said, though, there's a race condition such that the task could be executed while you're combing through the lists of `pending` and `scheduled` tasks...but sounds like in your case that may not come up in practice?

**Comment by zzzuzik** [comment]
yes, all of them are scheduled +1 year for `eta`. And, for sure, will be kicked off within a day or two.
As always, thank you for your quick help.  
Since my first question: #74 `Huey` is the most stable and enjoying part in our system.
