### ISSUE TITLE
Running huey with docker in a separate container

### ISSUE THREAD

**Issue by Rajesh-Yogeshwar** [coleifer/huey#242]
I have not been able to find an example anywhere that can point at how to setup huey with docker. I have a Django container, Redis container and Postgres container. Given that this is the setup can someone point as to how can I get `huey ` to talk to my postgres. Because currently when I tried I got following error
![screenshot from 2017-08-23 18-18-17](https://user-images.githubusercontent.com/7311146/29616537-780f22e2-882f-11e7-8537-30e567ef3600.png)

What I want to understand is where can I configure as to how to point to my postgres container in huey settings so that it can talk to it.
.

**Comment by coleifer** [comment]
Shoot mane this is not the right place for this type of question.

**Comment by Rajesh-Yogeshwar** [comment]
Wow, I did not know that. I should be looking at alternative solutions in that case. Thanks.
