### ISSUE TITLE
UTC is not the default

### ISSUE THREAD

**Issue by camilonova** [coleifer/huey#243]
Using the version 1.4 I'm having this settings:
```
HUEY = {
    'connection': {'host': REDIS_HOST, 'port': REDIS_PORT, 'db': 3},
    'consumer': {'workers': 4, 'worker_type': 'thread', 'utc': True},
    #'consumer': {'workers': 4, 'worker_type': 'thread', 'utc': False},
    'always_eager': False,
}
```
No matter if `utc` is True or False, the HUEY logs are showing `consumer.start :: UTC is disabled.`

So this is not correct https://github.com/coleifer/huey/commit/b604992bf22187ae8d7d29d9111ca04bcb034ca2#diff-22ab0e1b24df9ee7410dc1959a86d339R173

By default is running with UTC disabled.

**Comment by camilonova** [comment]
@coleifer any ideas?

**Comment by coleifer** [comment]
Yeah, Django is interpreting options with action="store_true" or action="store_false" as having a default value of the opposite, which is jacking things up.

**Comment by coleifer** [comment]
I believe this is fixed. Testing locally it seemed to be doing the right thing.

**Comment by camilonova** [comment]
@coleifer Thank you
