### ISSUE TITLE
rate limiting

### ISSUE THREAD

**Issue by madisvain** [coleifer/huey#247]
Thanks for the extremely simple to use task queue. I just cam to need rate limiting and well Huey currently does not provide a way to achieve this - might there be a pattern to do rate limiting or is the answer "You should probably switch to using Celery"?

**Comment by coleifer** [comment]
Huey doesn't provide rate limiting, no, but there are plenty of third party libraries you could use in addition to Huey to achieve this. Or of course switch to celery.
