### ISSUE TITLE
Is it possible/difficult to make it work with MongoDB?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#248]
I got fed by Celery: it's too complicated and unpredictable. Looking for an alternative.

We are using MongoDB replica set in our applications. So it would nice to not deploy Redis with replication/failover and use our existing MongoDB infrastructure.

Looks like Sqlite is supported in Huey ( http://huey.readthedocs.io/en/latest/contrib.html#sqlite-storage ), so I think it should not be difficult to adapt the code to work with MongoDB.

What do you think?

**Comment by psyonara** [comment]
I've done that myself. It was very easy to do, you just write a custom back-end.
However, unfortunately I don't have the code anymore, since we switched our installation over to Redis.
But you should be able to easily write the code for it in a day or less.

**Comment by mindojo-victor** [comment]
ok, that sounds good. Do you have any readings, hints for me to do this correctly?

**Comment by psyonara** [comment]
You could copy the code from the sqlite back-end, and then change it to interface with MongoDB. I think I used pymongo, if I remember correctly. You'll have to map the individual commands to the equivalent ones in MongoDB.

**Comment by mindojo-victor** [comment]
Thank you!

**Comment by mindojo-victor** [comment]
It's a pity there is not a single docstring in the code: https://github.com/coleifer/huey/blob/master/huey/storage.py

**Comment by coleifer** [comment]
Docstrings: https://github.com/coleifer/huey/commit/59ea58df2fa9f69d8132e4ad601267b0ed8c351f

**Comment by mindojo-victor** [comment]
Great! Thank you

**Comment by mindojo-victor** [comment]
https://github.com/coleifer/huey/blob/15f0c755d3ab89b1d8910396b2e144ead8cdc78a/huey/contrib/sqlitedb.py#L80
```python
    def unqueue(self, data):
        return (self
                .delete()
                .where(Task.data == data)
                .execute())
```
If I understand correctly, `data` can be huge, because it contains task arguments. But I have to index this field/column in order to make the query fast.

**Comment by mindojo-victor** [comment]
> This method is used to "delete" a task without executing it. It is not expected that this method will be used very often.

OK

**Comment by coleifer** [comment]
> If I understand correctly, data can be huge, because it contains task arguments.

Depends on what you're passing to your task. It will be whatever parameters you specify, along with a small amount of task metadata (task ID and such). Since task parameters must be pickled and are shuffled around the network/database, it's smart to keep them small. Of course huey doesn't prevent you from sending large pieces of data around, but it's better, if possible, to offload large chunks of data to dedicated storage and simply pass around references in your tasks. i.e., instead of passing a number of rows from a database, I'd pass a list of IDs or some other compact representation.

**Comment by mindojo-victor** [comment]
> It will be whatever parameters you specify, along with a small amount of task metadata (task ID and such).

I could not find (periodic) task id in the data:
```python
>>> import base64
>>> base64.b64decode('gAMoWBQAAABxdWV1ZWNtZF9jb3VudF9iZWFuc3EAaABOSwBLAE50cQEu')
b'\x80\x03(X\x14\x00\x00\x00queuecmd_count_beansq\x00h\x00NK\x00K\x00Ntq\x01.'
>>> aa=base64.b64decode('gAMoWBQAAABxdWV1ZWNtZF9jb3VudF9iZWFuc3EAaABOSwBLAE50cQEu')
>>> import pickle
>>> pickle.loads(aa)
('queuecmd_count_beans', 'queuecmd_count_beans', None, 0, 0, None)
```

Is this correct?

**Comment by coleifer** [comment]
Periodic task ID is simply the task name.

**Comment by mindojo-victor** [comment]
What if need to distinguish between different repetitions of the same task? Will assigning a unique id break anything?

**Comment by coleifer** [comment]
See https://github.com/coleifer/huey/issues/255#issuecomment-334520003
