### ISSUE TITLE
Web interface to see the state of the consumer? Limitations?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#249]
Is there a web interface to see what were the last let's say 100 tasks: their arguments, the result, start time, end time, current state of the task (started, pending, etc.), which worker (PID) on which host is/was running it?

So if I have a periodic report run by a Huey consumer (let's say each Sunday), I want to see the history of this -- when the last report was run, its stats. And if one is running right now.

**Comment by mindojo-victor** [comment]
Ok, I found a way to keep history of tasks. I'll create a back end for Mongo db. I will add `is_deleted` field and will work with it, instead of deleting the tasks from db. I'll also record the worker info in the task.
Thank you for an easy way to hook into this with storage subclassing! Though some dosctrings would really help.

**Comment by coleifer** [comment]
> Though some dosctrings would really help.

You're absolutely right, it's not exactly clear what the APIs are intended to do and you have to know and understand Redis to get an idea of their expected behavior. I hope to fix this soon.

**Comment by coleifer** [comment]
You can use the huey events stream (Redis only at the moment) to subscribe to events from the consumers. They publish all sorts of info. http://huey.readthedocs.io/en/latest/events.html

**Comment by coleifer** [comment]
Docstrings: https://github.com/coleifer/huey/commit/59ea58df2fa9f69d8132e4ad601267b0ed8c351f
