### ISSUE TITLE
Is there a mechanism to restart consumers?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#251]
If I have a memory leaking task, how can restart the worker after it has executed the task?

**Comment by coleifer** [comment]
You'll need to implement that yourself or use an off-the-shelf library.

**Comment by mindojo-victor** [comment]
What is the correct way to restart a consumer? Sending SIGHUP? Raising `SystemExit`?

**Comment by coleifer** [comment]
At the moment the consumer doesn't implement restart. Sorry, I think I misunderstood your question.

**Comment by expresspotato** [comment]
This is desired for us as well. A simple restart worker after serving X tasks

**Comment by mindojo-victor** [comment]
@expresspotato You could count tasks in `huey.consumer.Worker#process_task` and `raise SystemExit` when you get a certain count of tasks.

You would have to override `huey.consumer.Consumer#_create_worker`.

I would like this to be more elegantly, like declaring the worker/scheduler/consumer classes somewhere instead of imperatively overriding the whole method(s) risking to confuse the passed arguments (`*args`, `**kwargs` is not good). But...

**Comment by coleifer** [comment]
That's a gross hack to work around real memory leaks in your code.

**Comment by mindojo-victor** [comment]
Practicality beats purity

**Comment by expresspotato** [comment]
I agree for most use cases just fix the memory leak - in some regard though its a question of ease of use and increasing **reliability** for users / clients / investors. We make use of over 50 different libraries in our Django project and killing off workers does help us before the memory leaks (if there even are any are nipped in the bud before causing mayhem in production).

So gross hack in all honesty not really. You can work perfection until you're blue in the face or just add a few lines of code and keep everyone else happier. No one likes crashing code or unexpected backend results so the overhead to restart something every 16 32 64 runs is insignificant.
