### ISSUE TITLE
Duplicate and lost tasks?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#253]
Looking at [`SqliteStorage .dequeue`](https://github.com/coleifer/huey/blob/master/huey/contrib/sqlitedb.py#L64 ) and similar implementation for Redis I have questions:

1. There is a race condition in the sqlite storage -- a task could be taken by several consumers, before it gets deleted

2. The task is deleted, so if a worker dies, the task is lost?

**Comment by coleifer** [comment]
I don't believe there is a race condition in either. Redis is single-threaded and brpop and rpop are atomic operations. In SQLite, we request the task ID and then execute a DELETE using that specific ID and only return the task data if the task was, in fact, deleted (atomic operation).

In the second case, if a task is accepted by a worker, then the task will be executed. If the worker dies for some reason (killed, OOM, whatever) then the task is lost, correct.

**Comment by mindojo-victor** [comment]
```
    def dequeue(self):
        try:
            task = (self
                    .tasks()
                    .order_by(Task.id)
                    .limit(1)
                    .get())
        except Task.DoesNotExist:
            return
        res = self.delete().where(Task.id == task.id).execute()
        if res == 1:
            return task.data
```
Imagine that in almost the same moment 2 consumers get the last (and the same task) before the first consumer deletes it from db. This means that 2 consumers will run the same task twice.

**Comment by coleifer** [comment]
No, because we have the check that `res == 1` before returning the task data. Only one consumer thread/process will be able to delete the row, and only that thread that does the delete successfully will return the task data.

**Comment by mindojo-victor** [comment]
Thanks for the explanation, you are correct.
