### ISSUE TITLE
Support revocation of all instances of regular tasks, and single instances of periodic tasks

### ISSUE THREAD

**Issue by coleifer** [coleifer/huey#257]
> When you revoke a regular task, it puts a marker in the key/value data-storage indicating that the task with is revoked along with some metadata about how long to revoke the task, etc. When revoking a periodic task, I wanted huey to revoke all instances of that task until such time as the task is restored or the revocation expires. So periodic tasks do not have a unique task ID.
>
> I think I'll modify the logic and extend it so that the following is possible:
>
> * Revoke an instance of a task
> * Revoke all instances of a task
> A follow-on effect of this will be to give periodic tasks their own ID. And also to support revoking all instances of a regular task as well. Best of both worlds.

refs #255 

cc @mindojo-victor

**Comment by coleifer** [comment]
5f1318663722deca079a5ae5552679e81e4d8d09

**Comment by mindojo-victor** [comment]
> The above methods are now added to decorated tasks (where formerly
they were only available on decorated periodic tasks).

Can we then simplify the api, leaving only one decorator `task`, which when passed `crontab` arguments behaves like a periodic task?

**Comment by coleifer** [comment]
I've considered that, and in fact, that is the API that the `huey.contrib.minimal.MiniHuey` uses. For the time being I'm going to pass on modifying `Huey.task`, though. There's just a little bit too much special logic in there to handle "regular" tasks (the `schedule` and `inner_run` methods, specifically).
