### ISSUE TITLE
Can we pass the raw data to the storage methods?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#258]
https://github.com/coleifer/huey/blob/master/huey/storage.py#L21

As far as I understand `data` is passed to storage methods `pickle`d.

As I am using MongoDB which allows me to store dictionaries as is in the database documents, I would find a benefit in this. For example querying tasks by a sub-field, indexing, doing some additional logic in the storage based on the contents of `data` without unpickling it.

I am suggesting to pass `data` as raw dictionaries to storage methods, so that the storage would decide the best way to store the `data` in the database.

**Comment by mindojo-victor** [comment]
Oh, it's not a dictionary, it's a tuple.
```python
('8b151c42-0eea-4eb4-b65d-f242732f2021', 'queuecmd_count_beans', None, 0, 0, None)
```
https://github.com/coleifer/huey/blob/master/huey/registry.py#L48
I think it would be nice to pass it as `namedtuple` then.

**Comment by coleifer** [comment]
I'm going to pass on this, as huey treats the data as an opaque sequence of bytes for the purposes of the storage engine.

**Comment by mindojo-victor** [comment]
> huey treats the data as an opaque sequence of bytes

What's the point of this?

> for the purposes of the storage engine.

I think you are coupling your code. The storage knows better how to store
the data.

**Comment by coleifer** [comment]
It's treated that way because the storage engine is a storage engine -- it doesn't know about the data.

**Comment by mindojo-victor** [comment]
You are limiting possibilities to extend the code. For what advantage
instead?

**Comment by mindojo-victor** [comment]
I am trying to extract from the data function arguments for my purposes.
For thus I'll to rely that you are pickling it from a certain format, this
is coupling.

**Comment by mindojo-victor** [comment]
The only reason to theat the data as a byte sequence is unqueue method. But
it should be changed anyway imo, passing it task id instead.
