### ISSUE TITLE
Restart a consumer after a certain number of tasks

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#261]
Is it easy to implement something like http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_max_tasks_per_child ?

Or if there was a mechanism to restart the consumer manually ( #251  ) it should be easy to count tasks by myself and decide whether I need to restart the consumer because of leaking memory.

**Comment by coleifer** [comment]
Right now there is not, but I don't see why we should implement a restart signal at the very least. `SIGHUP` for instance?

**Comment by mindojo-victor** [comment]
You mean why a signal? It's a common technique, afaik.
http://docs.celeryproject.org/en/latest/userguide/workers.html#restarting-the-worker

I could be wrong.



On Oct 8, 2017 19:17, "Charles Leifer" <notifications@github.com> wrote:

Right now there is not, but I don't see why we should implement a restart
signal at the very least. SIGHUP for instance?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/coleifer/huey/issues/261#issuecomment-335017544>, or mute
the thread

**Comment by coleifer** [comment]
I'm suggesting using SIGHUP to trigger a restart. I'm not too sure how to restart processes with Python from within the process itself... is it sufficient to restart the workers or should the whole consumer process get restarted, for example? Would I use the os.exec family to start the new process?

**Comment by coleifer** [comment]
Looks like I want https://docs.python.org/3/library/os.html#os.execl

**Comment by coleifer** [comment]
Wanna try out 1ffb3ddbbc20e8716743011d2a4e02802f61f659 ?

**Comment by mindojo-victor** [comment]
If I understood correctly, if the master process receives SIGHUP, it restart itself with all the workers. If a worker receives SIGHUP, only it restarts. I am interested in the second case, because other workers could be ok.

**Comment by mindojo-victor** [comment]
> Wanna try out 1ffb3dd ?

Will try this later. Thank you!

**Comment by coleifer** [comment]
I did not implement this on a worker-by-worker basis. It applies to the consumer as a whole.

**Comment by coleifer** [comment]
If you're running the worker health checker, it should be possible to just kill the worker process using the standard `SIGTERM` and huey consumer will automatically restart a new worker to take it's place?

**Comment by mindojo-victor** [comment]
This should work. If health checker always running?

**Comment by mindojo-victor** [comment]
Looks like it is. This means that all I need is there in place already. I can count number of tasks and raise KeyboardInterrupt when I think the worker should restart. It will die and the consumer will raise another worker in its place?
