### ISSUE TITLE
huey consumer ReadOnlyError: master slave switch

### ISSUE THREAD

**Issue by jychen7** [coleifer/huey#262]
I have redis cluster (A as master and B as slave at the begining) behind HAProxy (have two frontend `redis-master` and `redis-online`) and also sentinel cluster to monitor redis.
It happens once that sentinels promote B as master while huey consumer keep connection to A.

And right now Huey don't allow to pass the connection object, it only accept connection params.
https://github.com/coleifer/huey/blob/master/huey/storage.py#L272

@coleifer 
Do you think it is good for Huey Consumer to support:
1. connect via Sentinel
https://github.com/andymccurdy/redis-py/blob/master/redis/sentinel.py

2. or auto reconnect after `ReadOnlyError`?

**Comment by coleifer** [comment]
You can just subclass RedisHuey / RedisStorage and implement whatever you like.
