### ISSUE TITLE
Is it difficult to set a timeout for a task?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#263]
Per task and default for all tasks?
http://docs.celeryproject.org/en/latest/userguide/workers.html#time-limits
https://stackoverflow.com/questions/11672179/setting-time-limit-on-specific-task-with-celery

**Comment by coleifer** [comment]
It depends on what worker model you're using.

With greenlets you can wrap your task like so ([docs](http://www.gevent.org/gevent.html#timeouts)):

```python
with gevent.Timeout(60):
    this_better_take_less_than_60_seconds()
```

With threads and processes it may require a bit more effort. You *should* be able to use the signal module but I haven't tested this myself:

```
from functools import wraps
import errno
import os
import signal

class TimeoutError(Exception):
    pass

def timeout(seconds=10, error_message=os.strerror(errno.ETIME)):
    def decorator(func):
        def _handle_timeout(signum, frame):
            raise TimeoutError(error_message)

        def wrapper(*args, **kwargs):
            signal.signal(signal.SIGALRM, _handle_timeout)
            signal.alarm(seconds)
            try:
                result = func(*args, **kwargs)
            finally:
                signal.alarm(0)
            return result

        return wraps(func)(wrapper)

    return decorator
```

**Comment by mindojo-victor** [comment]
Where is most appropriate place to apply this automatically to every task when it's executed?

**Comment by mindojo-victor** [comment]
And a more general question: how to get your code executed before/after any task?

**Comment by coleifer** [comment]
I'd just subclass `RedisHuey` (or whatever) and add a new `timed_task()` helper that returns a wrapped task...something like that?

Same goes for your other question. Just subclass and extend the `task` decorator.

**Comment by mindojo-victor** [comment]
That would mean changing the client code.

**Comment by coleifer** [comment]
Correct. Because the default behavior for Huey is not to enforce timeouts or have pre-/post-execution hooks.

**Comment by mindojo-victor** [comment]
Is adding possibility to extend task behavior out of Huey's scope?

**Comment by coleifer** [comment]
No, I think that may be worth looking into. Let me take a look into the code :)

**Comment by coleifer** [comment]
What do you think about the API proposed by 0716408 ?

**Comment by mindojo-victor** [comment]
Looks good, @coleifer . Thank you! Do you ever plan yo use signals? http://docs.celeryproject.org/en/latest/userguide/signals.html#task-prerun

**Comment by coleifer** [comment]
Huey has ["events"](http://huey.readthedocs.io/en/latest/events.html). The corresponding events in huey would probably be:

* `EVENT_STARTED`
* `EVENT_FINISHED`
* `EVENT_RETRYING`

They are emitted by the consumer, if you're curious about the code: https://github.com/coleifer/huey/blob/07d7940760067a149367b14df76e08608e0fabfc/huey/consumer.py#L153-L228

**Comment by mindojo-victor** [comment]
Thank you, this works:
```python
def _handle_timeout(signum, frame):
    raise TimeoutError


@huey.pre_execute()
def timeout_start(task):

    signal.signal(signal.SIGALRM, _handle_timeout)
    signal.alarm(10)


@huey.post_execute()
def timeout_stop(task, value, exc):
    signal.alarm(0)

```

**Comment by coleifer** [comment]
I believe that should work reliably so long as you're using the process worker model (as opposed to thread / greenlet).

**Comment by coleifer** [comment]
If threads, I think it might be possible for one worker thread to clear the alarm that was set by a different worker, since the alarm is specific to the process rather than the thread (?)

**Comment by mindojo-victor** [comment]
I am not using threads, they are difficult to cook.

**Comment by Tanmaypatil123** [comment]
> Thank you, this works:
> 
> ```python
> def _handle_timeout(signum, frame):
>     raise TimeoutError
> 
> 
> @huey.pre_execute()
> def timeout_start(task):
> 
>     signal.signal(signal.SIGALRM, _handle_timeout)
>     signal.alarm(10)
> 
> 
> @huey.post_execute()
> def timeout_stop(task, value, exc):
>     signal.alarm(0)
> ```

I am getting this error `ValueError: signal only works in main thread of the main interpreter` do you know what might be the reason .. i want to add timeouts for the tasks in huey . @coleifer @mindojo-victor

**Comment by coleifer** [comment]
Those hooks are run by the worker before and after the task executes. If you are using threads then these hooks are run in the worker thread (not the main thread).

**Comment by Tanmaypatil123** [comment]
> on bro you are trying to ping a guy on a 7 year old issue.

sorry for inconvenience .. can you tell me how can I solve this problem .

**Comment by Tanmaypatil123** [comment]
I am using huey for building machine learning micro service with flask .. and now I want terminate the task execution if it takes more than 60 sec for execution . I am switching from celery to huey and faceing this signal lib issue `ValueError: signal only works in main thread of the main interpreter`.

**Comment by coleifer** [comment]
Your best bet is to implement the timing logic yourself inside your task. The key is to periodically check if you have exceeded the time limit. You can use a thread and an Event to signal this.

**Comment by coleifer** [comment]
Here's a small example showing how you might do this:

```python
@huey.task()
def limit_time(n):                                                                       
    s = time.time()
    evt = threading.Event()
    def run_computation():                                                               
        for i in range(n):
            # Here we would do some kind of computation, checking our event
            # along the way.
            print('.', end='', flush=True)
            if evt.wait(1):                                                              
                print('CANCELED')
                return

        evt.set()                                                                        

    t = threading.Thread(target=run_computation)
    t.start()
            
    # Attempt to wait for the thread to finish for a total of 10s.
    for i in range(10):        
        t.join(1)

    if not evt.is_set():
        # The thread still hasn't finished -- flag it that it must stop now.             
        evt.set()
        t.join()

    print('limit_time() completed in %0.2f' % (time.time() - s))    
```
