### ISSUE TITLE
How to prevent multiple schedulers running?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#265]
I am deploying a web app with `huey` inside Supervisor in multiple identical servers.

What can I do to prevent multiple instances of `huey` scheduling duplicates? `--no-periodic` looks like a solution, but how to automate this, as I cannot create dynamic supervisor configuration.

Also ideally it would be nice to not disable scheduler completely, but somehow check periodically that there is another scheduler is running, and if not -- take the lead.

I had a similar problem with Celery, which (I think) I have resolved:

```python
class Scheduler(celery.beat.PersistentScheduler):
    """Our scheduler for Celery Beat that skips ticks if another scheduler is already running.
    """
    max_interval = 10

    def setup_schedule(self):
        conn = me.connection.get_connection(CELERY_DB_ALIAS)
        # create the lock document if it doesn't exist yet
        now = datetime.datetime.now(datetime.timezone.utc).timestamp()
        conn.get_default_database()['tick'].find_one_and_update(
            {'_id': 'lock'}, {'$setOnInsert': {'ts': now}}, upsert=True)
        self.ts = now
        return super().setup_schedule()

    def tick(self, *args, **kwargs):
        conn = me.connection.get_connection(CELERY_DB_ALIAS)
        # MongoDB strips microseconds
        now = datetime.datetime.now(datetime.timezone.utc).timestamp()
        result = conn.get_default_database()['tick'].update_one(
            {'_id': 'lock', '$or': [
                # this process knows its timestamp which gives him priority
                {'ts': self.ts},
                # or if the last tick timestamp was long ago we must take the lead
                {'ts': {'$lt': now - self.max_interval}},
        ]},
             {'$set': {'ts': now}}
        )
        if not result.modified_count:
            # we could not take the lead -- wait, maybe the current lead dies
            return self.max_interval
        self.ts = now
        return super().tick(*args, **kwargs)
```

Not sure if this is the best solution. Maybe you have other ideas?

**Comment by coleifer** [comment]
Huey consumer is configured at start-time, so you need to pass `--no-periodic` to the consumers you want to run w/o scheduler. Anything beyond that will involve doing some hacking around the internals.

**Comment by coleifer** [comment]
You can subclass the `Consumer` class and override to your heart's content.

**Comment by mindojo-victor** [comment]
If I understand correctly I will also need to write my own `huey_consumer.py`? 
Maybe add a configuration option to be able to specify consumer class which would default to `huey.consumer.Consumer`?

And even then it's not nice to override the whole method:

```python
    def _create_scheduler(self):
        return Scheduler(
            huey=self.huey,
            interval=self.scheduler_interval,
            utc=self.utc,
            periodic=self.periodic)
```

It would be nice to be able to specify the scheduler class via a configuration option.

**Comment by coleifer** [comment]
Check out b35818b5232924c1227c74c737430361ecc1ce59

**Comment by coleifer** [comment]
Should be possible to accomplish whatever you need using something like:

```python
class MyScheduler(Scheduler):
    pass

class MyConsumer(Consumer):
    def _create_scheduler(self):
        return MyScheduler(...)

class MyRedisHuey(RedisHuey):
    def create_consumer(self, **config):
        return MyConsumer(self, **config)
```

**Comment by mindojo-victor** [comment]
Thank you!
