### ISSUE TITLE
Stop multiple periodic tasks from running at same time

### ISSUE THREAD

**Issue by vaskokj** [coleifer/huey#266]
I have a task that runs a join between two tables. The result from that query finds which records exist in each table. If there exists a record in the left table but not in the right, the code processes the the record and puts it into the other table. Sometimes this process can take 30 seconds, Sometimes it can take an hour or more.

I have this on a periodic task that runs every 15 minutes. With a single worker this isn't a problem, because it does the work and moves on to the other tasks and eventually works its way through the queue of tasks. However, I am wanting to use more than a single worker. If I do this, there is a good chance that these periodc_tasks could start running at the same time. This could potentially create issues where multiple tasks are running at the same time stepping on each other (e.g. a long running job that is taking over 45 minutes and hasn't committed its results to the database, another worker could start the job and start doing the same exact work). So is there a way to lock a periodic_task where it will only be ran one at a time? I have other periodic tasks that don't have any impact on this one particular task that can run at the same time. 

The -n option won't work as all of my tasks are periodic_tasks().

**Comment by coleifer** [comment]
You'll want to use something to store a lock and check it in the task. Huey provides a general-purpose key/value interface that you can use, or you can use Redis, etc.

Something like this:

```python
@huey.periodic_task(...)
def my_task():
    if lock_is_set():
        return
    try:
        set_lock()
        ... do task ...
    finally:
        clear_lock()
```

Perhaps I can abstract this into a context manager, but in the meantime you'll need to do it yourself.

**Comment by coleifer** [comment]
See: 0b4ccf5288f062c060046467e8a64f154340cfc6

Added a new decorator / context manager you can use with/in your tasks.

**Comment by vaskokj** [comment]
Awesome! Thanks! Appreciate the information, changes and quick feedback!
