### ISSUE TITLE
Django management autodiscover

### ISSUE THREAD

**Issue by cburger** [coleifer/huey#269]
I have picked up an issue when running Huey with Django Defender. The issue is that the `run_huey` management command looks for `tasks` modules. Other third party apps may include `tasks` modules which might not necessarily be used based on their configuration. For instance Django Defender has a `tasks.py` which imports celery, and then fails as it is not installed.

I think `autodiscover` should be called more explicitly with a setting or argument to avoid issues like this.

**Comment by coleifer** [comment]
What exception does it fail with? `ImportError`?

**Comment by cburger** [comment]
Celery is not installed as it is not required based on the configuration of Defender, thus we get the following exception.

```
File "/Users/guest/venv/lib/python3.6/site-packages/defender/tasks.py", line 6, in <module>
    from celery import shared_task
ModuleNotFoundError: No module named 'celery'
```

**Comment by coleifer** [comment]
Is `ModuleNotFoundError` a subclass of `ImportError`? That's strange...

**Comment by cburger** [comment]
`ModuleNotFoundError` is a subclass of `ImportError`. This is new as of Python 3.6.

https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError

**Comment by coleifer** [comment]
I think 4a5dda8 ought to fix things.

**Comment by cburger** [comment]
Thank you, this fixes the issue.
