### ISSUE TITLE
Propagate errors to sentry

### ISSUE THREAD

**Issue by camilonova** [coleifer/huey#272]
How it is possible to propagate errors to sentry?

**Comment by coleifer** [comment]
I have no idea, but please let me know in the comments if you have a specific comment about *huey*.

**Comment by camilonova** [comment]
Thing is, we currently use Huey with Django, and when we have server errors with Django they are reported to Sentry. But when we have errors on Huey they don't.

Celery have support with https://docs.sentry.io/clients/python/integrations/celery/

Maybe it can be done using a decorator and I can work on that, but I'm not sure which way do you prefer.

Please let me know your thoughts.

**Comment by coleifer** [comment]
I don't use sentry and cannot advise. I'd suggest stackoverflow (?).

**Comment by raphael-riel** [comment]
@camilonova Here's my Django's LOGGING setup to get Huey's ERRORs sent to Sentry.
```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'sentry': {
            'level': 'ERROR',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        },
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'huey.consumer': {
            'level': 'INFO',
            'handlers': ['sentry', 'console'],
            'propagate': False,
        },
        'raven': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'sentry.errors': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        '': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
```

**Comment by camilonova** [comment]
@raphael-riel Amazing. Thanks a lot.

**Comment by raphael-riel** [comment]
Huey is converting exceptions to logging.error and these are sent to Sentry as per the above configuration. 
That's why Sentry wasn't catching exceptions in the first place; because Huey intercepts and convert ems in ERROR logs. All of this to avoid the exception to bubble up and cause a failure to the worker/consumer.

**Comment by camilonova** [comment]
Cool. Thank you.
