### ISSUE TITLE
How to disable periodic tasks elegantly

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#273]
I have a periodic task which should work only in production.

I could check the environment in the task itself, but that means creating a lot dummy tasks, which I don't want.

Right now I am doing:

```python
if settings.ENV == settings.Environment.PRODUCTION:

    # hourly
    @huey.periodic_task(crontab(minute='0'))
    def bi_export_payments():
        ...
```

But I don't like this, because "Flat is better than nested".

IIUC, making a decorator will not help.

I thought maybe if `crontab` function would have a boolean argument called `never`, this would allow me to put crontab values in settings and override them. For example having different periodicity of the same task in different environments. And I could disable a periodic task just overriding my settings.

**Comment by coleifer** [comment]
Just do this:

```python
def bi_export_payment():
    ...

if settings.ENV == settings.Environment.PRODUCTION:
    bi_export_payment = huey.periodic_task(crontab(minute='0'))
```
