### ISSUE TITLE
Task names

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#276]
I am storing tasks, their events in a separate storage, so that I can see task stats and other info. 
In one particular case I am trying in a task to check that no other similar task was scheduled and is still pending (not done yet).

I am trying to rely on task's `name` to find similar tasks. But for this I don't want to rely on the default implementation detail:
https://github.com/coleifer/huey/blob/07164083f6357d63a2a192961b74c61b4fb74ebd/huey/api.py#L777

I could pass the name manually to `app.task`, but I want to automate this. 

But because of the implementation https://github.com/coleifer/huey/blob/07164083f6357d63a2a192961b74c61b4fb74ebd/huey/api.py#L134 I cannot override `task` decorator to set `name` depending on `func`.

I think setting task name as `func.__module__` + `.` + `func.__qualname__` would fix my case but also would help debugging easier, because `name` would now contain full path to the task function.

Or/and refactor the decorator to get rid of the heavy magic in it, split it in such a way, that in subclasses it would be possible to decide which `create_task` and `QueueTask` implementations to use.

**Comment by coleifer** [comment]
Since there's already a mechanism for specifying the task name, I'm not inclined to change things up.

You could write another decorator:

```python
def my_task(*args, **kwargs):
    def decorator(fn):
        task_name = '.'.join((fn.__module__, fn.__name__))
        return huey.task(name=task_name, *args, **kwargs)(fn)
    return decorator
```

Re: your last point, refactoring the task decorator, I think that has merit and will consider it for a future release.

**Comment by coleifer** [comment]
I reconsidered and pushed the change: af9ad0ab867e1458892c6869a021f081c99d39aa

I've also added the ability to pass arbitrary keyword args to the `task()` decorator method. Those kwargs are set as attributes on the QueueTask class.
