### ISSUE TITLE
A periodic task which can be scheduled manually

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#277]
I have a function I want to be run, let's say, daily. But also I want to be able to run it on demand.

How to organize my code, `task` and `periodic_task` decorators?

**Comment by coleifer** [comment]
I would:

```python

def one_func():
    pass

one_func_task = huey.task()(one_func)
one_func_cron = huey.periodic_task(crontab(...))(one_func)
```

**Comment by mindojo-victor** [comment]
Yes, I thought of this option, but it's not very convenient...

**Comment by coleifer** [comment]
It's not very convenient? Well, write a helper function...it's just python.

```python
def make_task_and_cron(cron_rules, fn):
    task_fn = huey.task()(fn)
    periodic_fn = huey.periodic_task(cron_rules)(fn)
    return (task_fn, periodic_fn)

def one_func():
    pass

one_func_task, one_func_cron = make_task_and_cron(crontab(...), one_func)
```

Think outside the box, I'm sure there are other ways.

**Comment by mindojo-victor** [comment]
It's inconvenient from interface point of view. Having two functions doing the same, with different names, causes confusion.

**Comment by coleifer** [comment]
The only reason it is the way I've written it, is to provide instances of the function that can be called normally *and* as a task (as well as a reference to the periodic task, for convenience).

You don't need that, though. You could:

```python
def task(validate_fn=None, **kwargs):
    def decorator(fn):
        task_fn = huey.task(**kwargs)(fn)
        if validate_fn is not None:
            task_fn._periodic = huey.periodic_task(validate_fn)(fn)
        return task_fn
    return decorator

@task(crontab(minute='*/10'))
def one_func():
    pass
```

It's just python.

**Comment by mindojo-victor** [comment]
Thank you for the response. Would you please comment in this line ` task_fn._periodic = huey.periodic_task(validate_fn)(fn)` as I don't know Huey that well yet.

**Comment by coleifer** [comment]
Updated.

**Comment by mindojo-victor** [comment]
Sorry for being dumb. I thought `_periodic` is an attribute used by Huey.

Now I understand: we decorate the function twice, but do not wrap `task` with `periodic_task` or viceversa. So if we call the function, the regular `task` decorator is called. At the same time we register the function for periodicity. I guess the assigning result of `huey.periodic_task(validate_fn)(fn)` to `task_fn._periodic` is not necessary, as the function is registered in a periodic task registry?

**Comment by coleifer** [comment]
Correct!

**Comment by tehfink** [comment]
> one_func_cron = huey.periodic_task(crontab(...))(one_func)

Have things changed much since you wrote this? With Django 2.0.2 and huey 1.9, I get this error:

```python
]: huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(tasks.count_beans(20))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-04fe8e306127> in <module>()
----> 1 huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(tasks.count_beans(20))

~/Documents/Code/…-virtualenv/lib/python3.6/site-packages/huey/api.py in decorator(func)
    150                 default_retry_delay=retry_delay,
    151                 validate_datetime=method_validate,
--> 152                 **task_settings)
    153 
    154         return decorator

~/Documents/Code/…-virtualenv/lib/python3.6/site-packages/huey/api.py in __init__(self, huey, func, retries, retry_delay, retries_as_argument, include_task, name, task_base, **task_settings)
    573             name,
    574             include_task,
--> 575             **task_settings)
    576         self.huey.registry.register(self.task_class)
    577 

~/Documents/Code/…-virtualenv/lib/python3.6/site-packages/huey/api.py in create_task(task_class, func, retries_as_argument, task_name, include_task, **kwargs)
    848 
    849     if not task_name:
--> 850         task_name = 'queue_task_%s' % (func.__name__)
    851 
    852     return type(task_name, (task_class,), attrs)

AttributeError: 'TaskResultWrapper' object has no attribute '__name__'
```

**Comment by coleifer** [comment]
This code doesn't make sense:

```python
huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(tasks.count_beans(20))
```

You're passing "tasks.count_beans(20)" as if it were a function, but that's actually a task result. I think you meant:

```python
huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(tasks.count_beans)
```

**Comment by tehfink** [comment]
Thanks for the reply! Unfortunately, the same error still crops up:
```python
huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(tasks.count_beans)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-be89b13aeb63> in <module>()
----> 1 huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(tasks.count_beans)

~/Documents/Code/…virtualenv/lib/python3.6/site-packages/huey/api.py in decorator(func)
    150                 default_retry_delay=retry_delay,
    151                 validate_datetime=method_validate,
--> 152                 **task_settings)
    153 
    154         return decorator

~/Documents/Code/…virtualenv/lib/python3.6/site-packages/huey/api.py in __init__(self, huey, func, retries, retry_delay, retries_as_argument, include_task, name, task_base, **task_settings)
    573             name,
    574             include_task,
--> 575             **task_settings)
    576         self.huey.registry.register(self.task_class)
    577 

~/Documents/Code/…virtualenv/lib/python3.6/site-packages/huey/api.py in create_task(task_class, func, retries_as_argument, task_name, include_task, **kwargs)
    848 
    849     if not task_name:
--> 850         task_name = 'queue_task_%s' % (func.__name__)
    851 
    852     return type(task_name, (task_class,), attrs)

AttributeError: 'TaskWrapper' object has no attribute '__name__'
```

**Comment by coleifer** [comment]
Ah, I guess `count_beans` is decorated already by the `task()` decorator?

I can look into making this work, but the correct approach is this:

```python

def count_beans(n):
    print('Counted %s beans.' % n)

count_beans_task = huey.task()(count_beans)
count_beans_cron = huey.periodic_task(crontab(minute='*/1'))(count_beans)
```

**Comment by tehfink** [comment]
Thanks for the help. Still getting used to huey!

> `count_beans_cron = huey.periodic_task(crontab(minute='*/1'))(count_beans)`

I assume you meant: `count_beans_cron = huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(count_beans)` ?

Excuting this:
```python
In [9]: count_beans_cron = huey.contrib.djhuey.periodic_task(crontab(minute='*/1'))(count_beans)

In [10]: count_beans_cron
Out[10]: <huey.api.TaskWrapper at 0x1138289b0>

In [11]: count_beans_cron(10)
Out[11]: <huey.api.TaskResultWrapper at 0x11383a630>
```
gives this result in `python manage.py run_huey`:
```
INFO:huey.consumer.Worker:Executing gather.tasks.queue_task_count_beans: c254743c-2ec9-4f5f-8826-6ec8b1aeadc2
-- counted 10 beans -
```
I was hoping to see something like: `INFO:huey.consumer.Scheduler:Scheduling periodic task…`?

**Comment by tehfink** [comment]
After going over the documentation again, I'm not sure if Huey will allow my intended-use. From here:
http://huey.readthedocs.io/en/latest/imports.html
> Because of the way this works, it is strongly recommended that all decorated functions be imported when the consumer starts up.

I want to allow a user to dynamically create a periodic task via the admin: after clicking 'save' on a `PeriodicTaskModel` with `cron_frequency` of 60 seconds, is it possible/safe to create a new Huey task using arguments (e.g.: `title`, `owner`, `cron_frequency`, etc.)? And would it be better to trigger this using `post_save` or in the model's `save()`?

**Comment by coleifer** [comment]
What you would do for dynamic tasks is store the task metadata in some kind of persistent storage, and then create a "master" task that always runs and scans the dynamic task metadata, spawning tasks as necessary.

**Comment by tehfink** [comment]
> dynamic task metadata, spawning tasks as necessary.

But would this work with periodic tasks? And what would be the benefit over creating a task after a model's `save()`?

**Comment by coleifer** [comment]
*sigh*...

**Comment by tehfink** [comment]
Sorry if it's a stupid question, I guess I don't really understand from the documentation?

**Comment by tehfink** [comment]
@coleifer  Trying to follow your code from above:

>`def count_beans(n):`
> `        print('Counted %s beans.' % n)`
>`count_beans_task = huey.task()(count_beans)`

and assuming:
```python
from huey.contrib.djhuey import HUEY as huey
```
Is it correct?

Then:
```python
In [5]: count_beans_task(5)
Out[5]: <huey.api.TaskResultWrapper at 0x10d9c9ba8>
```

Results in this error from `python manage.py run_huey --huey-verbose`:
```python
ERROR:huey.consumer.Worker:Queue exception
Traceback (most recent call last):
  File "/Users/…virtualenv/lib/python3.6/site-packages/huey/consumer.py", line 113, in loop
    task = self.huey.dequeue()
  File "/Users/…virtualenv/lib/python3.6/site-packages/huey/api.py", line 302, in dequeue
    return self.registry.get_task_for_message(message)
  File "/Users/…virtualenv/lib/python3.6/site-packages/huey/registry.py", line 87, in get_task_for_message
    klass = self.get_task_class(klass_str)
  File "/Users/…virtualenv/lib/python3.6/site-packages/huey/registry.py", line 73, in get_task_class
    raise QueueException('%s not found in TaskRegistry' % klass_str)
huey.exceptions.QueueException: queue_task_count_beans not found in TaskRegistry
```

**Comment by mindojo-victor** [comment]
> I would:
> 
> ```python
> def one_func():
>     pass
> 
> one_func_task = huey.task()(one_func)
> one_func_cron = huey.periodic_task(crontab(...))(one_func)
> ```

It's not working because of
https://github.com/coleifer/huey/blob/533c681519f10b4e354e567b6d8790f07f8d8a4d/huey/registry.py#L26

The call `huey.periodic_task` doesn't add the function to `_periodic_tasks` because it is already present in the registry as a task on demand.
