### ISSUE TITLE
retry without logging an "unhandled exception"

### ISSUE THREAD

**Issue by meagerman** [coleifer/huey#280]
There are some situations where I use Huey and I want a task to be tried, but I don't want an error logged in my logging system because the error is being "handled", it's just the handling involves a retry. 

Adding the error to the logging system pollutes my logs and hides real unhandled errors. 

For example, I use Huey to make API calls against a system. Due to some timing issues, the API call may fail now, but will pass in the future, so I retry the task later. The failure, however, is totally normal and expected. But the only way to get Huey to retry later is to let the exception bubble up, which logs the error, even though it is an expected condition. 

As another example, I fail to get a lock on some resource, and I can't run the task. There is no exception here, I just need to retry later. But the only way is to make up a new exception and raise it, again, filling up the logs with errors that are perfectly normal. 

Probably the easiest solution I can propose is to add a new exception that tasks can raise like `RetryException`, which would cause a retry to occur, but would not be logged as an unhandled exception. I can provide a patch for this if the idea is approved.

**Comment by coleifer** [comment]
As far as logging goes, the Python logging framework is pretty good and I imagine you could write a filter for your purposes:

https://docs.python.org/2/library/logging.html#filter-objects

You can retry a task silently by simply re-calling it from within the task (or calling it's .schedule() method).

I don't see a need for another API.

**Comment by tuukkamustonen** [comment]
I am manually re-queueing the "gracefully failed" tasks with something like:

```python
@huey.task()
def task_handler(...):
    try:
        ...
    except RemoteServerUnavailable:
        task.handler.schedule(...)
```

It's pretty straightforward and not bringing much boilerplate, plus manually re-queueing allows to multiply the delay with backoff factor and add some jitter (though these could be built-in `huey` features also).

But yeah, if I could just raise `RetryException` or similar, it would still be a bit less code to write / things to care of.

**Comment by meagerman** [comment]
The retry policy for a task is currently set when the task function is registered -- it is not a property of the function implementation, but how that function is registered into Huey. If the function itself starts making decisions about retries, then there would be two places that define retry policies, and these could conflict with each other. This could be mitigated by having the task passed to the function, which can be inspected for whether retries should be allowed or not.

However, retrying explicitly also loses the information that the next run is actually a "retry" that can be kept and logged in Huey. Technically, the task is not being retried, but a new task is being scheduled. This means that the retry count is lost, and so finite retries could not be implemented properly within the function itself without receiving retry counts and other meta-data as arguments.

The solution I ended up implementing is the following:

1. I raise a custom exception when I want to retry a task not due to an exception, say `SilentError()`
2. I then add a log filter on `huey.consumer.worker` that filters out any log message related to `SilentError` exceptions, so they don't look like unhandled exceptions in the logs. 

It's a fairly simple solution, but I would still argue that there is a missing need to be able to use Huey's retry system without having to raise an exception that will be logged as a critical problem. Perhaps as a task method like `mytask.retry()`.

**Comment by coleifer** [comment]
> it is not a property of the function implementation, but how that function is registered into Huey

I may be misunderstanding your comment, but I don't think this is correct.

The way huey works is the `enqueue()` method accepts a `QueueTask` instance. The `QueueTask` contains the name of the function to invoke (which was registered), the arguments passed to the function, along with the number of retries. The `Huey.task()` decorator function dynamically creates a `QueueTask` subclass which, when the function is called, is instantiated with the appropriate metadata and enqueued.

All that may be beside the point, though, when the main consideration is an API to invoke the retry logic without raising an unhandled exception (or being forced to re-schedule the task).

I'll give it some more thought.
