### ISSUE TITLE
Scheduler died

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#281]
```
[11/Dec/2017 08:46:44] 23290 ERROR huey.consumer:473 Process Scheduler died!
```
After the scheduler died because of lost connection to the db, it was not restored, so I don't have periodic tasks working. In way it's my fault because I overrode its `loop` method without wrapping with `try/except`.

But what if the scheduler dies because of other reasons (out of memory, sigterm signal, ...)? I think the problem remains.

Or am I missing something?

Maybe it's worth running the scheduler in a separate process so that it could be managed by supervisor, like Celery does?

**Comment by coleifer** [comment]
If you're running multiple processes, then yes, it's possible that the scheduler process could get killed if the OS ran out of memory. Unlikely, but not impossible. Huey *does* try to keep an eye on the workers, I suppose I could add logic to check the scheduler as well?

**Comment by mindojo-victor** [comment]
>  I suppose I could add logic to check the scheduler as well?
Yes, I think. Because scheduler is also an important part of the system.

Thank you!

**Comment by coleifer** [comment]
00c33127c012854e601d8cd09e05c51235df02de
