### ISSUE TITLE
Task lock exceptions storing within huey.results.huey?

### ISSUE THREAD

**Issue by amcclanaghan-kvh** [coleifer/huey#290]
Charles @coleifer, great repo, management and continued development.  

I am running `1.6.1` and have recently leveraged the `@huey.lock_task(<lock_name>)`; working well and as expected.  One finding/question I did have was around the `TaskLockedException`.  I have noticed that when the `TaskLockedException` is thrown, a result (exception and stack) is added to the `huey.results.huey` redis hash.  My RedisHuey instantiation is `RedisHuey(events=False, store_errors=False, store_none=False)` and my function is `return None`.  What I find is that, in instances of lock unavailability, this `huey.results.huey` just continues to populate with `TaskLockedException` entries; one per attempt no greater.  And while a redis hash can get VERY large these "results" are not something I require.  I am interested in knowing if this functionality is by design or if there is something I am missing from an implementation perspective.  Thanks!

**Comment by coleifer** [comment]
Seems like a bug, let me check it out.

**Comment by coleifer** [comment]
So, here's the relevant code (api.py):

```python
    def execute(self, task):
        if not isinstance(task, QueueTask):
            raise TypeError('Unknown object: %s' % task)

        try:
            result = task.execute()
        except Exception as exc:
            if self.result_store:
                metadata = self._get_task_metadata(task, True)
                metadata['error'] = repr(exc)
                metadata['traceback'] = traceback.format_exc()
                self.put(task.task_id, Error(metadata))
                if self.store_errors:
                    self.put_error(metadata)
            raise
```

So we're storing errors as results, but I think the fix would be to move the "store_errors" conditional up to the line reading "if self.result_store".

**Comment by coleifer** [comment]
Proposed change:

```diff
--- a/huey/api.py
+++ b/huey/api.py
@@ -356,13 +356,12 @@ class Huey(object):
         try:
             result = task.execute()
         except Exception as exc:
-            if self.result_store:
+            if self.result_store and self.store_errors:
                 metadata = self._get_task_metadata(task, True)
                 metadata['error'] = repr(exc)
                 metadata['traceback'] = traceback.format_exc()
                 self.put(task.task_id, Error(metadata))
-                if self.store_errors:
-                    self.put_error(metadata)
+                self.put_error(metadata)
             raise
 
         if self.result_store and not isinstance(task, PeriodicQueueTask):

```

**Comment by amcclanaghan-kvh** [comment]
Feels right.  I'll apply this locally and let it run in dev for a bit.  Thanks for the quick response!

**Comment by amcclanaghan-kvh** [comment]
Passing for me and desired result achieved; `huey.results.huey` much less noisy.  Thanks again!

**Comment by coleifer** [comment]
Cool I'll push a new minor release.

**Comment by coleifer** [comment]
1.7.0 pushed to pypi.
