### ISSUE TITLE
Django Huey Not Verbose

### ISSUE THREAD

**Issue by sloweclair** [coleifer/huey#293]
I am having issues where running python3 manage.py run_huey -V doesn't output anything. I have also tried it with --huey-verbose with no luck. I also tried with --logfile but that didn't output anything either. 

Let me know what other information would be helpful

Here is my config:
```
HUEY = {
    'name': 'sip',
    'events': True,
    'always_eager': False,
    'store_errors': True,
    'backend_class': 'huey.RedisHuey',
    'blocking': True,
    'connection': {
        'host': REDIS_IP,
        'port': 6379,
        'db': 8,
        'read_timeout': 60,
        'max_errors': 1000
    },
    'consumer': {
        'loglevel': logging.DEBUG,
        'workers': 2,
        'worker_type': 'thread',
        'initial_delay': 0.1,
        'backoff': 1.15,
        'max_delay': 10.0,
        'utc': True,
        'scheduler_interval': 5,
        'periodic': True,
        'check_worker_health': True,
        'health_check_interval': 1
    },
}
```

**Comment by coleifer** [comment]
What huey version are you running?

**Comment by sloweclair** [comment]
OS: Debian 9
Django: 2.0.1
Huey: 1.7.0

**Comment by coleifer** [comment]
I have no idea...are you configuring logging elsewhere in your Django settings module?

**Comment by sloweclair** [comment]
Ahh that was the key,

I setup the logging in the settings, so I added huey.consumer loggers and its working.

Thanks!

**Comment by coleifer** [comment]
Good deal, I was gonna say -- I set up a test env with Django 2.0 and it was working just fine. Cheers.
