### ISSUE TITLE
"Support multiple huey instances" breaking changes 

### ISSUE THREAD

**Issue by mojeto** [coleifer/huey#297]
Hi and thanks for a great work, 
I'm so exited about multiple queue feature https://github.com/coleifer/huey/pull/230 I started testing it with our code already.

PR states it doesn't create a configuration breaking changes https://github.com/coleifer/huey/pull/230#issuecomment-311027848

However it breaks contracts of  Django configuration `@huey.task()` and `@huey.periodic_task()` methods/decorators in a way it makes most of our code broken.

## The Problem:
- Huey `task` and `periodic_task` methods have optional `name` parameter already 
    - used to set `task_name`
    -  django configuration `task` and `periodic_task` methods/decorators don't pass `name` parameter down to Huey methods anymore
    
-  `name` optional parameter is a first argument of django configuration `task` and `periodic_task` methods/decorators
   - first positional argument used as a queue name now.  Problem for `periodic_task` especially as it has positional argument already.

This example from documentation doesn't work on master
```
 # first positional argument (validate_datetime) used as a queue name instead
 @huey.periodic_task(crontab(minute='0', hour='3'))  
    def nightly_backup():
        sync_all_data()
```

Code causing incompatibilities https://github.com/coleifer/huey/blob/cfdc87cc7f438dac7b6b68db9f34f9b83b31ff80/huey/contrib/djhuey/configuration.py#L91-L97

Making first argument optional and second argument required (for periodic_task) is very unusual and in fact force to always specify both positional arguments or call function with keyword parameter `@huey.periodic_task(validate_datetime=crontab(minute='0', hour='3'))` in our case. 

As this feature isn't released yet, would you consider to change django configuration `task` and `periodic_task` functions to be backwards compatible?

Cheers

**Comment by coleifer** [comment]
> Making first argument optional and second argument required (for periodic_task) is very unusual and in fact force to always specify both positional arguments or call function with keyword parameter @huey.periodic_task(validate_datetime=crontab(minute='0', hour='3')) in our case.

Yes, this should have been caught when I was reviewing. Gross. Will push a fix. cc @Sebubu

**Comment by coleifer** [comment]
I think this should address the issue: 8181e32d69afc4ece0cd39438b757503aa987744

It restores the original behavior and, to specify a different queue, requires that you use `queue='some-queue'`.

**Comment by coleifer** [comment]
cc @MarcoGlauser
