### ISSUE TITLE
Workers seem to stop respoding after few hours of idleness?

### ISSUE THREAD

**Issue by umang0202** [coleifer/huey#298]
just started using huey, it seems our workers stop responding after being idle for a few hours. Restarting the workers fixes it.

I'm using django_huey and are starting the workers using a systemd service.

Anything I'm missing?

**Comment by coleifer** [comment]
Hmm, I have no idea. Perhaps you can share your Huey configuration? Are any errors being logged? Using redis? You polling or using the blocking approach?

**Comment by umang0202** [comment]
Here's our configuration (from django's settings.py):

```
HUEY = {
    'name': database_name,  
    'result_store': True, 
    'events': True,  
    'store_none': False,
    'always_eager': False, 
    'store_errors': True,
    'blocking': False,
    'backend_class': 'huey.RedisHuey',
    'connection': {
        'host': host_name,
        'port': 6379,
        'db': 3,
        'connection_pool': None,
        'read_timeout': 1,
        'max_errors': 1000,
        'url': None,
    },
    'consumer': {
        'workers': 20,
        'worker_type': 'thread',
        'initial_delay': 0.1,
        'backoff': 1.15,
        'max_delay': 10.0,
        'utc': True,
        'scheduler_interval': 1,
        'periodic': True,
        'check_worker_health': True,
        'health_check_interval': 1,
    },
}
```
No errors are being logged. Logs are full of "Sleeping for 0.999596118927002"s

**Comment by coleifer** [comment]
OK, yeah that makes sense. Do the workers continue logging "Sleeping for X"? Or at some point do the log messages cease?

When you restart the huey consumer, does it run through any backlog of messages from when it was not responsive?

Please try and paint a picture here, as there's some issue in your deployment and I'd like to help you diagnose it.

**Comment by coleifer** [comment]
Please comment with additional details and I will reopen the issue.

**Comment by umang0202** [comment]
Turns out our db connections were dying out. We caught the error and forced a ```django.db.connection.close()
```
That worked!

**Comment by coleifer** [comment]
Glad you got it sorted out, thanks for the update.

**Comment by expresspotato** [comment]
As this was really DB related just wanted to mention the following... We use the following decorator to close the connection after tasks are run. As our server will eventually close stale connections.
```

def close_db_connection(ExceptionToCheck=Exception, raise_exception=False, notify=False):
    """Close the database connection when we're finished, django will have to get a new one..."""
    def deco_wrap(f):
        @wraps(f)
        def f_wrap(*args, **kwargs):
            try:
                return f(*args, **kwargs)
            except Exception as e:
                raise e
            finally:
                from django.db import connection; 
                connection.close();

        return f_wrap
    return deco_wrap
```
