### ISSUE TITLE
Check if the consumer is working

### ISSUE THREAD

**Issue by diegocortassa** [coleifer/huey#305]
Hi,
Is there a way to know if a task is running? I know I can get the list of queued task with huey.pending() but I couldn't find a way to check if the consumer is working on a task when there is no other pending task.
Thanks!

**Comment by coleifer** [comment]
You can use the consumer event-stream to subscribe to events:

http://huey.readthedocs.io/en/latest/events.html

**Comment by diegocortassa** [comment]
I'll have a look at it, thanks for your help!
