### ISSUE TITLE
How to rate limit a task across all the processes and threads running it

### ISSUE THREAD

**Issue by slidenerd** [coleifer/huey#307]
First of all, thank you for the awesome library. I am trying to build a URL scraper which involves pinging an external API every 15 mins with a rate limit of 300/m I would like to save the data to the database after getting everything. My flow is somewhat like this
```

#Run this every 15 minutes
@task 
def map_reduce(self):
    #Fetch urls in parallel
    map(map(url) for url in list_of_urls) | reduce()

# Rate Limit this map to 300 requests per minute
@task(rate_limit='300/m')
def map(url):
    ...
    return data

#Get all the results from all the URLs
@task
def reduce(data):
    #Store to database
```

I searched the issues list and could not find anything on rate limits. How do I ensure map() is called only 300 times a minute. Thank you for your advice in advance

**Comment by coleifer** [comment]
Huey does not support rate limiting. You'll want to look into a third-party library to handle that. Upon being rate-limited, you'd probably want to force a retry, so you could raise a `RetryTask` exception, which will re-enqueue for retry.

There are a lot of ways you could work around this inside the map_reduce master-task as well.
