### ISSUE TITLE
Flush lock(s) on restart. <feature request>

### ISSUE THREAD

**Issue by amcclanaghan** [coleifer/huey#308]
@coleifer Great work on huey.  :-)

I have been successfully leveraging "lock(s)"; great addition/implementation.  I have, however, noticed the following recently in production; stale locks.  It appears that locks are managed via the 'huey.results.huey' redis hash.  Upon stop/start of huey the locks *can* persist within the ''huey.results.huey'' redis hash.  Upon restart huey will not service the stale methods/tasks (locks) because a lock entry still exists.

Scenario:

Huey running task "hello-world" every 5 minutes (or any decorated lock that may be killed).
Huey restarted via Supervisor (huey cycles as per request)
Huey task "hello-world" never runs again because preexisting lock entry exists in "huey.results.huey" redis hash.

Thoughts?

**Comment by coleifer** [comment]
Check out 2509a0b -- it adds the "-f" option to the consumer, which will flush stale locks at startup. A caveat is that huey only knows about locks that are instantiated at module-load time, so huey will find stuff like this:

```python
@huey.task()
@huey.lock_task('foo')
def foo():
    pass

@huey.periodic_task(...)
@huey.lock_task('bar')
def bar():
    pass
```

But it would not see this, since it is not encountered (and therefore registered) until it is interpreted:

```python
@huey.task()
def baz():
    with huey.lock_task('baz-lock'):
        pass
```

**Comment by amcclanaghan** [comment]
Looks like a nice addition.  Will give this a go in dev.  Thanks!

**Comment by coleifer** [comment]
Please comment if you have trouble, I'll re-open if needed.

**Comment by larsderidder** [comment]
A quick follow up question: What happens in case of multiple consumers and one of them restarts? I'm assuming, looking at the code, it just clears all locks, even if a different consumer has obtained one. Is that right?

I don't think it's a problem, but it's good to know.

**Comment by larsderidder** [comment]
> 
> But it would not see this, since it is not encountered (and therefore registered) until it is interpreted:
> 
> ```python
> @huey.task()
> def baz():
>     with huey.lock_task('baz-lock'):
>         pass
> ```

In case someone else finds this while searching, I had this scenario with dynamic lock names. I see two work-arounds. One is to define a dummy task with the lock name which is simply never called, allowing Huey to find the lock and flush it with the -f command. The other is on startup of huey (function with @huey.on_startup() decorator) to do huey.task_lock('baz-lock') and then call huey.flush_locks. I use the last pattern and it works well, and looking at the Huey code, there should be no negative side effects.

**Comment by coleifer** [comment]
> A quick follow up question: What happens in case of multiple consumers and one of them restarts? I'm assuming, looking at the code, it just clears all locks, even if a different consumer has obtained one. Is that right?

Yeah, there's no way to differentiate a validly held lock versus a stale lock.

**Comment by larsderidder** [comment]
Thanks, appreciated.

**Comment by cresg820** [comment]
Hi,
i'm using this code before consumer starts:
```    
for k in Config.huey.storage.result_items():
    if '.lock.' in k:
        Config.huey.storage.pop_data(k)
```
