### ISSUE TITLE
add EVENT_ENQUEUED event

### ISSUE THREAD

**Issue by MarcoGlauser** [coleifer/huey#311]
I'm currently building a separate exporter to monitor our huey queues with prometheus. The event api of huey is perfect for this. With the currently provided events, we cannot monitor the queue length. In order to be able to monitor the queue length, I would add an EVENT_ENQUEUED event that is fired whenever a task is added to the queue. 
Where would be the best place to add this?

**Comment by coleifer** [comment]
Events are enqueued by the application, typically, whereas events apply to operations performed by the consumer/workers. Anyways, you'd have to manage a bit of state to ensure you counted the queue length correctly.

If you want to measure the length a better way is to use the storage API's "queue_size()" method, e.g.

```python
huey = RedisHuey(...)

print('queue size:', huey.storage.queue_size())
```

**Comment by coleifer** [comment]
While I understand the desire to track enqueued tasks, it's fundamentally a different type of operation from all the other events and that's why I'm opposed to adding it.

**Comment by coleifer** [comment]
Rather than using a thread, you could subclass `RedisStorage` and override the enqueue method to push an event. That might be easier implementation-wise.
