### ISSUE TITLE
Django multiple consumers

### ISSUE THREAD

**Issue by juffardm** [coleifer/huey#322]
First of all, thanks for this awesome library. 
I try to use Huey with Django, and I want to handle tasks priorities, so I try to create two huey instances, each for a different priority. From what I understood, the huey integration for Django creates a single huey object per project...
How can I create multiple huey instances, and then how could I run two consumers, one pointing at each huey instance?
Thanks for your answer! :D

**Comment by coleifer** [comment]
There was a patch that a user submitted a couple months ago that implemented multiple huey for Django, but it had some fundamental issues that showed up when merged so I rolled it back. Here it is for reference: https://github.com/coleifer/huey/pull/230

I'm not planning to implement this any time soon myself, but if a high quality patch comes through I'd definitely consider trying it again.

**Comment by aungkhant0911** [comment]
Any news on this?

**Comment by coleifer** [comment]
Huey now supports task priorities, which I believe was the motivation for this in the first place.

**Comment by pablop94** [comment]
Hi, I'm interested in implement this feature. Do you have any tip of an edge case that you know may be difficult to implement?
