### ISSUE TITLE
How to get all scheduled tasks in django?

### ISSUE THREAD

**Issue by leench** [coleifer/huey#325]
I run the consumer with ./manage.py run_huey 
in ./manage.py shell
from huey.contrib.djhuey import HUEY
HUEY.scheduled()
I got QueueException: xxx not found in TaskRegistry

but after I run a task in this shell, It will get the list.
(sorry about my english.)

**Comment by coleifer** [comment]
You need to ensure all your task modules are imported before requesting the list of scheduled tasks.

**Comment by coleifer** [comment]
The docs explain: http://huey.readthedocs.io/en/latest/imports.html

**Comment by GrayCygnus** [comment]
@leench  thank you. You helped me figure out how to obtain the huey instance object, so I could then subscribe to the events channel (HUEY.storage.listener())
