### ISSUE TITLE
Enable a task to update its status

### ISSUE THREAD

**Issue by rsirres** [coleifer/huey#326]
Is it currently possible with huey to update the status within a task ?

My idea is to give a user feedback on the progress of a task. From the guide and source code I do not see a straightforward to do it. 

BTW: Nice project 👍

**Comment by coleifer** [comment]
Not built-in, no. You can subscribe the consumer events channel, however, and listen to messages that way: http://huey.readthedocs.io/en/latest/events.html

Alternatively, you can build progress reporting into your tasks themselves. You'll probably want some external storage layer to track this stuff, but that's typically the way you would implement it. You could also dig into the internals -- the APIs are all documented -- and possibly use some of the existing features in huey to add the reporting features you want.

**Comment by zevaverbach** [comment]
@coleifer you might want to redirect /events to /signals? And sorry to be hanging out in this old beer hall, but do I take it that signals and Huey overall still don't offer anything like Celery's `update_status`?
