### ISSUE TITLE
always_eager pre and post-execute hooks

### ISSUE THREAD

**Issue by danielecook** [coleifer/huey#327]
Is there a way to get huey to execute pre/post execute hooks with always_eager set to True?

I am trying to record when a task starts and finishes with these hooks within a test environment... When I run a task using the always_eager option the pre/post hooks are not run.

**Comment by coleifer** [comment]
That's a reasonable request, but at present this is not the way huey works.

**Comment by coleifer** [comment]
Committed a change that should add this behavior. See 44a4445

**Comment by danielecook** [comment]
Awesome - thank you!

**Comment by danielecook** [comment]
Ah - I thought this would also include `task_value` and `exc` for testing... (looks like you can easily pass task_value to the callback?) but I think I can work around it for now. I looked at the code a bit and there is a large block dedicated to catching exceptions so it might be cumbersome to add. Either way this is helpful - thanks.

**Comment by coleifer** [comment]
Oh shoot, that's my bad. I can fix.

**Comment by coleifer** [comment]
a8909f2b8f539582725d32479132d232421a5434

**Comment by danielecook** [comment]
Thank you very much! Very helpful!

**Comment by coleifer** [comment]
Thanks for the report, I appreciate your help as well.
