### ISSUE TITLE
Is there any monitoring tool for Huey?

### ISSUE THREAD

**Issue by bartlomieju** [coleifer/huey#328]
I am considering using Huey in my new project. However I haven't found any info about monitoring tool for Huey.

`celery` has [Flower](https://github.com/mher/flower/), while `rq` has [rq-dashboard](https://github.com/eoranged/rq-dashboard)

IMHO it's a must to have a dashboard for controlling queues and workers. I think I could spare a few hours to help out building one if it doesn't exist.

**Comment by coleifer** [comment]
Not that I'm aware of, though it should be possible to build one to your liking with the provided APIs and/or the consumer events.
