### ISSUE TITLE
Sub 1min intervals

### ISSUE THREAD

**Issue by szaydel** [coleifer/huey#33]
I may be missing something, but I am not seeing that currently with cron style schedule anything that's under 1 is allowed. Am I correct, or is there a way to schedule something to run more than once per minute?

**Comment by vitormhenrique** [comment]
Hello, is this still the case?
I'm building a monitoring system, where the background task would be collecting the data and would like to have a better control than 1 minute interval.

**Comment by coleifer** [comment]
What kind of monitoring system would that be? What kind of monitoring will the tasks be doing, and with what frequency?

**Comment by vitormhenrique** [comment]
Hello @coleifer thanks for the response, I'm monitoring a bunch of data from several machines using a simple API, the goal is to build a real time application with all that data at the end. It takes around 2 seconds to query 1000K machines and populate a PostgreSQL database. I would like to be able to run it every 30 seconds. 
I saw that there was one pull request apparently with the feature?https://github.com/coleifer/huey/pull/100/commits/7f1d83a78a755b95d52e344a62874c1753e6831e

Also, is there a way for multiple threads consume the same queue? I'm not really sure if setting multiple threads in the consumer is enough for this to happen.

**Comment by coleifer** [comment]
Thanks for the explanation. The reason I asked is because I have a sense that a general tool like Huey may not be the best fit for what sounds like a very specific, latency-sensitive application.

You could very easily write a simple script that delegates the monitoring checks to a handful of worker threads/processes. Just have the main thread run an endless loop and on given intervals delegate work to your pool.

Do you even need a task queue? I mean...if you're just running a single task over and over, why do you need a queue at all?

**Comment by vitormhenrique** [comment]
Hi @coleifer, no worries, 
The monitoring it's not really "latency-sensitive" I want to have control of when the monitoring starts "trying" to get information, but I don't really care when the data will be available. So my idea was to have one scheduled task to to start other individual tasks to get the data.
Something like the this:

<pre><code>
@task()
def get_server_data(server):
    do_semething_here

@periodic_task(crontab(seconds ='*/30'))
def every_ thirty_ seconds():
    for each server in server_list:
        get_server_data(server)
</code></pre>

Another thing is that this is just one part of the application, another part is that the django application will act like as rest api to another solution and will get a list of servers for example to turn off, them I'll put that list into a queue, where I can have better control if the task fail, etc...

Hopefully this explains a little bit better my intent.

**Comment by coleifer** [comment]
If its not latency-sensitive, and you **don't really care when the data will be available** then....what??

**Comment by vitormhenrique** [comment]
what I meant is that I don't need the data "asap", and if it fails to get the data, that is ok...

**Comment by coleifer** [comment]
You want to spam the shit out of some ~1000K (1 million?) servers, you don't really care about latency, you don't really care if there's missing data... yeah, don't use huey. Please.

**Comment by vitormhenrique** [comment]
@coleifer no, I don't want to spam any server, I'm sorry you got that impression.
I'm building a monitoring system for miners. And I had the incorrect value of computers, it's 1k to 10k, not 1000k lol... Sorry...
For each miner I want to get the heath of the machine to build a dashboard, I "care" about the data, but I just don't need it to be "right away".
For each machine I query the temperature, fan speed, voltages etc...

**Comment by carlosporta** [comment]
Hello, @coleifer. Can you help me to solve my problem?

We have several "normal" (more than a minute schedule) tasks and Huey works perfectly. But now we are facing some situations where we need to schedule a task in less than a minute intervals. Like the following two examples:

1 - Every ten seconds execute a request and insert the data into a data warehouse
2 - Watch a directory for a specific file, if it exists, process it on a worker

Do you think, I can use only Huey for those problems, or do I have to use Huey in conjunction with another system, or Huey is not the correct library for this? What is your opinion about it?

Thank you!
