### ISSUE TITLE
Restarting a worker after executing N tasks

### ISSUE THREAD

**Issue by federicoemartinez** [coleifer/huey#334]
We have been using huey for some time and we have found that after running many tasks the workers tend to consume a lot of memory (it might be a memory leak in our tasks). What we are doing is restarting the consumer from time to time with a crontab. 

I would like to be able to set a max_tasks_per_worker setting. Do you think that is worth to be added to the consumer or we should just add it as a post execute hook? 

Thanks!

**Comment by coleifer** [comment]
This has been requested before and you can see the discussion here: #261 and to a lesser extent in #251.

You can send a SIGHUP signal to the process which will restart the consumer. As far as implementing an automatic restart after X tasks, that is not something I'm interested in adding at this time.

You can also refer to the internal `Consumer` method "_handle_restart_signal()" and subclass/extend the consumer to implement similar logic after X tasks are processed.
