### ISSUE TITLE
Implementing task inside periodical task

### ISSUE THREAD

**Issue by ChefJ** [coleifer/huey#337]
Thx for developing such a nice and easy-to-use task queue.
However, I encountered a problem today.

```@lock_task('fetchexchangerlock')
@db_periodic_task(crontab(minute='*/1'))
def fetchexchanger():
    for pagenumber in range(1,7):
        r = requests.get("https://www.feixiaohao.com/exchange/list_"+str(pagenumber)+".html")
        print("Current Page:"+str(pagenumber))
        soup = BeautifulSoup(r.content, 'html.parser')
        lines = soup.find_all('tr')
        for line in lines:
            fetchexchangerworker(line)
            counter = counter+1
@task()
def fetchexchangerworker(line):
    #some other time-consuming task
```

If the fetchexchangerworker() takes too long, a new fetchexchanger() will begin,all the tasks in queue will accumulate and eat up all the system resources.
Here's my problem:

1. Is there any simple way to ignore the fetchexchanger calls until all the fetchexchangerworker done?

2. I noticed that maybe I can check if there were tasks of specific kind in specific status using huey.storage,

> https://huey.readthedocs.io/en/latest/events.html?highlight=huey.storage

but I failed with a `TypeError: 'module' object is not iterable.

How can I fix this? 

Thanks.

**Comment by coleifer** [comment]
You can use task locks for this: https://huey.readthedocs.io/en/latest/api.html#Huey.lock_task

**Comment by ChefJ** [comment]
Well...Thanks for your comment..
I forgot to paste that lock part . I do add lock to the the fetchexchanger(),but the fetchexchanger() would   done is work quickly due to all the fetchexchangerworker() are executed as task. If fetchexchanger() hits it's next period while the fetchexchangerworker() called by the former are not all ended, the task will accumulate,which would eat the resources up..

Give a lock to fetchexchangerworker() do solve the problem , but that would be slow....

**Comment by coleifer** [comment]
Well, I'd suggest you keep the lock around the periodic task, and then once you've enqueued all the sub-tasks, just wait for them all to finish...kind of like calling `.join()` on a bunch of threads.

**Comment by coleifer** [comment]
e.g.

```python
@db_periodic_task(crontab(minute='*/1'))
def fetchexchanger():
    tasks = []
    for pagenumber in range(1,7):
        r = requests.get("https://www.feixiaohao.com/exchange/list_"+str(pagenumber)+".html")
        print("Current Page:"+str(pagenumber))
        soup = BeautifulSoup(r.content, 'html.parser')
        lines = soup.find_all('tr')
        for line in lines:
            task.append(fetchexchangerworker(line))
            counter = counter+1

        # Wait for all tasks to finish.
        for task in tasks:
            task.get(blocking=True)

@task()
def fetchexchangerworker(line):
    #some other time-consuming task
```

**Comment by ChefJ** [comment]
That's awesome !!!
Thanks a lot for giving me this fantastic solution!
