### ISSUE TITLE
Docker Healthcheck with Django

### ISSUE THREAD

**Issue by nerdbaggy** [coleifer/huey#338]
I am running Huey with Django inside a docker container. I want to use the health check feature in docker to check on my workers. But looking through the API I can't really find a way to monitor how the worker is doing when started with run_huey. Any suggestions?

**Comment by coleifer** [comment]
No idea. If you're using threads/green threads for your workers you should be able to simply monitor the consumer process, but if you're using process workers it'll be more complicated.

**Comment by jedie** [comment]
I also would like to have a health check for docker. Any new idea around this?
