### ISSUE TITLE
ability to start workers from python? (without external services)

### ISSUE THREAD

**Issue by FelixSchwarz** [coleifer/huey#343]
I have a Python script which does a lot of computations which are easily parallelizable (CPU-bound). Previously I always wrote custom code (based on Python's multiprocessing module). Now I'm looking for some library which provides that glue code (less code to maintain and eventually the option to distribute the compute tasks over multiple computers).

But I'd like to start small: I'm looking for a way to create multiple workers (consumers in huey speak?) from a (CLI) script and distribute the load over these workers. At first I don't want to use external daemons (e.g. reddis). Overhead and latency of huey is likely not a huge concern as the compute jobs themself take at least a few seconds.

I assume something like this is possible with huey but I could not find out how. Should I start looking into simpledb and just create the simpledb worker from the main script? (Ideally the solution should also work on Windows.)

**Comment by coleifer** [comment]
I don't think that `huey` is what you're looking for. Or, maybe it is, but it's designed to read from some persistent queue/message broker. The consumer coordinates the receipt of messages, running the worker processes, distributing tasks, etc. I don't know if huey works on windows in multi-processing mode, probably not.

**Comment by FelixSchwarz** [comment]
Thank you for quick answer. I'll check if I can make it work quickly - otherwise I'll look for other options :-)

**Comment by FelixSchwarz** [comment]
> I don't know if huey works on windows in multi-processing mode, probably not.

Just so others might save some time if they research this: Huey Huey doesn't work on Windows (at least for worker processes) due to Windows limitations. Basically everything which is passed to the workers must be "picklable" and on Windows only static top-level functions can be pickled ([source](https://stackoverflow.com/a/8805244/138526) and [source](https://stackoverflow.com/a/26026069/138526)). Internally huey relies a lot on dynamically creating callables which are passed to workers.

So again a case where Windows is just too limited. I guess I forget too often how easy Unix/Linux is - until I have to build something which also works on Windows...
