### ISSUE TITLE
How to create a task function with an argument using huey?

### ISSUE THREAD

**Issue by kc1** [coleifer/huey#345]
[![enter image description here][1]][1]

Based on https://stackoverflow.com/questions/51959304/typeerror-decorator-missing-1-required-positional-argument-func, I can use huey to create a task function without an argument using:

    some_long_calculation_task = my_huey.task()(some_long_calculation)

However, I'd like to be able to pass in an argument, so I'd need something like:

    some_long_calculation_task(arg) = my_huey.task()(some_long_calculation(arg)).

How would I create a task function with an argument using huey?

  [1]: https://i.stack.imgur.com/JWGIw.png

**Comment by coleifer** [comment]
This is basic Python function composition. This is not a huey problem and I suggest you take the question to stackoverflow.

**Comment by coleifer** [comment]
If you have:

```python

def something(s):
    return s + 1

something_task = huey.task()(something)

# call something_task with an argument:
something_task(3)  # equivalent to "something(3)" but called as a task
```
