### ISSUE TITLE
Terminate or killing task process?

### ISSUE THREAD

**Issue by Balykovsky** [coleifer/huey#350]
How can i stop task when it's already running?

**Comment by coleifer** [comment]
It's complicated. And it may depend on the worker type you select.

If you are running the consumer with the "process" worker-type, you should be able to just kill the worker process. As long as you're running the worker health check, huey will determine that a worker has died and spawn a new process.

If you are using thread or greenlet/gevent, there is no such option. There is no "clean" API for killing a running thread in Python. With gevent it is only possible to kill a greenlet if it should yield at some point.

On the other hand -- you can design your tasks such that they check for some kind of a signal from another process -- and upon receiving such a signal, will terminate. But the consumer itself is not responsible for this. You can even use the huey result-store for communication.

This is a very vague question so it's hard to be more specific.

**Comment by Balykovsky** [comment]
@coleifer Thank you for response. i'll try to solve this problem and then post it here in comments.

**Comment by Pyrokine** [comment]
I supposed to add this notice to the document to notice the reader.

**Comment by JeffreyCA** [comment]
@coleifer is there any way to get the PIDs of the workers if using "process" type?

**Comment by coleifer** [comment]
You can use the regular system tools on your machine to inspect the list of running processes. There will typically be 1 main, 1 scheduler, and *n* workers if using the process worker type.
