### ISSUE TITLE
Using Huey with Supervisord 

### ISSUE THREAD

**Issue by bobozar** [coleifer/huey#354]
Hello Coleifer,

Can I get a comprehensive tutorial on how to use supervisord to monitor Huey? 

I saw the below in one of the issues you attended to.

[program:blog_queue]
directory=/whatever/path/
command=/path/to/bin/huey_consumer.py `blog.main.huey` --logfile=/path/to/huey-blog.log -S 300

the command code got me missing something. The highlighted code above, is blog the name of the app?

**Comment by coleifer** [comment]
I don't know what you mean by "app". It's a path to a Python module / class. So blog.main is a module and "huey" is an object in the blog/main.py file.
