### ISSUE TITLE
Run Huey in Django automatically

### ISSUE THREAD

**Issue by yinxiangming** [coleifer/huey#355]
Hi there. Is that possible to run Django management command "python manage.py run_huey" automatically after deployment? I am using Dokku now and have to run this command manually after each push. 

I tried to add the command in Dokku postscript in app.json. But found it will block the push process at the end. Have to give up finally. 

Thanks in advance.

**Comment by coleifer** [comment]
This is so irrelevant and off-topic

**Comment by Ak4zh** [comment]
Sorry to reopen the issue.
I am having similar issue.
I know I have to run the command `python manage.py run_huey` to start consumer but I don't know how to run this command in background when using a dockerfile for django.

It will be really helpful if you can add a dockerfile example in example section.

I have read your recommendation to use supervisor for this purpose and I tried but faced many errors setting due to lack of example.
A simple addition in docs part on how to run consumer with docker using a start.sh or something or an code example in django_ex for supervisor setup will be really useful.

Many user like me (still at learning stage for docker) opt huey because they find celery to be complex requiring lot's of configs.

**Comment by coleifer** [comment]
Why would you run it in the background, though? My understanding of how docker should work is that you'd run the consumer by itself, in the foreground, in a container. Your web app would run in a container. They'd talk to a redis instance (or whatever) in a container. etc.

If you just want to run it in the background, then background it with an "&".

**Comment by Ak4zh** [comment]
I have this Dockerfile that builds and run my django app:

```
# Use an official Python runtime as a parent image
FROM python:3.7
LABEL maintainer="hello@wagtail.io"

# Set environment varibles
ENV PYTHONUNBUFFERED 1
ENV DJANGO_ENV production

COPY ./requirements.txt /code/requirements.txt
RUN pip install --upgrade pip
# Install any needed packages specified in requirements.txt
RUN pip install -r /code/requirements.txt
RUN pip install gunicorn

# Copy the current directory contents into the container at /code/
COPY . /code/
# Set the working directory to /code/
WORKDIR /code/

RUN python manage.py collectstatic --no-input
RUN useradd wagtail
RUN chown -R wagtail /code
USER wagtail

EXPOSE 8000
CMD exec gunicorn valueplusbot.wsgi:application --bind 0.0.0.0:8000 --workers 3
```

I am trying to find a way so this same docker image first do starts my huey comsumer and then run my app with gunicorn

**Comment by vishwakarma0** [comment]
heyy @Ak4zh did you find the solution to run huey with docker?
It would really mean a lot, if you can provide some assistance to me as well, I'm also stuck on the same.
Please respond asap, I'm running out of time and patience.

**Comment by Ak4zh** [comment]
@vishwakarma0 Create a start.sh script

```
set -o errexit
set -o pipefail
set -o nounset

python3 /app/manage.py run_huey &
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
```

**Comment by coleifer** [comment]
It's not quite advisable to run Huey and Django in the same docker container. See https://stackoverflow.com/questions/19948149/can-i-run-multiple-programs-in-a-docker-container

https://docs.docker.com/config/containers/multi-service_container/

Docker docs:

>It is generally recommended that you separate areas of concern by using one service per container. That service may fork into multiple processes (for example, Apache web server starts multiple worker processes). It’s ok to have multiple processes, but to get the most benefit out of Docker, avoid one container being responsible for multiple aspects of your overall application. You can connect multiple containers using user-defined networks and shared volumes.

**Comment by vishwakarma0** [comment]
@jedie yes you are right, but the thing is I cant use docker-compose for production, I use kubctl, so most of my configuration needs to be in Dockerfile only

**Comment by dwjorgeb** [comment]
> It's not quite advisable to run Huey and Django in the same docker container. See https://stackoverflow.com/questions/19948149/can-i-run-multiple-programs-in-a-docker-container
> 
> https://docs.docker.com/config/containers/multi-service_container/
> 
> Docker docs:
> 
> > It is generally recommended that you separate areas of concern by using one service per container. That service may fork into multiple processes (for example, Apache web server starts multiple worker processes). It’s ok to have multiple processes, but to get the most benefit out of Docker, avoid one container being responsible for multiple aspects of your overall application. You can connect multiple containers using user-defined networks and shared volumes.

while I totally understand the reasoning, if your huey's task is working with django models or other django-related objects, it *needs* to be on the container running django, unless you create another container with a clone instance of django (same models, etc) just to run the `manage.py run_huey`, which just seems unefficient.

**Comment by coleifer** [comment]
>unless you create another container with a clone instance of django (same models, etc) just to run the manage.py run_huey

That's exactly what you should do.

**Comment by dwjorgeb** [comment]
> That's exactly what you should do.

understood. 

I actually already have a container running in similar fashion just to run cronjobs and other tasks, but it always felt like somewhat of a hacky solution to me tho and always wondered if there was a neater way of doing it.

Will probably move my cronjobs to Huey's scheduled tasks, as it simplifies the flow significantly.

Thanks for the reply.

PS: cute cat 😸

**Comment by smseidl** [comment]
> > unless you create another container with a clone instance of django (same models, etc) just to run the manage.py run_huey
> 
> That's exactly what you should do.

@coleifer - will this work if you are using the sqllite backend for Huey and the models?  Or do you need to be using Redis & Postgres for this to work?

**Comment by coleifer** [comment]
You’ll need to have the SQLite db on a shared volume.
