### ISSUE TITLE
Raising exception when in `always_eager` mode

### ISSUE THREAD

**Issue by kwilcox** [coleifer/huey#366]
I didn't spend a ton of time digging into this but it appears that when in `always_eager` mode that exceptions won't be raised from tasks. Instead, the results of calling a task is just `None`.

https://github.com/coleifer/huey/blob/11190ca41ec3bfa172fada1bd456160ef882e814/huey/api.py#L322-L324

Is this by design and would you be intersted in a PR that carries through the exception similar to a non-eager task?https://github.com/coleifer/huey/blob/11190ca41ec3bfa172fada1bd456160ef882e814/huey/api.py#L416-L423

I'll be the first to say I don't understand the ramifications of such a change but I'm willing to play around with it.

**Comment by coleifer** [comment]
f7c5b1d72b13896bc8e660c6931743426496ecd5

Thanks for reporting, this is now fixed and I've added a regression test. Pushed a new release, 1.10.3.
