### ISSUE TITLE
Support other serialization methods such as JSON for tasks

### ISSUE THREAD

**Issue by rammie** [coleifer/huey#368]
Thank you for Huey, it is awesome! After yet another mysterious celery outage, we've decided to give Huey a shot and are in the process of migrating a modest sized production codebase from Celery to Huey. So far, it's been a breeze.

Anyhow, two reasons that come to mind for why custom serialization is desirable:
1. Pickle is un-secure and allows for remote code injection. So if REDIS were compromised, the attacker could execute arbitrary code in the Huey consumers.
2. Pickle is relatively slow and task serialization is in the request code path when Huey is used alongside a web app.

Though this is currently possible by implementing a custom TaskRegistry, it requires duplicating some of the serialization/deserialization logic. I think pickle is still a sensible choice by default because of it's ability to serialize absolutely anything.

One thought would be to wrap just the pickle dumps and loads calls in TaskRegistry methods such as TaskRegistry.dumps/loads. This would allow for just overriding the serialization mechanism without knowledge of the internals (such as oc_raw possibly being another task) and would allow you to keep adding features while keeping the deserialization backward compatible. Thoughts?

**Comment by coleifer** [comment]
Personally, I'm not interested in abstracting out the serialization logic. Pickle works, and has been a good fit. Also, besides task serialization, the result-store APIs use pickle as well for storing arbitrary key/value data, such as task results or task error metadata.

**Comment by rammie** [comment]
Would you be open to a PR that abstracted serialization across the board?

Also, one last ditch effort to convince you that it is worthwhile to support this at some point - https://www.benfrederickson.com/dont-pickle-your-data/

**Comment by coleifer** [comment]
Security concerns could easily be solved by putting a message digest or whatever around the serialized data, and verifying the digest from within huey. No need, in my opinion, to come up with other serialization schemes or abstractions. And if you're running your redis on the public internet, you probably got more problems than worrying about a malicious pickle getting thrown in your task queue...

**Comment by gregtap** [comment]
There are valid use cases where you could have other non-python code dispatching tasks to huey. This is where a Json / messagepack serialization makes sense.

**Comment by coleifer** [comment]
The serializer is exposed as an extensible API, and furthermore, huey includes a `SignedSerializer`. You can trivially implement a Json or MsgPack serializer if you wish. Take a look in `huey.serializers` and then pass your implementation into the `Huey.__init__` method:

* https://huey.readthedocs.io/en/latest/api.html#Huey - see `serializer` parameter
* https://huey.readthedocs.io/en/latest/api.html#serializer - serializer API

**Comment by gregtap** [comment]
> The serializer is exposed as an extensible API, and furthermore, huey includes a `SignedSerializer`. You can trivially implement a Json or MsgPack serializer if you wish. Take a look in `huey.serializers` and then pass your implementation into the `Huey.__init__` method:
> 
> * https://huey.readthedocs.io/en/latest/api.html#Huey - see `serializer` parameter
> * https://huey.readthedocs.io/en/latest/api.html#serializer - serializer API

👍🏻 

> > other non-python code dispatching tasks to huey
> 
> Oh come on... That's straining credulity.

We did it 1o years ago with Celery on a large Django-driven system and a few java services in a very successful company. It does happen.

**Comment by coleifer** [comment]
>We did it 10 years ago with Celery on a large Django-driven system and a few java services in a very successful company. It does happen.

I stand corrected!
