### ISSUE TITLE
Passing the task instance using "include_task" raises an error

### ISSUE THREAD

**Issue by kultz** [coleifer/huey#371]
As mentioned i used `include_task=True` to pass in the task instance inside using the below code:
```python
@huey.task(include_task=True)
def add(a, b, task=None):
        task_id = task.task_id
	return a+b
```
But the consumer comes up with error:

> [2018-11-01 18:10:30,671] INFO:huey.consumer.Worker:Worker-4:Executing tasks.queue_task_add: 19790803-0b04-49ac-92a4-18142743ed2e
> [2018-11-01 18:10:30,672] ERROR:huey.consumer.Worker:Worker-4:Unhandled exception in worker thread
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/huey/consumer.py", line 241, in process_task
>     task_value = self.huey.execute(task)
>   File "/usr/local/lib/python2.7/dist-packages/huey/api.py", line 392, in execute
>     self.put(task.task_id, result)
>   File "/usr/local/lib/python2.7/dist-packages/huey/api.py", line 329, in put
>     pickle.dumps(value, pickle.HIGHEST_PROTOCOL))
>   File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
>     Pickler(file, protocol).dump(obj)
>   File "/usr/lib/python2.7/pickle.py", line 224, in dump
>     self.save(obj)
>   File "/usr/lib/python2.7/pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "/usr/lib/python2.7/pickle.py", line 396, in save_reduce
>     save(cls)
>   File "/usr/lib/python2.7/pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "/usr/lib/python2.7/pickle.py", line 754, in save_global
>     (obj, module, name))
> PicklingError: Can't pickle <class 'tasks.queue_task_add'>: it's not found as tasks.queue_task_add

**Comment by coleifer** [comment]
What version of huey?

**Comment by kultz** [comment]
Name: huey
Version: 1.10.1
Summary: huey, a little task queue
Home-page: http://github.com/coleifer/huey/
Author: Charles Leifer
Author-email: coleifer@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages

**Comment by coleifer** [comment]
Not sure what might be the problem. This logic is tested:

https://github.com/coleifer/huey/blob/master/huey/tests/test_consumer.py#L404-L417

**Comment by coleifer** [comment]
You can try it out...modify the `tasks.py` in the "simple" example (included with the huey source):

```python
@huey.task(include_task=True)
def print_task(task=None):
    print('got task id=%s' % task.task_id)
```

Results in:

```
[2018-11-01 14:15:12,158] INFO:huey.consumer.Worker:Worker-4:Executing tasks.queue_task_print_task: 7b232b7d-d368-4e96-babb-e9bbe7dc8619
got task id=7b232b7d-d368-4e96-babb-e9bbe7dc8619
[2018-11-01 14:15:12,158] INFO:huey.consumer.Worker:Worker-4:Executed tasks.queue_task_print_task: 7b232b7d-d368-4e96-babb-e9bbe7dc8619 in 0.000s
```

**Comment by kultz** [comment]
Updating to 1.10.3 solved the issue.
