### ISSUE TITLE
How does huey distribute tasks in a distributed system?

### ISSUE THREAD

**Issue by lsetiawan** [coleifer/huey#378]
Hi,
I am trying to understand how huey distribute and execute tasks within a distributed system. I have multiple huey consumers each in a kubernetes pod, and have 100 greenlet workers. When I execute the multiple tasks from a huey producer, it seems like the tasks are not distributed to all of the consumers, but rather only 1 or 2 out of 6 consumers. So I was wondering how this is determined? Thanks.

**Comment by coleifer** [comment]
Wow...that's a lot of worker connections to your Redis server. 100 greenlets * 6 consumers = 600 connections to Redis. Do you have a ton of purely IO-bound tasks (e.g. reading from a socket)? If not I'd suggest using threads for mixed workloads or processes for CPU workloads, and reducing the worker count to number of cores or so.

The Redis storage supports two modes of operation: blocking and polling. By default it will poll. Which means it uses exponential backoff up-to a timeout of say 10 seconds between polling. Each worker has its own connection to Redis and depending on which reads first (and in the event multiple requests come in, which one Redis processes first), that worker will dequeue the task.

You can try enabling blocking-mode, which uses a Redis blocking-right-pop. Just do `huey = RedisHuey(...blocking=True)`.

There's no distribution algorithm. Tasks get added to a Redis list and workers attempt to pop items off that list. In polling-mode, they will try to pop and if nothing is returned, will wait before trying again. In blocking-mode they will do a blocking-right-pop, which decreases latency.

**Comment by lsetiawan** [comment]
@coleifer Thanks for the thorough answer. That is very helpful. I have lots of tasks that read and write files and perform database inserts so that seems like an IO-bound tasks rather than CPU since I am not performing any computations. I will try the blocking mode and see if anything changes. :+1:

**Comment by coleifer** [comment]
File I/O is not cooperative with gevent. And unless your db driver is pymysql or psycopg2 with a gevent wait callback, you're running those synchronously too.

**Comment by lsetiawan** [comment]
Hmm... interesting. Good to know. Thanks for the info!
