### ISSUE TITLE
cannot schedule tasks on django

### ISSUE THREAD

**Issue by valhallen13** [coleifer/huey#379]
Hi,

I cannot schedule a task to run after a delay using the schedule after upgrading to django 1.11.
this is how im testing it:
```my_task.schedule(args=('string1'), delay=10)```

Below is the error that i get.
```
huey.consume.worker | Error adding task to schedule: my_app.tasks.queue_task_mark_email_message_as_failed_after_time: 64334559-08c9-43be-9a90-25c77067854e @2018-12-10 17:19:47.424274
```
 These are my settings:
```   
HUEY = {
    'name': 'my-tasks',
    # 'backend': 'huey.backends.redis_backend',  # required.
    'result_store': True,  # Store return values of tasks.
    'events': True,  # Consumer emits events allowing real-time monitoring.
    'store_none': False,  # If a task returns None, do not save to results.
    'always_eager': False,  # If DEBUG=True, run synchronously.
    'store_errors': True,  # Store error info if task throws exception.
    'blocking': False,  # Poll the queue rather than do blocking pop.
    'backend_class': 'huey.RedisHuey',  # Use path to redis huey by default,
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'connection_pool': None,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.
    
        # huey-specific connection parameters.
        'read_timeout': 1,  # If not polling (blocking pop), use timeout.
        'max_errors': 1000,  # Only store the 1000 most recent errors.
        'url': None,  # Allow Redis config via a DSN.
    },
    'consumer': {
        'workers': 3,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1.15,  # Exponential backoff using this rate, -b.
        'max_delay': 10.0,  # Max possible polling interval, -m.
        'utc': True,  # Treat ETAs and schedules as UTC datetimes.
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
```

I had to comment backend because it was breaking periodic tasks .

Is this a bug or is this a configuration error? 
Thanks,
Tudor

**Comment by coleifer** [comment]
You're missing a comma

```python
my_task.schedule(args=('string1',), delay=10)
```

**Comment by valhallen13** [comment]
Hi again, 

although i forgot the comma when writing this issue, the comma does exist in my code, so that is not the issue.

**Comment by coleifer** [comment]
Not sure what the actual error is. The code being executed is relatively straightforward when you add something to the schedule:

```python
    def add_to_schedule(self, data, ts):
        self.conn.zadd(self.schedule_key, {data: self.convert_ts(ts)})
```

Perhaps you have the wrong type of key (e.g. self.schedule_key is a list or a string instead of a sorted set)? Perhaps there's an issue connecting to the redis server?

I'd suggest you use an interactive debugger and step-into the code to see where the failure is occurring.

**Comment by coleifer** [comment]
Ahhh....yeah that's a big upgrade. Your application (which generates the tasks) and the consumer (which runs on the server executing the tasks) both need to be upgraded.

**Comment by vladlep** [comment]
Hi,

To continue Tudor's work, i was looking in this issue and i can replicate it in a hello world project. It might be that there are some bugs with certain versions of the components or that I am missing something from the documentation, but it is a persisting issue.

I installed the `Redis server v=4.0.9 ` with `sudo apt-get install redis-server `
On my system i have `Virtualenv 16.0.0`, `Python 2.7.15rc1` but on others we have python  2.7.14 or 2.7.9 and we still have the issue. In the [requirement.txt](https://github.com/vladlep/test-django-huey/blob/master/requirements.txt) you see the version of the python libs.

I made a hello world project to test scheduled tasks with. To run it you can follow these commands: 

```
git clone https://github.com/vladlep/test-django-huey.git
virtualenv venv
source venv/bin/activate
pip install -r test-django-huey/requirements.txt
python test-django-huey/manage.py runserver &
python test-django-huey/manage.py run_huey
```

Then if I open in the browser the page: 
`http://localhost:8000/huey/test/` 
I get the following error in the terminal:

```
(venv) vlad@vlad-laptop:~/work/temp$ python test-django-huey/manage.py run_huey
[2018-12-19 14:03:34,750] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 5581
[2018-12-19 14:03:34,750] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2018-12-19 14:03:34,750] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2018-12-19 14:03:34,750] INFO:huey.consumer:MainThread:UTC is enabled.
[2018-12-19 14:03:34,750] INFO:huey.consumer:MainThread:The following commands are available:
+ queue_task_hello_task
[19/Dec/2018 14:03:43] "GET /huey/test/ HTTP/1.1" 200 12
[2018-12-19 14:03:45,030] INFO:huey.consumer.Worker:Worker-1:Adding helloworld.tasks.queue_task_hello_task: 8caa75b1-da25-48eb-9c57-de6e57e74c5f @2018-12-19 14:04:43.933450 to schedule
[2018-12-19 14:03:45,032] ERROR:huey.consumer.Worker:Worker-1:Error adding task to schedule: helloworld.tasks.queue_task_hello_task: 8caa75b1-da25-48eb-9c57-de6e57e74c5f @2018-12-19 14:04:43.933450

```

In the [ django view ](https://github.com/vladlep/test-django-huey/blob/master/helloworld/views.py)  you see how the task is called. If i would call it without scheduling like `hello_task()` it would work.

Any idea what I could try? 

Thanks,
Vlad

**Comment by vladlep** [comment]
So I think i found it. If I change to `redis==2.10.6` instead of `redis==3.0.1` the scheduling seems to work. 
They released their 3.x versions on Nov 15 and I presume they change some interface and now huey does not work with the new release.

So I would recommend to adapt  the documentation until huey is adapted.
`pip install redis`  to `pip install redis==2.10.6`

I will continue my testing to make sure other things are working now still.

**Comment by coleifer** [comment]
Ahh, thanks @vladlep -- I didn't realize I had not yet released the Redis-py 3.0 compatibility fixes.

I've pushed a new release, 1.10.5, which specifies redis-py 3.0.0 as a dependency. This should resolve the issues.

**Comment by vladlep** [comment]
Ahh great. Did not know that was already done. 

Thanks! Vlad

**Comment by felipe3dfx** [comment]
The issue back using the following code:

```Python
process_payment_success.schedule(
    kwargs={
        'payment_id': payment_id,
        'retries': retries - 1,
    },
    delay=(60 * 10),
    convert_utc=False,
)
```

django==2.1.5
huey==1.10.5
python==3.6.7
channels_redis==2.3.3
django-redis-cache==1.8.1

Any ideas?
