### ISSUE TITLE
Questions: Has task run? Is running task completed?

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#381]
How can i check if a task has been called/run/completed?

Currently i looked into `HUEY.pending()` and check if there the task has a result.

First: How can i easier get all pending task IDs? I do this:

```
def get_pending_ids_by_func(task_func):
    task_pkg_path1 = "%s.%s" % (task_func.task_class.__module__, task_func.task_class.__name__)
    
    pending_ids=set()
    
    for pending_task in HUEY.pending(limit=None):
        task_pkg_path2 = "%s.%s" % (pending_task.__module__, pending_task.name)
        if task_pkg_path1 == task_pkg_path2:
            pending_ids.add(pending_task.task_id)
            
    return pending_ids
```

Then: I have the task ID and what to check if the task finished. Currently i check if result is not `EmptyData`, e.g.:
```
result = HUEY.storage.peek_data(key=task_id)
if result is not EmptyData:
    print("Task %r completed" % task_id)
else:
    print("Task %r return EmptyData -> not completed." % task_id)
```

But it seems that this will not work, if the task return something and not `return None`

**Comment by coleifer** [comment]
You can force huey to store "None", but be warned you can run out of ram if you aren't careful.

**Comment by jedie** [comment]
I better explain why I need all this: I want to write integration tests. I want to test the complete stack with redis server and without "always_eager" ;)

So, i need a solution to wait in tests for the completion of tasks. I'm trying to implement this as a context manager. It looks like this:
```
with WaitUntilHueyTaskEnded(<task_func>, timeout=2):
    self.client.get(...)

self.assert_task_are_done()
```

So the real question is: How to wait for task completion??

Currently my idea:

- collect all pending IDs *only* for `<task_func>`
- wait until all pending tasks are done by `if result != EmptyData`


But maybe everything is much easier to solve?














> pending_task_ids = [task.task_id for task in huey.pending()]

That doesn't help my function `get_pending_ids_by_func(task_func)`
I didn't want all pending tasks IDs: I only want the IDs for a given task func ;)


The return values are deleted when they are retrieved. How long are they stored if they are not retrieved? Forever?

**Comment by coleifer** [comment]
I would suggest that such an approach to testing is probably foolish, because you're essentially testing (at that point) that huey works as it should. Huey has its own unit tests and, provided you trust that it works, all you should need to do is use always_eager.

**Comment by jedie** [comment]
This isn't about testing Huey himself. It's about testing the whole stack. That includes huey and redis as backend...

In my case it's a docker compose project and django, huey, redis (and more) services are in separate containers...

**Comment by jedie** [comment]
I now try `store_none=True` but this doesn't help here:

I'd have expected that `HUEY.get(key=task_id, peek=True)` return `EmptyData` as long as the task is not finished. But it returns `None` as long as the task is running :(

But it's coded to deliver None back: huey.api.Huey.execute() looks like:
```
    def execute(self, task):
        ...
        result = task.execute()
        ...
        if self.result_store and not isinstance(task, PeriodicQueueTask):
            if result is not None or self.store_none:
                self.put(task.task_id, result)
        ...
```

**Comment by jedie** [comment]
Now i found a working setup:

* `result_store=True` and `store_none=True` is needed
* replace `HUEY.get()` with `HUEY.storage.has_data_for_key(<task_id>)`

`has_data_for_key` is only True if task has been finished.

**Comment by coleifer** [comment]
Why not just block when reading the result from the task itself?

```python
task_result = call_task_function()
# Block until task finishes.
task_result.get(blocking=True)
```

**Comment by jedie** [comment]
> Why not just block when reading the result from the task itself?

I can only do this, if i start the task directly in the test code... But e.g.: the test code used the django test client and the view calls the task... I can't easy make `.get(blocking=True)` isn't it?
Okay: I can try to patch the code via unittest.mock... But this is everytime a little bit tricky...

**Comment by jedie** [comment]
I'm changing my approach and check: `HUEY.all_results()`

`all_results()` returns a dict with the task id as keys. But I can't find a way to get the actual task class based on that task id.

**Comment by coleifer** [comment]
If I were your employer I'd probably fire you for wasting so much time.
