### ISSUE TITLE
huey.exceptions.QueueException: queue_task_FooBar not found in TaskRegistry

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#382]
Sometimes i get this if i call `HUEY.pending()`:
```
src/apps/huey_itegration/test_utils.py:58: in update_task_ids
    for pending_task in HUEY.pending(limit=None):
/usr/local/lib/python3.6/site-packages/huey/api.py:523: in pending
    for m in self.storage.enqueued_items(limit)]
/usr/local/lib/python3.6/site-packages/huey/api.py:523: in <listcomp>
    for m in self.storage.enqueued_items(limit)]
/usr/local/lib/python3.6/site-packages/huey/registry.py:87: in get_task_for_message
    klass = self.get_task_class(klass_str)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <huey.registry.TaskRegistry object at 0x7f317a255eb8>
klass_str = 'queue_task_healthcheck'

    def get_task_class(self, klass_str):
        klass = self._registry.get(klass_str)
    
        if not klass:
>           raise QueueException('%s not found in TaskRegistry' % klass_str)
E           huey.exceptions.QueueException: queue_task_healthcheck not found in TaskRegistry

klass      = None
klass_str  = 'queue_task_healthcheck'
self       = <huey.registry.TaskRegistry object at 0x7f317a255eb8>

/usr/local/lib/python3.6/site-packages/huey/registry.py:73: QueueException
```

Maybe this is just a timing problem?

The task looks like:

```
@periodic_task(crontab(minute="*"))
def healthcheck():
    ...
```

The task is finished very quickly. So maybe it exists while `self.storage.enqueued_items(limit)` but is ended in `self._registry.get(klass_str)` ?!?

EDIT: i try to add a `time.sleep(0.1)` in the task... Mabe this is a work-a-round if it's a timing problem?!?

**Comment by coleifer** [comment]
That's odd, I'm not sure. Can you print out for me `registry._registry.keys()`?

**Comment by coleifer** [comment]
The problem is that the identifier being used to identify the task is seemingly not found in the registry. The problem is most likely that when you're checking `pending()` you haven't imported all the task functions from your app. So the in-memory registry of tasks sees a task name but doesn't know what class / function it maps to.

The fix would be, wherever you're calling `pending()`, to ensure that all tasks have been imported by that point.

**Comment by jedie** [comment]
> The fix would be, wherever you're calling pending(), to ensure that all tasks have been imported by that point.

I'm sure the task is registered.

Adding a `time.sleep(0.1)` in the task fixed that. So i think it's a timing problem.

**Comment by coleifer** [comment]
That doesn't make any sense to me, but ok.
