### ISSUE TITLE
SQLAlchemy storage extension?

### ISSUE THREAD

**Issue by whoiswes** [coleifer/huey#383]
Wondering if anyone has any interest in a SQLAlchemy storage backend for Huey.  I recently ported the SQLite backend over to use vanilla SQLAlchemy, and while it probably needs polishing, it's functional.

I wanted to ask if such an extension would be useful to anyone else.

Love huey, thanks @coleifer for an awesome little module!

**Comment by coleifer** [comment]
Not me, but feel free to put it on github or whatever.

**Comment by dmitrypol** [comment]
@whoiswes  - did you post your work anywhere?  I like Huey but would be nice to use a more robust DB as queue.  And I don't need Redis scale

**Comment by whoiswes** [comment]
@dmitrypol - I threw up a gist [here](https://gist.github.com/whoiswes/ba517bf2cead564e31ce52013304c171)

I haven't touched this in almost a year, so it probably needs refactoring for Huey 2.x.  At the time I wrote this, we were able to use it, along with a SQLAlchemy-centric port of the sherlock module, to do a distributed task scheduler entirely in the database.  It worked well but we had issues with Huey's cron functionality so we moved to something else.

Hope this is useful for someone.

**Comment by dmitrypol** [comment]
Thanks @whoiswes for such quick response.  Out of curiosity, what did you end up using?  Ideally I want ability to run on demand and scheduled jobs via SQL table as queue with multiple consumers.  And it would be nice to have a web GUI too ;-).

**Comment by whoiswes** [comment]
@dmitrypol - we try to stay with python where possible (small team), so apscheduler is our current solution, plus the aforementioned sherlock port for distributed locks.  It works fairly well but I think we're going to need a proper queue to solve some concurrency issues, so Huey will be getting another look next week!
