### ISSUE TITLE
Schedule task error redis 5.0.3

### ISSUE THREAD

**Issue by felipe3dfx** [coleifer/huey#388]
The issue back using the following code:

```Python
process_payment_success.schedule(
    kwargs={
        'payment_id': payment_id,
        'retries': retries - 1,
    },
    delay=(60 * 10),
    convert_utc=False,
)
```
redis-server 5.0.3
django==2.1.5
huey==1.10.5
python==3.6.7
channels_redis==2.3.3
django-redis-cache==1.8.1

Any ideas?

_Originally posted by @felipe3dfx in https://github.com/coleifer/huey/issues/379#issuecomment-459725868_

**Comment by coleifer** [comment]
What version of the Python Redis client library are you using?

What error are you receiving?

**Comment by felipe3dfx** [comment]
`Error adding task to schedule: membership.tasks.queue_task_process_payment_success: e5a96f50-8e6f-41ef-bfb0-f25ebc99feaf @2019-01-31 14:57:37.034875`

acme==0.28.0
aioredis==1.2.0
asgiref==2.3.2
asn1crypto==0.24.0
async-timeout==3.0.1
attrs==17.4.0
autobahn==19.1.1
Automat==0.6.0
backcall==0.1.0
backports.tempfile==1.0
backports.weakref==1.0.post1
certbot==0.28.0
certifi==2018.1.18
channels==2.1.6
channels-redis==2.3.3
chardet==3.0.4
click==6.7
colorama==0.3.7
command-not-found==0.3
ConfigArgParse==0.11.0
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
daphne==2.2.4
decorator==4.3.2
distro-info==0.18
dj-inmemorystorage==1.4.1
Django==2.1.5
django-admin-sortable==2.1.11
django-appconf==1.0.2
django-axes==4.5.4
django-compressor==2.2
django-debug-toolbar==1.11
django-dynamic-fixture==2.0.0
django-extensions==2.1.5
django-ipware==2.1.0
django-redis-cache==1.8.1
django-test-plus==1.1.1
django-widget-tweaks==1.4.3
fail2ban==0.10.2
future==0.15.2
gunicorn==19.9.0
h11==0.8.1
hiredis==1.0.0
httplib2==0.9.2
httptools==0.0.11
huey==1.10.5
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
iotop==0.6
ipython==7.2.0
ipython-genutils==0.2.0
jedi==0.13.2
josepy==1.1.0
language-selector==0.1
lxml==4.3.0
mock==2.0.0
msgpack==0.6.1
ndg-httpsclient==0.4.4
netifaces==0.10.4
PAM==0.4.2
parsedatetime==2.4
parso==0.3.2
pbr==3.1.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
piprot==0.9.10
prompt-toolkit==2.0.7
psycopg2-binary==2.7.7
ptyprocess==0.6.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
Pygments==2.3.1
pygobject==3.26.1
PyHamcrest==1.9.0
PyICU==1.9.8
pyinotify==0.9.6
pyOpenSSL==17.5.0
PyPDF2==1.26.0
pyRFC3339==1.0
pyserial==3.4
python-apt==1.6.3
python-debian==0.1.32
python-magic==0.4.15
pytz==2018.9
PyYAML==3.12
raven==6.10.0
rcssmin==1.0.6
redis==2.10.6
reportlab==3.5.13
requests==2.21.0
requests-futures==0.9.9
requests-toolbelt==0.8.0
requests-unixsocket==0.1.5
rjsmin==1.0.12
service-identity==16.0.0
six==1.11.0
sqlparse==0.2.4
ssh-import-id==5.7
systemd-python==234
tblib==1.3.2
traitlets==4.3.2
Twisted==18.9.0
txaio==18.8.1
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
uvicorn==0.3.29
uvloop==0.12.0
wcwidth==0.1.7
websockets==7.0
z3c.rml==3.6.1
zope.component==4.3.0
zope.event==4.2.0
zope.hookable==4.0.4
zope.interface==4.6.0
zope.schema==4.9.3

**Comment by coleifer** [comment]
You need redis-py >= 3.0, you have 2.10 installed.
