### ISSUE TITLE
Task UUID clashing

### ISSUE THREAD

**Issue by teodoricoramos** [coleifer/huey#389]
Hi,
I encountered task UUID clashing when sending same task multiple times.
2 instances of same task getting same UUID that is why the other task does not execute.
See the log snippets below:

[2019-02-02 12:13:18,825] INFO:lib.store:Worker-7:STATUS_79__tf1__mm1__0__test_save_results: test_save_result ended
[2019-02-02 12:13:19,082] INFO:lib.manager:Worker-1:STATUS_73_73__tf3: Sent test "item-78|mm2|test_save_results|loop:23" to the queue
[2019-02-02 12:13:19,239] INFO:huey.consumer.Worker:Worker-7:Executing **test_modules.sample_group.test_save_results.queue_task_test_save_results: f1eb2270-12ab-44a8-9a28-47424e5855b5**
[2019-02-02 12:13:19,390] INFO:lib.store:Worker-7:STATUS_78__tf3__mm2__0__test_save_results: test_save_result started
[2019-02-02 12:13:19,490] INFO:lib.store:Worker-7:STATUS_78__tf3__mm2__0__test_save_results: test started at: 1549080799.39
[2019-02-02 12:13:19,604] INFO:huey.consumer.Worker:Worker-5:Executing **test_modules.sample_group.test_save_results.queue_task_test_save_results: f1eb2270-12ab-44a8-9a28-47424e5855b5**
[2019-02-02 12:13:19,658] INFO:lib.manager:Worker-2:STATUS_71_71__tf1: Sent test "item-79|mm1|test_save_results|loop:23" to the queue
[2019-02-02 12:13:19,790] INFO:lib.store:Worker-5:STATUS_78__tf3__mm2__0__test_save_results: test_save_result started

I am using Sqlite for the storage. I have a main task that sends other tasks to queue base on a config file.

**Comment by coleifer** [comment]
I'm unclear what the issue is. If you send the same task (with the same task id), then it will use the same task id?

Please format your logs. The output is unreadable.

If you can provide more info I'll reopen.

**Comment by teodoricoramos** [comment]
Hi, sorry for not explaining clearly.

In my setup, there is a main task (called send_to_queue) that sort of acts like a queue manager.
What its doing is executing the "work" tasks and sending them to the queue.
All the work tasks are placed in a directory and imported dynamically and executed dynamically also. 
The sequence of executing the work tasks is dynamic (read from an excel config file).

An example of work flow is like this:
work_task_1 (repeat n times)
work_task_2 (repeat n times)
...
work_task_n

What was shown above was a single work flow that will be executed sequentially by the queue manager.

The queue manager can be invoked multiple times to execute different work flow at the same time.
In this case, there will be at least 3 queue manager running at the same time as separate tasks and each of this are executing their own work flow. For example,

Queue Mngr Task 1 (Work Flow 1)
work_task_A (repeat 20 times)
work_task_B (repeat 30 times)

Queue Mngr Task 2 (Work Flow 2)
work_task_B (repeat 10 times)
work_task_C (repeat 10 times)
work_task_A (repeat 5 times)


In the queue manager (send_to_queue) the line that executes a work task is like below:
`handler = getattr(work_tasks_module, task_name)(args)`

The problem that I encountered is that 2 different queue manager tasks executing the same work_task but different arguments can sometime get "the same UUID" causing one of the 2 to not be executed at all.

For an example, please see the below logs:

`[2019-02-02 12:13:19,239] INFO:huey.consumer.Worker:Worker-7:Executing test_modules.sample_group.test_save_results.queue_task_test_save_results: f1eb2270-12ab-44a8-9a28-47424e5855b5`
`[2019-02-02 12:13:19,604] INFO:huey.consumer.Worker:Worker-5:Executing test_modules.sample_group.test_save_results.queue_task_test_save_results: f1eb2270-12ab-44a8-9a28-47424e5855b5`

In this case, there are 2 queue managers. The first one executed the task test_save_results in worker 7.
And the other queue manager executed also the task test_save_results in worker 5.
The problem is, they both get the same UUID:
 f1eb2270-12ab-44a8-9a28-47424e5855b5

This resulted in only one task executing. The other one did not since it was masked by the other one with the same UUID.

I invoke my consumer like below:
`huey_consumer lib.manager.huey -w 8`

And all the tasks uses the @huey.task() decorator.

Hope this explains the case clearly and I apologize for my bad phrasing as my English is not that good.
Please do tell me if you need more info.
Thank you for creating this library. It is very easy to use and very solid.

**Comment by coleifer** [comment]
Use triple-backticks or indentation to express code blocks. Single backticks are for inline code. The GitHub docs (see link below the comment text-box) are helpful: https://guides.github.com/features/mastering-markdown/

**Comment by coleifer** [comment]
I wonder if your code is somehow not threadsafe...I'd suggest looking in that direction.

This is a very unusual and difficult-to-understand use-case, with lots of weird parts (is dynamic import the issue? does it only happen with multiple queue managers? etc, etc). If you can create a very minimal test-case to replicate, I will be better able to help you.
