### ISSUE TITLE
Allow using a different class for scheduler and worker

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#391]
Would you please make such changes to allow overriding the class used for scheduler and worker?

```
--- a/huey/consumer.py
+++ b/huey/consumer.py

 class Consumer(object):
+
+    scheduler_class = Scheduler
+    worker_class = Worker
+
     def __init__(self, huey, workers=1, periodic=True, initial_delay=0.1,
                  backoff=1.15, max_delay=10.0, utc=True, scheduler_interval=1,
                  worker_type='thread', check_worker_health=True,

     def _create_worker(self):
-        return Worker(
+        return self.worker_class(
             huey=self.huey,
             default_delay=self.default_delay,
             max_delay=self.max_delay,

     def _create_scheduler(self):
-        return Scheduler(
+        return self.scheduler_class(
             huey=self.huey,
             interval=self.scheduler_interval,
             utc=self.utc,
```

Because currently I have to override `Consumer._create_worker` and `Consumer._create_scheduler` copying the original implementation and changing the class used which is not DRY and I risk to miss the moment when the original implementation changes.

**Comment by coleifer** [comment]
That would imply that any `scheduler_class` and `worker_class` overrides would implement the exact same constructor. Just override the _create_worker and _create_scheduler methods.

**Comment by mindojo-victor** [comment]
Yes, the constructor would be the same. And in most of the cases the custom Worker or Scheduler classes would be subclasses of the the original classes, the constructor not touched at all, some other methods would be overridden.

**Comment by mindojo-victor** [comment]
Do I understand correctly that you don't welcome contributions (I haven't found any contribution guidelines) and you prefer to keep Huey non-extendable so it can serve mostly your purposes?
It would be nice to state this attitude in a `CONTRIBUTING` file, so that people would not waste their time.

**Comment by coleifer** [comment]
I didn't think it was a good idea at first. After a day I thought it would probably be a fine addition: db68a555080270ff4195ccd861542e7a4164cc6e

**Comment by coleifer** [comment]
> Do I understand correctly that ... you prefer to keep Huey non-extendable so it can serve mostly your purposes?

It was quite easy to extend Huey in exactly the way you wished. This just makes it even easier -- two attributes instead of two methods for the simple case.

I do keep Huey extensible as much as I think is useful. I rely on people who use the library to help find the places where this becomes difficult. Look at the storage backend abstractions -- they are extremely amenable to extension or customization.
