### ISSUE TITLE
Option to queue task, discarding result

### ISSUE THREAD

**Issue by thomassross** [coleifer/huey#392]
We can globally discard results with `result_store=False` when creating the `Huey` object, but it would be nice to be able to discard results for specific task calls.

**Comment by coleifer** [comment]
By default Huey will not store results for tasks that return `None`. This can be controlled by the `store_none` parameter (defaults to `False`). So if you wish to avoid storing results for a given task, you can simply return `None` (or omit a `return`) and by default nothing will be stored.

**Comment by thomassross** [comment]
What I'm suggesting is a way to disable result storage at call time, so you can have a task that can be called discarding the result and storing the result:

```python
@task
def my_task():
    return True


@task
def my_task_discard_result():
    my_task.call_local()


def use_one():
    # Queue my_task and print the result
    res = my_task()
    print(res(blocking=True))


def use_two():
    # Queue my_task and ignore the result
    my_task_discard_results()

    # do some other stuff...


def use_three():
    # My suggestion
    my_task.call_no_result()

    # or maybe
    res = my_task()
    res.discard_result()

    # do some other stuff...
```

**Comment by coleifer** [comment]
What I'm saying is that Huey already has the capability: just do not return anything and your task will not put anything in the result store.
