### ISSUE TITLE
Huey executes task every minute

### ISSUE THREAD

**Issue by ovalseven8** [coleifer/huey#393]
In my Django project I have one `tasks.py` file with the following content.

```
@db_periodic_task(crontab(minute='*/1'))
def send_mails():
    management.call_command('send_mail')


@db_periodic_task(crontab(day='*/5'))
def delete_email_logs():
    management.call_command('purge_mail_log', 7)
```

The `send_mails()` task should run every minute and the `delete_email_logs()` task should run every 5 days. Unfortunately, I noticed that the `delete_email_logs()` task is executed every minute.

```
huey_1    | [2019-02-11 15:33:39,401] INFO:huey.consumer.Worker:Worker-2:Executing website.tasks.queue_task_delete_email_logs: 5debc8e6-4e62-4916-89ec-922d50de8cbc
...
huey_1    | [2019-02-11 15:34:37,196] INFO:huey.consumer.Worker:Worker-1:Executing website.tasks.queue_task_delete_email_logs: ec75e528-f914-4556-a5b6-28f4c24bfa44
```

I am not sure if I missed something in the docs. Perhaps someone can clarify me.

**Comment by coleifer** [comment]
You need to specify at what minute and hour it should run. The way you have it configured, it will run every minute of every hour every 5 days.

**Comment by jedie** [comment]
Think it's a good idea to insert more examples in the docs, isn't it?
