### ISSUE TITLE
Executing tasks more frequently than 1 minute

### ISSUE THREAD

**Issue by karamanolev** [coleifer/huey#395]
I know you're probably seeing it for the 15th time, but still, people need to execute tasks frequently. In my case - I'm polling a remote API that emits events and I want to ingest them frequently. I have a hacky solution that others might find use of. Please consider adding this functionality (maybe not exactly in the way I implemented it...). I feel extremely dirty and a lesser person after writing this, but it seems to work. No, it's not a good solution in many ways. I still feel better than using a once-per-minute tasks that schedules more frequent tasks.

I my understanding is that through the years you could hack around the 1 minute internal limitation in different ways, but currently reading the source it seems like it's not possible. If you make it work, then you break the crontab entries. But you can't, because of `self._q, self._r = divmod(60, self.interval)` and subsequent logic for when to execute `enqueue_periodic_tasks`. I hacked around it by calling enqueue_periodic_tasks every iteration with `None` for the datetime, which I use to mean "fire the tasks that need to execute every N seconds" and `not None` has the original meaning. In order to use it, one needs to replace the built-in Huey scheduler with this one, which I did by creating a custom manage.py command that overwrites `Consumer.scheduler_class` with my own. Make sure to replace @crontab with the @Crontab provided here. It's a drop-in replacement.

```python
import time

from huey import crontab
from huey.consumer import Scheduler


class IntervalSeconds:
    def __init__(self, interval):
        self.seconds = interval
        self.next_execution = time.time()

    def __call__(self, dt):
        if dt is None:
            now = time.time()
            if now >= self.next_execution:
                self.next_execution = max(now, self.next_execution + self.seconds)
                return True
        return False


class Crontab:
    def __init__(self, *args, **kwargs):
        self.crontab = crontab(*args, **kwargs)

    def __call__(self, dt):
        if dt is None:
            return False
        else:
            return self.crontab(dt)


class FrequentIntervalScheduler(Scheduler):
    def __init__(self, *args, **kwargs):
        kwargs['interval'] = 1
        super().__init__(*args, **kwargs)

    def loop(self, now=None):
        super().loop(now)
        self.enqueue_periodic_tasks(None, None)
```

**Comment by coleifer** [comment]
> I'm polling a remote API that emits events and I want to ingest them frequently

Found the problem.
