### ISSUE TITLE
How add a trace Id for all tasks?

### ISSUE THREAD

**Issue by viperfx** [coleifer/huey#396]
Is there a way to wrap tasks that get run? So I can add a trace_id to my log system.

Similar to how I can use this Django middleware to add a trace_id to all Django requests:

```
import uuid
import logging
from structlog import wrap_logger
import sentry_sdk

logger = wrap_logger(logger=logging.getLogger("structlog_logger"))


class RequestIdMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        request_id = request.META.get("HTTP_X_REQUEST_ID", str(uuid.uuid4()))
        if request_id:
            with sentry_sdk.configure_scope() as scope:
                scope.set_tag("request_id", request_id)
        logger_values = dict(request_id=request_id)
        logger.new(**logger_values)
        return self.get_response(request)

```

**Comment by coleifer** [comment]
Yes and no. Yes in the sense that Huey is just Python and as such is very hackable.

No in the sense that the consumer only logs the task ID and the task name, typically, so getting extra metadata in your huey logs will take a bit more work.

I'm going to assume that you're spawning these tasks from somewhere within the request/response cycle. Since you're using django to set a request ID already, and since huey's `TaskResultWrapper` exposes the task's ID, you could correlate the request ID with the task ID, e.g.

```python

def some_view(request):
    task_result = some_task()
    logger.info('request %(request_id)s invoked task %(task_id)s', task_id=task_result.task.task_id)
```

**Comment by viperfx** [comment]
I am launching many of the huey tasks from another background process. Not technically within request/response but the above suggestion would work.

However, the reason I was hoping to find a way to wrap the task is because structlog allows binding context to the thread. Therefore, a task_id can be attached to all future logs that get run by huey.

If I am understanding correctly, the above suggestion would only work to log that one log line. Since the task is scheduled within another thread, the binding of the context would not work?

**Comment by coleifer** [comment]
I'm not sure how the context you're talking about works. Huey supports 3 approaches to concurrency -- threads (default), processes or greenlets. How well it works may depend on which worker model you're using.

**Comment by viperfx** [comment]
Okay, I am using threads for all my workers.

Structlog allows me to bind a context onto the thread, that is used to call the huey task and carry out the rest of the work. 

I just need to do `logger.new(request_id=<request_id>)` somewhere early enough in the thread before huey does any work on the task. Here is a simple flask example - http://www.structlog.org/en/stable/examples.html#flask-example

I am using the same technique in my Django middleware. Its early enough in the request, that until the request/response cycle ends, that `request_id` stays present in the thread.

**Comment by viperfx** [comment]
The closest analogy to what I might need in practice is a custom task class in celery - http://docs.celeryproject.org/en/latest/userguide/tasks.html#instantiation

**Comment by viperfx** [comment]
Hope my explanation made it clear what I'm trying to do @coleifer

**Comment by coleifer** [comment]
Huey provides an `on_startup` hook that runs whenever a worker thread starts (typically this is just at the very start of the consumer running).

Docs: https://huey.readthedocs.io/en/latest/api.html#Huey.on_startup
