### ISSUE TITLE
running after a  long time tasks throw errors

### ISSUE THREAD

**Issue by JasperYanky** [coleifer/huey#397]
`django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
`

**Comment by coleifer** [comment]
MySQL kills idle connections after a certain amount of time.

I'd suggest consulting the Django docs for the solution, as Django is managing your database connections.

**Comment by rchinna** [comment]
Even I am hitting this error if I let my huey run in my server for long. Is there a solution ?

**Comment by coleifer** [comment]
> Is there a solution ?

Learn how to use your database / tools. It's not a huey issue, at any rate.

**Comment by JasperYanky** [comment]
I solve my problem like this:

from django.db import connection
Your task here
connection.close()
