### ISSUE TITLE
Threads are not executed concurrently

### ISSUE THREAD

**Issue by vrbrito** [coleifer/huey#400]
Hello,

First, I'd like to thanks for the amazing initiative of developing Huey.

My problem is, the tasks assigned concurrently do not seem to run concurrently in a multi-worker and thready consumer. I say that because when trying to run a single task, it takes about 2s to complete its execution, when using 10 workers to run 10 similar tasks, the total time taken is about 10s. It's not the 20s expected if all the workers were working on series execution, but it's not the result expected as well.

Could you check if I have my settings all alright? I'm running on Django.

`HUEY = {`
`'connection': {'connection_pool': ConnectionPool(host='localhost', port=6379, db=1, max_connections=10)},`
`'consumer': {'workers': 10,'worker_type': 'thread'},`
`'always_eager': False`
        `}`

**Comment by coleifer** [comment]
Depends on what kind of work you are performing in your tasks.

If it is CPU-bound work, then you are running into the limit imposed by python's global interpreter lock. Python only allows one OS thread to run at any given time.

**Comment by vrbrito** [comment]
Are there any suggestions on actions that could give me better performance regarding multiprocessing?

**Comment by coleifer** [comment]
Yeah, use the "process" worker type:

```
$ huey_consumer.py -k process ...
```

Or to use your django example:

```
'consumer': {'worker_type': 'process', ...
```

**Comment by vrbrito** [comment]
And if I'm even screwed and use windows, any additional suggestions?
