### ISSUE TITLE
Huey 2 Task not found in TaskRegistry

### ISSUE THREAD

**Issue by michaeltoohig** [coleifer/huey#402]
I just started using Huey yesterday and today see version 2 released. Yesterday I followed this example to get things running https://github.com/pjcunningham/flask-huey-example but with Huey 2 my tasks are no longer being registered.

I simplified everything to just `huey = RedisHuey()` to remove issues related to the changes in configuration but still having issues. What else has changed that would interfere with this pattern I was using?

```
# run_huey.py
from project.queue import create_huey

from project.tasks import test

huey = create_huey()

if __name__ == '__main__':
    pass
```

```
# project/queue.py

from huey import RedisHuey

def create_huey():
    _huey = RedisHuey(url='redis://localhost:6379/?db=1')
    return _huey
```

```
# project/tasks.py

from project.queue import create_huey
huey = create_huey()

@huey.task()
def test():
    print('test-huey')
    return 'completed'
```

I don't mind returning to the older version in the meantime but perhaps I just missed something in the docs?

**Comment by coleifer** [comment]
Huey tasks are registered with a particular instance. In 1.x there was a global registry. So the "Huey" instance in tasks.py is not the same as the one in "run_huey.py".

To fix, use just one Huey instance:

```python
# run_huey.py
from project.tasks import huey
from project.tasks import test

if __name__ ...
```

**Comment by coleifer** [comment]
For what it's worth, here is a simple explanation of how you might organize your code:

https://huey.readthedocs.io/en/latest/imports.html

**Comment by coleifer** [comment]
Also, I've added a minimal flask example to the examples directory: https://github.com/coleifer/huey/tree/master/examples/flask_ex
