### ISSUE TITLE
ConfigurationError: The connection configuration is over-determined.

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#403]
After update i get this error:

> huey.exceptions.ConfigurationError: The connection configuration is over-determined. Please specify only one of the the following: "url", "connection_pool", or "connection_params"

In this case the values are:

```
url=None
connection_pool=ConnectionPool<Connection<host=redis,port=6379,db=0>>
connection_params={'events': True, 'result_store': True, 'store_errors': True}
```
To fix this i removed `events, result_store, store_errors` from my `HUEY` dict.

Can you pleas add a complete example with "connection_pool" here: https://huey.readthedocs.io/en/latest/django.html#setting-things-up

**Comment by coleifer** [comment]
There already is an example: https://huey.readthedocs.io/en/latest/django.html#configuration-examples

I've also made a commit that will remove the deprecated kwargs from the init arguments, and show a deprecation warning if you attempt to use them.
