### ISSUE TITLE
How can I clear record in redis if the task is completed?

### ISSUE THREAD

**Issue by Hammer2900** [coleifer/huey#404]
There is a problem, task that come in redis are not removed from it.
Does the library delete completed tasks?

**Comment by coleifer** [comment]
You have three options:

* If your task function returns `None`, then nothing is put in the result store.
* If you read the result, it is removed. eg via the result object that is returned when you call a task function.
* You can specify `results=False` when initializing Huey to disable result storage for all tasks.

**Comment by camflan** [comment]
@coleifer how about all the tasks in a pipeline? After the pipeline has successfully completed, I don't need any intermediate results left over, but I _do_ need those results to pass data through the pipeline, right?

**Comment by coleifer** [comment]
> I don't need any intermediate results left over, but I do need those results to pass data through the pipeline, right?

I hadn't considered this. There are lots of ways you can work around this, but there isn't an api that specifically would address this scenario. Thinking about it, the best way would probably be:

```python

# new option when enqueueing pipeline:
res = huey.enqueue(pipeline, persist_intermediate_results=False)

# ordinarily enqueueing a pipeline will return a ResultGroup, but if the above
# is true, we probably want it to act just like a normal result.
actual_final_result = res(blocking=True)
```

You could always just call `huey.storage.flush_results()` at 3am or whatever, but yea, I think this is worth implementing.

**Comment by coleifer** [comment]
I just prototyped an implementation for this and it's kinda yuck. At present it requires adding special cases in a couple different places. I'll think about this some more, duly noted however.

Another option is to try out the `RedisExpireHuey`, which stores results in regular keys and attaches a TTL which is handled by redis to automatically expire them.

**Comment by camflan** [comment]
OK, thanks. It would be incredible to help clean up some 'headless' pipelines that we're building. Just a small test batch ballooned our redis memory usage by 4 gigs. 😬 

Is RedisExpireHuey composable with PriorityRedisHuey?

**Comment by coleifer** [comment]
As of 416e8da1ca18442c08431a91bce373de7d2d200f
