### ISSUE TITLE
What should I do if I want to store the results of the task for 24 hours?

### ISSUE THREAD

**Issue by QAQ110** [coleifer/huey#407]
What should I do if I want to store the results of the task for 24 hours?

**Comment by QAQ110** [comment]
Save in redis。

**Comment by coleifer** [comment]
The way the result store works is super simple.

When a task finishes, the result is stored in the result store. If you use the task result handle to read the result, this is a *destructive* read. The idea is: we don't want to clutter up our storage by storing results forever, as it would grow without end. So when we read the result, the result is then removed. You can, however, preserve the result for additional reads by specifying `result.get(preserve=True)` [here are the docs](https://huey.readthedocs.io/en/latest/api.html#Result.get).

Regarding expiring results after 24 hours. Redis has the ability to expire keys, but by default Huey stores all results in a single Redis Hash (to avoid cluttering up the keyspace). So you would probably want to just store the results in regular old redis keys and then add an expire to them. I could probably implement this in 20 minutes by subclassing `RedisStorage`...so I may just do that.

**Comment by coleifer** [comment]
Implemented. Here's the commit: 23e211e1d9b1a0b321c83d5b0373a52baa058988

Relevant code: https://github.com/coleifer/huey/commit/23e211e1d9b1a0b321c83d5b0373a52baa058988#diff-b625af72a67dfb4be3153a50d2c25fa2

**Comment by QAQ110** [comment]
thank you very much! When can I get this from pypi?

**Comment by QAQ110** [comment]
It seems that there are some problems, did not introduce RedisExpireStorage in huey.api, resulting in an exception

**Comment by coleifer** [comment]
Whoops, fixed. Thanks.
