### ISSUE TITLE
More documentation / example for Django

### ISSUE THREAD

**Issue by rajchinna** [coleifer/huey#410]
Hi, 

Thank you so much for the wonderful library. I am just trying to get a simple Django internal site for  doing some heavy processing of log files. Currently my design is something like this.. 

Can you share some documentation on how to schedule tasks from django and provided updates back to user ? How can I track process of all running background tasks and update the users via DJango ?

**Comment by rajchinna** [comment]
Important note. I didn't see any option to request documentation. hence opened issue.

**Comment by coleifer** [comment]
How to schedule tasks... well, that's covered in the [task scheduling documentation](https://huey.readthedocs.io/en/latest/guide.html#scheduling-tasks) in some detail, so I won't repeat myself here, as well as the [periodic task guide](https://huey.readthedocs.io/en/latest/guide.html#periodic-tasks) for repeating tasks.

If you want dynamic repeating tasks, I've added a short section to the guide: [dynamic periodic tasks](https://huey.readthedocs.io/en/latest/guide.html#dynamic-periodic-tasks). Note that this only applies when your worker-type is threads (the default) or greenlets. If you use process, the worker processes are running in completely separate space from the scheduler, so there's currently no way to talk to the scheduler process and modify its in-memory schedule. This may change at some point, but just fyi.

Huey provides a number of introspection methods which you can use to look in and see what's going on:

* https://huey.readthedocs.io/en/latest/api.html#Huey.pending - gets a list of all tasks that are in the work queue awaiting execution as soon as a worker is available.
* https://huey.readthedocs.io/en/latest/api.html#Huey.scheduled - gets a list of all tasks that are sitting in the schedule for execution in the future

Huey also provides quite a few signals which you can bind handlers to, to attach additional logic to certain operations:

* [Signals short guide](https://huey.readthedocs.io/en/latest/guide.html#signals)
* [Signals doc](https://huey.readthedocs.io/en/latest/signals.html)

Hope that helps.

**Comment by rajchinna** [comment]
Thanks for taking your time and providing update. 

Here is the problem I am facing.. 

Setup. 

1. I have Django setup with Huey & gRPC.
2. I could schedule sample huey add tasks from Django views.py

But, when I try to schedule the same from my gRPC service I am hitting the following error.. 

D:\tools\web\first\emonhelper>python grpc_server.py
Traceback (most recent call last):
  File "tests.py", line 4, in <module>
    from tasks import add
  File "D:\tools\web\first\helper\tasks.py", line 2, in <module>
    from huey.contrib.djhuey import periodic_task, task
  File "C:\ProgramData\Anaconda3\lib\site-packages\huey\contrib\djhuey\__init__.py", line 69, in <module>
    HUEY = getattr(settings, 'HUEY', None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\conf\__init__.py", line 64, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting HUEY, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Here is a quick summary of my design. 

1. DJango server via IIS + (gRPC & Huey as service) running on windows server. 
2. Python gRPC Clients on Linux machines will be pushing the logs to the server via gRPC + rsync. 
3. **gRPC will be scheduling tasks via huey.**  <- _**here is the issue**_
4. Huey will do heavy lifting of processing my logs & store the summary in server. 
5. Django will query the Huey tasks and provide an update to end users via HTTP.

I am sure I might be missing some simple steps.. I will be of great help if you can give some steps to resolve.

**Comment by coleifer** [comment]
Note: Please format your code in the future. I have edited your issue to make the traceback formatted as code.

**Comment by coleifer** [comment]
> But, when I try to schedule the same from my gRPC service I am hitting the following error..

You're trying to interact with a django application without defining your django settings module, apparently. This is very basic django stuff. There's an example of using huey + django in the code repo which might also help you. https://github.com/coleifer/huey/tree/master/examples

I think you might be missing some foundational knowledge of these tools.

**Comment by rchinna** [comment]
Thank you so much for quick response. Yes. I figured out that it was basic DJANGO settings that caused the error.. 

As you pointed out I am looking for the foundation guide for these key tools. I saw couple of tutorials and documents but most of them talks about the usage of tools/libs as standalone entities. Especially Django has huge community support but still it lakes on these corner cases. 

Since your the author for Huey I was seeking your inputs. 

Once again thank you so much for the prompt update.

**Comment by rchinna** [comment]
Hi,

I am here with one more issue and this seems to not a popular one as none of the forums have any answer to this.. Hence I came here to ask this question. 

I got Huey and Django working fine for a while.. Then I started implementing the features on my solution.. But, after everything went right I installed Huey command as service using django windows tools and surprisingly I am not able to see any output of print statements (even with --huey-verbose) in the logs file (D:\logs\hueyservice.txt) and the service returns without running anything.... After digging further its noticed that if I run the command "python manager.py run_huey" then everything is working as expected. My tasks getting executed and results are shown in console & log file. 

I noticed that my long running tasks uses subprocess & os.system().. These API's are not running properly if I run them as service and they work well if I run it in debug mode (pythonwinservice.exe --debug myapp) or python mange.py run_huey... But, it fails as long as I start the app as service using Windows SCM. 

Here is sample log that I am getting 

```
[2019-04-16 21:42:27,997] DEBUG:huey.consumer:MainThread:Workers are up and running.
[2019-04-16 21:42:27,997] DEBUG:huey.consumer:MainThread:Scheduler is up and running.
[2019-04-16 21:42:28,028] INFO:huey:Worker-3:Executing edp_processor.add: 5a6c481f-1624-4df3-92bc-9b67c8b8c150
[2019-04-16 21:42:28,090] INFO:huey:Worker-3:edp_processor.add: 5a6c481f-1624-4df3-92bc-9b67c8b8c150 executed in 0.062s
[2019-04-16 21:42:28,731] DEBUG:huey.consumer.Scheduler:Scheduler:Sleeping for 0.9967625141143799
[2019-04-16 21:42:29,091] DEBUG:huey.consumer:MainThread:Checking worker health.
[2019-04-16 21:42:29,091] DEBUG:huey.consumer:MainThread:Workers are up and running.
[2019-04-16 21:42:29,091] DEBUG:huey.consumer:MainThread:Scheduler is up and running.
[2019-04-16 21:42:29,731] DEBUG:huey.consumer.Scheduler:Scheduler:Sleeping for 0.9965624809265137
```

huey_service.ini
```
[services]
# Services to be run on all machines
run=huey
clean=d:\logs\huey.log

[huey]
command=run_huey
parameters=--logfile d:\logs\hueyservice.log --huey-verbose

[runserver]
# Runs the debug server and listen on port 8000
# This one is just an example to show that any manage command can be used
command=runserver
parameters=--noreload --insecure 0.0.0.0:8000

[log]
filename=d:\logs\hueyservice.log
level=INFO
```

huey_service.py 

```
#!/usr/bin/env python
import os
import os.path
import sys
import win32serviceutil

# This is my base path
base_path = os.path.dirname(os.path.abspath(__file__))
if not base_path in sys.path:
    sys.path.append(base_path)

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myhelper.settings")
    
from django_windows_tools.service import DjangoService,test_commands

class Service(DjangoService):

    _base_path = base_path
    _svc_name_ = "django-huey-service"
    _svc_display_name_ = "Django Huey background service"
    _config_filename = "huey_service.ini"


if __name__ == "__main__":    
    if len(sys.argv) > 1 and sys.argv[1] == 'test':
        test_commands(base_path)
    else:
        win32serviceutil.HandleCommandLine(Service)

```

My tasks.py

```
@task()
def processedp(destination_path, platform, sockets, views, name, dbinstance=None):
    edp = EDPWrapper(platform, sockets, views, dbinstance)
    return edp.process(destination_path, outputname=name)
```

My Installed Apps.

```
INSTALLED_APPS = [
    'edpprocessor.apps.EdpprocessorConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'django_windows_tools',
    'django_grpc',
    'edp_processor',
    'django_tables2',
]

HUEY = {
    'huey_class': 'huey.RedisHuey',  # Huey implementation to use.
    'name': DATABASES['default']['NAME'],  # Use db name for huey.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': False,  # If DEBUG=True, run synchronously.
    'utc': True,  # Use UTC for all times internally.
    'blocking': True,  # Perform blocking pop rather than poll Redis.
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'connection_pool': None,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.

        # huey-specific connection parameters.
        'read_timeout': 1,  # If not polling (blocking pop), use timeout.
        'url': None,  # Allow Redis config via a DSN.
    },
    'consumer': {
        'workers': 8,
        'worker_type': 'thread',
        'initial_delay': 0.1,  # Smallest polling interval, same as -d.
        'backoff': 1.15,  # Exponential backoff using this rate, -b.
        'max_delay': 10.0,  # Max possible polling interval, -m.
        'scheduler_interval': 1,  # Check schedule every second, -s.
        'periodic': True,  # Enable crontab feature.
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
}
```
