### ISSUE TITLE
timezone support?

### ISSUE THREAD

**Issue by shuxiang** [coleifer/huey#411]
Thank you for your wonderful job, I use huey in production environment. Add timezone support for periodic tasks will be useful, something like crontab(hour='1', minute='1', timezone='US/ASIA timezone') 

:)

**Comment by coleifer** [comment]
You know, adding timezone support brings in a dependency on a timezone library like pytz, and in the interests of keeping `huey` as small and lightweight as possible, that's not something I intend to add.

Recall that the `crontab()` function simply returns a new function that behaves like this:

```python

f = crontab(minute='0', hour='0')

# f is implemented something like this:
def f(dt):
    # By default, dt will be a naive datetime in UTC.
    return dt.minute == 0 and dt.hour == 0
```

So you can of course implement your own validate function that accepts the naive datetime coming from huey and applies whatever logic to return True or False.

**Comment by shuxiang** [comment]
I got you point. I change local code `crontab` function, add a argument `validate_date`, then return partial(validate_date...). 

thanks

**Comment by l0n3woof** [comment]
@shuxiang I am trying to run the periodic tasks in american timezone, I can't just hard code as they have daylight savings. Can you please help me with the logic here?

**Comment by coleifer** [comment]
@l0n3woof - You can always run in local time if that's easier.

**Comment by julianwachholz** [comment]
@coleifer 
> You know, adding timezone support brings in a dependency on a timezone library like pytz, 

Would you be open for a change now after Python 3.9 introduced [`zoneinfo`](https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo) in the standard library back in October 2020? :)
It could also work well together with huey's Django contrib module to sync with the `TIME_ZONE` setting for example.

**Comment by coleifer** [comment]
By default Huey's crontab/periodic tasks run in the server's local timezone, just like the system crontab. If you want to do something with timezones there, you can provide your own `validate_datetime()` function when registering your periodic task -- all the `crontab()` function does is return a callable that returns `True` if it should run at the given time.

The other methods, such as `.schedule()`, already support timezones, as does the `expires=` keyword argument, so I'm not sure what more is needed.

**Comment by reorx** [comment]
> By default Huey's crontab/periodic tasks run in the server's local timezone, just like the system crontab.

This is what I expect initially. However, because the `utc` keyword argument of `Huey` is `True` by default, Huey uses UTC rather than the server's local timezone. I suggest setting this keyword argument to `False` by default so that Huey's `crontab` function works just like the system crontab, making Huey's behavior more intuitive for newcomers.

**Comment by reorx** [comment]
Looking back at the old code, I found myself in a situation where there were three different timezones running on the machine :

1. The system timezone was set to EDT.
2. The Django `TIME_ZONE` was set to CST.
3. Huey used UTC time.

The code was as follows 😂: 

```
# NOTE crontab uses UTC time, so if we want 09:00 CST, we need to set it to 01:00 UTC
# This is because Huey uses UTC by default, and although this could be changed by Huey(utc=False),
# it is better to convert the time to UTC because huey uses datetime.datetime.now() to get the current time,
# which does not follow settings.TIME_ZONE, but uses the system timezone, which may cause inconsistency in the time.
@db_periodic_task(crontab(hour=1,minute=0))
def create_daily_reports_task():
    ...
```

Perhaps `huey.contrib.djhuey` should include a crontab function that syncs with Django's `TIME_ZONE` setting, providing Django users with a reliable way to define crontab tasks that work as expected.

**Comment by reorx** [comment]
To sum up my suggestion:
1. Set `Huey.utc` to `False` by default, making huey.crontab behave the same as the system crontab.
2. Provide a new crontab function in `huey.contrib.djhuey` that follows Django's `TIME_ZONE` settings.

In this way, no additional timezone libraries need to be added, nor do we need to consider the compatibility of the `zoneinfo` built-in library. The core Huey package still only supports local timezones and UTC, both of which are provided by the built-in datetime library. Djhuey facilitates Django in supporting various `TIME_ZONE` settings, as it is expected to be used with Django installed. For other use cases where specific timezone support is needed, developers should write their own crontab function. 

If you find this suggestion worthwhile, please let me know, I'd like to contribute a PR.

**Comment by coleifer** [comment]
>This is what I expect initially. However, because the utc keyword argument of Huey is True by default, Huey uses UTC rather than the server's local timezone.

I apologize, you are correct on this. Every minute, the consumer goes through the periodic tasks it knows about and asks them if they should run at <x> time. If `huey.utc` is `True` (the default), then <x> is the current UTC timestamp - otherwise it is the server local time.

Unfortunately it's just a little bit tricky to do everything with respect to the Django timezone at present -- we normalize times that come in for scheduled tasks, retry delays and etas, task expiration times.

You can just wrap the builtin huey `crontab()` function:

```
from django.utils import timezone

def django_crontab(minute='*', hour='*', day='*', month='*', day_of_week='*', strict=False):
    validate_fn = crontab(minute, hour, day, day_of_week, strict)
    def wrapper(timestamp):
        # Here we assume huey.utc is True, thus `timestamp` is a naive utc datetime object.
        # We convert it here to a naive datetime in the django TIME_ZONE.
        ts = timezone.localtime(timestamp.replace(tzinfo=timezone.UTC()))
        return validate_fn(ts.replace(tzinfo=None))
    return wrapper
```

That said -- I wonder if, in your case, it makes sense to try overriding Huey's `read_periodic()` method so that it runs the cron with respect to the `TIME_ZONE` you've got configured? For example:

```python
from django.utils import timezone

class DjangoTZRedisHuey(RedisHuey):
    def read_periodic(self):
        # Get naive datetime with respect to settings.TIME_ZONE.
        ts = timezone.localtime(timezone.now()).replace(tzinfo=None)
        return [task for task in self._registry.periodic_tasks
                if task.validate_datetime(ts)]
```

We definitely can't change the default `utc=True` nor do I think that's a good idea.
