### ISSUE TITLE
HueyException in Task pipelines when following the documentation guide

### ISSUE THREAD

**Issue by demestav** [coleifer/huey#412]
To reproduce:

Following the documentation guide, create the *demo.py* file and run a consumer. When executing the line `result = huey.enqueue(task)` the script raises an exception `huey.exceptions.HueyException: demo.add not found in TaskRegistry`.

**Comment by coleifer** [comment]
It works fine for me.

![s1555940907 9289646](https://user-images.githubusercontent.com/119974/56503576-73819b80-64db-11e9-83d7-50f5e9515de4.png)

**Comment by coleifer** [comment]
Code in demo.py from above example:

```python
from huey import RedisHuey

huey = RedisHuey()

@huey.task()
def add(a, b):
    return a + b
```

**Comment by demestav** [comment]
@coleifer Thank you. It wasn't clear for me that I had to import huey from *demo.py*. I was importing the main library. Works now.
