### ISSUE TITLE
Is it impossible to lock the task when multiple workers？

### ISSUE THREAD

**Issue by sylvoslee** [coleifer/huey#413]
if so, is there any other way to achieve it? Thank you.

huey_consumer.py main.huey -w 2
WARNING:huey:Worker-2:Task 197238e9-f004-4112-affb-b76c5ef4380f not run, unable to acquire lock.

**Comment by coleifer** [comment]
You might have a stale lock when you started your consumer. Try running Huey consumer with the `-f` option, which will flush locks at startup. Locks should work fine regardless of how many workers you use.

**Comment by sylvoslee** [comment]
`huey_consumer.py main.huey -w 2 -f`

`@huey.task()
@huey.lock_task('lock')
def test():
    for i in range(10):
        time.sleep(1)
        print(f'sleep {i} second')
    
    return`

`[2019-05-02 06:53:47,569] INFO:huey:Worker-2:tasks.test: 5d6fa824-3df1-44c3-8181-c858e95d7fbd executed in 10.300s
[2019-05-02 06:54:03,799] INFO:huey:Worker-2:Executing tasks.test: f0e3c821-6eb8-471a-85ed-efa4273c17d1
sleep 0 second
sleep 1 second
sleep 2 second
sleep 3 second
[2019-05-02 06:54:08,791] INFO:huey:Worker-1:Executing tasks.test: e7a0b021-c48a-47bb-8998-20fb59f5c3f3
[2019-05-02 06:54:08,791] WARNING:huey:Worker-1:Task e7a0b021-c48a-47bb-8998-20fb59f5c3f3 not run, unable to acquire lock.
sleep 4 second
sleep 5 second
sleep 6 second
sleep 7 second
sleep 8 second
sleep 9 second
[2019-05-02 06:54:14,056] INFO:huey:Worker-2:tasks.test: f0e3c821-6eb8-471a-85ed-efa4273c17d1 executed in 10.257s`

i hope the test task Consumption in order，what should I do

**Comment by coleifer** [comment]
Please format your code.

**Comment by sylvoslee** [comment]
sorry,update it

**Comment by coleifer** [comment]
Oh, I see what you mean. So you expect it to act like a semaphore? It is not a semaphore -- it is a simple lock. It ensures that one task cannot be executed in parallel. A use-case would be you have a report generation task that runs every 10 minutes, but occasionally it can take 15 minutes to complete -- you want to ensure that it does not start a stampede, so you use a lock to ensure that only one instance of the task can run at a time.

If you want something like a semaphore, you can probably implement one quite easily using the TaskLock and redis primitives like INCR/DECR or pushing onto a list or whatever other atomic operations you might use.
