### ISSUE TITLE
why not call hset function

### ISSUE THREAD

**Issue by GeorgeWang1994** [coleifer/huey#414]
when i want to debug add function，i fund it call pop_data，but it not call set data function？ It make me so confused.

this is add function:
![image](https://user-images.githubusercontent.com/29206315/57216123-8dfe5d80-7021-11e9-93d8-549fca198acd.png)

and it call pop_data function when get data
![image](https://user-images.githubusercontent.com/29206315/57216117-8343c880-7021-11e9-97aa-7154cbd0e656.png)

but why not call set data function？if it call，where？
![image](https://user-images.githubusercontent.com/29206315/57216259-f1888b00-7021-11e9-95fc-3d93fe71e8b5.png)

**Comment by coleifer** [comment]
I don't know what you're asking. Your code in the `pop_data()` is incorrect, there's no such thing as "pipe.a()"... what is going on with that? Are you editing the code in `storage.py` for some reason?

The code for storing a result is `Huey.put_result()`. This happens after a successful execution of the task.

**Comment by GeorgeWang1994** [comment]
thank you，i understand。




| |
王大鼎
|
|
邮箱：georgewang1994@163.com
|

签名由 网易邮箱大师 定制

On 05/06/2019 22:07, Charles Leifer wrote:

I don't know what you're asking. Your code in the pop_data() is incorrect, there's no such thing as "pipe.a()"... what is going on with that? Are you editing the code in storage.py for some reason?

The code for storing a result is Huey.put_result(). This happens after a successful execution of the task.
