### ISSUE TITLE
Equivalent of .send

### ISSUE THREAD

**Issue by olymk2** [coleifer/huey#417]
If i call a function in huey is there a way to choose if it should run via huey or directly.

In other queues I have used you use .send to invoke via the queue, I could not find something similar in huey looking over the docs, basically something like below I am after so i can choose when to invoke the queue or run directly.

````
@huey.task
def myfunc():
    return 1

myfunc.send()  # use huey
myfunc() # dont use huey
````

**Comment by coleifer** [comment]
Did you bother to read the docs before posting this?

When you call a `huey.task`-decorated function, then the task is enqueued.

To avoid the "huey" logic and call the function directly, use `.call_local()`: [docs](https://huey.readthedocs.io/en/latest/api.html#TaskWrapper.call_local).

**Comment by olymk2** [comment]
Thanks for pointing me in the right direction, I did search the docs but obviously I was looking for the wrong thing, thanks for pointing me at the correct place in the docs.
