### ISSUE TITLE
When are tasks acknowledged?

### ISSUE THREAD

**Issue by benregn** [coleifer/huey#418]
When are Huey tasks acknowledged? In comparison with Celery, it has a `task_acks_late` to only acknowledge a task after it has been executed.

Sorry if this covered by the docs, I couldn't find anything.

**Comment by coleifer** [comment]
Huey doesn't use an amqp-style workflow, nor does it attempt to ensure at-least-once delivery. There's no ack. The workflow, once a worker begins a task, is simple:

* Execute task
* If unhandled exception occurs and the task has one or more retries, it is re-enqueued.
* If the task finishes successfully, the return value is placed in the result store (though None return values are not stored by default).
