### ISSUE TITLE
Dose huey support multiple consumer processes on different machine?

### ISSUE THREAD

**Issue by liuzhijun** [coleifer/huey#419]
Suppose there are too many tasks and have to use more than one machine to process.

**Comment by coleifer** [comment]
Yeah, they just need to have access to the same Redis instance (or whatever you're using for the queue storage).

If you use crontab-like tasks, be sure to start every consumer EXCEPT 1 with the `-n` flag to avoid spawning duplicate instances of your cron-tasks. https://huey.readthedocs.io/en/latest/consumer.html#options-for-the-consumer
