### ISSUE TITLE
PostgreSQL storage backend, would a contribution be welcome?

### ISSUE THREAD

**Issue by abeluck** [coleifer/huey#427]
Would you be interested in a PR for a Postgres storage backend?

**Comment by coleifer** [comment]
You can already use Postgres via the `huey.contrib.sql_huey` backend.

For postgres specifically, I will consider implementing it. I know that by using some nice pg-specific features, it should be possible to get a pretty slick storage engine for pg.

**Comment by oz123** [comment]
Didn't test this, but it looks good
https://pypi.org/project/huey-pg/#description. 

I am currently in a search for a task queue. I want to keep my stack small, so I prefer not to use redis.
