### ISSUE TITLE
After updating to 2.1.0, adding a connection url results in error

### ISSUE THREAD

**Issue by sfitzgerald16** [coleifer/huey#428]
Running with Django, the default Huey configuration works, but when running pytest after adding a connection url param to Huey, getting this error:

```ValueError: The connection configuration is over-determined. Please specify only one of the the following: "url", "connection_pool", or "connection_params"```

Setting the host, port, db and connection_pool to None doesn't help. As far as I can tell, I'm only using 'url', not 'connection_params' or 'connection_pool', so not sure what needs to change to resolve this.

**Comment by coleifer** [comment]
Can you please share your configuration, or how you are setting this up so I can replicate it?

Also you did not mention what version you were upgrading from.

**Comment by coleifer** [comment]
I'd suggest just overriding the `host` / `port` / whatever instead of trying to do host/port in the settings and something else in the tests. Or refactor your django ~global variables~ "settings".

**Comment by sfitzgerald16** [comment]
We're upgrading from 1.10.3. We aren't using the host/port etc. settings, only using the 'url' param to our redis url. This is what we had working in the previous version, with the exception of 'immediate' being 'always_eager':

```HUEY = {
    'connection': {
        'url': REDIS_URL,
    },
    'consumer': {
        'periodic': True,
        'workers': 4,
    },
    'immediate': DEBUG,
}
```

REDIS_URL locally is redis://localhost:6379

**Comment by coleifer** [comment]
f4c766a40c9c188356f12b1ccf79f9fc27d3352f

**Comment by sfitzgerald16** [comment]
Much better now, thank you!
