### ISSUE TITLE
how to get results of async task

### ISSUE THREAD

**Issue by qgriffith-zz** [coleifer/huey#43]
This is more of a question then an issue. So I apologize for opening this here. I didn't see any where else to ask questions.

I am planning on using Huey with django. The task is going to call an API that will build and destroy new machines in the "cloud".  I figured out how to get the taskid and I can store that in a session or cache.  How do I take that ID and get the status of the job?  I am looking to see if the job is queued, failed, has not been ran, or was successful.  I want to create a page that list all the task for the last hour and the status that they are in.

**Comment by eldamir** [comment]
Sorry for resurrecting this issue. I cannot find anything in the docs about this usecase. It seems that the API required me to keep a reference to the task and ask it for results until there is a result.

I want my website to request an action. An id string is returned. The website can then request information about the action by providing the id.

So how do I get the ID of a task? And how do I get task results, when all I have is the ID?

**Comment by coleifer** [comment]
You can construct an AsyncData object by hand. Or simply pass the task I'd to huey._get().

For granular info store task state in a table you manage.
