### ISSUE TITLE
Calling a task to be executed immediately

### ISSUE THREAD

**Issue by denizdogan** [coleifer/huey#432]
Sorry if this has been answered somewhere in the documentation, I just haven't been able to find it.

Is there any way to make a single task call immediate? I guess I could just do:

```python
huey.immediate = True
my_task(3)
huey.immediate = False
```

But is there any prettier way? I'm thinking something along the lines of a context:

```python
with huey.immediate(True):
    my_task(3)
```

Any such thing? Thanks.

**Comment by coleifer** [comment]
Just call the underlying function directly.

```python
my_task.call_local(3)
```

**Comment by coleifer** [comment]
https://huey.readthedocs.io/en/latest/api.html#TaskWrapper.call_local
