### ISSUE TITLE
module name is __main__

### ISSUE THREAD

**Issue by miluChen** [coleifer/huey#436]
Suppose I have a `main.py` like below:
```
from huey import RedisHuey

huey = RedisHuey()

@huey.task()
def add(a, b):
    return a + b

if __name__ == '__main__':
    for i in range(1000):
        add(i, i+1)
```
I may want to run the producer as `python main.py` and start consumer as: `python huey_consumer.py main.huey`.
However, when the producer register `add`, the `task_to_string` actually stores `__main__.add` instead of `main.add`. This causes a problem because the consumer thinks what's registered is `main.add`.
https://github.com/coleifer/huey/blob/085685a6cb38d9ffa1bcee82480bd7fb1696faed/huey/registry.py#L16-L17

I know it's probably not the best practice of the usage of huey, but it'll be great if `__main__` is never used as the module name when registering a task.

**Comment by coleifer** [comment]
You're going to need to add a second module that imports `main.add` and does the task enqueueing. Simple as that.

Or you can subclass and override the Registry implementation.
