### ISSUE TITLE
Is it possible to create a task with specific task_id?

### ISSUE THREAD

**Issue by yigitest** [coleifer/huey#438]
Hi,

I was using QueueTask class with optional task_id parameter with huey 1.x.x. 
What is the recommended approach for specifying task_ids in the huey 2.0?

Thanks,

**Comment by coleifer** [comment]
While the id can be specified, it's not necessarily exposed as a public API. Nor was it intended as a public API in the 1.x versions. So subject to change without notice.

You can achieve similar functionality, though, in a variety of ways. Here's one that occurred to me:

```python
@huey.task()
def add(a, b):
    return a + b

task = add.task_class(args=(1, 2), id='my-custom-id')
res = huey.enqueue(task)
```
