### ISSUE TITLE
dispatcher?

### ISSUE THREAD

**Issue by ingoogni** [coleifer/huey#440]
Is there an elegant way to create a dispatcher from the @huey decorated functions? My goal would be something like `dispatcher={'add':add}`. What I tried is using the register, but I'm not sure that's the way.
```
@huey.task()
def add(a, b):
    return a + b

for k, v in huey._registry._registry.items():
    print(k, v)
    res = huey._registry._registry[k](1,2)
    print(res)
    print(res.id)
    print(res.name)
    res1 = huey._registry._registry[k].schedule((1,2), delay=10)
```
With my shaky python I'm not sure what I got here, `res` seems fine, `res1` fails. Some guidance is appreciated.

**Comment by coleifer** [comment]
You're using undocumented/internal APIs which are subject to change without notice. Check the API docs for a comprehensive view of what is supported:

https://huey.readthedocs.io/en/latest/api.html

Not only is `Huey._registry` not a public API, neither is `Registry._registry`.

That being said, what goes in the registry? A mapping of name to task class. Not even task classes are really part of the API. Decorated functions return a TaskWrapper, which handles instantiating and enqueueing/scheduling a task instance.

I'd suggest writing your own wrapper that wraps `task()` and manage the registry in your own way.

```python
huey = RedisHuey()
registry = {}

def mytask(*args, **kwargs):
    def decorator(fn):
        task_wrapper = huey.task(*args, **kwargs)(fn)
        registry[fn.__name__] = task_wrapper
    return decorator

@mytask()
def add(a, b):
    return a + b

registry['add'](1, 2)
registry['add'].schedule(...)
```

**Comment by ingoogni** [comment]
I'll have to chew on that a bit. Thanks.
