### ISSUE TITLE
Windows Redis >2.10.6 incompatibility

### ISSUE THREAD

**Issue by salasls** [coleifer/huey#444]
Hey,

I think there is some incompatibilty with the latest version with redis on Windows (didn't check all versions, just updated to latest 3.3.8 and got problems with consuming tasks)

On Windows 10 with python 2.7.11 and redis 3.3.8 when running a consumer (very simmiliar to the one from example code from You) I got this error:
Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
( https://stackoverflow.com/questions/19570672/non-blocking-error-when-adding-timeout-to-python-server )

The problem is (I think) related with this:
( https://pypi.org/project/redis/ )
2.X users should make sure they’re wrapping their lock code in a try/catch like this:
try:
    with r.lock('my-lock-key', blocking_timeout=5) as lock:
        # code you want executed only after the lock has been acquired
except LockError:
    # the lock wasn't acquired

If this could be fixed, would be great/
Going back with redis to 2.10.6 works for me - no error in consumer
Thx for your awesome work :)

**Comment by coleifer** [comment]
No idea, but probably the issue is with either redis-py or redis.
