### ISSUE TITLE
Issue with Changelog > 1.11.0 > Backwards-incompatible changes > consume all tasks before upgrading

### ISSUE THREAD

**Issue by karnaker** [coleifer/huey#447]
Regarding Changelog > 1.11.0 > Backwards-incompatible changes > "Because these changes will impact the serialization (and deserialization) of messages, it is important that you consume all tasks (including scheduled tasks) before upgrading."

I would like to determine whether my program will be affected by this change. I am using huey-1.10.0 and would like to upgrade to the latest version of huey (2.1.1). If any tasks in queue will be affected, is there a way to convert them to become 2.1.1 compatible?

Also, is there a way to view all huey scheduled tasks in redis via the redis-cli? I was not sure what commands to use for this (tried lrange, key, etc.).

Please let me know if you need any additional information to better respond, and I will be happy to update/reply. Thank you in advance for your time and help with this.

**Comment by coleifer** [comment]
You'll need to look and see but I don't think it will be straightforward making such a large jump. Better would be to set up a second huey install running the latest version and push all new work there, while you let your 1.x version drain any remaining work.

**Comment by coleifer** [comment]
You can always try it out, however, and Huey does have some provisions to attempt to correctly handle messages in the older format. Try and see?
