### ISSUE TITLE
Can't retrieve result in callback

### ISSUE THREAD

**Issue by pyahmed** [coleifer/huey#449]
First of all - thank you for this wonderful library :-)

I'm trying to retrieve the result of a task from within a callback which does not work.
My minimal setup:
```
# demo2.py

import time
import huey

huey_queue = huey.SqliteHuey(filename='demo2.db')

@huey_queue.signal(huey.signals.SIGNAL_COMPLETE)
def task_success(signal, task):
    print("----")
    print(task)
    print(signal)
    print(huey_queue.get(task.id))
    print("----")

@huey_queue.task()
def slow_task():
    time.sleep(3)
    return "OK"
```
```
# taskrunner2.py

from demo2 import slow_task

k1 = slow_task()
slow_task()
```

Terminal 1:
`huey_consumer.py demo2.huey_queue`

Terminal 2:
`py  taskrunner2.py`

Output in terminal 1:
```
----
demo2.slow_task: 1c0a3cd7-2132-46c4-b37f-d1cf124dfcfd
complete
None
----
```

However when I open IDLE / ptpython or standard python prompt, I can import the huey_queue and retrieve the result:
```
from demo2 import huey_queue
res = huey_queue.get("1c0a3cd7-2132-46c4-b37f-d1cf124dfcfd")
print(res)
'OK'
```

Am I doing something wrong or is it not possible to retrieve the result within the callback? I tried adding a delay in the callback before retrieving the results but it made no difference.

Win10
Python3.7.3
huey 2.1.2

/EDIT removed unnecessary line

**Comment by coleifer** [comment]
Huey runs the `SIGNAL_COMPLETE` signal after the task has finished executing, but before it places the result on the result store (or takes any other action, such as running post-execute hooks, retrying the task, etc).

This was a design decision, as the canonical way to "wait for a task to finish" is to resolve the result.

I'd suggest that you can make the result resolution call blocking, if you really want to do this, but I think there are enough edge-cases (i.e., deadlocking if your task fails, because COMPLETE is called but the result is never generated) that it's not a robust design.

**Comment by coleifer** [comment]
Y'know, I re-read the documentation for the COMPLETE signal, and I think I ought to change the code a bit so that your example works as you would expect.

**Comment by coleifer** [comment]
Resolved in e9f6225

**Comment by coleifer** [comment]
Also note that `huey.get(task.id)` will work, kinda, but you should really use the result wrapper instead:

```python

result = huey.result(task.id)
```

**Comment by hkyq** [comment]
Hey @coleifer , I'm running a slightly modified version of the code above:

```py
# demo.py
import time
from config import HUEY
import huey

@HUEY.signal(huey.signals.SIGNAL_COMPLETE)
def task_success(signal, task):
    print("----")
    print(task)
    print(signal)
    print(HUEY.result(task.id))
    print("----")

@HUEY.task()
def slow_task():
    time.sleep(3)
    return "OK"
```

```py
# config.py
from huey import SqliteHuey

HUEY = SqliteHuey(filename='huey.db')
```

```py
# demo2.py
import demo

t = demo.slow_task()
print(t.get(blocking=True, preserve=True))
```

And when running the consumer and `demo2.py`, this is what I get:

```py
----
demo.slow_task: 5cfd64a7-5f2b-40cd-a555-c966e276af68
complete
None
----
```

What did I do wrong?

**Comment by coleifer** [comment]
This change has not been tagged in a release yet, so you would need to be running off master until I tag a new release.
