### ISSUE TITLE
Exponential backoff for retries

### ISSUE THREAD

**Issue by miluChen** [coleifer/huey#451]
Hi!!!

It's a good experience of using `huey`. Now...

In our usage, each individual task will make a HTTP call to another server running somewhere else. It happens that that server may be overloaded at some peak time and I would get "503 Server Error".

I was wondering whether an exponential backoff option for retry is useful here. Since if the fixed retry window is too small, it may fail soon if the overload period of the server is long. And if the fixed retry window is too large, it may just unnecessarily wait for too much if it's some other issue caused the retry.

**Comment by coleifer** [comment]
You can specify the number of retries along with the retry delay. I think between those two it should be sufficient -- you can always settle for a medium-sized retry delay and just use a bunch of retries. I don't see any reason why not to, so long as you're not DoS-ing the server you're trying to hit.

**Comment by miluChen** [comment]
🤔 Yeah... I just thought it might be a nice feature and was thinking to contribute to `huey`.

**Comment by coleifer** [comment]
If you want to fiddle with task settings at run-time, you can request huey to pass the task instance into your task function, and modify it yourself.

Something like this?

```python
@huey.task(retries=10, retry_delay=1, context=True)
def my_task(a, b, task=None):
    # task will be the task instance when the task is run by the consumer
    try:
        return do_something(a, b)
    except Exception as exc:
        task.retry_delay *= 1.15
        raise exc
```

**Comment by miluChen** [comment]
Yeah, that's a very valid option. But it requires the users to know much more.

**Comment by BSVogler** [comment]
I think an exponential retry strategy is a common use case. It should be an option in the task arg list or that example should be documented in the documentation.

**Comment by coleifer** [comment]
You can just use function composition to make your own implementation. I put this together, based on my earlier comment, in 5 minutes:

```python
import functools

def exp_backoff_task(retries=10, retry_backoff=1.15):
    def deco(fn):
        @functools.wraps(fn)
        def inner(*args, **kwargs):
            task = kwargs.pop('task')
            try:
                return fn(*args, **kwargs)
            except Exception as exc:
                task.retry_delay *= retry_backoff
                raise exc
        return huey.task(retries=retries, retry_delay=1, context=True)(inner)
    return deco


# Example use:
@exp_backoff_task(retries=5, retry_backoff=2)
def test_backoff(a):
    print(a)
    raise ValueError('forcing retry')
```

**Comment by BSVogler** [comment]
Great, thank you!

**Comment by Tragio** [comment]
Hi @coleifer 👋,

I'm using your Django extension, and I'm wondering what is the use of the `'backoff': 1.15` in the `settings.py` of `HUEY`. Does that somehow implement the backoff for retry? 🤔 

If not, what is the right way to implement the above code in Django. From my understanding the `return huey.task(retries...` is bringing the instance that was previously initialized with the configs, but in Django we don't do that manually as you do inside the extension. 🤔 Still learning Django so it can be a stupid question 😅 

Thank you very much for your great work!

**Comment by coleifer** [comment]
This is not the backoff for task retry - it is for consumers that poll and controls backoff for how much additional time to wait if the queue is empty. The 3 values are the initial delay (how much time to wait between polling), the backoff (increase delay by this factor when no tasks present) and max_delay (maximum time to wait between polling).

Therefore the docs are still relevant: https://huey.readthedocs.io/en/latest/guide.html#exponential-backoff-retries

You should be able to adapt the above code to Django by replacing `huey.task(...)` with `djhuey.task(...)`. I'm not really convinced that exponential backoff for retries is ever that great of an idea, but it is possible with Huey.
