### ISSUE TITLE
Client/Server tasks

### ISSUE THREAD

**Issue by polakovicp** [coleifer/huey#453]
Hello, is it possible to split tasks to client side (caller) and server side (consumer)?
Client - can be imported by everyone, who needs to call the `doit` function, but don't want to or can not (linux) import other task dependancies
```
# File: client.py

@huey.task()
def doit():
    ...
```

Server - used by task consumer, evironment dependant (e.g. pythoncom can be used only on Win)
```
# File: server.py
import pythoncom


@huey.task()
def doit():
    # use something platform dependant
    return "yay!"
```

Currently, the exception is raised on server side
```
huey.exceptions.HueyException: client.doit not found in TaskRegistry
```

**Comment by coleifer** [comment]
This is just python/imports/etc. Not to do with huey.
