### ISSUE TITLE
Running multiple consumers spawn across multiple hosts

### ISSUE THREAD

**Issue by dduraipandian** [coleifer/huey#457]
As per the author of Huey, It is not possible to distribute tasks to multiple hosts.

https://github.com/coleifer/huey/issues/64

Celery distributes the tasks to consumers which is running on multiple machines because it uses the same broker. So When i start the consumer aka worker, broker url is pointed to same message broker.

In that case, when i use RedisHuey; can't i use consumers spawn from diffirent machines?

Appologies for raising this issue here, when i am asking a question.

**Comment by coleifer** [comment]
> It is not possible to distribute tasks to multiple hosts

How do you infer that? The linked issue doesn't seem relevant either.

You can absolutely run multiple independent consumers. Just point them at the same Redis server acting as your queue.
