### ISSUE TITLE
How do I handle shutdown from tasks?

### ISSUE THREAD

**Issue by MrNaif2018** [coleifer/huey#458]
Hello! First of all, thank you for your great project!
I have web app(in async framework), and I want to integrate task queue, but as my functions are async, I use` asgiref.sync.async_to_sync `wrapper, but when executing database access from task it says `gino not initialized`, so I initialize it in startup event, but if I initialize it, it says `RuntimeError: event loop closed.` 
So I added a function to run event loop forever, but I can't shutdown it gracefully(while True needs some condition).
Or is there some `on_shutdown` event which could be used to clear up resources?
![image](https://user-images.githubusercontent.com/39452697/67802033-7f0dda80-fa9b-11e9-8a41-e2ef405289ef.png)

**Comment by coleifer** [comment]
Holy shit bro what the hell are you doing?

This is most definitely not a huey bug.

**Comment by MrNaif2018** [comment]
It is not a bug, I am asking is there some decorator in hue like `@on_startup`, but for shutdown? If so I could release resources properly.

**Comment by coleifer** [comment]
There's no reason to smash async shit into the tasks run asynchronously by your task queue.

**Comment by MrNaif2018** [comment]
So I should use some other libraries for async task queues, right?

**Comment by SnapDragon7410** [comment]
> 
> 
> There's no reason to smash async shit into the tasks run asynchronously by your task queue.

ew async hater
