### ISSUE TITLE
Silence exception log when retrying

### ISSUE THREAD

**Issue by NakulK48** [coleifer/huey#462]
Hey,

Our use case is similar to this one - https://github.com/coleifer/huey/issues/280 - if an error is logged it triggers an alarm, and we don't really want this to happen if the error has been "handled" by being retried - only if all of the retries have failed and the error is still occurring.

There's a commit linked to that issue that would have allowed me to fix this by just doing 

```python
except Exception:
  task.retries -= 1
  raise RetryTask()
```

But that functionality seems to have since been removed - `task.retries` goes down to 0 but it keeps retrying. 

How would you recommend that we handle this now, given that the task decorator currently includes a number of retries and we'd quite like it to keep obeying that?

**Comment by NakulK48** [comment]
To be clear on exactly what we want here: `huey` silently retries if it receives an error up to its retry limit, and then re-raises the error if it's hit that limit and the error is still occurring.

**Comment by coleifer** [comment]
If a task fails due to an *unhandled* exception, an error is going to be logged - whether or not the task is going to be retried.

The behavior of `RetryTask` is such that it retries the task irrespective of any "automatic" or pre-configured retries. It is explicit and says "I don't give a damn, re-run this." You can modify your code snippet to also say, "but if task.retries == 0 reraise the original exception" and probably be fine.

```python
except Exception as exc:
    if task.retries > 0:
        task.retries -= 1
        raise RetryTask()
    raise exc
```

I get the dilemma you're facing, but I'm not sure I want to change the way things behave currently.

I'd suggest writing your own

**Comment by NakulK48** [comment]
Using that approach, if I set `retries=2` to start, it ends up running 5 times in total

**Comment by coleifer** [comment]
You may need to fiddle with the conditionals or ordering, I didn't test that.

**Comment by NakulK48** [comment]
I think the problem is that `flaky_task.retries` isn't actually updated when `task.retries` is.

That is, the `TaskWrapper` object has its retries updated, but that doesn't filter back to the actual value of `flaky_task.retries` and I'm not sure there's any way of accessing it from within the function.

**Comment by coleifer** [comment]
`flask_task`? Are you passing the task object into the context of the task function?

**Comment by NakulK48** [comment]
The decorated function has a retries field, but that field doesn't match up
with the retries field inside the wrapper object.

**Comment by coleifer** [comment]
Are you passing the task object into the context of the task function?

**Comment by NakulK48** [comment]
Ah thanks - once I set `context=True` and used the `task` argument it worked fine.

One other bit of unrelated surprise when I was testing - should https://github.com/coleifer/huey/blob/master/huey/api.py#L407 also be checking whether `immediate=True`? We've got a retry delay on the function and wouldn't really want that to apply when testing.
