### ISSUE TITLE
Cancel a long running task?

### ISSUE THREAD

**Issue by mindojo-victor** [coleifer/huey#468]
Hi @coleifer 

Please advice how to correctly cancel a long running task. 
There is `CancelExecution` exception but it works only in pre-execute hooks.
I could kill the worker, but if the task has a retries, it will start again.

**Comment by coleifer** [comment]
There's no way to do that, unfortunately. You can't easily interrupt a running thread, and it adds a lot of complexity -- should an interrupted task be marked as an error? Should it be retried? What about subsequent executions?

The solution is to modify your task to track its time and cancel itself if it has the potential to run for a long time. You can do this with socket timeouts if it's making a slow network call, or if there is a loop to perform a check during the loop body.
