### ISSUE TITLE
Scout APM integration for Django

### ISSUE THREAD

**Issue by cburza** [coleifer/huey#469]
ScoutAPM recently added support for tracking Huey tasks. 

Please see https://docs.scoutapm.com/#huey

In order to register the signals the Django management command needs to be altered slightly.

I have the following in my `huey/contrib/djhuey/management/commands/run_huey.py` file:

```python
def handle(self, *args, **options):
    ...
    config.setup_logger(logger)

    if 'scout_apm.django' in settings.INSTALLED_APPS:
        from scout_apm.huey import attach_scout
        attach_scout(HUEY)

    consumer = Consumer(HUEY, **config.values)
    ...
```

Would it be possible to add support for this in version 1 and 2 of Huey?

**Comment by coleifer** [comment]
No plans to do so, surely there is a better way(?). At any rate, I'd take this up with the scout APM folks who created the integration.

**Comment by adamchainz** [comment]
(For anyone coming from search engines - this was fixed in https://github.com/scoutapp/scout_apm_python/issues/391).
