### ISSUE TITLE
`immediate=True` is incompatible with `blocking=True`

### ISSUE THREAD

**Issue by regisb** [coleifer/huey#472]
The following piece of code never terminates:

```
from huey import RedisHuey
huey = RedisHuey(immediate=True)

@huey.task()
def foo():
    pass
    
result = foo()
result.get(blocking=True)
```

This is annoying because some of my production code has `blocking=True`, while my unit tests use `immediate=True`. It means that in order to test my production code I need to resort to something like:

```
result.get(blocking=not huey.immediate)
```

I am not too familiar with the internals of huey, but it seems to me that the problem comes from the following piece of code in `api.py`:

    def enqueue(self, task):
        if self._immediate:
            self.execute(task)
        else:
            self.storage.enqueue(self.serialize_task(task), task.priority)

If you don't have time to spend on this I can try to figure out a workaround by myself.

EDIT: I am running huey 2.1.3.

Oh and thanks for all your work on Huey, I have been using it for a couple years now and it's the first issue that I have encountered :)

**Comment by coleifer** [comment]
The problem is that your task function has no return value and huey, by default, does not store `None` in the result store. You can fix this by either:

1. return a non-None value from tasks where you do blocking
2. instruct huey to store `None` as a valid task result (warning: this can fill up your result-store if you run lots of tasks and never read the results).

As far as I can tell this has nothing to do with the use of `immediate`.

**Comment by BSVogler** [comment]
I have the same issue when immediate mode. It will not return and block forever. It works when disabling the immediate mode. My method returns an integer.

**Comment by coleifer** [comment]
>As far as I can tell this has nothing to do with the use of immediate.

Again, this has nothing to do with `immediate`:

```python
huey = RedisHuey(immediate=True)

@huey.task()
def add(a, b):
    return a + b

res = add(1, 2)
print(res.get(True))
# prints "3"
```

**Comment by BSVogler** [comment]
As I said the problems shows only when I enable immediate mode. I am using djhuey if this matters. I could try find a minimum example where this problem shows.

**Comment by ElSamhaa** [comment]
Hey, sorry to revive an old issue, but I've just hit the same limitation and I'd like to say that it's more intuitive IMHO to handle `None`s and no-returns automatically on the library level.
Thanks for the great project BTW 🙂

**Comment by coleifer** [comment]
I’m not sure what you mean by handling it at the library level. Result handles reference a key in the result store. Huey doesn’t store none in the result store by default. Therefore blocking on a value that never gets put in the result store is ineffectual.
