### ISSUE TITLE
queue a task from PHP; worker is written in Python

### ISSUE THREAD

**Issue by vkatochka** [coleifer/huey#476]
Hi
Is there some way to queue a task from PHP directly? Or, over HTTP? Or, in another way?
In addition to queuing, there is a need to wait until the worker's completion, and get the result of his work to PHP. Is it possible?
Used Redis Broker.

**Comment by coleifer** [comment]
It's do-able but definitely won't be easy. Huey uses python's pickle serializer by default (see `huey/serializer.py`). You'll want to probably subclass and implement a json serializer or something that works well with both python and php. That will allow you to talk to huey from both environments.

To enqueue a task you can see `registry.py` - the `create_message()` method. This takes the task name, and various task metadata, and creates a message which is then serialized and put in the queue. You'll have to emulate that from PHP - e.g., craft a message which huey will be able to read.

Finally, to get the result from PHP you'll need to get it from the result store directly, which would be a redis `hget` + `hdel` on the result-store key + task result identifier.
