### ISSUE TITLE
Serializer is not forwards/backwards compatible with application changes

### ISSUE THREAD

**Issue by adamchainz** [coleifer/huey#477]
The default Serializer class is not forwards/backwards compatible with application changes and enqueued tasks in a few ways:

* The Pickle HIGHEST_PROTOCOL is always used. This makes upgrading Python to a new version with a new pickle protocol (such as Python 3.3 -> 3.4) a one way operation. If a roll back is needed to the previous version, enqueue tasks will not be readable as they're encoded in a pickle protocol only usable on the new Python version.
* The "decompress" logic in deserializiation is guarded by `if self.comp` and `if self.use_zlib` checks. Changing these flags in a new application version prevents enqueued tasks from being read by the correct path, and either compressed data will not be uncompressed, or it will be uncompressed with the wrong compression algorithm.

The first problem should probably be solved by making users explicitly choose their pickle version. Python has changed both `DEFAULT_PROTOCOL` and `HIGHEST_PROTOCOL` in recent versions (3.8 and 3.4 respectively) so neither is "stable" to use from a library perspective.

The second problem can be solved by rewriting the `deserialize()` method to check the dequeued data to see if it's able to decompress it.

**Comment by coleifer** [comment]
Although 3.3 is not supported, 3.8 certainly is. That being said, the protocol used for serializing should not matter as long as the consumer can still read it. This would only be a problem if, as you mentioned, you upgraded to 3.8, enqueued a bunch of tasks, and then downgraded to 3.7. I'm not too worried about this situation as it is easy to workaround (custom serializer) and would only occur under some very weird conditions...and even then, you could just keep running the 3.8 consumer process until it emptied out the queue.

The decompress thing should be more flexible, however - I will look into addressing that.

**Comment by adamchainz** [comment]
> you could just keep running the 3.8 consumer process

This is not normally feasible. If I'm deploying an upgrade to Python 3.8 and find a bug in my application caused by this upgrade, I have to stop the 3.8 consumer process immediately.

I wouldn't cause this a *weird* condition. It's perhaps rare, but I've seen many rollback/forwards incompatibilitiies in my time that have caused damage. I'd prefer if the library defaults were "safe" or at least encouraged users to consider the problem.

**Comment by adamchainz** [comment]
Btw I should have written, since this affects a client I can schedule some time to work on both kinds of incompatibility here if you want.

**Comment by coleifer** [comment]
49dd3ad3ae147bb31eca68420475ab130ece9625 allows the pickle protocol to be explicitly specified when initializing the serializer. Additionally, if compression is enabled, the deserializer check if the data is not compressed and log a warning if that occurs. This should enable people to safely enable compression (but not vice-versa as I don't want the overhead/noise for the default case).

**Comment by adamchainz** [comment]
Thanks for your quick work! 👍
