### ISSUE TITLE
Consumers are frozen after ancountering an exception

### ISSUE THREAD

**Issue by keddad** [coleifer/huey#479]
I've got an app which utilizes huey. If I start workers when there are already tasks in Redis, or add some tasks, they work for a while and then just freeze. There are still a lot of tasks in Redis, but scheduler appears to ignore them. But logs are saying that everything is fine
```
[2020-01-09 17:13:56,914] DEBUG:huey.consumer:7:Checking worker health.
[2020-01-09 17:13:56,914] DEBUG:huey.consumer:7:Workers are up and running.
[2020-01-09 17:13:56,914] DEBUG:huey.consumer:7:Scheduler is up and running.
```

I've tried different types of workers. but they all hang. The only hint I have is that they all work fine, when encounter some exceptions and only when stop, but it can be just a coincidence. If a worker fails when executing a task from pipeline, all the pipeline is canceled and it just moves to the other tasks, right?

**Comment by keddad** [comment]
Yep, where is definitely something wrong with exceptions. I've made such a test file:
```
from huey import RedisHuey

h = RedisHuey(host="localhost", port=6379)  # TODO тут пиздень


@h.task()
def bad_task():
    raise Exception

```

When the worker encounters exception, it just freezes and does nothing more. How can I fix such behavior?

**Comment by coleifer** [comment]
That is incorrect.

You can easily test this via the huey simple example (`huey/examples/simple/`). In the screenshot below, I'm calling an "add" task with a string and a None value, which raises an unhandled exception in the task. The worker logs the unhandled error and continues processing tasks.

![s1578592239 2231889](https://user-images.githubusercontent.com/119974/72091660-4ded2a00-32d6-11ea-892b-6032e9aaa2e1.png)

>If a worker fails when executing a task from pipeline, all the pipeline is canceled and it just moves to the other tasks, right?

The error will be propagated up and the subsequent tasks will not be enqueued.

**Comment by coleifer** [comment]
You can see what happens in a pipeline where a task produces an error:

![s1578592408 3425949](https://user-images.githubusercontent.com/119974/72091835-b63c0b80-32d6-11ea-9bc8-d782da77094e.png)

**Comment by keddad** [comment]
That`s strange. Anyway, thanks.
