### ISSUE TITLE
Accessing Arguments passed to a task

### ISSUE THREAD

**Issue by PadamSethia** [coleifer/huey#480]
Hi ,
I'd like to know if there's a way to access the arguments that have been passed to the task ?
Thanks

**Comment by coleifer** [comment]
This begs the obvious question of what do you need the task arguments for? God only knows. At what time do you intend to read the task arguments?

If you spent a moment looking at the code, I think you'd see that they are serialized into the task message (along with other metadata). Check `registry.py` in the `create_message()` and `create_task()` methods to see what is going on.

**Comment by PadamSethia** [comment]
I actually need live updates to show the progress of the task in the dashboard . And I haven't found a way yet. Can you help to point to the specific docs that could help? 
From what I've seen with RQ and Huey when compared to RabbitMQ , accessing the jobs is not as easy , or it is something that I am unable to find in the docs yet..

**Comment by PadamSethia** [comment]
Hi , 
What I am doing right now is passing a ID to my task which then gets the details from a table and runs the task.
So , I need to be able to kill the task somehow with an API call .

I'm very new to task workers. If possible can you guide me to the right direction ? 
Thanks!
