### ISSUE TITLE
HUEY.delete() not documented / ambigous

### ISSUE THREAD

**Issue by pyahmed** [coleifer/huey#483]
I was just looking if there is a way to delete (not revoke) a scheduled task from the queue. Turns out there is a HUEY.delete() method which takes as an input a key. After trying it - the task was still listed when I ran HUEY.scheduled(). 

This method is not listed in the docs, so I checked the api.py and it says:
```
def delete(self, key):
    return self.storage.delete_data(key)
```
Am I correct in assuming this method just deletes the data/result from storage?

**Comment by coleifer** [comment]
If a method is undocumented, why would you make assumptions about what it does? The proper way to remove a task after it has been scheduled is to revoke it, as the docs state. The method you mentioned is for deleting a key from the result-storage and is not part of the documented APIs.

**Comment by pyahmed** [comment]
I simply saw it from the list of options offered in the python prompt, maybe it was too naive to assume that calling delete() with a key would delete the corrosponding task ;-)
