### ISSUE TITLE
Django/postgres -specific storage/brokering

### ISSUE THREAD

**Issue by jarekwg** [coleifer/huey#484]
Hey @coleifer,

Lovely stuff!

Just interested what your thoughts are around padding out the djangoey bits of huey.
Would you be interested in Django-specifc storage definitions:
- DjangoCachedStorage - for talking to redis (or other) through django's higher-level wrappers
- DjangoDBStorage - for talking to db through Django ORM
Too bloaty, or on potential roadmap?

Also, I apologise if this is in the docs or an existing issue and I've missed it, but is the queue inspectable? to see QUEUED/DOING/DONE kind of thing? eg. If i were using a db backend, would I be able to see the Task in there through its whole life cycle, or only its result?

Similarly, any plans to leverage postgres for locking?

Not pushing, just probing whether you have ideas of expansion into these areas, or if the preference is to keep it lightweight. :)

Cheers!

**Comment by coleifer** [comment]
I'm not interested in supporting a Django backend for task/schedule/result-storage, but those are fine candidates for a 3rd-party library if you'd like to make one. The queue is inspectable using the storage APIs [sorta documented here](https://huey.readthedocs.io/en/latest/api.html#BaseStorage). Your huey instance will have a `storage` attribute which exposes the storage interface, and provides methods for inspecting the queue/schedule/results.
