### ISSUE TITLE
non daemon workers

### ISSUE THREAD

**Issue by gaborbernat** [coleifer/huey#485]
What's the main reason workers are daemon like? Can we have an option to have them non-daemonized? We have some workers that need to do some cleanup operation, and not being able to execute atexit, or guarantee finishing of the processing are causing issues.

**Comment by coleifer** [comment]
Ahhh, if you don't want to run a separate worker process, then what is the point of using huey at all? Just set up a synchronized queue (e.g. [queue.Queue](https://docs.python.org/3/library/queue.html)) and a couple threads, or use `multiprocessing` -- all part of the standard lib.

If you want to see how simple an in-process task-queue is to write, check out the `mini` huey extension module: https://github.com/coleifer/huey/blob/master/huey/contrib/mini.py -- it is in-process and uses gevent, so it's only suitable for certain kinds of workloads. But the concept could easily be modified to use regular threads.

**Comment by gaborbernat** [comment]
The reason for huey is the persistent local queue system 🤔

**Comment by gaborbernat** [comment]
And I don't want in process, but workers still need to do some cleanup work when they exit.

**Comment by gaborbernat** [comment]
My question wasn't about in process, was about having worker processes that are of type non daemon, so they can do cleanup on exit.

**Comment by coleifer** [comment]
Thanks for clarifying - I think I understand what you're asking. Workers are managed by the huey consumer, so they don't export state or anything like that. Since workers are managed, there are no provisions for worker-specific shutdown / etc. Bear in mind that, depending on your configuration, your workers may be processes, threads or green threads.

**Comment by gaborbernat** [comment]
Yeah I know this, in my case I use processes, and wonder if in this case can we make them non Daemon so they can do cleanup via atexit 🤷‍♀️

**Comment by coleifer** [comment]
They're not demonized, as they run in the foreground just like a regular process.

**Comment by gaborbernat** [comment]
https://github.com/coleifer/huey/blob/master/huey/consumer.py#L215 says otherwise

**Comment by gaborbernat** [comment]
Furthermore we'd like that when the consumer gets a signal it forwards those to the workers and gives them a short time, let's say 2-3 seconds, to finalize before killing them. Currently as worker processes are daemons are instantly killed when the consumer ends... without any chance of cleanup ☹️

**Comment by gaborbernat** [comment]
Would you expect a PR trying to implement the above? (maybe as an opt-in rather than change of behaviour)

**Comment by coleifer** [comment]
>worker processes are daemons
I think you might not understand what this means, or are using the term incorrectly. They are not daemons. They are simply regular old child processes. There are no daemons. Just the main process and, if you use the process worker-model, a few child processes.

**Comment by gaborbernat** [comment]
Yeah but at the moment child processes are set to be of type Daemon which means atexit is not executed on them. Why have that property set to true?

**Comment by coleifer** [comment]
That doesn't mean what you think it means. It's a holdover from the threading API, which multiprocess uses for compatibility. Read the python docs:

>Additionally, these are not Unix daemons or services, they are normal processes that will be terminated (and not joined) if non-daemonic processes have exited.

**Comment by gaborbernat** [comment]
I've read it. Note the not joined part. This is that hurts us. If its not joined it cannot be cleaned up. Not joined means if the parent exits the worker is killed, similar as kill -9 does. It cannot do cleanup work in such case.

**Comment by gaborbernat** [comment]
So I was slightly wrong on this. The reason why the atexit is not run is not tied to the daemon flag; but rather to the fact of using the fork strategy to create workers - see https://bugs.python.org/issue39675

**Comment by coleifer** [comment]
I'd suggest you register custom signal handlers and then send those signals to the workers when you want to cleanup.
