### ISSUE TITLE
forking processes is unsafe on MacOS for python3.8+

### ISSUE THREAD

**Issue by gaborbernat** [coleifer/huey#486]
See https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods

> Changed in version 3.8: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See bpo-33725.

https://bugs.python.org/issue33725

**Comment by coleifer** [comment]
Spawn has problems of its own, and I do not plan on changing the semantics to accommodate a toy unix with broken syscalls. It's fine to use fork().

**Comment by gaborbernat** [comment]
@coleifer this might be a fine thing to say, but then maybe mention in the readme that macOS is not supported/recommended 🤷‍♂
