### ISSUE TITLE
provide cleanup registers for workers

### ISSUE THREAD

**Issue by gaborbernat** [coleifer/huey#487]
We already have [startup hooks](https://huey.readthedocs.io/en/latest/shared_resources.html#startup-hooks), can we have clean up hooks? These would be called just before the worker exits around here in a finally https://github.com/coleifer/huey/blob/master/huey/consumer.py#L344

PS. We cannot use ``atexit`` because https://bugs.python.org/issue39675

**Comment by coleifer** [comment]
Yes, I think this would be a good idea.

**Comment by gaborbernat** [comment]
Thanks, do you plan a release with this?

**Comment by gaborbernat** [comment]
Ping 👍
