### ISSUE TITLE
get number of currently executed tasks

### ISSUE THREAD

**Issue by gaborbernat** [coleifer/huey#488]
Is there any way to get the number of currently executed tasks? These are no longer part of the ``scheduled_count`` or ``scheduled_count`` for the queue; as they are being actively worked on.

**Comment by coleifer** [comment]
What do you mean "currently executed"? Tasks that are running *right now at this instant*? That is not something `huey` currently supports, though you can infer it from the signals mechanism.

**Comment by gaborbernat** [comment]
My question was if this information could be provided from out of the box. I understand it's not supported now, but should it be?

**Comment by miluChen** [comment]
Is it okay to reopen this issue @coleifer ?

Suppose I start huey and listen from some pipe for a while. All the created tasks are scheduled to run after 5s. And some point, I may just decide to stop the system. Instead of simply shutting it down, I want to first process all the tasks in the queue then shut it down.

Potentially, I could check the queue size (e.g. pending_count + scheduled_count). However, it's possible that the queue size is 0 while some workers are processing the tasks. If I simply stop the system when the queue size is 0, i.e. send SIGINT or some other signal to consumer or workers, it's not guaranteeing the queue will be empty in the end. Because it's still possible that some worker experiences some exception, e.g. HTTP error, and requeue the task for later retry.

This above situation can be solved if there is a way to get number of currently executed tasks. I think there are other ways to achieve the same need. Do you think it's a valid use case? Is it possible to support it in huey? @coleifer

**Comment by atlekbai** [comment]
Hello, @miluChen @gaborbernat !
I was searching for a solution too, so I posted mine here: https://stackoverflow.com/a/64664260/11270738
Basically, I used the mechanism of signals provided by @coleifer

**Comment by coleifer** [comment]
https://github.com/coleifer/huey/issues/488#issuecomment-721133571 - Your post is not correct and is prone to race conditions when there are multiple workers. Signals may be executed synchronously by the worker (as part of task execution), but if you have multiple workers then the execution of the signals may be interleaved.

**Comment by atlekbai** [comment]
> [#488 (comment)](https://github.com/coleifer/huey/issues/488#issuecomment-721133571) - Your post is not correct and is prone to race conditions when there are multiple workers. Signals may be executed synchronously by the worker (as part of task execution), but if you have multiple workers then the execution of the signals may be interleaved.

By workers, you mean consumers, or processes (which number is defined in command line: `huey_consumer.py entrypoint.huey -k process -w $NUMBER_WORKERS`)?

**Comment by atlekbai** [comment]
@coleifer thanks! I thought that signals are executed synchroniously no matter of racing condition. I changed the code and edited the post. Waiting for your response :)

```python3
from huey import RedisHuey
from huey.constants import EmptyData
from huey.signals import SIGNAL_EXECUTING, SIGNAL_COMPLETE, SIGNAL_ERROR, SIGNAL_REVOKED

EXECUTING_PREFIX = "executing"

redis_addr = os.getenv("REDIS", "localhost")
huey = RedisHuey('entrypoint', host=redis_addr)

def get_executing_count():
    global huey
    redis_client = huey.storage.redis_client()
    _, matching = redis_client.hscan(huey.storage.result_key, match=f"{EXECUTING_PREFIX}-*")
    return len(matching)

@huey.signal(SIGNAL_EXECUTING)
def task_signal_executing(signal, task):
    global huey
    huey.storage.put_data(f"{EXECUTING_PREFIX}-{task.id}", 1)

@huey.signal(SIGNAL_COMPLETE)
def task_signal_complete(signal, task):
    global huey
    huey.storage.delete_data(f"{EXECUTING_PREFIX}-{task.id}")

@huey.signal(SIGNAL_ERROR, SIGNAL_REVOKED)
def task_signal_error(signal, task, exc=None):
    global huey
    huey.storage.delete_data(f"{EXECUTING_PREFIX}-{task.id}")
```

**Comment by coleifer** [comment]
That is potentially very inefficient, it just depends on how many results are in the result store. I would not recommend that approach.

**Comment by onasipim** [comment]
> What do you mean "currently executed"? Tasks that are running _right now at this instant_? That is not something `huey` currently supports, though you can infer it from the signals mechanism.

Wouldn't that be one of the main responsibilities of a message broker? To have knowledge what's going on in the queue. Any idea if this is going to get implemented? If not could you please draw a rough sketch how to implement it with signals as you mentioned. Thanks!

**Comment by coleifer** [comment]
It's pretty easy to accomplish, depending on which backend/broker you use. Redis is probably the easiest... Just attach handlers. Modifying the above code example, it is trivial to store the currently-running task IDs in a redis set:

```python
# e.g., get redis conn from our huey object:
huey = RedisHuey('entrypoint', host=redis_addr)
redis = huey.storage.redis_client(connection_pool=huey.storage.pool)

def get_executing_count():
    return redis.scard('executing-tasks')

@huey.signal(SIGNAL_EXECUTING)
def task_signal_executing(signal, task):
    redis.sadd('executing-tasks', task.id)

@huey.signal(SIGNAL_COMPLETE)
def task_signal_complete(signal, task):
    # task finished successfully
    redis.srem('executing-tasks', task.id)

@huey.signal(SIGNAL_ERROR, SIGNAL_LOCKED, SIGNAL_INTERRUPTED, SIGNAL_CANCELED)
def task_signal_error(signal, task, exc=None):
    # some kind of issue.
    redis.srem('executing-tasks', task.id)
```

Other idea might be to use redis pubsub to stream events, if that's more suitable to your use-case:

```python

@huey.signal()
def signal_handler(signal, task, exc=None):
    redis.publish('queue-events', json.dumps({'signal': signal, 'task_id': task.id}))
```

Also note you can always inspect the queue length, result-store size, schedule size, etc, using the storage API methods [documented here](https://huey.readthedocs.io/en/latest/api.html#BaseStorage):

* `queue_size()` - number of tasks waiting to run
* `enqueued_items()` - the actual data
* `schedule_size()` etc
* `scheduled_items()`
* `result_store_size()`
* `result_store_items()`

**Comment by onasipim** [comment]
Thank you very much for your detailed explanation. As the storage API does not help solving the problem of determining the running tasks I used your approach with signals. Using Django and the sqlite backend I came up with following

```python
from huey.contrib.djhuey import task, HUEY
from huey.signals import SIGNAL_EXECUTING, SIGNAL_COMPLETE, SIGNAL_ERROR, SIGNAL_LOCKED, SIGNAL_INTERRUPTED, \
    SIGNAL_CANCELED

HUEY.storage.sql('create table if not exists executing (key text not null, primary key(key))', commit=True)

@task()
def task_to_do():
    pass

def get_executing_count():
    return HUEY.storage.sql('select count(key) from executing', results=True)[0][0]

def is_task_executing(task_id):
    if HUEY.storage.sql('select exists (select 1 from executing where key=? limit 1)', (task_id,), results=True)[0][0] == 1:
        return True
    else:
        return False

@HUEY.signal(SIGNAL_EXECUTING)
def task_signal_executing(task):
    HUEY.storage.sql('insert into executing (key) values (?)', (task.id,), True)

@HUEY.signal(SIGNAL_COMPLETE)
def task_signal_complete(task):
    HUEY.storage.sql('delete from executing where key=?', (task.id,), True)

@HUEY.signal(SIGNAL_ERROR, SIGNAL_LOCKED, SIGNAL_INTERRUPTED, SIGNAL_CANCELED)
def task_signal_error(task):
    HUEY.storage.sql('delete from executing where key=?', (task.id,), True)
```

I still think that your library would benefit from such a functionality out of the box across all backends.

**Comment by coleifer** [comment]
Beware with Sqlite you may run into "database is locked" errors and the like, which (if unhandled correctly) will lead to your state table being corrupt/incorrect.
