### ISSUE TITLE
Handle error on last retry only & retrieve exception traceback

### ISSUE THREAD

**Issue by jvzammit** [coleifer/huey#490]
Not an issue; asked a question on SO, posting here in the hope that someone authoritative with this task queue can answer it:

https://stackoverflow.com/questions/60341868/huey-task-queue-handle-error-on-last-retry-only-retrieve-exception-traceback

Question Title: `Huey Task Queue handle error on last retry only & retrieve exception traceback`

TIA!

**Comment by coleifer** [comment]
Questions belong on SO, the issue tracker is for issues.
