### ISSUE TITLE
Feature proposal, make `.then` and `.error` support Task instances

### ISSUE THREAD

**Issue by cdosborn** [coleifer/huey#491]
Curious if you would support a pr to extend `.then` and `.error`.

Right now they assume that their first argument is a `TaskWrapper`. If we permitted a `Task`, then it would be easier to build some pipelines.

For example, you may want to do something like:
```
pipelineA = blah.s().then(success).error(handle_a_error)
pipelineB = ... similar to above but for B stuff
pipelineC = ... similar to above but for C stuff

# This doesn't work because pipelineB is missing a `.s` method
pipelineA.then(pipelineB).then(pipelineC)
```
To achieve the same thing currently:
```
pipelineA.on_complete = pipelineB
pipelineB.on_complete = pipelineC
```

I think this change would be nice, since it allows pipelines to be used interchangeably with tasks, and the distinction between a Task and Signature doesn't seem huge, the Task just has some arguments already.

**Comment by coleifer** [comment]
It's unusual to be dealing with a task instance directly, unless it is a pipeline or created with `.s()`. Calling a task-decorated function creates the task instance, enqueues it, and returns you a result handle, so you're never really dealing with the task.

That said, making pipelines composable certainly makes sense to me, and should be easy to support.

**Comment by coleifer** [comment]
Thanks for the suggestion. This is now implemented in master.

**Comment by cdosborn** [comment]
Wow, super.
