### ISSUE TITLE
document do not match about RedisHuey

### ISSUE THREAD

**Issue by vernvern** [coleifer/huey#496]
huey version: **2.1.3**

## document do not match about RedisHuey

`RedisHuey` \`s doc in [Huey`s API](https://huey.readthedocs.io/en/latest/api.html):
![image](https://user-images.githubusercontent.com/20513223/75136601-29330180-5720-11ea-83b9-444d306bd91a.png)

`RedisHuey` \`s doc in `help(RedisHuey)`:
![image](https://user-images.githubusercontent.com/20513223/75136662-54b5ec00-5720-11ea-870d-f85bcf7493ce.png)

## problems

`help(RedisHuey)` looks like `Huey`\`s doc. 

And  `SqliteHuey`、`RedisExpireHuey`  in the same problem.

**Comment by coleifer** [comment]
Common parameters are documented on the Huey object:

https://huey.readthedocs.io/en/latest/api.html#huey-object

I've added some notes to the docs to hopefully help make that more clear. Thanks.
