### ISSUE TITLE
retry task

### ISSUE THREAD

**Issue by miluChen** [coleifer/huey#501]
Suppose the consumer and several workers are running just fine. Suddenly, something happened (e.g. getting the signal from the OS saying the machining will be shut down in 1 min), and I want to stop the workers from executing now and retry later. Will this be a nice-to-have feature in `huey`?

**Comment by coleifer** [comment]
I'm not sure how you would handle that in huey. I'd also assume that the OS will first try to gracefully stop the huey consumer (meaning tasks can continue) up to a given time before it kills it. I don't think you'd need this, but you can always configure a process-manager in front of your consumer to handle sending the regular unix signals to the consumer on some event.

**Comment by miluChen** [comment]
The problem is that the worker may take quite long time to finish, e.g. 15 mins. OS will try to gracefully stop the consumer but will eventually "ungracefully" kill it since the worker can not finish in time. Together with the fact that the task is dequeued when the worker picks it up, it means the unfinished task is gone in this case and there is no way to retry it.

It'll be great if the consumer has some way to tell the worker to just stop and enqueue the task. The task could be picked up later to retry.
