### ISSUE TITLE
Change timeframe of periodic task during runtime

### ISSUE THREAD

**Issue by faulander** [coleifer/huey#503]
I have a function which gets data from an api, which is paged results. I want to get that api results in a 1 minute timeframe until the last set of data. When this is received, i want to change the timeframe to 24 hours. Is this possible?

Pseudo Code:
- @db_periodic_task(crontab(minute='*/1'))
- get_api(page)
- page += page
- if api doesn't deliver data, change contab to 24hrs

**Comment by coleifer** [comment]
I don't think this is a good fit for periodic tasks.

Just write a task that starts reading the data, and if there's more data, have it schedule another run in 1 minute -- if no more data, schedule the next run in 24 hours.
