### ISSUE TITLE
Potential Memory Leak when periodic task queues tasks   

### ISSUE THREAD

**Issue by ccostel** [coleifer/huey#504]
## Issue 
It seems the way I use huey causes a memory leak.
- periodic task runs every 10 min
- periodic task loops through list of 5000 objects and calls a huey task 
- huey task has `retries=1` and can raise a requests exception
- running 1 consumer with 90 threads -> `huey_consumer.py tasks.huey --workers=90`
- after every 5000 tasks are finished machine ram is still allocated and grows on the next periodic task execution
- eventually machine runs out of the 15 Gb of RAM and my PC crashes. 

## Things I notice and might be relevant
- redis-cli `llen <task_key>` is 0 even when consumers are still executing
- redis-cli `hlen <task_result_key>` is always growing but does not seem to be the place where all 15Gb of RAM are used.

## Questions
1. Am I doing something stupid? 
2. Am I missing some configuration on task/periodic_task? 
3. Is it supported to have a periodic_task call tasks and do I do it correctly?
4. Are my tasks being closed/handled correctly?
5. Did I find a memory leak? :thinking: 

## Sample Code 

**tasks.py**
```
import requests
from huey import RedisHuey
from huey import crontab
from models import Node, Ingestor
from nknspider.nknscraper import NKNScraper
from enums import NODE_EVENTS

huey = RedisHuey('nknanalytics-huey', '127.0.0.1')


def check_for_events(node, old_metrics, new_metrics):
	# compares values
	# persists data to the DB
	pass


@huey.task(retries=1)
def scan_node(node):	
	try:
		scraper = NKNScraper(node.ip)
		metrics, neighbour_ips = scraper.get_node_data()

		old_metrics = {
			"uptime": node.get_last_hismetric('uptime'),
			"props": node.get_last_hismetric('props'),
			"state": node.get_last_hismetric('state')
		}

		check_for_events(node, old_metrics, metrics)
		Ingestor.ingest_his_metrics(node, metrics)
		
	except requests.exceptions.HTTPError as e:
		print(e.response.text)
		print("NODE_EVENT_OFFLINE")

@huey.periodic_task(crontab(minute='*/10'))
def scan_all_nodes():
	nodes = Node.query.filter_by(active=True).all()
	for node in nodes:
		r = scan_node(node)


```

## Final notes
Thank you @coleifer for both celery and huey. I've used celery and hope huey can be a more clean and simple way of achieving my goals.

**Comment by coleifer** [comment]
Huey - the python code - does not leak memory. However, if your tasks that you are spawning return a non-empty value, then those return values are placed in the results store and will not be removed unless read (via the result handle). I'd suggest making sure the tasks you are spawning do not have a return value.

Additionally, it is difficult to diagnose because I have no idea where your RAM usage is occurring. Is it the python process or redis?

Lastly, what do you mean when you say you are running 90 huey consumers? A single consumer with 90 worker processes? 90 threads? 90 greenlets?

**Comment by ccostel** [comment]
> Huey - the python code - does not leak memory. However, if your tasks that you are spawning return a non-empty value, then those return values are placed in the results store and will not be removed unless read (via the result handle). I'd suggest making sure the tasks you are spawning do not have a return value.

Thanks for this clarification.

> Additionally, it is difficult to diagnose because I have no idea where your RAM usage is occurring. Is it the python process or redis?

I've also not been able to diagnose where the issue is happening. I thought I was not using huey properly. 
I will try to look if it is indeed redis.

> Lastly, what do you mean when you say you are running 90 huey consumers? A single consumer with 90 worker processes? 90 threads? 90 greenlets?

1 consumer with 90 threads -> `huey_consumer.py tasks.huey --workers=90` 
I updated the issue description too. 

**A followup questions:**
1. Does a task always needs to return something a non-empty value?
2. Is it ok to use a `periodic_task` to call regular `tasks`?

**Comment by coleifer** [comment]
Whoa... I would not use nearly so many threads. Maybe use 1x number of cores, but even then Python is always going to run single-threaded. Multiple threads are fine for normal workloads because Python can context-switch at appropriate times, but when you are crunching numbers its a terrible idea.
