### ISSUE TITLE
task - no result

### ISSUE THREAD

**Issue by amainz** [coleifer/huey#506]
I am just starting with Huey and tried the example:

```
huey = SqliteHuey(filename="/home/and/db.sqlite3")
huey.immediate = True

@huey.task()
def add(a, b):
    return a + b

print('1 + 2 = %s' % result.get(blocking=True))
```
It works fine for testing purposes.

When I switch to 
`huey.immediate = False`

I do not get any response. It seems to hang forever with no error at all.

The worker puts out this only:
```
python3 manage.py run_huey 
[2020-03-21 06:43:00,847] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 54037 at 2020-03-21 06:43:00.847231
[2020-03-21 06:43:00,847] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[2020-03-21 06:43:00,847] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[2020-03-21 06:43:00,847] INFO:huey.consumer:MainThread:The following commands are available:
```

The SQLite DB is in place and I see that records are added to table "task".

Any idea how I can troubleshoot this deeper?

**Comment by coleifer** [comment]
Possibly your consumer and app are pointing to different database instances? Or maybe you have `settings.DEBUG = True`?

Huey is not fundamentally broken, so it's probably something in your configuration.

**Comment by amainz** [comment]
Good hint.

I looked at the redis requests:
The default settings I copied had as name reference (settings.py):
`  'name': settings.DATABASES['default']['NAME'],  # Use db name for huey`

which did not correspond to the init:
```
pool = ConnectionPool(host='localhost', port=6379, max_connections=20)
huey = RedisHuey('my-app', connection_pool=pool)
```

Now at least this works. 

I get now another error:
`huey.exceptions.HueyException: den.tasks.add not found in TaskRegistry`

I looked at your documentation and found the separation into config.py, app.py and task.py, which has been applied to my codebase to prevent this error, but still get it.

I have the task.py in an subapp => app/subapp

Could this be an issue? I do not know where "manage.py run_huey" is normally looking.

**Comment by jonnyarnold** [comment]
Hi @amainz! The error you're getting is covered in the [troubleshooting](https://huey.readthedocs.io/en/latest/troubleshooting.html) section of the documentation:

> Exception occurs when a task is called by a task producer, but is not imported by the consumer. To fix this, ensure that by loading the Huey object, you also import any decorated functions as well.

Hopefully this will point you in the right direction 🙂
