### ISSUE TITLE
TaskWrapper has no method 'map'

### ISSUE THREAD

**Issue by cymoo** [coleifer/huey#507]
There is an example in API documents: [map(it)](https://huey.readthedocs.io/en/2.0a/api.html#TaskWrapper.map)

```
@huey.task()
def add(a, b):
    return a + b

rg = add.map([(i, i * i) for i in range(10)])

```

But 'map' was not found in 'TaskWrapper'.
It does exist in tag 2.0.0.

```
def map(self, it):
        return ResultGroup([self.huey.enqueue(t) for t in self._apply(it)]) 
```

**Comment by coleifer** [comment]
Is there a question? `map()` is added in 2.x

**Comment by cymoo** [comment]
> Is there a question? `map()` is added in 2.x

no `map()` in 2.2, but it does has in 2.0

**Comment by coleifer** [comment]
https://github.com/coleifer/huey/blob/2.2.0/huey/api.py#L776

**Comment by cymoo** [comment]
> Is there a question? `map()` is added in 2.x

So sorry...My cat jumped on my keyboard and deleted those 3 lines when I browsed the source code...
Thanks so much for your reply so quickly.
btw, I am a big fan of peewee for many years ^_^

**Comment by coleifer** [comment]
Cats always be up to crazy pranks. You're good brother, no worries!
