### ISSUE TITLE
tasks.add not found in TaskRegistry

### ISSUE THREAD

**Issue by amainz** [coleifer/huey#508]
I am using Huey in Django and took your example .add code.

I get now the error:
`huey.exceptions.HueyException: den.tasks.add not found in TaskRegistry`

I looked at your documentation and found the separation into config.py, app.py and task.py, which has been applied to my codebase to prevent this error as suggested, but I still get it.

I have the task.py in an subapp => app/subapp

Could this be an issue? I do not know where "python manage.py run_huey" is normally looking.

**Comment by coleifer** [comment]
>Huey is not fundamentally broken, so it's probably something in your configuration.

Additionally, I am not here to tutor you or debug your code.

Questions like this belong on stackoverflow, please.

https://huey.readthedocs.io/en/latest/contrib.html#django

**Comment by coleifer** [comment]
There is also a django example app: https://github.com/coleifer/huey/tree/master/examples/django_ex
