### ISSUE TITLE
Some tasks not getting called

### ISSUE THREAD

**Issue by CameronSima** [coleifer/huey#509]
I have a Django rest framework app that calls 2 huey tasks in succession in a serializer create method like so:

def create(self, validated_data):
    user = self.context['request'].user
    player_ids = validated_data.get('players', [])
    game = Game.objects.create()

    tasks.make_players_friends_task(player_ids)
    tasks.send_notification_task(user.id, game.id)
    return game

@db_task()
def make_players_friends_task(ids):
    players = User.objects.filter(id__in=ids)
    // process players

@db_task()
def send_notification_task(user_id, game_id):
    user = User.objects.get(id=user_id)
    game = Game.objects.get(id=game_id)
    // send notifications

When running the huey process in the terminal, when I hit this endpoint, I can see that only one or the other of the tasks is ever called, but never both. I am running huey with the default settings (redis with 1 thread worker.)

If I alter the code so that I am passing in the objects themselves as parameters, rather than the ids, and remove the django queries in the @db_task methods, things seem to work alright.

The reason I initially used the ids as parameters is because I assumed (or read somewhere) that huey uses json serialization as default, but after looking into it, pickle is actually the default serializer.

One theory is that since I am only running one worker, and also have a @db_periodic_task method in the app, the process can only handle listening for tasks or executing them at any time, but not both. This is the way celery seems to work, where you need a separate process for a scheduler and a worker each, but this isn't mentioned in huey's documentation.

**Comment by coleifer** [comment]
>One theory is that since I am only running one worker, and also have a @db_periodic_task method in the app, the process can only handle listening for tasks or executing them at any time, but not both

No, huey has no "gotcha's" like that. The worker parameter applies only to the worker count. There will always be a separate scheduler.

I'm not sure what you're running into. I'd suggest dropping print statements in your code (and optionally in the db_task() code) and trying to figure out where exactly the problem occurs.

Huey is well-tested and used by a lot of people. You should be able to add as many tasks as you like, regardless of worker count, and see them executed.

**Comment by CameronSima** [comment]
Should I expect to see an error logged if my application code throws an Exception?

**Comment by coleifer** [comment]
Yes.

**Comment by CameronSima** [comment]
I added print statements as you suggested inside the `@db_task` decorated methods, still the same issue. With each call, I'll see either "Executing make_players_friends_task" OR "send_notification_task", sometimes neither, but not both. Which one gets called seems random, and the print statements don't get called at all for the method that doesn't run.

**Comment by CameronSima** [comment]
I added print statements as you suggested inside the `@db_task` decorated methods, still the same issue. With each call, I'll see either "Executing make_players_friends_task" OR "send_notification_task", sometimes neither, but not both. Which one gets called seems random, and the print statements don't get called at all for the method that doesn't run.

**Comment by coleifer** [comment]
I'd suggest connecting to redis via telnet or the CLI and running a `MONITOR` command to see if your commands are reaching the queue properly.
