### ISSUE TITLE
@on_startup function not run if it has the same name as another function

### ISSUE THREAD

**Issue by zeraien** [coleifer/huey#510]
If I have multiple functions decorated with @on_startup, with the same name, even if they are in different modules, only one of the functions will be run.
This seems like a bug to me since other tasks can have the same function name as long as they are in different modules.
Besides, there are only so many imaginative function names you can come up with to decorate with @on_startup... :-)

**Comment by coleifer** [comment]
Just name it something different in the `@on_startup()` decorator, e.g.:

```python

@huey.on_startup('whatever')
def my_function_with_same_name():
    pass
```

**Comment by zeraien** [comment]
I agree that there is a workaround, but still feels like a bug to me, since regularly decorated functions can have the same names... If I find the time to make a pull request, would you consider it? ;-)
