### ISSUE TITLE
Error: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

### ISSUE THREAD

**Issue by bertothunder** [coleifer/huey#513]
Hi there,

 I've started using Huey for a new project, and just found this error.

 The specific task's function definition would be like this:

```
from tasks import huey

@huey.task
def reset_user_password(session, username)
```

Being the <session> parameter a sqlalchemy session object (coming from sessionmaker()) and created in a Flask app (this tasks are being queued from graphql endpoints, so the session is always provided). However, seems Huey can't pickle that session object, given the error in the subject.
 
I know it'd be probably a much better idea to create the session within the task, but in this case it helps during the tests (since the session fixture we use will rollback any data being introduced / modified through each test).

I'm not much familiar with pickle, googling about this specific error does not seem to help much, either. Any idea?

**Comment by bertothunder** [comment]
Hi again,

 I think I understand the issue, right now the original error is gone. 

 In my original code, the `session` object was constructed using a scoped_session constructor from a SQLAlchemy's sessionmaker() factory, which was bound to the postgresql connection later configure method. This seems to make the session instance unpickeable, from my tests.

I'm constructing the fixture now in a different order:

```
@pytest.fixture(scope='function')
def session(sqlengine):
    connection = sqlengine.connect()  # sqlengine is constructed somewhere else
    transaction = connection.begin()
    session = sessionmaker()
    session.configure(bind=connection)
    session = scoped_session(session)

    def teardown():
        transaction.rollback()
        connection.close()
        session.remove()

   return session
```

This helps with the original issue, however, I've now a new one I can't really understand.

2020-04-21 11:21:59,365 - ERROR - graphql.mutations:mutations.py:104 - Error happened on mutation resetPassword: "can't pickle _thread._local objects"

This is happening, again, the time I'm calling the task function (not even when huey tries to execute it). But no idea what the _thread._local object comes from.

**Comment by coleifer** [comment]
You can't pickle your sqlalchemy session ... You need to manage a separate session within your task consumer process.

**Comment by bertothunder** [comment]
Yeah, that would be the rightful answer, I agree, but it has a major caveat that has got me for 3 days and could not fix, yet.... testing!

A bit of scenario: 

My actual project relies heavily on background tasks, where I did evalute huey and dramatiq as rightful replacements for celery. I like more huey for several reasons.

Some of the tasks are heavy tasks based on repeatable steps, so I've designed a set of smaller tasks, and then modelled the heavy tasks into huey pipelines.

For unit tests, I've this pytest fixture for a session:

```
@pytest.fixture(scope='function')
def session(request, engine):
@pytest.fixture(scope='session')
def sqlengine(request):
    """
    Get the db engine
    :param request:
    :return:
    """
    engine = create_engine(DB_URI)
    return engine


@pytest.fixture(scope='function')
def session(request, sqlengine):
    """
    Session for use in tests
    :param request:
    :param sqlengine:
    :return:
    """
    connection = sqlengine.connect()
    transaction = connection.begin()
    session = scoped_session(sessionmaker())
    session.configure(bind=connection)

    def teardown():
        transaction.rollback()
        connection.close()
        session.remove()

    request.addfinalizer(teardown)
    return session
 ```

This ensures that any change done through the test is deleted immediately, which keeps a predictible testing scenario.

However, this session can't be passed to the huey task, which means that, as you suggested, the session should be created within each task. Only issue with this approach is there's no control over the data generated / modified during those tasks, which breaks my testing scenario.

I've considered some different approaches to this problem, without any sucess so far. How do you perform tests on this kind of scenarios?

**Comment by coleifer** [comment]
The consumer runs as a separate process. A database connection (represented by the sqla session) typically has a socket open to the database and a whole bunch of other state. You can't pass them around from one process to another.

Check out the huey startup hooks - these can be used to initialize resources that will be shared by the workers.

Alternatively look at the implementation of the `db_task()` decorator in the Django "djhuey" extension. That decorator handles opening/closing the conn around the task body.
