### ISSUE TITLE
Unable to perform periodic tasks using mini_huey

### ISSUE THREAD

**Issue by varunsarvesh** [coleifer/huey#515]

**Comment by coleifer** [comment]
https://huey.readthedocs.io/en/latest/contrib.html#MiniHuey.start

**Comment by varunsarvesh** [comment]
>>> from huey.contrib.mini import MiniHuey
>>> from huey import crontab
>>> huey = MiniHuey()
>>> huey.start()
>>> @huey.task(crontab(minute='*'))
... def fun():
...     f = open("demofile.txt", "a")
...     f.write("zzyy   ")
...     f.close()
... 
>>> fun()



i tried this , stiill only once it is being executed , could you help me @coleifer

**Comment by coleifer** [comment]
Are you running that from a python interactive session? MiniHuey uses gevent. You need to monkeypatch so that the loop will run and switch tasks...

**Comment by varunsarvesh** [comment]
Im actually running this django shell,  
 from gevent import monkey
 monkey.patch_all()
does including this in manage.py , wiil loop the tasks , or wat else, and is there a way to check is the periodic task is still in progress and for mini_huey is the consumer needed??( i.e. the run_huey command is it needed for mini_huey also?)

**Comment by varunsarvesh** [comment]
ive tried including the above sniipet into manage.py still unable to perform periodic tasks using mini_huey , what else should , im lost here, can you help me out @coleifer

**Comment by coleifer** [comment]
http://c9x.me/articles/gthreads/intro.html
