### ISSUE TITLE
get task_id in logs

### ISSUE THREAD

**Issue by cresg820** [coleifer/huey#516]
Hi, any idea of how to get task_id in in log?

With celery i've created a custom log handler and attached it with after_setup_task_logger signal like below:

```
class RedisLogFilter(logging.Filter):
    def filter(self, record):
        if get_current_task() is None:
            return 0
        else:
            return 1


class RedisLogHandler(logging.StreamHandler):
    def emit(self, record):
        publish_event({
            'event': 'log_entry',
            'task_id': get_current_task().request.id,
            'msg': self.format(record),
        })
```

could you please add contibuting guidelines? Or you don't want third party contributors?

last questione: what are you plans for the future?

**Comment by coleifer** [comment]
We don't use a global / context-local system, so there's not really a way to get ahold of it like that. You can configure your tasks to accept the task as an argument and do your logging within your application code, of course. Another option is to use the [signals](https://huey.readthedocs.io/en/latest/signals.html) mechanism.

**Comment by cresg820** [comment]
> You can configure your tasks to accept the task as an argument and do your logging within your application code, of course. 

You mean something like this?
```
@huey.task(context=True)
def pippo(task=None):
    task.logger.debug("my log")
```
But i need a custom task class of something similar.

> Another option is to use the [signals](https://huey.readthedocs.io/en/latest/signals.html) mechanism.

I'm not getting the point, could you provide some example?

**Comment by coleifer** [comment]
>Hi, any idea of how to get task_id in in log?

I'm suggesting ways you can get the task-id in your code, so that you can include it in your logs.
