### ISSUE TITLE
Huey ignores schedule and runs task one after another

### ISSUE THREAD

**Issue by Larleyt** [coleifer/huey#523]
As the topic says, huey ignores the schedule and runs tasks one after another
Let's say I have
In `huey_config.py`:
```
huey_q = RedisHuey("sync-queue", host=os.environ.get("REDIS_URL", "localhost"), immediate=False)
```

In `huey_run.py` which is eventually invoked by `huey_consumer.py`:
```
from .zd_sync import grab_period_task, grab_period_cron
from .huey_config import huey_q
<some logging related logic>
```

In `zd_sync.py`:
```
grab_period_task = huey_q.task()(grab_period)
grab_period_cron = huey_q.periodic_task(
    validate_datetime=crontab(
        minute='0',
        hour=f'*/{config.SYNC_LOOKBACK_HOURS}'),
    name="grab_period_cron"
)(grab_period)
```

, where `SYNC_LOOKBACK_HOURS` is _a lot_ of hours, `grab_period_task` is usual, manually invoked task, `_cron` – a scheduled one.

Consumer is then run as:
`huey_consumer.py -f pkg.sync.huey_run.huey_q -w1` inside Docker (maybe the Docker somehow matters)

What am I doing wrong?

**Comment by coleifer** [comment]
You might check to see if your queue is filled-up with pending tasks from previous executions that failed or something. Flushing your redis is a good start.

If this doesn't help, then please share the logging output (verbose-mode) of the consumer.

When you say "one task after another" you'll have to be more clear. Like, constantly? Or whenever the scheduler wakes up, it is enqueueing your task?

huey is not fundamentally broken, so I am very inclined to believe you have a code or logic error.
