### ISSUE TITLE
about  job alive question

### ISSUE THREAD

**Issue by ldbfpiaoran** [coleifer/huey#524]
Hello, I have been studying distributed queues recently. There are sonmething I don’t understand. After registering a worker, if the worker exits abnormally, how does the task management know whether it is alive

**Comment by coleifer** [comment]
You can see how this is implemented in `huey/consumer.py`. Each environment provides a handler for checking whether a thread/process/greenlet is alive. The liveness-check, if enabled, uses this to restart dead workers.
