### ISSUE TITLE
Singleton shared tasks?

### ISSUE THREAD

**Issue by traverseda** [coleifer/huey#526]
I'm using the whoosh search engine library to index a large amount of documents with some fairly CPU-intensive operations preparing the data for the search engine. It's part of an intranet search system I'm hoping to get made part of the internet-in-a-box project, but which I'm testing on my multi-TB personal archive.

I'm running into two big problems, the first is in any kind of cluster most of the computers involved wouldn't be able to actually add files to the index, since it relies on local resources. The second is that whoosh would really prefer to handle it's own multiplexing, I can spawn a bunch of writers but then they each get their own cache, there's contention for the index lock, the write-caches end up being pretty much useless, and in general efficiency goes out the window.

I'm wondering if there's some way I could make a task a singleton, so that there's only one *consumer* for that type of task?  I don't care what process that consumer runs in, I just want it to be a singleton, have there be only one process consuming that type of task and have it not be migrating.

Obviously one approach would be to spawn an entirely separate consumer that only handles those particular tasks, which would work but which would complicate my implementation a great deal. 

Any thoughts on how I could handle this in a clean way? Currently I'm thinking that I'd probably fork before a create/launch my consumer and load in my singleton tasks, then launch my general-purpose consumers.

**Comment by coleifer** [comment]
Huey has a concept of locks which ensure only 1 instance of a task is executing at a given time, but that is not quite what you're after.

Using a separate consumer with a single worker is probably what you want for the exact situation you are describing. I'd suggest thinking a bit outside the box, though. I mean, a regular multiprocessing.Queue is probably all you need, coupled with something draining the queue and writing to whoosh.

**Comment by traverseda** [comment]
Unfortunately a simple multiprocessing queue won't work if there's more than one PC involved. I'm trying to support local processing as well as  small clusters. It can get pretty CPU intense, depending on exactly what you're indexing. I expect that to get worse as time goes on.
