### ISSUE TITLE
huey.exceptions.TaskException is not pickleable

### ISSUE THREAD

**Issue by cdosborn** [coleifer/huey#536]
I have a parent task which calls sub tasks (this is illustrated in a code example at the bottom). The parent task will call get on the sub tasks' results. If a sub task fails, then it will raise the child's exception, failing itself. The caller of the parent task, chains with the .error to register an error handler task. Whenever the child task raises any exception, huey throws an internal error and fails to run the error handler task.

```
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/huey/consumer.py", line 108, in loop
    task = self.huey.dequeue()
  File "/venv/lib/python3.7/site-packages/huey/api.py", line 301, in dequeue
    return self.deserialize_task(data)
  File "/venv/lib/python3.7/site-packages/huey/api.py", line 276, in deserialize_task
    message = self.serializer.deserialize(data)
  File "/venv/lib/python3.7/site-packages/huey/serializer.py", line 93, in deserialize
    return self._deserialize(data)
  File "/venv/lib/python3.7/site-packages/huey/serializer.py", line 73, in _deserialize
    return pickle.loads(data)
TypeError: __init__() missing 1 required positional argument: 'metadata'
```

I dug around a bit, and found out that this is because TaskException is not pickleable. TaskException has a very simple definition, so this is actually an issue with BaseException. BaseException provides its own `__reduce__`, a method which instructs pickle on deserialization. That method results in `TaskException` being called with the args passed to BaseException, not the args passed to `TaskException` so a TypeError is thrown. Huey could either pass all its arguments to Exception, or it could define it own `__reduce__` method, or it could make its metadata argument optional. 

```
@huey.task()
def parent():
    t = child()
    t.get(blocking=True)

@huey.task()
def child():
    raise Exception("Oh no!")

@huey.task()
def handle_error(exc):
    pass

pipeline = parent.s().error(handle_error.s())
huey.enqueue(pipeline)
```
https://stackoverflow.com/a/41809333/1213041

**Comment by coleifer** [comment]
Is there any reason to call the subtask in that manner when you are effectively calling it synchronously anyways? I think a lot of effort on your part could have been avoided by simply calling it as a regular function. Task-decorated functions have a `call_local()` method which provides access to the un-decorated function. I think I'm going to recommend this for now, but please comment if there's a compelling argument against this.

**Comment by cdosborn** [comment]
The code example I provided is contrived, but in my use case I have a parent task which spawns many child tasks, then needs to wait for them to complete.
