### ISSUE TITLE
Difficult to override Task base class

### ISSUE THREAD

**Issue by brettmcintosh** [coleifer/huey#537]
I've overridden `Task` to include some custom logic in `Task.then` and I've also overridden `TaskWrapper` to use the new `CustomTask` class as its `task_base`. To get my `Huey` instance to use the new `CustomTaskWrapper` class, I have to also override the hard-coded `TaskWrapper` usages in `Huey.task` and `Huey.periodic_task`, which I can only do by rewriting the method and replacing `TaskWrapper` with `CustomTaskWrapper`. 

This would be much easier if `Huey` included a class attribute called `task_wrapper_base`, and then used `self.task_wrapper_base` instead of the hard-coded `TaskWrapper` in its methods.

Is there an existing way to do this that's easier? If not, would you be open to me making a PR to make this change? I'd have to define `Task` and `TaskWrapper` before `Huey` to set `Huey.task_wrapper_base = TaskWrapper`, so it would involve moving some existing code around, but other than that it's a pretty small change.

**Comment by coleifer** [comment]
You're welcome to use huey however you like, of course, but I'm not interested in maintaining that.
