### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by minyoung90** [coleifer/huey#539]
Hi,

Python 3.6.8
Django 2.2.8
hue 2.2.0
redis 3.5.3

I got this runtime error when passing a parameter as a type of python dictionary.

> **dictionary changed size during iteration**

If I erase decorator (db_tast()) then, I can call the function but, after adding the decorator, above runtime error occurs.

My source is below (I called this function in a Django view).
Without parameter is fine
```
@db_task()
def submit(submit_env: dict) -> None:
    pass
```

**Comment by minyoung90** [comment]
Finally, I tested passing **any parameter** with @db_task() gives me the same error

**Comment by coleifer** [comment]
Without the actual traceback its impossible to tell where the problem is.

**Comment by minyoung90** [comment]
For users, Not any parameters, int type is fine

**Comment by coleifer** [comment]
>Without the actual traceback its impossible to tell where the problem is

This means: please post the full traceback
