### ISSUE TITLE
Query regarding sharing of resource between consumers and main program

### ISSUE THREAD

**Issue by Scsourav18** [coleifer/huey#541]
Hi
I have just started using huey. I have implemented a function which is using huey task. I have a singleton class 'S'  which is initialized by a service 'A' prior to calling the task decorated function 'F' in my application. The huey consumers (worker type as thread)are started when the application starts. When I access the singleton class 'S' within the task decorated function 'F', instead of using the already created object of  'S',  its creating a new object. Is there any way through which the workers can use the same object of  'S' which was created by service 'A' instead of creating a new one or am I missing some point regarding this.

Thanks

**Comment by coleifer** [comment]
I'm sorry but I don't understand the question.
