### ISSUE TITLE
Unable to handle signals with django

### ISSUE THREAD

**Issue by adricu** [coleifer/huey#546]
Hi 

I am trying to handle Huey signals in a django deployment but I am not capable of see them executed in production.
In local I can see them executed by debugging the code, but when I launch the worker process with `python manage.py run_huey -n` I am not able to have the code executed.

Is there any preferable place in Django where I should place signal handlers?

Thanks,

Adrián

**Comment by coleifer** [comment]
>Is there any preferable place in Django where I should place signal handlers?

Presumably anywhere that is loaded as an import-time side-effect during startup.

**Comment by meetmangukiya** [comment]
I have declared a singal handler in a `views.py` file in django as:

```py
from huey.contrib.djhuey import signal

@signal()
def signal_handler(signal, task, exc=None):
  print(signal, task.id)
```

However, the handler is never being called 🤔 
Any suggestions / hints @coleifer ?

**Comment by coleifer** [comment]
@meetmangukiya - probably your views.py is not being imported during the consumer startup (manage.py run_huey) so the signal handler is never registered.

**Comment by meetmangukiya** [comment]
@coleifer that was the problem, thanks!

**Comment by AashishDhakal** [comment]
@meetmangukiya How did you manage to solve it? I am experiencing the same issue.
