### ISSUE TITLE
task not found in TaskRegistry

### ISSUE THREAD

**Issue by tijs** [coleifer/huey#55]
I just upgraded to the latest version in master to make use of the fix for closing the db but it seems huey is no longer finding the tasks after the update for some reason. I was already running a pretty recent version so not sure what could have changed... i upgraded huey and restarted the workers which should recreate the task registry in redis again right?

```
QueueException: queuecmd_create_initial_notifications not found in TaskRegistry
  File "huey/bin/huey_consumer.py", line 124, in check_message
    task = self.huey.dequeue()
  File "huey/api.py", line 211, in dequeue
    return registry.get_task_for_message(message)
  File "huey/registry.py", line 70, in get_task_for_message
    klass = self.get_task_class(klass_str)
  File "huey/registry.py", line 60, in get_task_class
    raise QueueException('%s not found in TaskRegistry' % klass_str)
```

**Comment by vindarel** [comment]
Hi ! I get this error after following the django tutorial. Looks like to me a small bit is missing about organizing the imports.

[The doc](https://huey.readthedocs.io/en/latest/imports.html#imports) gives a clear example with a config, a tasks.py and a main.py. However the Django doc doesn't say on how to organize the imports. 

I tried to put my decorated task into a new `tasks.py` and to import it into my models. I also feel I had to create a `huey = RedisHuey("testing")` in my settings.py and import it at the same time as the task, into my models. I'm still getting the error.

Can you give some tips ? Thanks !

**Comment by coleifer** [comment]
Check out the django example code:

https://github.com/coleifer/huey/tree/master/examples/django_ex

If you've already done this, can you share the relevant portion of your settings module?

is djhuey in your installed apps?

**Comment by vindarel** [comment]
I had not seen this example, but it's similar to the doc. I can make it work in a new django project, but not in mine :(

I have `huey.contrib.djhuey` in my settings.py:

```
DEBUG = False

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'bootstrap3',
    'bootstrap_admin',
    'django.contrib.admin',
    # Custom:
    'mod_wsgi.server',
    'huey.contrib.djhuey',

    'myapp',
)

HUEY = {
    'name': DATABASES['default']['NAME'],  # Use db name for huey.
    'result_store': True,  # Store return values of tasks.
    'events': True,  # Consumer emits events allowing real-time monitoring.
    'store_none': False,  # If a task returns None, do not save to results.
    'always_eager': DEBUG,  # If DEBUG=True, run synchronously.
    'store_errors': True,  # Store error info if task throws exception.
    'blocking': False,  # Poll the queue rather than do blocking pop.
    'connection': {
        'host': 'localhost',
        'port': 6379,
        'db': 0,
        'connection_pool': None,  # Definitely you should use pooling!
        # ... tons of other options, see redis-py for details.

        # huey-specific connection parameters.
        'read_timeout': 5,  # If not polling (blocking pop), use timeout.
        'max_errors': 1000,  # Only store the 1000 most recent errors.
        # 'url': None,  # Allow Redis config via a DSN.
    },
}
```

in tasks.py

```
from huey.contrib.djhuey import crontab, periodic_task, db_task
from models import Inventory

@db_task()
def longtask(pk):
    print "long task"
    import ipdb; ipdb.set_trace()
```

and in my api.py I just `from tasks import longtask`, but anyway with shell or run_server (I run `run_huey` first) it throws

```
ERROR [huey.consumer.Worker] Queue exception
Traceback (most recent call last):
  File "/home/vince/.virtualenvs/abelujo/local/lib/python2.7/site-packages/huey/consumer.py", line 94, in loop
    task = self.huey.dequeue()
  File "/home/vince/.virtualenvs/abelujo/local/lib/python2.7/site-packages/huey/api.py", line 225, in dequeue
    return registry.get_task_for_message(message)
  File "/home/vince/.virtualenvs/abelujo/local/lib/python2.7/site-packages/huey/registry.py", line 70, in get_task_for_message
    klass = self.get_task_class(klass_str)
  File "/home/vince/.virtualenvs/abelujo/local/lib/python2.7/site-packages/huey/registry.py", line 60, in get_task_class
    raise QueueException('%s not found in TaskRegistry' % klass_str)
QueueException: queuecmd_longtask not found in TaskRegistry
```

I really think this is the same configuration and layout as the simple working project…

Any hints ? Thanks again.

*(I could point to my project if needed)*

**Comment by vindarel** [comment]
Found it. I'm so thankfull to [a comment on another project](https://github.com/BFriedland/systorian/blob/1103cc77225dd8a8c6ef7f268f4574f057c89a99/systorian/metrics/tasks.py): 

> Must be named tasks.py and be in the top level of an INSTALLED_APPS directory
for Huey to find it.

Mine wasn't at the top level but alongside a `models` directory.
