### ISSUE TITLE
Changing periodic task creates a new supervisor process

### ISSUE THREAD

**Issue by privateuly** [coleifer/huey#553]
Thank you for this package.  I am trying to install huey with Django and running it with supervisor.   I set up a periodic task such as 

    @periodic_task(crontab(hour='*',minute='0'))
    def send_email_to_self():
        send_mail( ... )

But when I change the timing, say to run it on the half hour, I see that there are now two `python manage.py run_huey` in supervisor status.  So I have two tasks running.   How can I make sure that changing the task timing doesn't create a new process?  Thanks.

Here are some relevant conf files:
huey_supervisor.conf
```
[program:huey]
command = /webapps/myproject/env/bin/huey_start   
user = django_user
stdout_logfile = /webapps/myproject/logs/huey_supervisor.log  
redirect_stderr = true                                           
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8       
autostart=true
autorestart=true
startsecs=10
startretries=3
exitcodes=0
stopsignal=TERM
stopwaitsecs=10
```
huey_start
```
#!/bin/bash
PROJECTDIR=/webapps/myproject/src
cd $PROJECTDIR
source ../env/bin/activate    # Activate the virtual environment
python manage.py run_huey
```

**Comment by coleifer** [comment]
Huey doesn't have any autorestart on code change functionality. Are you restarting the supervised process?

You probably want to use sigint instead of sifterm, as int gives a graceful shutdown. I'd suggest reading the consumer docs. I'm guessing if you eliminate supervisor everything works as you expect?

**Comment by coleifer** [comment]
OH, I forgot. It's **right here in the docs**:

>If you plan to use supervisord to manage your consumer process, be sure that you are running the consumer directly and without any intermediary shell scripts. Shell script wrappers interfere with supervisor’s ability to terminate and restart the consumer Python process. For discussion see GitHub issue 88.

**Comment by coleifer** [comment]
https://huey.readthedocs.io/en/latest/consumer.html
