### ISSUE TITLE
Store locks separate from results in the storage layer

### ISSUE THREAD

**Issue by dboslee** [coleifer/huey#555]
It would be useful to store locks separate from results within the Storage class for the case where you want to flush out stale locks that were created at runtime like in the example below...
```
@huey.task()
def locking_task(user_id):
    with huey.lock_task(user_id):
        pass
```

Then you could have the option to flush the locks from storage on startup without needing the locks to be registered with the huey instance.

Let me know what you think. Happy to help implement

**Comment by coleifer** [comment]
This implies a new lock-specific API to the storage layer, which I have no intention of maintaining. It should be straightforward to modify either the Huey impl or the underlying Storage to add your own locking mechanism. You can see that it's essentially a wrapper around `put_if_empty()` and `delete()`.

If it were me, I'd:

* override your huey `lock_task()` method or provide a second implementation.
* subclass and override the `huey.api.TaskLock` class, specifically the `__enter__` and `__exit__` methods

If you use Redis you might utilize the expire functionality to give your locks a TTL, for instance.

Please let me know if you have a question on this and I'll do my best to help you with your impl.
