### ISSUE TITLE
Issue in db_periodic_task()

### ISSUE THREAD

**Issue by sumit4613** [coleifer/huey#556]
```
@db_periodic_task(crontab(minute='0', hour='15'))
def notify_user():
    # do something
```

I was trying to run a periodic task that runs at 3 pm every day. I used the above sample code to do this.
The task executed at 3 pm, now the issue is that after executing one time this task was running continuously every minute while
I just need to execute this task at 3 pm every day.

Is there something wrong with my crontab config or is this the issue with `Huey`.

Also, if I want to run a task at 9 am and 3 pm every day, what should be the crontab config.

Thanks.

**Comment by coleifer** [comment]
Can you share the log output?

**Comment by coleifer** [comment]
I think that something must be wrong in either a) your explanation of the issue, b) discrepancies between your actual code and what you pasted.

I ran a very minimal test django startproject / django startapp and a placeholder db periodic task that specifies a particular minute and hour, and it's working fine:

```
[2020-09-11 13:26:13,788] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task foo.tasks.test_periodic_task: 5f27b16f-2f50-45c2-bc39-748f38bb7bc6.
[2020-09-11 13:26:13,789] INFO:huey:Worker-1:Executing foo.tasks.test_periodic_task: 5f27b16f-2f50-45c2-bc39-748f38bb7bc6
hello world
[2020-09-11 13:26:13,789] INFO:huey:Worker-1:foo.tasks.test_periodic_task: 5f27b16f-2f50-45c2-bc39-748f38bb7bc6 executed in 0.000s
```

After executing once, the task did not run again while I observed.

Also, I would be *very* surprised to find something so fundamental in huey to be broken.

**Comment by sumit4613** [comment]
@coleifer maybe there was some discrepancy in my actual code. Now it's working fine. Btw thanks for maintaining this task queue.

**Comment by coleifer** [comment]
>Now it's working fine

Before opening an issue it's good to spend some time debugging it locally first. Especially when your issue implies something *foundational to the library* is broken. Because it's probably not.

**Comment by sumit4613** [comment]
Okay, will remember this from next time. :sweat_smile:
