### ISSUE TITLE
Retries, results, blocking and exceptions.

### ISSUE THREAD

**Issue by amcclanaghan-kvh** [coleifer/huey#557]
Hello @coleifer,
       As always, enjoy and appreciate this project and your continued efforts.  Lot of great progress and support; thank you.  I did have a topic I wanted to raise RE task retries, blocking or non blocking, results and exceptions.  

I believe somewhere ~ 2.0 `store_errors` was deprecated.  Prior to `store_errors` being deprecated one could fairly reliably ensure (errors were not "results") that a task with retries would not return a (source code driven) result (`None` or other) until all retries were complete; very easy to accomplish programmatically.  However, now when raising an exception, within a task to trigger a retry, the task result raises an exception where it used to return `None`.  Simplest solution for some implementations; `try/except` every request for the task result and handle appropriately.     

For `blocking=True, timeout=10` however it's a bit different.  Lets assume we are blocking for a task with retries such as `retries=2, retry_delay=3, context=True`.  And lets also say this task is making HTTP/S requests and is using the `retries=2` to account for multiple hosts or perhaps just remote HTTP/S errors; not advocating or endorsing the implementation just using as example.  The caller would rely upon the `blocking=True` to carry out the 2 attempts and return the ultimate result, however if the first task attempt raised an exception the blocking would be satisfied/unblocked by the exception.  If the ultimate result requestor was an HTTP/S based consumer they would be forced into an async OR the server side implementation would have to, off the worker/io process/thread, loop, then try/except to account for the first exception to get to the result of the second try.

I am wondering if a slight devaluing of `blocking=True` took place in the deprecation of `store_errors` within context of tasks with retries.  I am also wondering if there is not an opportunity within `get_raw_result/get`, via task decoration, to enable the suppression of exceptions (as they may be handled in consumer code).  I'd be very interested in hearing your thoughts.  

Thanks and keep the rubber side down. ;-)

**Comment by coleifer** [comment]
Blocking on the result-store always felt like a kludge, and to be honest, at that point what is the benefit of using huey rather than doing the computation locally or using true RPC?

I think the best way to handle that scenario -- taking action upon the success of a task -- is handled with task chaining.

https://huey.readthedocs.io/en/latest/guide.html#task-pipelines

Let me know if you have additional questions on that.

**Comment by coleifer** [comment]
Additionally, the exception raised when you do make the blocking call to `get()` contains metadata which indicates the remaining number of retries -- so you could implement a wrapper, if you wish.
