### ISSUE TITLE
Add to docs paragraph about task delivery reliability

### ISSUE THREAD

**Issue by hmoravec** [coleifer/huey#559]
As mentioned in https://github.com/coleifer/huey/issues/418, Huey does not attempt to ensure at-least-once delivery. I haven't found any mention about delivery reliability in the docs. I think this should be mentioned as once of the first things as it is one of the key differences compared to other libraries like Dramatiq or Celery.

**Comment by coleifer** [comment]
Ehh, I mean it doesn't ACK, but failures are put into the result store. Any kind of assurances are just what you would infer from the underlying storage, so it's kind of complicated to try and disentangle. Going to pass for now.

**Comment by hmoravec** [comment]
The [consumer workflow](https://huey.readthedocs.io/en/latest/consumer.html#consumer-internals) is described in the docs but in the step 4 I am missing what happens when the worker process is killed abruptly in the middle of task processing. It looks like the task is lost as it was pulled from the broker and information about the failure was not put into the store.

**Comment by coleifer** [comment]
Yes, that is correct.

>SIGINT is used to perform a graceful shutdown.
>
>When the consumer is shutdown using SIGTERM, any workers still involved in the execution of a task will be interrupted mid-task.

I can clarify that any tasks killed mid-execution are considered "lost".
