### ISSUE TITLE
Feature Request: Dispatch tasks to specific consumers

### ISSUE THREAD

**Issue by danbradham** [coleifer/huey#563]
Hello,

I've been using huey on an internal project at work and it's been a pleasure so far. The simplicity of the API made it very easy to get started and extend huey where we needed to. The last thing we'd like to be able to do is dispatch tasks to specific consumers. To give you a bit of context, we have multiple servers at different sites, and we'd like to have 1 central task queue with consumers at each site.

Here's what I think would be really cool. 

Add the ability to specify a list of queues when starting a consumer. These would be in addition to the default queue.
```
huey_consumer.py my.huey --queues="site1"
```
Then add a parameter to the enqueue and schedule methods to specify a queue.
```
task = some_task.s(...)
result = huey.enqueue(task, queue="site1")
```
```
result = some_task.schedule(delay=10, queue="site1")
```
Finally allow tasks and periodic_tasks to specify their default queue at definition.
```
@huey.task(queue='site1')
def site1_task():
    ...

@huey.periodic_task(crontab(minute='*/3'), queue='site2')
def site2_periodic_task():
    ...
```
In this scenario queuing a task normally would simply add the task to the default queue, which any consumer should pick up.

Is this something you would consider adding in the future?

**Comment by coleifer** [comment]
This is not something I intend to add. You can try using multiple huey instances in your application.
