### ISSUE TITLE
Huey Monitor...

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#564]
I start a Django project for monitor Huey Tasks: https://github.com/boxine/django-huey-monitor

At the moment the whole thing is kept very simple. I just store all Huey signals into Database, see signal handler here: https://github.com/boxine/django-huey-monitor/blob/master/huey_monitor/tasks.py (I should rename the file)

![grafik](https://user-images.githubusercontent.com/71315/102213449-0bb16d00-3ed7-11eb-93d3-bccb41cc61bd.png)

![grafik](https://user-images.githubusercontent.com/71315/102213508-1f5cd380-3ed7-11eb-9da1-d96597b9c87f.png)

Question: 

What is the best way to get information form the Huey worker?
e.g.: How many worker exists. How many are idle/busy etc.

**Comment by coleifer** [comment]
Information about worker state or consumer internals is not exported via any APIs. Doing so would require a communication channel from the consumer / workers / scheduler, which does not exist. Signals are scoped to a task, whereas task-less state (e.g. a worker is idle) is not something that is visible outside the consumer.

**Comment by jedie** [comment]
Can you provide an official API?
Can you give some hints on what we can do until there is an official API?

**Comment by coleifer** [comment]
Doing so would involve a separate channel, as I mentioned, which adds complexity. Thankfully, the consumer implementation is fairly simple and you can override the `Huey.create_consumer` method to provide an instrumented implementation of a consumer if you wish. That is currently the way I would recommend.

I will give this some thought, though.
