### ISSUE TITLE
Notifying worker threads of SIGINT

### ISSUE THREAD

**Issue by JeffreyCA** [coleifer/huey#565]
If the consumer receives a SIGINT, how can I listen for this event at the worker level if I'm using threads? Or is there a way to catch this in the current task that's running?

**Comment by coleifer** [comment]
The worker threads are notified using a `threading.Event`. You can see how each worker-type implements things by looking at the subclasses of `Environment` in `huey.consumer`.

`SIGINT` performs a graceful shutdown, so the workers will finish their task and then stop.
