### ISSUE TITLE
Multiple consumer processes and periodic tasks

### ISSUE THREAD

**Issue by pumelo** [coleifer/huey#567]
This is not an issue but rather a question for clarification:

I'm running the consumer inside a container which runs on kubernetes. So the idea is that consumers can be scaled when required.

As each consumer runs a scheduler, when I have periodic tasks: Won't they be added mulitple times, if multiple consumers are running?

In order to prevent this I would have to add the `--no-periodic` flag to all instances of the consumer except for one instance, right?

Is this pattern generally supported? It's not mentioned explicitly but I think the desing currently is to support one consumer which will launch multiple workers (process, greenlet, thread) right?

**Comment by coleifer** [comment]
>In order to prevent this I would have to add the --no-periodic flag to all instances of the consumer except for one instance, right?

Yes, that's correct.

>Is this pattern generally supported?

Yes, setting "no-periodic" will basically just run a number of workers.

**Comment by pumelo** [comment]
Thank you for the clarification, and in general for sharing huey and also peewee 👌
