### ISSUE TITLE
Signal if worker died?

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#569]
It would be great to get information about when a worker died and which running tasks are affected.

The Problem: Huey-Monitor just capture all signals of a task. The "last signal" state of a task 
The last state of a task of course remains at "executed" even if the worker diet.

**Comment by coleifer** [comment]
Signals are not stateful and there's no way to retain that knowledge when a worker process is killed. Signals are scoped to a task, as I mentioned, and huey does not guarantee at-least-once. If a worker is killed while executing a task, then that task is simply "lost", so there's no provision for exposing this kind of information.

**Comment by jedie** [comment]
Hm, yet. My work-a-round in https://github.com/boxine/django-huey-monitor/pull/10 is also not a really good idea because it also updates still running tasks...

Any suggestions?

**Comment by coleifer** [comment]
Not at present, unfortunately, but I'm thinking about it.

**Comment by meetmangukiya** [comment]
I have declared a singal handler in a `views.py` file in django as:

```py
from huey.contrib.djhuey import signal

@signal()
def signal_handler(signal, task, exc=None):
  print(signal, task.id)
```

However, the handler is never being called 🤔

**Comment by coleifer** [comment]
https://huey.readthedocs.io/en/latest/signals.html

See SIGNAL_INTERRUPTED
