### ISSUE TITLE
Question: Will tasks be retried/requeued if huey is stopped while processing task?

### ISSUE THREAD

**Issue by benlei** [coleifer/huey#571]
I'm not seeing anything obvious about this scenario in the documentation. The scenario being:

1. Huey is started.
2. Task T consumes a message M.
3. Huey is stopped (Task T did not run to completion)

If I start back Huey, will task T re-consume message M?

**Comment by coleifer** [comment]
If you shut-down huey gracefully, then it will finish the task before exiting.

If you forcefully terminate the consumer, then the task is lost and not retried.
