### ISSUE TITLE
Add signal when consumer exits but task unfinished

### ISSUE THREAD

**Issue by GrayMissing** [coleifer/huey#573]
I'd like to add a new signal when consumer exits by SIGTERM but left task unfinished, which is a common case for consumer upgrade, so that I can add signal handler to handle it properly, otherwise I have to periodically check whether some tasks accidentally

**Comment by jedie** [comment]
Cool. This is nice for huey-monitor, too.

**Comment by coleifer** [comment]
As I mentioned on the PR you opened, this will only work when using the "process" worker model. I've updated the docs accordingly and merged the patch.

**Comment by coleifer** [comment]
Resolved and signal should now work with any worker type: 76c2b3777df3a317af3897f0c773f36b07ce1676
