### ISSUE TITLE
Revoking dynamically created periodic tasks

### ISSUE THREAD

**Issue by ducnguyen2020** [coleifer/huey#576]
Hi, I have been trying to find a way to revoke the tasks created dynamically just like the one in this guide:
https://huey.readthedocs.io/en/latest/guide.html#dynamic-periodic-tasks

I tried using the revoke() function with task_name but it's not working. 
Revoke_by_id() also didn't work because the id of the periodic task is different for each run.

Wondering if you can help me with this? Thank you!

**Comment by coleifer** [comment]
You can keep a reference to the task class of the dynamically-created periodic task and use:

    huey_instance.revoke_all(task_class)

The task class is added as an attribute to the `periodic_task` - decorated function.

Alternatively, you can pull the task-class from the registry, but that is getting a bit into the undocumented/internals.

**Comment by ducnguyen2020** [comment]
Hi, thank you for your reply. I am a student doing a personal project so still learning Huey!

I am still confused of how to keep that reference. Can you give me an example of how this works?

I followed your code on the documentation:

tasks.py: 
`def dynamic_ptask(message):
    print('dynamically-created periodic task: "%s"' % message)

@huey.task()
def schedule_message(message, cron_minutes, cron_hours='*'):
    # Create a new function that represents the application
    # of the "dynamic_ptask" with the provided message.
    def wrapper():
        dynamic_ptask(message)

    # The schedule that was specified for this task.
    schedule = crontab(cron_minutes, cron_hours)

    # Need to provide a unique name for the task. There are any number of
    # ways you can do this -- based on the arguments, etc. -- but for our
    # example we'll just use the time at which it was declared.
    task_name = 'dynamic_ptask_%s' % int(time.time())

    taskclass = huey.periodic_task(schedule, name=task_name)(wrapper).task_class
    return taskclass
`

main.py:
`from config import huey
from tasks import schedule_message
from huey import crontab

def main():
     taskclass = schedule_message('I run every 5 minutes', '*/5')
     print(taskclass)
main()
`

I got this error:
`_pickle.PicklingError: Can't pickle <class 'tasks.task_name'>: attribute lookup task_name on tasks failed`

Thank you in advance!

**Comment by coleifer** [comment]
I'd suggest maybe you could consider different design choices, as doing dynamic periodic tasks and handling revocation and all that may but be the best choice for you

**Comment by verydemo** [comment]
I have the same problem, No elegant solution?
```
huey.periodic_task(schedule_crontab, retries=retries, name=task_name, id=f'myid')(wrapper)
```
 a custom ID for periodic_task？
