### ISSUE TITLE
Would huey ever have a UI component?

### ISSUE THREAD

**Issue by nitrocode** [coleifer/huey#577]
Hi. Just curious, is the huey team open to a GUI component ? Is there a roadmap ? what do others use for a frontend ?

We were considering building one for our purposes since we're moving off of celery and flower.

**Comment by coleifer** [comment]
I'm not interested in maintaining one, but it's certainly do-able to some extent. The queue, schedule, and result-storage are all run-time introspectable with various methods on the `Huey` instance. In my own experience I've had the best luck just monitoring the queue length to ensure it is emptying, and attaching an email handler to the huey logger at ERROR level. This covers email alerts for tasks that fail and misbehaving tasks.

**Comment by jedie** [comment]
Take a look in my https://github.com/boxine/django-huey-monitor project

**Comment by coleifer** [comment]
Thanks @jedie - I hope your project proves useful to others. Truly glad to have you as a huey user and contributor!

**Comment by nitrocode** [comment]
@jedie That looks fantastic. Does it allow retrying jobs too?

@coleifer im sure others are looking for a gui for huey too. Would it be ok to reference that project from the huey README?

**Comment by jedie** [comment]
> Does it allow retrying jobs too?

Currently not: Pull requests welcome ;)

**Comment by nitrocode** [comment]
@coleifer @jedie

I added some more information to the README in case others come looking for a GUI. If this gets accepted, I imagine more people will the django monitor which means potentially more contributions.

If it needs to be reworded, let me know and I'll update. 

Thanks again for both projects!
