### ISSUE TITLE
Building container with not yet established redis server

### ISSUE THREAD

**Issue by VijayStroup** [coleifer/huey#583]
huey==2.3.0

I'm trying to build a container for my api that utilizes huey.

I'm using docker swarm, and I have my docker-compose file run the api container after the databases I'm using for the huey tasks (redis), and after the database accessed in the huey task functions (mongo).
The only problem is, when using docker stack deploy, you can not specify a `build` command at time of deployment, the container must already be built. With this the issue arises when trying to build the container to use ahead of time where it does not resolve either of the two databases, and the redis.ping() call stops the container building.

I feel like this must be a common issue many face, however I was not able to find the solution.
Is there some way where you can build the container ahead of time without it crashing, and then when the docker stack is deployed, it will connect to the databases?

**Comment by coleifer** [comment]
This is a docker-specific question and probably StackOverflow will be a better place to get answers.
