### ISSUE TITLE
Ability to modify the Error dict

### ISSUE THREAD

**Issue by DjMoren** [coleifer/huey#590]
Hi,

First of all, thank you for developing this great project. Really impressed.

I wanted to share an idea to know if that makes sense for you and in that case, try to develop a MR or wait for your development. 

In this case, the idea is to have the ability to change the metadata stored in the Error object. 

Now, its hardcoded as:
`
{
  'error': repr(exception),
  'retries': task.retries,
  'traceback': tb,
  task_id': task.id,
}
`

At least for me, it could be interesting to have the ability to add more fields here, so maybe it could be moved to a helper function that receives the task, the exception and the traceback and returns a dict. This is a naive implementation proposal that should need deeper analysis to find the best fit, but I explained it just to give a simple idea.

What is your opinion?

Thanks

**Comment by coleifer** [comment]
What additional information are you looking to add?

**Comment by DjMoren** [comment]
I was thinking in adding the task name and task arguments in some cases. Do you think that there's a better way to achieve this?

Thanks
