### ISSUE TITLE
Batch tasks sumbittal

### ISSUE THREAD

**Issue by fingoldo** [coleifer/huey#591]
Hi! what is the recommended way to submit a lot of tasks (10M), particularly, to the redis remote backend? Currently i'm getting very low speed of 15 tasks/sec (server is in another country) with vanilla decorated task call, and, it seems, the same rate with a map over a list of tuples (it just hangs and tasks start executing, so i'm concluding it's sending consecutively behind the curtains).

**Comment by coleifer** [comment]
For each task there is a deal of work that happens, including serializing the task name, arguments, metadata, and writing it to redis. There are no provisions for batching.

What you're describing seems like an anti-pattern for huey. I don't know why you have 10M tasks to run, why they need to be run elsewhere, or whether this is a one-time operation or something you plan to do repeatedly -- but for really anything, I think you're better off probably just running these using a standard-library multiprocess pool or threadpool (if they're not CPU-bound). Huey's use-case is to be always-running and to process jobs that may be sent any time.

**Comment by fingoldo** [comment]
That's interesting. My use case was a distributed downloading of a bunch of files from different nodes (IPs), that's why multiprocessing and the like are not appropriate and I thought Huey is a better match. I measured speed of local queuing, it was around 3000 tasks/sec, so definitely batching would help, if it ever will be on the roadmap.
Also I had to implement random delays between requests coming from single node, luckily, task can use global variables and it's easy to store time of last request and sleep whatever interval is needed.
Also wondering, what happens with the task, if it was taken from redis for execution, but while executing something happened, for example worker and/or scheduler process died. Will such task be resheduled by other workers, possibly on other machines? Did not see it in the docs...

**Comment by coleifer** [comment]
Distributed downloading 10M different files? Is this a one-time operation or something you do repeatedly?

**Comment by coleifer** [comment]
Huey does not re-enqueue tasks that are interrupted since tasks are not guaranteed to be idempotent.

You can bind something to SIGNAL_INTERRUPTED if you want to add this logic, though:

https://huey.readthedocs.io/en/latest/signals.html#signals

**Comment by fingoldo** [comment]
Let's say a few-time-per-year operation )
Aha so my understand was correct about not re-enqueuing of tasks. In my opinion, it's a drawback.. I think it's more logical to reschedule till it's completed or failed.
Thank you for suggestion of using signals!
