### ISSUE TITLE
[Question] : some help on my misunderstanding

### ISSUE THREAD

**Issue by tboulogne** [coleifer/huey#595]
Hello @coleifer,

Could you help me understand my misunderstanding please :-).

Let me explain.

I got a list of functions. On a django view, i choose one and preparte a cron format field and save in database. With signals (on save), i call this :

```
 res = schedule_task(instance.func, instance.name, instance.id,  instance.cron)
```
Got a task_id from this fonction :

```
@huey.task()
def schedule_task(_function, name, schedule_id, cron):
    crons = cron.split(" ")
    # Create a new function that represents the application
    # of the "dynamic_ptask" with the provided message.
    def wrapper():
        funcs = _function.split(".")
        method = funcs[len(funcs) - 1]
        funcs.pop()
        module = importlib.import_module('.'.join(funcs))
        method = getattr(module, method)
        method()
        

    # The schedule that was specified for this task.
    schedule = crontab(minute=crons[0], hour=crons[1], day=crons[2], month=crons[3], day_of_week=crons[4])

    task_name = 'dynamic_%s' % slugify(name)

    huey.periodic_task(schedule, name=task_name)(wrapper)
```

1/ Each time the task run, the ID is different.
2/ If i try to revoke task 
```HUEY.revoke_by_id("ed35c878-cb75-44c3-bc6a-e714542f38c9")```
The periodic task continue.

What did i miss ?

Thanks for help.

Regards

**Comment by coleifer** [comment]
Typically I advise you ask questions on StackOverflow rather than the issue tracker - so just FYI that's the preferred place for these kinds of things.

Doing dynamic tasks is a fairly advanced usage. When you revoke a task by ID you are only revoking one "instance" of the task. A periodic task will have a different "id" each time it is run. Ex:

```
08:34:10 Enqueueing periodic task tasks.every_other_minute: 354882c6-7227-42ac-af2f-6b9e8139b66d.
08:34:10 Executing tasks.every_other_minute: 354882c6-7227-42ac-af2f-6b9e8139b66d        
This task runs every 2 minutes.
...
08:36:10 Enqueueing periodic task tasks.every_other_minute: ad289234-5c72-4aa5-b6ed-4d37a49abc3c.
08:36:10 Executing tasks.every_other_minute: ad289234-5c72-4aa5-b6ed-4d37a49abc3c
This task runs every 2 minutes.
```

You probably want to (instead) use `huey.revoke_all()` to prevent the periodic task from running -- or if you want to completely stop it you can `huey._registry.unregister(...)`.

Ex:

```python

@huey.periodic_task(...)
def some_periodic_task():
    pass

some_periodic_task.revoke()
# Or:
# huey.revoke_all(some_periodic_task.task_class)
```

Note you will need to keep a reference around to the dynamic task in order to be able to revoke it later.

**Comment by tboulogne** [comment]
@coleifer thanks :-)

**Comment by pirate** [comment]
Is there any way to pickle a reference to the dynamic task so that a dynamically added periodic task can be revoked from a different process?

**Comment by coleifer** [comment]
If you are just wanting to revoke you can check out how revoking is implemented - it's quite simple and uses an internal API but hopefully this helps:

https://github.com/coleifer/huey/blob/2dedbb33094182228ce1c433b57c88e3a494d90b/huey/api.py#L504
