### ISSUE TITLE
Automatically consume an unfinished task if the Huey consumer is restarted

### ISSUE THREAD

**Issue by pksol** [coleifer/huey#598]
Our Huey consumer restarts sometimes (it can be planned or unplanned maintenance, version upgrade, etc.).

Whenever this happens, tasks that are in the middle of consumption are "lost" and won't be retied.

Is it possible to add a mark in the Redis queue only after a task was completed (either successfully or unsuccessfully) so that if Huey is restarted the same task is picked up once more?

**Comment by coleifer** [comment]
Huey is not guaranteed at-least-once delivery, and does not do acknowledgement of completed tasks. The consumer supports a soft shutdown for this reason -- any in-flight tasks will be finished before the consumer exits. It sounds like you are not using this, however.

You can add a signal handler for the `SIGNAL_INTERRUPTED` signal, which is run when a task is interrupted during execution (by a hard shutdown) - using this signal you can add logic to handle tasks that are interrupted during execution:

https://huey.readthedocs.io/en/latest/signals.html

**Comment by rudyryk** [comment]
@coleifer I found this discussion and your recommendation useful and worth adding to documentation, some minimal example would be awesome. I believe it's quite common to restart workers on deployment to reload tasks code, and sometimes tasks are just too long, i.e. video processing etc.

**Comment by coleifer** [comment]
3e7bdf253a02813eff138a2db6b00554d81a8e57 - hopefully this helps clarify.

Docs here: https://huey.readthedocs.io/en/latest/consumer.html#consumer-shutdown
