### ISSUE TITLE
Question: Call task remotely

### ISSUE THREAD

**Issue by WilliamDEdwards** [coleifer/huey#599]
First off, apologies if this is not the right place for questions (which it probably isn't). I couldn't find recommended communication channels in the docs.

I would like to call a task remotely, i.e. from another server than the server the Huey consumer runs on. I couldn't find a recommended way in the docs, so I'm thinking of letting my remote system call a RabbitMQ consumer that runs on the server where the Huey consumer runs, and having the RabbitMQ consumer call my `huey.task` decorated function. I could then let the remote system retrieve the task result by doing a RabbitMQ RPC call with the task ID (that is, if I can retrieve the task object by the task ID - haven't used Huey yet, so not sure). Is there another recommended way that I missed in the docs?

**Comment by coleifer** [comment]
If you're using Redis for your huey implementation, then you shouldn't need to do anything special. Just ensure that your `RedisHuey` redis connection details are correct and your redis server accepts connections.

This is an extremely foundational concept for using huey... e.g.,

* server A running your code
* server B is just running the huey consumer and any tasks it receives
* server R (or A or B) is running Redis

If you want to invoke some tasks from server C, then you just need to be sure it can also talk to Redis.

**Comment by WilliamDEdwards** [comment]
Yep, sorry, failed to mention the caller can't reach the consumer directly. Clear.

**Comment by coleifer** [comment]
Instead of adding rabbitmq I'd suggest finding a way to talk to your Redis server. Even over an ssh tunnel should be fine for limited use.
