### ISSUE TITLE
Huey scheduler doesn't run periodic tasks at the specific time.

### ISSUE THREAD

**Issue by lidiasm** [coleifer/huey#602]
Hi! How are you? I've been using Huey for a few months but now I have some issues with periodic tasks. The scheduler starts but doesn't run the tasks. I tried by X hours, a range of hours or specific ones but nothing works for me. I don't know if maybe it's some kind of issue after some update of yours. I'd like to know what is going on because I love this library and I'm using it for many projects.

Let me know if you need more details to understand what I tried to mean. Thank you in advance!!

**Comment by coleifer** [comment]
I'm unable to provide time to debug problems, but the periodic tasks are very fundamental to the operation of Huey and are covered by tests, so presumably there's a bug somewhere in your implementation. I'd suggest trying StackOverflow.

**Comment by coleifer** [comment]
If you want to see a minimal example of running periodic tasks, check out the `examples/simple` directory: https://github.com/coleifer/huey/tree/master/examples/simple
