### ISSUE TITLE
[Feature Request] periodic_task with seconds instead of crontab

### ISSUE THREAD

**Issue by Archmonger** [coleifer/huey#608]
Would be nice to be able to specific a certain amount of seconds instead of doing things the cron way.

Even if that exact seconds intervals isn't a guarantee, still would be a solid implementation.

For example if the scheduler is polling at 5 seconds, it would be acceptable for a 45 second periodic task to be up to 5 seconds late.

**Comment by coleifer** [comment]
This is not supported - periodic tasks run maximum once-per-minute, regardless of the scheduler interval.

**Comment by Archmonger** [comment]
@coleifer If I was to PR an `periodic_tasks` accepting either a `crontab` or `int seconds`, would you consider merging it? Or would you prefer huey to not have this capability?

**Comment by coleifer** [comment]
The periodic task scheduler, which is built into the `Scheduler`, handles ensuring things are run once per minute.  I'd suggest - if this is something you really want - that you do the following:

* subclass `Scheduler` and write your own implementation
* create a new subclass of `Consumer` that sets `MyConsumer.scheduler_class = MyScheduler`
* override `Huey.create_consumer` to use your custom Consumer class

This can all be done without needing to modify huey internals.

I do not plan on merging such functionality, but you are welcome of course to implement this yourself and publish it on your own github.
