### ISSUE TITLE
scheduled() not returning periodic tasks

### ISSUE THREAD

**Issue by BSVogler** [coleifer/huey#609]
We have constructed a method to prevent multiple workers from enqueuing the same periodic task. For that, we use `djhuey.scheduled()`.

However, this function does not appear to return periodic tasks only the regularly scheduled ones. Is there a way to see a list of scheduled periodic tasks? We also noticed that the periodic task was not stored in Redis. Is there a way to put periodic tasks in the regular queue?

EDIT: A possible solution I thought of is to use the regular task and schedule it and with the signals reschedule the task every time. I think it would be great to have this type of processing directly built-in.

**Comment by coleifer** [comment]
Is there a reason you chose not to use this: https://huey.readthedocs.io/en/latest/guide.html#locking-tasks

Once per minute the scheduler checks the periodic tasks list to see if any should be run - they do not go through the schedule system. Periodic tasks go directly into the work queue if they should be run.

I have no plans to change this design at the moment.

**Comment by BSVogler** [comment]
Thank you. I am aware of the lock. When there are multiple processes multiple periodic tasks can get added to the queue. As far as I understand it the lock only prevents the parallel execution of a section. When the worker queue is full the multiple scheduled tasks might run with a delay thus some of them not being blocked in the lock.

for scheduled task this can be prevented by checking the list of already scheduled ones before scheduling, however, as you noted this is not possible with periodic tasks.
