### ISSUE TITLE
Unable to add task to queue from another/same task

### ISSUE THREAD

**Issue by Tumornator** [coleifer/huey#614]
I have a task which takes certain arguments, and I would wish to restart the task or trigger the task based on its output values.
Here's what I have tried :

-  **Periodic Task** : Since my task takes arguments, and according to Docs
```md
Because functions decorated with periodic_task are meant to be executed at intervals in isolation, they should not take any required parameters nor should they be expected to return a meaningful value
```
So I can't really use the periodic task

- **Using schedule inside a task** : 
```python

@huey.task()
def launch_device(device:Device):
    app = create_huey_app()
    with app.app_context():
        try:
            app.logger.info(f"[NEW TASK] : {__name__} - {device.title}")
            for account in device.account:
                account.launch()
        except Exception as ex:
            app.logger.exception(ex)
            app.logger.critical(f'Failed to launch account : {device.account} on {device.title}')
        finally:
            account.running=False

        app.logger.debug('Device All accounts run complete')
    print('complete')
    return launch_device.schedule((device),delay=5)
```

Output:
```shell
[2021-08-04 21:24:02,390] [INFO] : [NEW TASK] : app.tasks - Test
....
...
...
...
[2021-08-04 21:24:03,074] [DEBUG] : Device run complete
complete
```

There is no output afterwards.
There is no error.
The program does not end.

One clumsy way of doing it is I can use While True loop
```python
@huey.task()
def launch_device(device:Device):
while True:
    app = create_huey_app()
    .....
```
and signal its stop whenever I want it to stop.
But it would be better if I could trigger the task from within the task

P.S. : One worker = 1 device. That's how I have kept my App design, so that I could configure workers and manage devices accordingly

**Comment by coleifer** [comment]
I suppose you have something wrong with your code or other issue. It is perfectly fine to schedule tasks within another task, as exemplified here (which prints the timestamp when called, then schedules itself to run again in ~10 seconds):

![huey-ex](https://user-images.githubusercontent.com/119974/128219402-0afd31c5-7df2-4c34-adc1-2e3ab4c6ea59.png)

I suggest trying StackOverflow if you have a particular question.

**Comment by coleifer** [comment]
To clarify the screenshot:

* top pane shows the entirety of "x.py", a task that prints time and schedules itself
* middle shows running the consumer / consumer output
* bottom shows invoking the task for the initial time (note the time printed in the ipython console matches the time the task first runs in middle pane)

**Comment by coleifer** [comment]
Please see also the API docs for the signature to the schedule method, as you may be confused about it: https://huey.readthedocs.io/en/latest/api.html#TaskWrapper.schedule
