### ISSUE TITLE
[Question] How to use this to allow web app end users set their own scheduled tasks in a dynamic way?

### ISSUE THREAD

**Issue by simkimsia** [coleifer/huey#615]
I have read https://huey.readthedocs.io/en/latest/guide.html#dynamic-periodic-tasks

I am still unable to wrap my head around how this can be used to achieve the feature I am looking for.

I am going to use your code examples only adding an extra function`my_dynamic_ptask` above them.

```python

# this is my own written app
from app.blahblah import email

def my_dynamic_ptask(email_address, message):
    email(email_address, message)

@huey.task()
def new_schedule_message(email_address, message, cron_minutes, cron_hours='*'):
   ...
    
def dynamic_ptask(message):
    print('dynamically-created periodic task: "%s"' % message)

@huey.task()
def schedule_message(message, cron_minutes, cron_hours='*'):
    # Create a new function that represents the application
    # of the "dynamic_ptask" with the provided message.
    def wrapper():
        dynamic_ptask(message)

    # The schedule that was specified for this task.
    schedule = crontab(cron_minutes, cron_hours)

    # Need to provide a unique name for the task. There are any number of
    # ways you can do this -- based on the arguments, etc. -- but for our
    # example we'll just use the time at which it was declared.
    task_name = 'dynamic_ptask_%s' % int(time.time())

    huey.periodic_task(schedule, name=task_name)(wrapper)
```

I spin up a django web app and the user can create their own schedule to send an email.

Suppose I have a datatable called `user_schedule_my_dynamic_tasks` that saves all these schedules just to execute `my_dynamic_ptask`

- id (primary key)
- user_id (the logged_in user)
- cron_minutes
- cron_hours
- cron_days

So you can easily imagine two different users setting up entirely different dynamic schedules that call the same `my_dynamic_ptask`

I can imagine a code that's like this 

```python

# the model is UserScheduleMyDynamicTask
the_schedule = UserScheduleMyDynamicTask.objects.get(id=17)

# somehow between the fetching of the database record and the update of the new cron_minutes, i need to kill the previously run and run the new scheduled task

# i don't know how to kill the old scheduled task. Is there an id I can reuse to find it to kill it?
# I also don't know how to setup one within the django business code
new_schedule_message( ... here we put the right parameters ...)


# the new cron_minutes, etc is saved 
the_schedule.save()


```

Am I directionally correct? 

Is this out of scope for huey?

**Comment by coleifer** [comment]
>Is this out of scope

This is just what happens when you have a hammer, every problem looks like a nail.

The better way to do this is to have a single task that you control which runs every minute or whatever, and this task reads your user schedules and fires off individual tasks for sending the emails.

```python

@huey.periodic_task(crontab(minute='*'))
def my_main_task():
    query = UserScheduleMyDynamicTask.objects.find_tasks_to_run_right_now()
    for user_schedule in query:
        # Here you would fire off a task per user-specified operation.
```

You can decide how clever you want to be in terms of figuring out which user tasks should be run at a given time.
