### ISSUE TITLE
avoiding circular import(?) with immediate=True

### ISSUE THREAD

**Issue by lordzappo** [coleifer/huey#616]
Env:
python 3.8.2
huey                          2.3.2
Django                        3.2.6

Here is my problem:
app/tasks.py: contains scheduled tasks e.g.

    @periodic_task(crontab(hour="1,12"))
    def renew_creds_task():
        ....

then we expose routes in the router to call those manually if need be

    @router.get("/refresh/renew_creds")
     async def renew_creds(request: HttpRequest):
         renew_creds_task()
         return HttpResponse(f"task launched")`

works fine with an actual redis instance.  In immediate=True, so I can write tests, I receive:

    ValueError: Attempting to register a task with the same identifier as existing task. Specify a different name= to register this task. 

Thoughts?

**Comment by coleifer** [comment]
Maybe you're importing your tasks twice - I don't believe this is a circular import issue but rather an issue in the way you're importing your code.

I'd suggest posting on SO as this is a question and not a huey bug.

**Comment by lordzappo** [comment]
but, why does this error only occur with immediate=True, then? 

and if you want to schedule a periodic task and also have it be called by a route to not be periodic, I'm forced to put it in one file if I want to use immediate=True to test?  Otherwise of course I have to import the tasks into a view/route file in addition to the django "find my tasks" magic that already occurs...
