### ISSUE TITLE
FileNotFoundError from queue temp file

### ISSUE THREAD

**Issue by lpil** [coleifer/huey#620]
Hello!

We're using Huey in process mode and a few times a day we get errors like so:

```
FileNotFoundError
[Errno 2] No such file or directory: 'huey/queue/ffff-017be9e5658a' -> 'huey/queue/ffff-017be9e5658a.tmp'

huey/storage.py in dequeue at line 917
huey/api.py in dequeue at line 314
huey/consumer.py in loop at line 109
```

I believe this is when two workers attempt to dequeue a job at the same time. It seems there is no ill-effect to this, but the errors are quite noisy in our exception tracker and logs.

Would it be possible to catch this error if there is no problem?

Thanks,
Louis

**Comment by coleifer** [comment]
Are you using a `FileLock` or did you specify `use_thread_lock`? I wonder if there's a problem with the file lock implementation, as it should prevent that.

**Comment by coleifer** [comment]
When you have a chance, please try 06f767a60145c72c2def5df7749af9e4d60b9757 and see if this resolves your issues -- it does a proper flock().

I will close for now but please comment if this does not resolve the issue.

**Comment by lpil** [comment]
Thank you. We'll try this once we have finished our current work and report back with any findings

**Comment by lpil** [comment]
Hi @coleifer , unfortunately we are still getting this error after deploying the new version. Is there something we could do to help debug?

**Comment by coleifer** [comment]
What arguments are you passing to your consumer when you run it?

**Comment by coleifer** [comment]
For what it's worth, I've tried to replicate this issue and have not had success. Here's my script -- it is a periodic task that runs every minute and spawns 20 tasks. Then it blocks while reading their results. It has been running without issue:

```python
from huey import FileHuey
from huey import crontab


huey = FileHuey(path='/tmp/huey-test')

@huey.task()
def rtask(n):
    return n

@huey.periodic_task(crontab(minute='*'))
def ptask():
    rg = rtask.map(list(range(20)))
    results = rg.get(blocking=True)
    assert results == list(range(20))
```

**Comment by lpil** [comment]
Sorry about the delay, I didn't get a notification for some reason.

We start Huey like so:

```
./manage.py run_huey --flush-locks --workers 4 --worker-type=process
```

Is there something we could do to provide you with more debug information?

**Comment by coleifer** [comment]
Like I said above, I've been running the above script without issues, with anywhere from 4 to 8 process workers. I have not been able to replicate your issue.
