### ISSUE TITLE
AWS SQS support

### ISSUE THREAD

**Issue by ianrodrigues** [coleifer/huey#621]
Hey @coleifer! That's a nice project, indeed. Do you have any plans to support AWS SQS? Of course, SQS does not support all the features Redis support, like defining priority, but it's a good solution for a pay-as-you-go/serverless model. I'm interested in writing a PR supporting SQS, but I'd like to know your thoughts.

**Comment by coleifer** [comment]
I've looked into this in the past and have simply not seen demand for it. Additionally, SQS uses a slightly different model - more like beanstalk, where there are explicit ACKs. I think throwing the tasks into SQS is really the easier part. The trickier part is the result and schedule storage. Results could easily be put into S3, I suppose, but the schedule really needs to have an ordered data-structure of some kind. I think this would probably be best implemented as a third-party addon, at any rate.
