### ISSUE TITLE
Removing RedisExpireHuey results explicitly

### ISSUE THREAD

**Issue by gonewest818** [coleifer/huey#623]
I see in the documentation that results are expired automatically after a TTL, and generally that's what I want, but is it also possible to remove a result explicitly when I know the result isn't needed any longer?

**Comment by coleifer** [comment]
Yes, you can call `huey.storage.delete_data(key)` where key is the result-key for the given task. Alternatively, you can subclass `RedisExpireStorage` and override the `pop_data` to implement a destructive read if you want all your results to be deleted upon being read once.
