### ISSUE TITLE
Different behavior during configuration change

### ISSUE THREAD

**Issue by adursun** [coleifer/huey#626]
Hello, thank you for the great library!

I'm using huey v2.4.1 with Django. I recently changed Django's database host and sent `SIGHUP` signal to restart the consumers. After the change,

- Django connected to the **new** database
- Tasks with `@task` decorator connected to the **new** database
- Tasks with `@periodic_task` decorator tried to connect to the **old** database and failed

I checked the related logs and verified it is a connection problem during a `periodic_task`.

```
OperationalError
could not connect to server: Connection timed out
	Is the server running on host "x.x.x.x" and accepting
	TCP/IP connections on port x?
```

The problem continued until a server reboot and `periodic_task` connected to the new database.

All tasks are defined in the same file and related imports are:

```python
from huey import crontab
from huey.contrib.djhuey import periodic_task, task
```

Does `periodic_task` handle consumer restarts and configuration changes different from `task`?

**Comment by coleifer** [comment]
No, it should handle it the exact same. When you restart via SIGHUP the consumer stops all workers and scheduler, then does an `exec()` to replace the running process with a new invocation. Possibly the scheduler did not stop, though? In any event the solution would have been to just completely stop, then restart the consumer.

**Comment by adursun** [comment]
I'm using the following commands to start / restart huey and it worked great for 6 months. After the configuration change normal tasks (for example, `send_account_activate_email_task`) connected to the new database. On the other hand, periodic task (`send_daily_stats_task`) didn't.

```bash
# start
./manage.py run_huey --workers 2 --worker-type thread --logfile ./logs/huey.log

# restart
pkill -HUP -f "run_huey"
```
