### ISSUE TITLE
Signals vs Events

### ISSUE THREAD

**Issue by MarcoGlauser** [coleifer/huey#630]
Hi, 

I'm a bit late in terms of the events API deprecation. I built a [huey prometheus](https://github.com/MarcoGlauser/huey-exporter) exporter for redis a while back with huey 1.x in mind. This basically just hooked into the events API and made them available for prometheus monitoring.

I wanted to upgrade the exporter recently to huey 2.x but I noticed that the events are gone completely and that there's no more storage event api I can hook into. Are there any alternatives to receive these signals/events in redis? The way I see it, to make it compatible, I would have to register signals in the consumer, send the signals to redis and listen for them in the separate exporter process.

**Comment by coleifer** [comment]
@MarcoGlauser - yeah that sounds about right. It depends on what signals you want to subscribe to, but the gist of it would be to register a signal handler. You can register a handler for "any" signal, as well.

```python

@huey.signal()
def handle_any_signal(signal, task, *args, **kwargs):
    ...
```

Inside your handler you can just push events to a Redis PUBSUB channel or do whatever else.
