### ISSUE TITLE
support for redis cluster

### ISSUE THREAD

**Issue by yiresumenan** [coleifer/huey#632]
when i use a redis cluster as the broker, the remote redis cluster raise a error 「bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS arrayrn」,which i track and find out the problem is about this script at "huey/storage.py" line352  SCHEDULE_POP_LUA = """\
local key = KEYS[1]
local unix_ts = ARGV[1]
local res = redis.call('zrangebyscore', key, '-inf', unix_ts)
if #res and redis.call('zremrangebyscore', key, '-inf', unix_ts) == #res then
    return res
end"""

I replace it with the new script 
SCHEDULE_POP_LUA = """\
local unix_ts = ARGV[1]
local res = redis.call('zrangebyscore', KEYS[1], '-inf', unix_ts)
if #res and redis.call('zremrangebyscore', KEYS[1], '-inf', unix_ts) == #res then
    return res
end"""
the error didn't raise again.
it's because the lua script use a local variable key to store KEYS[1], which is not supported by redis cluster.

HOPE the author can fix this bug! thanks a lot.

**Comment by coleifer** [comment]
Thanks for figuring out what the issue was. I had no idea redis-cluster couldn't handle this kind of operation. Fix is available on master now.
