### ISSUE TITLE
[Question] Sub 1 second scheduling, and more efficient consumers

### ISSUE THREAD

**Issue by heshiming** [coleifer/huey#634]
First of all thank you for such a well written, lightweight library. I've been using it for years and it worked great.

I'm looking to improve my current application, that means I'd like to have the scheduler run at say 0.1 sec intervals. My application needs that level of time resolution. And when tasks come, I need 5-10 consumers to execute them in parallel.

Of course currently the minimum interval for the scheduler is 1 sec. I understand redis BRPOP is probably a low cost command but it doesn't cost nothing. So even if I tweaked the code to let scheduler run at 0.1 sec intervals, 10 consumers bombing redis that way will create unnecessary idle load on the CPU.

Is it currently possible for me to run a single consumer who will create automatically spawn additional consumers as it enters task execution, so that additional tasks can be fulfilled? And how bad it is if I let the scheduler run BRPOP every 0.1 sec?

**Comment by coleifer** [comment]
You can look and see how this person implemented this:

https://github.com/Archmonger/Conreq/blob/a11f5748e9a41646bcce35fb70c259c6cac61905/conreq/internal/bg_tasks/api.py

https://github.com/Archmonger/Conreq/blob/a11f5748e9a41646bcce35fb70c259c6cac61905/conreq/internal/bg_tasks/consumer.py

He's basically overridden the consumer (returned by `Huey.create_consumer()`) and written a special crontab helper that can validate seconds.

**Comment by coleifer** [comment]
The above was more specifically geared towards running *periodic* tasks with sub-minute intervals.

If you are *only* interested in checking for explicitly scheduled tasks (e.g. tasks run with an `eta` or `delay`) then you can safely override the Scheduler and set the interval to any value you want.
