### ISSUE TITLE
Stop a long running task from outside

### ISSUE THREAD

**Issue by vortec** [coleifer/huey#635]
Hi everyone,

I'm working with a bunch of long-running tasks which I'd like to stop from the outside. Signals seem to only work the other way round (send a signal from a task to the outside), so therefore I don't know how I'd accomplish that.

Can someone guide me into the right direction? Thank you!

**Comment by coleifer** [comment]
There is not really a mechanism built-in to huey for this. What I'd suggest is that, if your tasks have a natural "loop", to check every so often if a flag has been set indicating the task should stop.

```python
@huey.task()
def my_long_running_task(...):
    for i in range(1000):
        if i % 10 == 0:
            if some_flag.is_set(): return
        ....
```

Then you can write-up some code to set the cancellation flag when you wish to cancel the task. If you're already using Redis this should be pretty easy. Each task executed by huey has a unique ID so you can use that.
