### ISSUE TITLE
[Question] Trying to consolidate my learning. Any issues with the diagrams I draw?

### ISSUE THREAD

**Issue by simkimsia** [coleifer/huey#637]
Both diagrams assume django setup

## Generic diagram

![hueyv2 logical](https://user-images.githubusercontent.com/245021/142987401-0ba33825-3ec5-49fc-8355-59562cb8dc6d.png)

## Sequence diagram for ajax polling 
![mermaid-diagram-20211123155258](https://user-images.githubusercontent.com/245021/142987702-f3e5cf48-e1ab-422d-a53f-55ead1b37a23.png)

**Comment by coleifer** [comment]
Top one looks about right to me. Can't speak for the bottom one.
