### ISSUE TITLE
Double logs

### ISSUE THREAD

**Issue by wgordon17** [coleifer/huey#639]
Running Huey with Django, I'm seeing duplicated logs on my consumer

```
[2021-11-24 15:23:19,555] DEBUG:huey.consumer.Scheduler:Dummy-7:Sleeping for 0.9967123280002852
DEBUG 2021-11-24 15:23:19,555 consumer 13542 4532967344 Sleeping for 0.9967123280002852
```

Is this a Django logging configuration bug, or a Huey logging configuration bug?

(Also, what's with the `Dummy-7` naming? Nvm, looks like it's just an odd naming choice by `gevent` 👍 )

**Comment by jedie** [comment]
think it wrong logging config ;)

**Comment by coleifer** [comment]
Yeah, just try changing around your logging config. The `run_huey` management command will check for any handlers bound to `huey` logging namespace, and only attach the stream/file-handler if no logger was configured yet for "huey" namespace.

**Comment by wgordon17** [comment]
Thanks, definitely my fault, but the reference to the `"huey"` namespace definitely helped!

For anyone else that stumbles across this, this was what I added to my Django `LOGGING` config to solve the issue

```
LOGGING = {
...
    "loggers": {
        "huey": {"level": "INFO", "handlers": ["console"], "propagate": False},
    }
...
}
```
