### ISSUE TITLE
huey can't connect to Redis if redis-py >= 4.0 is used

### ISSUE THREAD

**Issue by ekini** [coleifer/huey#642]
In https://github.com/redis/redis-py/commit/6b37f4bedc349eb2c91e680d2ef811a3c2f7e879 the authors made a backwards incompatible change that removed `decode_components` parameter, which is used here https://github.com/coleifer/huey/blob/3ce5e6dd15c4cee79be5997161f544190d29d07b/huey/storage.py#L386

Could probably lock down required version <4 here https://github.com/coleifer/huey/blob/master/setup.py#L10 or check `redis.VERSION` and don't use decode_components for >=4.0.

**Comment by coleifer** [comment]
Thanks for finding and sorting this out. Fix is pushed to master.
