### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'decode_components'

### ISSUE THREAD

**Issue by chapkovski** [coleifer/huey#643]
I have a huey service running on Heroku server with Django.

It returns this error when I start the consumer (using `python manage.py run_huey`)
The configuration in settings looks like that:

```python
 {'connection': {'url': 'redis://:paab960023cc0bbeba3c969a3a67152b17a91f2bf62f189761fcafecedc14dde7@ec2-3-227-178-167.compute-1.amazonaws.com:16029'}, 'immediate': False}
```
HUEY version is 2.4.2

The full log is here https://pastebin.com/NvQC5wjr

**Comment by coleifer** [comment]
Yes, this is already reported https://github.com/coleifer/huey/issues/642

To prevent more issues like this I've gone ahead and pushed a new release 2.4.3 which contains the fix.
