### ISSUE TITLE
Help: Run huey_consumer from python file in Windows

### ISSUE THREAD

**Issue by danielcuellarp** [coleifer/huey#645]
Hi, I come to you for a collaboration:

I am creating a program with python 3.9 for the WIndows operating system with PyQt5, where the idea is that when the program starts it executes some tasks and that when the program is closed it stops executing them.

Therefore, I have created the task process with Huey and when I run it from the console with "huey_consumer.py task.huey" it works correctly.

When trying to run it from python files I am doing it:

`process = subprocess.Popen(['huey_consumer.py', 'task.huey'])`

But it throws the following error:

`OSError: [WinError 193] %1 no es una aplicación Win32 válida`

I understand that the executable is missing, but I have tried it like this:

`process = subprocess.Popen(['huey_consumer.py', 'task.huey'], executable=sys.executable)`
`process = subprocess.Popen(['python', 'huey_consumer.py', 'task.huey'])`

but it returns the following:

`huey_consumer.py: can't open file 'C:\Users\...\...\...\task.huey': [Errno 2] No such file or directory`

Does anyone know a way to solve this case? 

Thank you.

**Comment by coleifer** [comment]
I'm quite sure that Qt comes with some kind of an event loop for exactly this type of thing. Huey seems like a horrible fit.

**Comment by danielcuellarp** [comment]
> I'm quite sure that Qt comes with some kind of an event loop for exactly this type of thing. Huey seems like a horrible fit.

But I need Huey for the periodic tasks, that is, I need to execute a process every hour on the dot (example 10:00, 13:00, etc.)
