### ISSUE TITLE
Attempting to register a task with the same identifier as existing task

### ISSUE THREAD

**Issue by vishwakarma0** [coleifer/huey#650]
Hi,
Have been using huey for a while now, never faced this issue, suddenly it is showing this error, even though I checked my git log don't see any changes in the task name.
Note: Each and every task name is unique

`ValueError: Attempting to register a task with the same identifier as existing task. Specify a different name= to register this task. "app.tasks.collect_player"`

Thanks,
Vishwakarma

**Comment by coleifer** [comment]
Maybe you are importing your tasks module in two different ways, eg

```
from app.tasks import collect_player
 ..
from tasks import collect_player
```

Or something similar that is causing the module to be imported under two separate paths.
