### ISSUE TITLE
Making the consumer logger quiet?

### ISSUE THREAD

**Issue by zopyx** [coleifer/huey#651]
I integrated huey into the CMS Plone which comes with its own logging and its own logger setup.
Is there some change to make the consumer quiet and log only to a configured logfile?
I have this configuration and I still see output on the console (in addition to the output in  `huey.log`

```

consumer_options = {
    "backoff": 1.15,
    "check_worker_health": True,
    "extra_locks": None,
    "flush_locks": False,
    "health_check_interval": 10,
    "initial_delay": 0.1,
    "max_delay": 10.0,
    "periodic": True,
    "scheduler_interval": 1,
    "worker_type": "thread",
    "workers": 4,
    "logfile": "huey.log"
}

h = load_huey("zopyx.typesense.huey_tasks.huey")

config = ConsumerConfig(**consumer_options)
config.validate()
config.setup_logger()
consumer = h.create_consumer(**config.values)

th = threading.Thread(target=consumer.run)
th.start()

LOG.info("Started Huey consumer thread")

```

**Comment by coleifer** [comment]
Huey logger is well-behaved and should log only to the `huey` namespace. Possibly whatever you're using is also configuring a root logger which is also handling the huey logs? You may also want to add the `verbose=False` to your consumer options. Alternatively you may look into the `propagate` setting.
