### ISSUE TITLE
Question: Purpose of pre-execute hooks?

### ISSUE THREAD

**Issue by MichaelVoelkel** [coleifer/huey#652]
Hello guys,

first of all, thanks for creating such a great library!

I would have a question. We had quite some discussions on whether or not to use pre-execute hooks for checking preconditions for one specific task. What happened was that we did some mistake in the pre-execute hook that was only supposed to be applied for one task (which we forgot to check) and then all tasks were broken.

So I personally advocated not using pre-execute hooks for checking singular tasks but instead just checking preconditions within the task itself and then cancelling them if needed.

Would there be any advantage in checking preconditions for one particular task in the pre-execute hook? Would you agree with my notion, rather with the opposite, or is there no clear recommendation for or against the usage?

An accompanied question would clearly be if you had any specific use-cases in mind when providing the pre-execution hook. I could not find any ideas in the documentation (which I might have missed, sorry if this is the case). Could you maybe give a few or link me?

Thanks again and all the best!

**Comment by coleifer** [comment]
A pre-execute hook that fails with an uncaught exception should not affect the actual running of the task, so I'm a little confused about that aspect of your comment. As long as the hook did not raise a `CancelExecution` then the task(s) would still be executed -- your hook would just need to be debugged.

On to your main question, it depends... You can write a decorator that either no-ops or raises an unhandled exception, and wrap the relevant tasks with it:

```python
from functools import wraps
from huey import CancelExecution
from myapp import huey

# Let's say we want to skip execution when 'something' is passed to a task.

def validate_some_condition(fn):
    @wraps(fn)
    def inner(task_arg1, *task_args, **task_kwargs):
        if task_arg1 == 'something':
            # here you can raise an exception or just exit returning None
            # raise CancelExecution('not running task')
            return
        return fn(task_arg1, *task_args, **task_kwargs)
    return inner

@huey.task()
@validate_some_condition
def my_task(arg1, *args, **kwargs):
    print('arg1 is not equal to "something"')
    # ... etc ...
```

Or you can use a pre-execute hook and just look at the `task` parameter they are called with. Up to you.

**Comment by MichaelVoelkel** [comment]
Thanks for the thorough explanation!

To address the confusion on your side introduced by my incomplete description: We actually forget (totally our fault, clearly) to check against the task name and just named the task something like `pre_foo_task` and forgot that this will not only apply to `foo` but all task, so then this precondition was applied to _all_ the tasks. Clearly a fault on our side but as this could induce system-wide problems, it might be a sound choice to rather stick to your suggestion to use decorators as pre-checks.

**Comment by coleifer** [comment]
No, it does *not* get caught by the pre-execute machinery - it would be treated as an unhandled exception (and if the task had retries, it would be retried).
