### ISSUE TITLE
Huey deployment with password protected redis

### ISSUE THREAD

**Issue by vishwakarma0** [coleifer/huey#653]
Hi,
Could anyone please help me, I'm trying to deploy huey with redis (Azure cache for Redis) which is password protected, I'm not able to find any docs or source that uses password based Huey redis deployment.
Any source or docs would be helpful.

**Comment by coleifer** [comment]
You just pass the redis args to `RedisHuey`, and they are forwarded to the redis constructor: https://github.com/coleifer/huey/blob/master/huey/storage.py#L364

The doc for the redishuey class lists a number of the arguments, including password: https://huey.readthedocs.io/en/latest/api.html#RedisHuey
