### ISSUE TITLE
Question: Can I see currently running jobs?

### ISSUE THREAD

**Issue by mgleichaufbosch** [coleifer/huey#658]
Is there a possibility to differentiate between a taskid that is currently running and just doesn't exist?
While it's running, the taskid isn't present in huey.all_results() and get(taskid) returns None.
After completion it is present in all_results() and get(taskid) returns the result as expected.

Background: I'm writing an API where a post to endpoint A starts a task and I want to provide an endpoint B that allows polling of the task status. Now I would like to provide different status response for a plain invalid taskid and a currently running taskid.

I'm using sqlite for storage. Is that the cause? Or do I need to use signals and write to the sqlite?

Even more background on what i'm doing:

app.py:
```python
from flask import Flask, url_for
import worker
from huey import SqliteHuey

huey = SqliteHuey(filename='worker.db', fsync=True)

app = Flask(__name__)

@app.route("/create/<a>", methods=["POST"])
def create_task(a):
    task = worker.create_hue_task(a)
    return task.id, 204

@app.route("/allresults")
def allresults():
    return str(huey.all_results())
```

worker.py:
```python
import time

from huey import SqliteHuey

huey = SqliteHuey(filename='worker.db', fsync=True)

@huey.task()
def create_hue_task(a):
    time.sleep(20)
    return a+a
```

and then just start the worker and the app:
```shell
huey_consumer worker.huey
# in another shell
flask run
```

**Comment by coleifer** [comment]
Huey does not provide this. The result won't be populated until the task is done. But rather than trying to use huey to try to figure out if the task is still running, I'd suggest you implement status updates within the task itself. Task functions can accept a task parameter, which can give you the task ID if you want to use that as a key.

```python
@huey.task(context=True)
def my_task(a, task=None):
    task_id = task.id
    database.write_task_status(task.id, 'starting')
    ...
    database.write_task_status(task.id, 'finished')
    return result
```

**Comment by coleifer** [comment]
You can also implement this using task pre- and post-execute hooks or signals:

* https://huey.readthedocs.io/en/latest/api.html#Huey.pre_execute
* https://huey.readthedocs.io/en/latest/signals.html

**Comment by jedie** [comment]
But you can't currently not detect died tasks, see: https://github.com/coleifer/huey/issues/569 ;)

**Comment by coleifer** [comment]
That's actually been added. Bear in mind this only occurs if you hard shutdown the consumer. Graceful shutdown finishes all running tasks.

https://huey.readthedocs.io/en/latest/signals.html

See SIGNAL_INTERRUPTED

**Comment by coleifer** [comment]
Oh, I suppose if the operating system kills the worker process for using all the ram...but if that's the case you've got bigger problems.
