### ISSUE TITLE
Periodic task locks forever...

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#663]
I have trouble with a periodic task that is locked forever...

I have something like this:
```
@periodic_task(crontab(minute='0', hour='*'))  
@lock_task('foo_bar-lock')  
def foo_bar():
    # ...do something...
```

It works a while, but some day this tasks are never executed anymore, because it's always locked. I see this in huey monitor: The task started every hour, but the signal is always "locked"...

The question i ask myself is: How does such endless locking come about? Maybe the task duration was longer than one hour?
Current work-a-round: I implement a way to call `HUEY.flush_locks()` if this happens.

**Comment by coleifer** [comment]
You should be able to look at the logs and see whether a previous invocation took longer than an hour.

What exactly is the task doing?

I'd add extra logging and watch what happens.
