### ISSUE TITLE
Failed to retry task

### ISSUE THREAD

**Issue by 12Tall** [coleifer/huey#664]
Hi Charles,  
I just find that some huey task can't be retried, while others is normal.  This is weird to me. Do you know how to fix it? thanks!

```python
# add_number can be retried normally
@huey.task(retries=3,retry_delay=30)
def add_numbers(a, b):
    raise Exception('add_number task failed')
    return a + b

# this test task cannot be retried
@huey.task(retries=3,retry_delay=30)
def test(task_path):
    res = os.system('''cd .\\tasks\\{} & python task.py'''.format(task_path))
    if res != 0:
        raise Exception('test task failed')
    return 'OK'
# and got the following log
# [2022-04-30 19:53:09,777] INFO:huey:Worker-1:Requeueing 542567d3-58ea-4af2-81fa-af9e8d8b126a, 2 retries
# [2022-04-30 19:53:09,812] INFO:huey:Worker-1:Added task 542567d3-58ea-4af2-81fa-af9e8d8b126a to schedule, eta 2022-04-30 11:53:39.777879
# then the consumer won't retry the task anymore
```
Here is the source code of my `task.py`  
```python
import os
os.system('echo > a.log')
exit(1)
```

**Comment by coleifer** [comment]
Your task is calling `os.exit`?

**Comment by coleifer** [comment]
Oh I see, you're shelling out to that file. That shouldn't matter.

How are you running your consumer?

**Comment by coleifer** [comment]
I'll just add that retrying tasks is tested thoroughly, so this is likely something in your config or the way you're running Huey.

Please respond with:

* Are all tasks failing to be retried or just one?
* what message broker do you use? Redis, SQLite or filesystem?
* how do you run the consumer?
* are you able to tell whether the task is being added to the schedule?

Please comment and I'll reopen the issue, but I'm quite sure this is user error in some way.

**Comment by 12Tall** [comment]
Hi @coleifer ,
Sorry for late reply, I call huey with `subprocess.Popen(['py', '-3.9', 'huey_consumer.py', 'main.huey']) ` as background process in my flask web service, while the broker is a remote redis server. Seems (almost) all the tasks failed to retry.  
Today, I switched the da to a local sqlite.db, it works! maybe there are some issues with my db configuration. But thanks for your help!

**Comment by coleifer** [comment]
That's very strange, I can't think of any plausible explanations for the tasks not being retried.

**Comment by 12Tall** [comment]
Yes, it is. Maybe it's because I'm the lucky one 😂
