### ISSUE TITLE
Undocumented behavior for DEBUG mode in Django

### ISSUE THREAD

**Issue by udit-001** [coleifer/huey#666]
Based on the documentation present here: https://huey.readthedocs.io/en/latest/contrib.html#debug-and-synchronous-execution

I have `DEBUG=True` in my django settings, and no configuration for Huey provided in my project, so based on the docs every task should execute synchronously, without me having to run huey or redis? But I get the error that it is unable to connect to redis, and when I run redis I get a `ResultTask` as return value instead? So am I doing something wrong to be unable to get the synchronous mode working correctly? Should I be passing the Huey configuration in my Django project settings as the one mentioned in this section: 
https://huey.readthedocs.io/en/latest/contrib.html#debug-and-synchronous-execution

**Comment by coleifer** [comment]
You're right, I didn't anticipate that someone would completely leave `HUEY` unspecified. Please drop at the bare minimum the following into your settings:

```
HUEY = {}
```
