### ISSUE TITLE
repeat multiple tasks in pipeline

### ISSUE THREAD

**Issue by bengerman13** [coleifer/huey#668]
Hi @coleifer - we're using huey in a couple projects for some provisioning tooling. There's one pipeline we have that sometimes fails on one task, and we want to basically go back three tasks to recover.

The docs don't seem to suggest this is supported (which makes sense - this is kind of a silly thing to do, and doesn't seem compatible with how huey consumes tasks from pipelines), but I'm wondering if you've seen a pattern or strategy for solving this kind of problem, or if I've missed something in the docs.

**Comment by coleifer** [comment]
Probably the best option in that case is to make a parent task that calls the subtasks, or in the task that is prone to failure catch the exception and explicitly re-enqueue a new pipeline.
