### ISSUE TITLE
Periodic Tasks are enqueuing but not executing sometimes

### ISSUE THREAD

**Issue by harshavardhannarla** [coleifer/huey#674]
Using django extension of huey

Settings.py
```
# Huey configuration
HUEY = {
    'name': 'test-django',
    "immediate": False,
    'blocking': True,  # Use blocking list pop instead of polling Redis.
    'immediate': DEBUG,
    'results':True,
    'consumer': {
        
        'loglevel': logging.DEBUG,
        'workers': 16,
        'scheduler_interval': 1,
        'periodic': True,

    },
}

```

tasks.py of an app
```
@db_periodic_task(crontab(minute='*/1'))
def get10minData():
    nodes=IIIT_Node.objects.all()
    for elem in nodes[:4]:
        data = get_data_from_element(elem, 10)
        d = get_object_IIIT_10min(elem, data)
        iiit_data_10min.objects.filter(created_at = d.created_at).filter(node = d.node).delete()
        d.save()
        while(iiit_data_10min.objects.filter(node=elem).count() >= 2):
            iiit_data_10min.objects.filter(node=elem).first().delete()
    nodes=Airveda_Node.objects.all()

@huey.signal()
def print_signal_args(signal, task, exc=None):
    if signal == signals.SIGNAL_ERROR:
        print('%s - %s - exception: %s' % (signal, task.id, exc))
        subject = f'Task [{task.name}] failed'
        message = f"""Task ID: {task.id} Args: {task.args} Kwargs: {task.kwargs}
        Exception: {exc}
        {traceback.format_exc()}"""

```

output of python3 manage.py run_huey:
INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task node.tasks.get10minData: 311423f8-515a-4949-ac01-d993cce6109b.
NFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task node.tasks.get10minData: 7300d65d-aca1-4d26-a01b-3388f490d643.

INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task node.tasks.get10minData: a8a138af-b2d8-4040-ac6e-1cd4dd9bfb5d.
INFO:huey:Worker-12:Executing node.tasks.get10minData: a8a138af-b2d8-4040-ac6e-1cd4dd9bfb5d
INFO:huey:Worker-12:node.tasks.get10minData: a8a138af-b2d8-4040-ac6e-1cd4dd9bfb5d executed in 3.720s

INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task node.tasks.get10minData: 3e3d478c-ffc3-4b52-a431-8a652c9a1498.
INFO:huey:Worker-9:Executing node.tasks.get10minData: 3e3d478c-ffc3-4b52-a431-8a652c9a1498
INFO:huey:Worker-9:node.tasks.get10minData: 3e3d478c-ffc3-4b52-a431-8a652c9a1498 executed in 3.788s

As you can see it did not get executed the first 2 times it just enqueued , Is there any way to see what happened to those tasks, even signal handler is not catching the start of task

**Comment by coleifer** [comment]
I'm not sure what could be causing this, but if you can produce a failing test case I will be happy to look into it. Otherwise, I'd suggest debugging it.
