### ISSUE TITLE
Using same redis instance for two huey instances running on different machines

### ISSUE THREAD

**Issue by SaffronWolf** [coleifer/huey#675]
Is it possible to use the same redis instance for two huey instances running on different machines? I tried supplying the same redis url to huey instances but it results in `not found in TaskRegistry` error.

**Comment by coleifer** [comment]
You probably need to specify a different `name` for your different huey instances, if they're sharing a Redis server. It's no problem, though, definitely do-able. Just try something like:

```python
# app1.py
huey = RedisHuey(name='app1')

# app2.py
huey = RedisHuey(name='app2')
```
