### ISSUE TITLE
Create own signal

### ISSUE THREAD

**Issue by jizekki** [coleifer/huey#681]
I want to track a task progression (using % of completion). What I do right now is register the task progression in a database within the implementation of the task as it progresses. However This could be a performance issue as I interrogate the database a lot. So what I want to do is use a signal (`SIGNAL_PROGRESSION` for example) with a parameter to send the progression of the task from the consumer and implement a signal handler in my application to receive that signal. So my questions are :
- Is there a way to do this with the current configuration?
- If no, is there another way to do this while avoiding the use of any database or message brokers ?

Thanks in advance.

**Comment by coleifer** [comment]
>send the progression of the task from the consumer and implement a signal handler in my application to receive that signal

This is not how signals work. The docs are hopefully clear:

>Callbacks can be registered as signal handlers, and will be called synchronously by the consumer process.

That means the consumer (the workers) are the ones who execute signal handlers.

If you want to talk to your application from your tasks, then you need to use some intermediary storage or IPC -- Huey's storage API can be used for this if you don't need everything your relational database provides. Or you can use redis' pubsub. Or any number of other things.
