### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by adamchainz** [coleifer/huey#682]
I've been rolling out Mypy on a client project, and Huey is one of the packages in use without type hints. I've started writing some stubs that are checked into the project. Would you be interested in adding type hints to Huey itself, along with the requisite `py.typed` file?

**Comment by coleifer** [comment]
I don't intend to maintain that or keep it in sync with changes to the main codebase, as I don't use typing. Probably best to keep it as a separate package/fork.

**Comment by adamchainz** [comment]
Fair enough!
