### ISSUE TITLE
Kill crashed task after x seconds

### ISSUE THREAD

**Issue by JoeTseHot** [coleifer/huey#686]
hi, thanks for the excellent code

I run the huey consumer using 8 "threads" because Windows is too crappy to support -k process and the software my company use is too crappy to support linux

I have about 5 concurrent tasks to feed the consumer at any one time.  I notice that if one of them crash/run into an error, the 4 remaining tasks are just stuck and I have to Ctrl+C the terminal window running the consumer to free it.

I suspect it is because the 5 tasks share one process and because of the global interpreter lock, crash in one thread means crashing in all threads.

I tried to run huey consumer in process mode but this seems to be impossible.  Another solution I can think of, is to automatically kill a task after 20 seconds (the normal time a task is expected to complete in).  I believe setting a sunset time for a task can be done in redis queue (another awesome program I cannot run natively on Windows)

I checked the @huey.task(expiry=n) documentation and found that it only controls if the task will be started at all, which is not what I am looking for.

I wonder if you have any idea on how to solve this?  Thanks a bunch.

**Comment by coleifer** [comment]
I'm not clear what "crash" means in this case. If a task fails with an unhandled exception, then the exception is caught by the worker and the error is logged / task retried if any retries are specified.

At any rate, there is no mechanism for killing a task after it has been running for X seconds, I'm sorry.

**Comment by JoeTseHot** [comment]
ah, do you mean that even if a task fails with an unhandled exception (which is what I mean by crash), the worker will keep working and consume tasks, and that other existing, concurrent tasks will continue to be worked on?  If yes, I may have misunderstood the problem I am facing in production and need to look again 

just want to say thank you again for the code and for the speedy response, you are the best!

**Comment by coleifer** [comment]
>ah, do you mean that even if a task fails with an unhandled exception (which is what I mean by crash), the worker will keep working and consume tasks, and that other existing, concurrent tasks will continue to be worked on?

Yes exactly.

**Comment by coleifer** [comment]
I'd suggest adding logging to your tasks and checking the Huey logs and the app logs as a good first step.
