### ISSUE TITLE
New release that includes CancelExecution

### ISSUE THREAD

**Issue by kbakk** [coleifer/huey#687]
Hi,

There seems to have been some new features (in particular [_Canceling from within a Task_](https://huey.readthedocs.io/en/latest/guide.html#canceling-from-within-a-task)). 

This seems to have been added to master (https://github.com/coleifer/huey/commit/b17c8dc59ee9941ea7aa8ae75f6fdb77307642ab), but not yet released. Is a new release planned that will include this?

Changes since 2.4.3 (currently on PyPI): https://github.com/coleifer/huey/compare/2.4.3...master

Either way, I would like to thank you for this great package! 🚀 ✨

**Comment by coleifer** [comment]
Sure, 2.4.4 should be up on pypi now.
