### ISSUE TITLE
Add macOS fix to non-.py version

### ISSUE THREAD

**Issue by hyperknot** [coleifer/huey#690]
[This commit fixes the huey_consumer.py file](https://github.com/coleifer/huey/commit/bf002c85ae444954c3237fa4b056fbf9111448a1), however it doesn't fix the `huey_consumer` file. Basically on macOS if you start `huey_consumer` it's broken but if you start `huey_consumer.py` it's good.

It just needs a copy-paste into the other file.

**Comment by hyperknot** [comment]
Any reason it cannot be in `consumer_main()` function?

**Comment by coleifer** [comment]
>however it doesn't fix the huey_consumer file

There is no `huey_consumer` file. That's an entry point created by setup.py. It's the same thing, though.

**Comment by coleifer** [comment]
We don't put it in there per the documentation, which says to put it in the `if __name__` block:

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method

**Comment by hyperknot** [comment]
I don't understand, how does it solve the problem that no one on macOS can run `huey_consumer`. Either there should be a wrapper function or maybe the whole CLI endpoint shouldn't be offered. (I guess that'd break a lot of installations, so wrapper function is the only proper solution.)

That `__name__` comment is just about making sure it runs exactly once and never has an accidental side-effect. I think making `consumer_main_cli()` would do the same effect.

**Comment by coleifer** [comment]
Well it's just strange to need a) to run the consumer from the entry point only (workaround is to just invoke the script directly which will work fine), b) to run it locally on a Mac, and c) use multiprocessing.

**Comment by hyperknot** [comment]
I just happen to mirror a production environment locally, hence the multiprocessing bit. I'm happy to use the .py version, there is absolutely no problem with that, but it was not easy to figure out that the non-py version has a bug which is not present in the .py version. Hopefully people will find this thread and do the same.
