### ISSUE TITLE
What's the best way to wait for a task to completely finish before moving on?

### ISSUE THREAD

**Issue by a3rosol** [coleifer/huey#692]
Hi,

I have two tasks:

`def api_req():
    a = abc.get(something)
    return a

def launch_api_reqs(large_number):
    tasks = [api_req() for i in range(large_number)]
    results = [task_result.get(blocking=True) for task_result in tasks]
    return results

`

I call launch_api_reqs but need to wait until an ungodly number of api_req have completed to process the results from launch_api_reqs. However, the code above doesn't really block for a sufficiently large number of large_number.

What's the best way to achieve the desired outcome with huey?

**Comment by coleifer** [comment]
Please take the time to learn how to properly format your code. It's worthwhile.

I'm not sure what you're asking. If you want to block for a single task, then call `.get(blocking=True)` on it's result handle. If you want to block for a group of tasks, then call `.get(blocking=True)` on all their result handles.

**Comment by a3rosol** [comment]
Terribly sorry, I formatted the code a bit better.
What I'm trying to achieve is the following:

In an effort to make thousands of api calls (function `api_req()`) I call `launch_api_reqs`. However, I must wait for `launch_api_reqs()` to complete and get its results before my code can continue. Using the above code snippet, I can't achieve the desired outcome. For small numbers, the code _seems_ to work. If I launch 1000 `api_reqs()` the blocking doesn't seem to work anymore.

The question is: how can I launch a large number of tasks, wait for them to complete (blocking is entirely ok) and then continue with my program?

**Comment by coleifer** [comment]
>the blocking doesn't seem to work anymore.

Have you been able to track down where the issue is?
