### ISSUE TITLE
Djhuey existing logger detection doesn't check for parents handlers

### ISSUE THREAD

**Issue by pelletier** [coleifer/huey#693]
We are running huey as part of a django application. In our app, loggers are defined like this in django's settings.py:

```python
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "rich": {"datefmt": "[%X]"},
    },
    "handlers": {
        "stderr": {
            "class": "logging.StreamHandler",
            "formatter": "rich",
            "level": "INFO",
        },
    },
    "loggers": {
        # ... other loggers omitted
        "huey": {"level": "INFO"},
    },
    "root": {
        "handlers": ["stderr"],
        "level": "INFO",
    },
}
```

We've noticed that huey generated all logs twice: once using the rich formatter, once with seemingly its own format.

I believe the issue is in this check:

https://github.com/coleifer/huey/blob/03f2c2acf7e9b34087d561a32dc200c4c2f4125c/huey/contrib/djhuey/management/commands/run_huey.py#L84-L88

It  checks whether `handlers` is set on the logger itself, but in our case the handler is set in its parent. This seems to be confirmed by explicitly defining the handler on the `huey` logger:

```python
# snip
    "loggers": {
        # ... other loggers omitted
        "huey": {"level": "INFO", "handlers": ["stderr"]},
    },
# snip
```

This configuration does not cause duplicated logs.

We have a workaround so it's not a problem for us. It was confusing for us for a little bit, so figured you'd like to know. I'm not sure whether this behavior is on purpose, so feel free to close this issue if it is!

**Comment by coleifer** [comment]
I'm open to suggestions on how to improve the interaction between huey and Django w/r/t logging, but at the moment I think we'll just trust users to work around if they run into this.
