### ISSUE TITLE
Django: Can't customize worker options when using Huey instance for the settings

### ISSUE THREAD

**Issue by gokhanmeteerturk** [coleifer/huey#694]
While using Huey instance as HUEY settings like below, run_huey.py's Command class uses default consumer options.
```python
from huey import RedisHuey

HUEY = RedisHuey('my-app')
```
It would be nice to be able to send default consumer options through the Huey instance in settings.py instead of just this:
```python
            if isinstance(settings.HUEY, dict):
                consumer_options.update(settings.HUEY.get('consumer', {}))
```

**Comment by coleifer** [comment]
I plan to keep things decoupled for Django users. You can specify any consumer options on the command-line if you need to, or write your own management command that calls `run_huey` with the options you prefer.
