### ISSUE TITLE
Crontab with dash and slash executes every minute

### ISSUE THREAD

**Issue by DataCerealz** [coleifer/huey#695]
Hello,

if have several db periodic tasks set up with Django using redis.
However, every crontab following the pattern e.g. `minute=“1-59/3”, hour=“*” …`
Or
`minute=“15-45/6”, hour=“*” …`
and so on executes every minute in the given range.
When providing a range like 15-45 the interval of /6 gets ignored on every task using the decorator
`@db_periodic_task(crontab(…))`.

Any assistance highly appreciated, but I don’t see where my syntax would be wrong according to Huey docs. All other jobs using only a range or only */6 behave as expected.

**Comment by coleifer** [comment]
Yeah, huey doesn't support that notation (dashed group + slash). Your options would be:

1. Specify it manually, e.g. minute="1,4,7..."
2. Specify it manually w/an expression, e.g. `minute=",".join(map(str, range(1, 59, 3)))`
