### ISSUE TITLE
Comparison between redis, sqlite, file-system, and in-memory storage?

### ISSUE THREAD

**Issue by LazyGeniusMan** [coleifer/huey#699]
I notice that `huey` support several backend, the homepage said it supports `redis, sqlite, file-system, or in-memory storage`. But I can't find the comparison for them in the docs, like pros, cons, suitable use case, etc. It would be nice if it's also added into docs.

**Comment by coleifer** [comment]
If you don't know, just use Redis.

**Comment by coleifer** [comment]
(I will flesh out the docs a bit, though)
