### ISSUE TITLE
Schedule task that is located in another codebase

### ISSUE THREAD

**Issue by ekeric13** [coleifer/huey#701]
I was wondering if it was possible to enqueue a task that is in another codebase.

Essentially the equivalent of [celery's `send_task`](https://docs.celeryq.dev/en/stable/reference/celery.html#celery.Celery.send_task)

Example online of how celery uses send_task:
https://www.distributedpython.com/2018/06/19/call-celery-task-outside-codebase/

Essentially trying to do this:
app1.py code
```
def endpoint():
	r = huey.send_task('add', 3, 4)
	print(r)
```
app1 execute
```
# start server
python app1.py
```

app2.py
```
@huey.task()
def add(a, b):
    return a + b
```
app2 execute
```
# start consumer
python huey_consumer.py main.huey
```

**Comment by coleifer** [comment]
Absolutely as long as the code is import-able wherever the consumer is running. The idea is to have a special task in your codebase that accepts a dotted path to some arbitrary callable, and when the consumer runs the task, the callable will be imported and run.

You can do something like this:

```python
from importlib import import_module

@huey.task()
def path_task(path, *args, **kwargs):
    path, name = path.rsplit('.', 1)  # e.g. path.to.module.function
    mod = import_module(path)  # Dynamically import the module.
    return getattr(mod, name)(*args, **kwargs)  # Call the function.

# Example usage might be:
# foo.py
def add_these(a, b):
    return a + b

# Somewhere else, we can tell the consumer to use the "path_task" to import
# the foo module and call "add_these(1, 2)", storing the result in the
# result-store like any other task.
path_task('foo.add_these', 1, 2)
```

Doc: https://huey.readthedocs.io/en/latest/guide.html#run-arbitrary-functions-as-tasks
