### ISSUE TITLE
Passing kwargs when using TaskWrapper.map

### ISSUE THREAD

**Issue by MarkusH** [coleifer/huey#702]
Thank you for building huey. It's been a pleasure to try it out. I really like how its code is readable and understandable!

I'm trying to use `TaskWrapper.map()` on a task that requires keyword-only arguments, e.g:

```python
@task()
def mytask(a, b, *, foo, bar):
    print(f"{a=}, {b=}, {foo=}, {bar=}")

mytask.map([((1, 2), {"foo": 3, "bar": 4}), ((5, 6), {"foo": 7, "bar": 8})])
```

However, I'm getting a `TypeError` exception:

```python
Traceback (most recent call last):
  File "/home/markus/.venvs/myenv/lib/python3.9/site-packages/huey/api.py", line 380, in _execute
    task_value = task.execute()
  File "/home/markus/.venvs/myenv/lib/python3.9/site-packages/huey/api.py", line 787, in execute
    return func(*args, **kwargs)
TypeError: mytask() missing 2 required keyword-only arguments: 'foo' and 'bar'
```

The problem is, that in `huey/api.py:787`, `args = ((5, 6), {'foo': 7, 'bar': 8})` and `kwargs = {}`.

Debugging where the `args` are coming from, it appears that `TaskWrapper._apply()` does not correctly pass on the `kwargs` to `TaskWrapper.s()`.

Thinking about the code for `_apply()`, I think, this would fix the issue:

```python
def _apply(self, it):
    # Each item in `it` can be one of those:
    # - a single value, i.e. not a tuple, in which case the value will
    #   be passed as the first and only positional argument
    # - a 2-tuple, where the 1. item is an n-tuple and the 2. item is a
    #   dict; the 1. item is thus *args and the second one **kwargs
    # - any other tuple, in which case, the tuple itself is *args

    for item in it:
        if not isinstance(item, tuple):
            yield self.s(item)
        elif len(item) == 2 and isinstance(item[0], tuple) and isinstance(item[1], dict):
            yield self.s(*item[0], **item[1])
        else:
            yield self.s(item)
```

However, the suggested change breaks the current behavior, where a task takes 2 positional arguments, the first being a tuple and the second being a dict:

```python
sometask.map([((1, 2), {"a": 3, "b": 4})])
# previously
sometask((1, 2), {"a": 3, "b": 4})
# now
sometask(1, 2, a=3, b=4)
```

I do _not_ have an idea how to fix or detect that.

**Comment by coleifer** [comment]
Thanks for the report. I have no intentions of changing this, but my suggestion would be to see that `map()` is really just an extremely trivial wrapper and you can just create your own implementation, or just create the result group directly, e.g.:

```python
# If having a result group is important to you,
rg = ResultGroup([
    sometask(*a, **k) for (a, k) in iterable
])
```
