### ISSUE TITLE
How to run multiple consumers safely and execute startup code only once?

### ISSUE THREAD

**Issue by eabra** [coleifer/huey#703]
I have some code that sets up the environment and I need to make sure that the code is execute only once and not every time another consumer is started.
I'm running a consumer that executes periodic tasks and that starts first and multiple consumers that don't execute periodic tasks.
How can I tell those consumers to ignore the code that sets up the environment and to just execute the tasks?
I've tried adding those tasks into a seperate file but then I get an error saying that those tasks can't be found in the TaskRegistry.

Example:

```
prepare_environment()
reset_db()

@huey.periodic_task(crontab(minute='*/1'))
def some_recurring_task():
    pass

@huey.periodic_task(crontab(minute='*/1'))
def another_recurring()
    some_task()


@huey.task()
def some_task()
```

`prepare_environment()` and `reset_db()` should only run once and should not be executed by another consumer again.
What would be a sensible way to achieve this?

**Comment by coleifer** [comment]
I don't think I understand the question, or more importantly, I don't understand why this is huey-specific. Sounds like you figured out how to run the multiple consumers safely with regards to only running periodic tasks from one consumer. The rest of this sounds like a generic python question. I'd suggest setting a flag in Redis or something else when the first consumer starts up and sets up the environment, and then other processes can check the presence or absence of that flag. Something like that, perhaps.
