### ISSUE TITLE
Crontab function without default values 

### ISSUE THREAD

**Issue by lucacillario** [coleifer/huey#706]
```python
def crontab(minute='*', hour='*', day='*', month='*', day_of_week='*'):
```

These are quite dangerous default values IMHO. If one forgets to override one of the parameters, the default is **"*"**.

Since testing a cronjob is not always easy, I would be extra careful about using such "wide" defaults.

What about adding a `crontab` function without defaults?

**Comment by coleifer** [comment]
These settings have existed for 10 years so I'm not inclined to change them. The docs make it clear https://huey.readthedocs.io/en/latest/api.html#crontab
