### ISSUE TITLE
Huey logging "Dummy-1" when using greenlet - Workers monkey patch Postgres?

### ISSUE THREAD

**Issue by rtu-dataframe** [coleifer/huey#707]
Hi, i've noticed using the "greenlet" workers that huey worker is printing out the following log with the word "Dummy":

`[2023-02-09 11:56:17,404] INFO:huey:Dummy-1:Executing...`

Is this normal?

Also a bonus question, when using the "greenlet" workers, i'm patching my django app in the `manage.py` using this code:

#!/usr/bin/env python
import os
import sys

```
# Apply monkey-patch if we are running the huey consumer.
if 'run_huey' in sys.argv:
    from gevent import monkey
    monkey.patch_all()

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myapp.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)

```

i also need to patch postgres? it's automatically monkey patched from gevent? A DB pool like `django-db-geventpool` is needed?

**Comment by coleifer** [comment]
The default logging formatter includes the thread or process id, which for gevent is something like "dummy" since they're not real threads.

Yes you need to bind a special callback for psycopg2: https://www.psycopg.org/docs/advanced.html#support-for-coroutine-libraries

**Comment by rtu-dataframe** [comment]
Thank you.
