### ISSUE TITLE
Avoid using `setup.py install`

### ISSUE THREAD

**Issue by jonnyarnold** [coleifer/huey#708]
Hi there! Thanks for Huey, it's working great for our organisation.

When installing Huey with Python 3.11 and pip 23.0, the following deprecation warning is given during `pip install`:

```
DEPRECATION: huey is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

To be clear, the package continues to install -- but, as the message says, this will fail in pip 23.1. 

I hope this helps!

**Comment by coleifer** [comment]
Thanks, added the magic file and it will be present in the next release.

**Comment by coleifer** [comment]
Pushed 2.4.5 to pypi.

**Comment by edmcdonagh** [comment]
Hi @coleifer - did that fix it for you? I have huey as a dependency and I'm still getting this message when installing to a fresh Python 3.10 venv. You won't see the message if you have wheel installed in the venv already.

Checking the version installed, I have 2.4.5 so it should work ok...
