### ISSUE TITLE
unable to lock: <lock_name> is never removed from results

### ISSUE THREAD

**Issue by mcosta74** [coleifer/huey#710]
I have some "fire and forget" tasks (I start them and they don't return anything); since I don't want to have multiple instances of it running a the same time I protect them with a lock

```py
@db_task(**kwargs)
@lock_task('my-lock')
def my_taks():
    do_something()
```

The lock works well but I see that the lock-error is stored in the `results` and never removed. This means that under some conditions the REDIS storage will grow indefinitely.

is it something expected?

**Comment by coleifer** [comment]
Yes, your options are to:

1. Use a lock context manager and catch the exception yourself, returning `None` to avoid adding a result.
2. Use the result-store directly to implement your own locking
3. Use a non-None return value and resolve the task result
4. Use redis-expire storage, which stores results in top-level keys with an expiry
