### ISSUE TITLE
Question/Feature request: task graphs

### ISSUE THREAD

**Issue by mcminis1** [coleifer/huey#712]
As a developer I want to be able to define a graph of tasks to be executed so that one task can be the input for multiple other tasks, or multiple tasks can feed their output into another task so that I can perform more complicated API call flows. In addition, I'd like to support decision flow within the graph to allow for recursion and task execution that depends on the output of preceding tasks. Also, when possible, I'd like to be able to define the maximum number of tasks to execute concurrently to avoid memory, compute, or network resource starvation.

Is this something that is already possible? If not, do you think it would be difficult to implement?

**Comment by coleifer** [comment]
Lol bro just use airflow or something if you want all that. Huey supports chainable tasks that can pipe data through, but it's more akin to a unix pipe than a dag.

**Comment by mcminis1** [comment]
OK, I can find something else. Airflow is too heavy, i just want something to do smaller async graphs without polling. i like how lightweight your project is and am willing to do the work myself.

thanks for the quick reply!
