### ISSUE TITLE
Scheduled tasks repeating themself after deployment

### ISSUE THREAD

**Issue by ekinertac** [coleifer/huey#714]
HI, 

We have lot of scheduled tasks in our project. Hourly, daily etc. 

If I understand huey correctly, it register all the scheduled tasks on startup to the redis then runs them at their specified time.
After i changed some code and restart the supervisord controlled huey workers the old scheduled tasks stays on the redis database and they run together with the newly deployed code. 

Most of our tasks includes database inserts and now we have duplicate inserts in our database. 

Is there away to clear old scheduled tasks in redis records created by huey when starting up workers ?

**Comment by coleifer** [comment]
This sounds like a deployment issue - I'm assuming you have some process that adds tasks to the schedule, and when you deployed it re-added duplicate tasks to the schedule.

You can run `huey.scheduled()` to get the list of all available scheduled tasks. You can run `huey.storage.flush_schedule()` to clear the schedule, and then re-add (`huey.add_schedule(t)` or `huey.enqueue(t)`) the tasks you want to keep.

**Comment by ekinertac** [comment]
thanks for the quick response 👍

**Comment by ekinertac** [comment]
I've tried your suggestions on my project but whatever I do, I got empty list object with `huey.scheduled()` method. I think i'm using the wrong huey instance. 

We're using `django_redis`'s cache backend with django, and I thought it was a good idea to use it with huey also. 

in our `config/huey.py` file I extended `huey.RedisHuey` class like this:

```python
# config/huey.py

from django_redis import get_redis_connection
from huey import RedisHuey


class DjangoHuey(RedisHuey):
    """
    Subclassed to use the existing connection pool from the Django
    cache backend, when using `django-redis`.
    """

    def __init__(self, *args, **kwargs):
        connection = get_redis_connection()
        kwargs["connection_pool"] = connection.connection_pool

        super().__init__(*args, **kwargs)
```

and register the `DjangoHuey` class in the `HUEY` config variable in the `settings.py` file

```python
# config/settings/common.py

HUEY = {
    "huey_class": "config.huey.DjangoHuey",  # Huey implementation to use.
    "name": "huey",  # Use db name for huey.
    "results": True,  # Store return values of tasks.
    "store_none": False,  # If a task returns None, do not save to results.
    "immediate": False,  # If DEBUG=True, run synchronously.
    "utc": True,  # Use UTC for all times internally.
    "blocking": False,  # Perform blocking pop rather than poll Redis.
    "consumer": {
        "workers": 50,
        "worker_type": "greenlet",
        "initial_delay": 0.1,  # Smallest polling interval, same as -d.
        "backoff": 1.15,  # Exponential backoff using this rate, -b.
        "max_delay": 10.0,  # Max possible polling interval, -m.
        "scheduler_interval": 1,  # Check schedule every second, -s.
        "periodic": True,  # Enable crontab feature.
        "check_worker_health": True,  # Enable worker health checks.
        "health_check_interval": 1,  # Check worker health every second.
    },
}
```

I added a simple custom django management command which triggers `huey.scheduled()` or `huey.storage.flush_schedule()` using the huey instance you did write in the documentation.


```python
# apps/core/management/commands/flush_huey.py

from django.core.management import BaseCommand
from huey.contrib.djhuey import HUEY as huey


class Command(BaseCommand):
    help = 'Flushes the Huey queue'

    def handle(self, *args, **options):
        # huey.storage.flush_schedule()
        print(huey.scheduled())

```

I'm running the custom command in a seperate terminal session after I run the `./manage.py run_huey` command, but always I get empty list

**Comment by coleifer** [comment]
Regarding scheduled tasks, perhaps this was confusion around terminology. Scheduled refers to ordinary tasks that you explicitly `schedule` to run at a certain time, or after a certain delay. These are in contrast to `periodic_task` which are more like "cron jobs" that run automatically.

I had assumed you were having an issue with the former, but if it is always returning an empty list, then perhaps the issue is with the latter periodic tasks?

**Comment by coleifer** [comment]
*If* the issue is with periodic tasks instead, you might try inspecting `huey._registry.periodic_tasks` to see what all it has registered? I'm wondering if *possibly* your tasks are being imported twice using different module paths, e.g. `myapp.tasks.periodic_task_one` and `myproj.myapp.periodic_task_one`?

**Comment by ekinertac** [comment]
haha yeah I meant `periodic_task` instead of scheduled. 
now i'm using `revoke_all` function for cancelling the current periodic tasks with:

```python
for task in huey._registry._periodic_tasks:
    revoke_all(task)
```

the tasks are still in the registry but they looks like not running. i'll deploy the code and let you know the results.

thanks a lot!

**Comment by coleifer** [comment]
So periodic tasks are kept in the local memory registry and when the scheduler sees that they're ready to run, it will enqueue them for execution.

I wonder now if part of the issue is that you're using greenlet workers. Greenlets cannot be preempted, so if you have a long running cpu-intensive task it can block everything else from running. You might consider switching to threads and using a smaller number of workers.

**Comment by coleifer** [comment]
Just a note that running `revoke_all()` will prevent them from running in the future as well. Do you have any logs you can share showing the double execution, as that might shed some light on the underlying cause. I still think its possible that they are being imported twice under two different module namespaces. Alternatively, the consumer was not actually shut down and you ended up with two running?

You can see what all tasks are sitting waiting to be executed by running `huey.pending()` and seeing what all is sitting waiting to be executed.

**Comment by ekinertac** [comment]
@coleifer sent the log file to your email since logs has some private stuff

**Comment by ekinertac** [comment]
> Just a note that running `revoke_all()` will prevent them from running in the future as well. 

yes the exact thing happened, after revoking the tasks they didn't run in the next cycle
