### ISSUE TITLE
Huey Duplication of Periodic Tasks

### ISSUE THREAD

**Issue by Natgho** [coleifer/huey#716]
Hello,

I have a scaled project with 4 pods running in K8s environment. Within the project, my periodic tasks are running over and over for each pod. I am looking for a solution to this situation. I tried using the lock_task function, but as far as I can see, this function is only written to prevent periodic functions from running at the same time. Ultimately, Huey uses these tasks over redis. Is there a feature to prevent periodic tasks from being duplicated? Or is this a known bug?

**Comment by coleifer** [comment]
You are presumably running 4x consumers. You will want to only run one consumer with "periodic tasks" enabled, and the other 3 with the "-n" or "--no-periodic" option.

**Comment by Natgho** [comment]
Sorry but my project is django project, there is no seperation for different settings under the django;
https://huey.readthedocs.io/en/latest/contrib.html#setting-things-up

The definitions are under the settings py;
![image](https://user-images.githubusercontent.com/6623948/221601597-9e37ca13-21c6-459f-9eeb-ee2da710b7d2.png)

**Comment by Natgho** [comment]
How can I define multiple settings for one django project because of this purpose?

**Comment by Natgho** [comment]
I will try it and let you know, during this time, please would you keep open this issue?

**Comment by coleifer** [comment]
No, I will not, since there is no fix I intend to apply.

**Comment by jedie** [comment]
> You are presumably running 4x consumers. You will want to only run one consumer with "periodic tasks" enabled, and the other 3 with the "-n" or "--no-periodic" option.

Hm. This is a limitation: If you have many, heavy Periodic Tasks, then only one consumer can process them?
Or is the idea, than only one consumer starts the "periodic tasks", but all active consumer can process them?

**Comment by jedie** [comment]
Sounds okay. But it will be a kind of a feature that Huey will deal with that problem, and choose automatically one of the consumer to enqueueing of the periodic tasks...

**Comment by Natgho** [comment]
I totally agree with @jedie.  Yes I will try to manually check this status.  But it already works in with huey redis.  Why don't you think of a feature that can handle consuming between tasks via redis? @coloifer

**Comment by Natgho** [comment]
@coleifer are you planning to add this feature?

**Comment by coleifer** [comment]
>Huey
>
>a lightweight alternative.

I'm not interested in implementing some form of leader election, failover, etc. I assume you realize that is implied by having huey "figure it out". Celery also looks like it requires you manually specify a single "beat" process for scheduling periodic tasks.

Most users run Huey on a single server with numerous workers, so the periodic task scheduling is integrated into the consumer. If you want to run Huey consumers across multiple servers that is absolutely supported and do-able, but you will need to ensure that only one consumer runs the periodic task scheduler. This is very easy: https://github.com/coleifer/huey/issues/716#issuecomment-1446547076
