### ISSUE TITLE
Does huey provide a method for passing messages between two workers?

### ISSUE THREAD

**Issue by wnark** [coleifer/huey#717]
I read the official wiki and GitHub issue. Huey doesn't seem to provide the officially recommended method for two workers to communicate. I tried tcp communication. Although it works, it seems that the communication speed cannot keep up with the speed of my message generation.
I don’t know how shared memory communication is. I searched all afternoon and found that there is really no way to communicate with common queues. After all, the queue created by A worker cannot be returned to B worker for use.

**Comment by coleifer** [comment]
Not sure how to advise.
