### ISSUE TITLE
How to correctly schedule a Pipeline task?

### ISSUE THREAD

**Issue by ChowDPa02k** [coleifer/huey#720]
I'm working on something like automatically generating grouping / pipeline tasks.
After reding the docs, when i was making a pipeline, found that when I use `.s()` method, it returns a `Task` instance, which cannot be scheduled.
When i schedule a task with `.schedule()` method, it returns a `Result` instance, which cannot be piped and enqueued.
And when i enqueue a pipeline, it returns a `ResultGroup` instance, which cannot be rescheduled.

After discovering, i tried to reschedule a pipeline like this way, but sometimes i found that the `.then()` tasks might not be executed.
Is there any elegant way to approach it?

```python
try:
    if trigger['type'] == IME:
        result = huey.enqueue(series)
    elif trigger['type'] == DELAY:
        result = huey.enqueue(series)
        for res in result:
            # Reschedule only the first task.
            # But i doubt that if the task being consumed fast enough (before the reschedule method called), 
            # the reschedule would not work
            res.reschedule(delay=trigger['value'])
            break
```
log in consumer:
```
[2023-03-08 16:07:30,209] WARNING:huey:Worker-1:Task executors.testFunction.handler: eb767388-36a5-4820-811b-934444c6d4fc 3 retries -> executors.fileInfoFetcher.handler: d2c758f1-66ec-4265-923c-58ac91773681 was revoked, not executing
WARNING:huey:Task executors.testFunction.handler: eb767388-36a5-4820-811b-934444c6d4fc 3 retries -> executors.fileInfoFetcher.handler: d2c758f1-66ec-4265-923c-58ac91773681 was revoked, not executing
[2023-03-08 16:07:30,210] INFO:huey:Worker-1:Added task 62d05202-2f24-48e4-a147-52d5d731eea5 to schedule, eta 2023-03-08 08:07:44.651581
INFO:huey:Added task 62d05202-2f24-48e4-a147-52d5d731eea5 to schedule, eta 2023-03-08 08:07:44.651581
[2023-03-08 16:07:46,320] INFO:huey:Worker-1:Executing executors.testFunction.handler: 62d05202-2f24-48e4-a147-52d5d731eea5 @2023-03-08 08:07:44.651581 3 retries
INFO:huey:Executing executors.testFunction.handler: 62d05202-2f24-48e4-a147-52d5d731eea5 @2023-03-08 08:07:44.651581 3 retries
{'expired': 30, 'hello': 'hi', 'calculate_sha1': False, 'database': {'index': 'index.db'}}
[2023-03-08 16:07:46,321] INFO:huey:Worker-1:executors.testFunction.handler: 62d05202-2f24-48e4-a147-52d5d731eea5 @2023-03-08 08:07:44.651581 3 retries executed in 0.000s
INFO:huey:executors.testFunction.handler: 62d05202-2f24-48e4-a147-52d5d731eea5 @2023-03-08 08:07:44.651581 3 retries executed in 0.000s
```
It seems that when the first task was revoked and rescheduled, the after tasks will be removed.

**Comment by coleifer** [comment]
Unfortunately, at present this is not well-supported. For a use-case like this, my recommendation would be to implement the pipeline logic yourself and have a parent-task that calls the appropriate subtasks.

**Comment by coleifer** [comment]
The following commit hopefully makes things a little bit easier by adding support for `delay`/`eta` to the `.s()` (and concomitantly `.then()`) method. e01f71bbcf7da9be0daaacf9e3ce065756f9311a

**Comment by ChowDPa02k** [comment]
> The following commit hopefully makes things a little bit easier by adding support for `delay`/`eta` to the `.s()` (and concomitantly `.then()`) method. [e01f71b](https://github.com/coleifer/huey/commit/e01f71bbcf7da9be0daaacf9e3ce065756f9311a)

Thank you soooooo much, the update works well in my business code 🥰
