### ISSUE TITLE
How to revoke/cancel only already scheduled instances of a given task ?

### ISSUE THREAD

**Issue by StitiFatah** [coleifer/huey#721]
For example if I do : 
```
res1 = add.schedule((1, 2), delay=60)
res2 = add.schedule((1,2),delay=60)
```
and want to revoke them with  `add.revoke()` It'll not only cancel them but also prevent me of running any future `res3.add.schedule((1,2),delay=60)` unless  using `add.restore()`, however it'll also restore `res1` and `res2` if their scheduled time hasn't yet expired. 

How could I only cancel already called instances of  the `add` task and not subsequent ones ?

Thanks in advance. 

**Edit** : I figured out I could just check all scheduled instances of a certain name using the scheduled method and then revoke them by id like that : 

```python

from huey.contrib.djhuey import HUEY

for instance in HUEY.scheduled():
    if  instance.name == "add":
        HUEY.revoke_by_id(instance.id)
```

I don't close it in case there is an other way to answer the question.

**Comment by coleifer** [comment]
You would call the `revoke` method on the result handle, e.g.

```python
res1 = add.schedule((1, 2), delay=60)
res1.revoke()
```

**Comment by coleifer** [comment]
https://huey.readthedocs.io/en/latest/api.html#Result.revoke

**Comment by StitiFatah** [comment]
> You would call the `revoke` method on the result handle, e.g.
> 
> ```python
> res1 = add.schedule((1, 2), delay=60)
> res1.revoke()
> ```

Yes I've seen that on the docs, it's just above the `revoke all instances of a given task` the  but in my case don't directly have access to those individual instances and wanted to revoke all already scheduled instances
