### ISSUE TITLE
"Enqueueing periodic task" but not running

### ISSUE THREAD

**Issue by Natgho** [coleifer/huey#722]
I have some tasks (checks something every minute), but this tasks not running every minute;
![image](https://user-images.githubusercontent.com/6623948/225006325-839d817b-26af-4091-8c3f-2e60d98b6d01.png)
![periodic](https://user-images.githubusercontent.com/6623948/225006434-c0dfcda8-487e-4b2e-bc54-2e9aa3047071.png)

I written sample function for checking, it has same situation;
![image](https://user-images.githubusercontent.com/6623948/225006661-492c8df7-fc8e-4b9d-85c9-3e08436d2ec9.png)

**Comment by coleifer** [comment]
I have no idea what to tell you -- you can try running the sample Django app bundled with the Huey source code. It works just fine for me. I added the following to the example `tasks.py`:

```python
@db_periodic_task(crontab(minute='*'))
def every_minute():
    tprint('This task runs every minute.', 35)
```

Here is some example consumer output:

```
08:46:27 Enqueueing periodic task djangoex.test_app.tasks.every_minute: 5e928070-1489-4e14-937a-a5881c7378e3.
08:46:27 Executing djangoex.test_app.tasks.every_minute: 5e928070-1489-4e14-937a-a5881c7378e3
This task runs every minute.
08:46:27 djangoex.test_app.tasks.every_minute: 5e928070-1489-4e14-937a-a5881c7378e3 executed in 0.036s
08:46:44 Executing djangoex.test_app.tasks.add: 678a8977-9571-4b8e-9323-9596e546dabb
08:46:44 djangoex.test_app.tasks.add: 678a8977-9571-4b8e-9323-9596e546dabb executed in 0.000s
08:47:27 Enqueueing periodic task djangoex.test_app.tasks.every_minute: ae929735-f448-4258-b433-a9886746a3b9.
08:47:27 Executing djangoex.test_app.tasks.every_minute: ae929735-f448-4258-b433-a9886746a3b9
This task runs every minute.
08:47:27 djangoex.test_app.tasks.every_minute: ae929735-f448-4258-b433-a9886746a3b9 executed in 0.001s
```

You can clearly see the task is being run every minute (also the regular tasks are working).

**Comment by Natgho** [comment]
I changed the code simple print, result is the same;
![image](https://user-images.githubusercontent.com/6623948/225025406-8fab230b-07b6-41fb-9f3f-0c6a9dfdb39e.png)
![image](https://user-images.githubusercontent.com/6623948/225025503-8470494f-02d0-431e-ba6d-df3cdef33b22.png)

**Comment by coleifer** [comment]
All I can tell you wish assurance is that huey is not fundamentally broken in some way and that the issue is in your code or configuration somewhere.

**Comment by Natgho** [comment]
Hello,

I finally solved the problem; I'm sharing it in case someone else has it;

If more than one Huey is using the same Redis, and Django is connecting as a connection_pool, the workers are mixing with each other. And the workers of 2 different projects are getting each other's tasks.
