### ISSUE TITLE
Support for blue/green deployments?

### ISSUE THREAD

**Issue by astec-dsa** [coleifer/huey#723]
I have demand in my project to implement blue/green deployment for the application which is using Huey. Huey supports i.e. SQLite and Redis, we're considering usage of both (SQLite in short-term, Redis in long-term).
For RabbitMQ there's "federation plugin" in place for blue/green deployment purpose - https://www.rabbitmq.com/blue-green-upgrade.html

But for SQLite or Redis I haven't found anything like this.

Would Huey support the case if we'll for example do "migrate" on 2 Redis queues? https://redis.io/commands/migrate/

In my team we have to decide which way to go:
- have 2 separate queues and "synchronize" them during switch green->blue or blue->green
- have 1 queue but then set "color" to tasks
- any other idea?

Does Huey support anything or this, so we won't need any custom solution? I'm afraid that having 2 separate queues and trying to "migrate" data from one into another might not work due to storage of "result" which might not be pulled by new software version or it might be pulled too late. So we might need to customize migration...

Would be nice if you could give us some advice :)

**Comment by coleifer** [comment]
This is not well supported by Huey out of the box. I think typically what people do is deploy with a new queue name and let the "old" queue consumer run until the queue is drained (typically with periodic tasks disabled). In this way your backlogged tasks can finish running on the old code. If you have a lot of scheduled tasks you can copy them over to the new queue using Huey's apis for listing all scheduled tasks.

Beyond this it's really up to you how you want to proceed.
