### ISSUE TITLE
allow custom auto-discovery modules to the Django extension

### ISSUE THREAD

**Issue by giancastro** [coleifer/huey#727]
The documentation mentions at https://huey.readthedocs.io/en/latest/contrib.html#django the Django extension provides auto-discovery of `tasks.py` modules to simplify task importing.

Considering bigger projects, I want to be able to set custom modules that automatically get discovered. For example, instead of one module `tasks.py`, I want to split it into multiple modules e.g. `core.py` and `maintenance.py`.

**Comment by coleifer** [comment]
Then you can just `import core` and `import maintenance` inside your `tasks.py`.

**Comment by giancastro** [comment]
https://github.com/coleifer/huey/blob/eacdd8543095cd021a2a91c35762b21dbe6afc6c/huey/contrib/djhuey/management/commands/run_huey.py#L77

`django.utils.module_loading.autodiscover_modules` allows multiple modules, e.g. `autodiscover_modules("core", "maintenance")`.

**Comment by coleifer** [comment]
Huey sticks to the convention of using `tasks` and you may (inside your tasks.py) import any additional modules. You can suppress the linting errors if it is an issue for you, create your own management command, run `autodiscover_modules` inside your own tasks, or any number of other approaches.
