### ISSUE TITLE
Killed consumer process not restarted

### ISSUE THREAD

**Issue by mexezero** [coleifer/huey#728]
If a process type worker is killed via SIGKILL (i.e. from Linux OOM killer) the call to `proc.is_alive()` in the health check still returns true and the process is never restarted. Note that currently the process is left as a zombie process, but even if SIGCHLD is ignored by the parent, the process would no longer exist but `proc.is_alive()` would still return true.

This can be easily reproduced in linux by running:
1. `huey_consumer.py <test app> -v -k process`
2. `ps -aux | grep huey_consumer` and find the PID for a worker process
3. `kill -9 <pid>`
4. `ps -aux | grep huey_consumer` and notice the zombie process
5. View huey.consumer logs and notice the health check doesn't do anything

Adding a `proc.join()` call with a very small timeout is one way to fix this, there may be others.

**Comment by coleifer** [comment]
While I believe you, I cannot replicate on my linux machine running python 3.7.3 or 3.11.0. I fired up the "simple" example consumer with the following options:

```
# Use 4 worker processes, simple + verbose logging.
python ../../huey/bin/huey_consumer.py main.huey \
  --workers=4 \
  -k process \
  -S \
  -v
```

This printed the list of worker processes, one of which I killed:

```
$ kill -9 3137
```

The following is the relevant snippet from the consumer logs:

```
20:27:54 Sleeping for 0.9978511869999238                                                  
20:27:54 Checking worker health.                                                          
20:27:54 Worker 2 died, restarting.                                                       
20:27:54 Scheduler is up and running.                                                     
20:27:54 calling startup hook "startup_hook"                                              
process 3154, thread 140182910474048 - startup hook
```

This worked reliably when I killed workers repeatedly. When I shut down the consumer all 4 workers were still running and successfully executed their shutdown hooks.

I also tried an even smaller example, which also seems to work just fine:

```
import multiprocessing as mp
import os
import signal
import time


def run():
    while True:
        print('child is alive')
        time.sleep(1)

p = mp.Process(target=run)
p.daemon = True
p.start()

time.sleep(1)
pid = p.pid
print(pid)

print('kill:', os.kill(pid, signal.SIGKILL))

time.sleep(0.1)  # Give a little time for process to be cleaned-up.
print('is alive?', p.is_alive())
```

Output is:

```
child is alive
killing 3974
is alive? False
```

**Comment by mexezero** [comment]
No problem thanks for investigating. Must be something specific to my environment. I'll just monkeypatch if I can't isolate it.

**Comment by Scherlac** [comment]
What happens with an on going task? I don't see any verification here:

https://github.com/coleifer/huey/blob/master/huey/consumer.py#L466

We often see task remain in 'In Progress' state.

**Comment by Scherlac** [comment]
At the following point we would need to store information on task id an worker id to ensure recovery from killed worker situation:

https://github.com/coleifer/huey/blob/aeaa36e5cc11381830d2ea8c01b6ac63335b357e/huey/consumer.py#L110
