### ISSUE TITLE
Is there any possibility to make signal functions communicate with other python scripts via Queue / Pipe?

### ISSUE THREAD

**Issue by ChowDPa02k** [coleifer/huey#730]
I made an signal handler to handle SIGNAL_COMPLETE, check its function name, if the name was 'something', then send its result to an PySide.Signal, call a ui Window to user.

Found that i cannot pass anything outside into the @huey.signal() decorated method, such as Qt.Signal. So I tried to make a Queue, then write a Queue handler in my main.py:

```python
# manager.py
from config import huey, sig

@huey.signal(SIGNAL_COMPLETE)
def success_handler(signal, task, *args, **kwargs):
    sig.put(task.id)
    print('hello, world')

huey._signal.connect(success_handler)
```

```python
# config.py
from huey import SqliteHuey

huey = SqliteHuey('huey.db')

IME = 'IMMEDIATE'
DELAY = 'DELAY'
ETA = 'ETA'

from multiprocessing import Process, Queue
sig = Queue()
```

```python
# main.py
from config import sig

def f_signal_handler(q: multiprocessing.Queue):
    while True:
        msg = q.get(block=True)
        logger.debug('Got message: {}'.format(msg))
        if msg['type'] == 'cd':
            observer.unschedule_all()
            observer.schedule(file_handler, msg['path'], recursive=True)
            observer.schedule(watchdog_log_handler, msg['path'], recursive=True)
        elif msg['type'] == 'exit':
            break
        else:
            # Here is designed to call UI using msg
            logger.debug(msg)

......

if __name__ == '__main__':
    # Init signal handler
    signal_handler = f_signal_handler
    t = threading.Thread(target=signal_handler, args=(sig,))
    t.start()
```

Run consumer by `huey_consumer manager.huey`

Turns out that, the Queue can recieve other signals I send in main and other modules, but consumer seems to send nothing to Queue. And btw, I can see 'hello world' in stdout, so the signal function works.

I know it's probably not what huey.signal() was desiged for, if there's no other way to do so, I just plan to go Socket

**Comment by coleifer** [comment]
I cannot advise. Signals work but run in the context of the consumer process so that may be your issue. Might be worth looking into qts functionality for running everything (including your tasks) if this is a desktop type application. Or when you have cpu-intensive work to just use multiprocessing. I'm thinking Huey is probably a (very) bad choice here.

**Comment by ChowDPa02k** [comment]
I just went Socket. It's the most suitabale way to communicate between my code and consumer. Another Question, how to get task result with the `task` instance received in @huey.signal method? Tried `huey.result(task.id)`, it will block forever (when blocking=True) or just return None 😢
