### ISSUE TITLE
SIGNAL_REVOKED is sent before the task enters the “executing” state, can i get any signal at the time when i revoke a task?

### ISSUE THREAD

**Issue by ChowDPa02k** [coleifer/huey#731]
I just found the SIGNAL_REVOKED was sent when the task reach its scheduled time.

For example, if i have a task that scheduled 24h delay, i will got my own SIGNAL_REVOKED handler function triggered tomorrow, thats not my need

I want to have a signal that emitted when i call `task.revoke()` or `huey.revoke_by_id(task.id)`, to clean something immediately, is that any idea?

**Comment by coleifer** [comment]
That's not how it works - we only check if a task was revoked or not when we are ready to actually execute it (as it may be restored in the meantime, etc).
