### ISSUE TITLE
Negative retries causes infinite retries... ¿hidden feature?

### ISSUE THREAD

**Issue by juancerezo** [coleifer/huey#732]
Hello,

Trying to get a task to retry infinite times. I tried setting the retries argument to -1. Huey replanned the task and indicated that there were -2 retries left. It has been retrying infinitely, decrementing the number of retries as a negative number.

```python3
@huey.task(retries=-1, retry_delay=30)
@huey.lock_task("my-lock")
def my_infinite_retries_task():
    # do stuff
```

I found this very useful. I haven't seen it documented, can you include it as functionality in this way or is it preferred to control it with a flag? 

Best Regards

**Comment by coleifer** [comment]
Infinite retries seems, to me, never something advisable. While it works, it is not guaranteed to work in future versions.
