### ISSUE TITLE
Tasks states are not maintained in case the worker is kill by the running task.  

### ISSUE THREAD

**Issue by Scherlac** [coleifer/huey#733]
As mentioned in the issue bellow, the tasks states are not maintained in case the worker is kill by the running task.  

https://github.com/coleifer/huey/issues/728

In case we see an error log similar to the following, the currently running task is lost:

```log
20:27:54 Sleeping for 0.9978511869999238                                                  
20:27:54 Checking worker health.                                                          
20:27:54 Worker 2 died, restarting.                                                       
20:27:54 Scheduler is up and running.                                                     
``` 
The following code sections clearly shows this behavior:

https://github.com/coleifer/huey/blob/cc439d55890033a32443e79a2cd483979c2a672c/huey/consumer.py#L479

https://github.com/coleifer/huey/blob/cc439d55890033a32443e79a2cd483979c2a672c/huey/consumer.py#L455

It is also clear that the `dequeue` and `execute` methods do not record the worker `id` the execution is scheduled:

https://github.com/coleifer/huey/blob/cc439d55890033a32443e79a2cd483979c2a672c/huey/consumer.py#L110

https://github.com/coleifer/huey/blob/cc439d55890033a32443e79a2cd483979c2a672c/huey/consumer.py#L110

I do not expect this issue will be solved, but should at least emphasized in the documentation.

**Comment by coleifer** [comment]
If the OOM killer is your issue, then you have bigger problems than huey. Simply retrying the task is unlikely to be of any help. At any rate, Huey is an at-most once task queue with explicit retries. An at-least-once task queue requires a concept of a visibility timeout (e.g. SQS/beanstalk) and an explicit ACK from the worker when the task is finished. We do not use this task queueing design out of a desire for simplicity. My opinion is that if you see OOM errors in your tasks, it is a sign that you need to buy more memory or redesign your tasks.

**Comment by Scherlac** [comment]
I have nothing to do with the code inside the task, I'm only responsible for the back-end and infrastructure to schedule those tasks and give for the end user a clear information about the test result. My end users are currently unhappy as they see 'In Progress' task in the list.

**Comment by coleifer** [comment]
Where are you pulling this "In Progress" from?

**Comment by Scherlac** [comment]
That is the last state before we lose the task that is killed.

**Comment by coleifer** [comment]
Where is that state coming from?

**Comment by coleifer** [comment]
You still have not answered my original question. Answer it or don't, it's up to you, but quit wasting my time.

**Comment by Scherlac** [comment]
I don’t intend to waste anyone’s time. That’s why I suggest we document this behavior of killed worker/task and emphasize it. As previously mentioned, the `In Progress` status is a derived one that we maintain in our backend service. It represents the state of tasks after the `SIGNAL_EXECUTING` signal. If the worker dies, no signal is sent related to the specific task that was running on the worker. Therefore, our backend cannot record any updates.
