### ISSUE TITLE
Clarify on_commit_task vs Django on_commit

### ISSUE THREAD

**Issue by spapas** [coleifer/huey#735]
Django has the on_commit (https://docs.djangoproject.com/en/4.2/topics/db/transactions/#django.db.transaction.on_commit) method that is used when we want to run something after the current tx commits.  This is the usual method in Django to make sure that an async task won't be started until the tx commits. 

Can you clarify what's the difference between on_commit and the  `on_commit_task` decorator (https://github.com/coleifer/huey/blob/fa999de41273eaaa92a203efcad0c5260d0e2124/huey/contrib/djhuey/__init__.py#L159) ? `on_commit_task` seems to actually use transaction.on_commit internally.

Thank you

**Comment by coleifer** [comment]
How would you write a Huey task that accepts arbitrary arguments, and which also only enqueues itself after the current transaction is committed, using Django's `transaction.on_commit`? Huey tasks are enqueued the moment they are called, so you would probably have to make a one-off lambda to actually call the `@task`-decorated function on commit, and close over the arguments. Furthermore the `on_commit` prevents you accessing the return value from the task (the result handle).

So unless I'm misunderstanding something, I don't know how you would *comfortably* use Django's `transaction.on_commit` with Huey.

**Comment by spapas** [comment]
To asnwer your first question, I would call it like you propose, using a lambda. For example let's suppose we've got a huey task:

```
@db_task
def work_on_item(item_id):
    Item.objects.get(id=item_id).do_something()
```

And a view that crates a task and works on it:

```
def create_and_operate_item(request):
    item = Item.objects.create()
    transaction.on_commit(lambda: work_on_item(item.id))
    render({})
```

So, my understanding is that the `on_commit_task` 
* makes sure that the the decorated task will be called after the transaction finishes even if you don't use on_commit in your view
* gives you access to the value from the task

About *comfortably*  using Django's on_commit I think using the lambda is common practice.

**Comment by spapas** [comment]
Exactly, that clarifies everything thank you so much!
