### ISSUE TITLE
Can worker create a pid file ?

### ISSUE THREAD

**Issue by spapas** [coleifer/huey#736]
Hello I'd like my huey worker to create a pid file when run so then I can use it to restart it using something like `cat /home/serafeim/huey-worker.pid | xargs kill -HUP` ; is this possible ?

I know that I could use something like `pgrep -f run_huey` however using the PID is preferable for me.

Thank you

**Comment by spapas** [comment]
Also if you've got a better recommendation on how to restart the worker when the app is changed please share, I'm using systemd to start it.

**Comment by coleifer** [comment]
Why wouldn't you use `systemctl restart`?

I personally use supervisord but both of these tools make it unnecessary to use a pidfile. Just tell the process manager to restart your service.

Docs https://huey.readthedocs.io/en/latest/consumer.html?highlight=supervisord#supervisord-and-systemd

**Comment by spapas** [comment]
Restarting through systemctl will need to use sudo. I want to restart the app without root access to the server. 

Maybe consider adding an optional pid file? This should be similar to the celery workers pid https://docs.celeryq.dev/en/stable/userguide/workers.html#restarting-the-worker

Thank you
