### ISSUE TITLE
Clarify `storage` vs `get_storage`

### ISSUE THREAD

**Issue by spapas** [coleifer/huey#737]
The `get_storage` method of Huey seems to *create* a new storage object:

```
from huey.contrib.djhuey import HUEY as huey

huey.storage == huey.get_storage()
> False

s1 = huey.get_storage()
>  <huey.storage.RedisStorage at 0x1aba9f0ca30>

s2 = huey.get_storage()
> <huey.storage.RedisStorage at 0x1aba9f0dd80>

s1 == s2
> False
```

I would expect it to create the storage if it doesn't exist or return the current one. Also notice that here https://github.com/coleifer/huey/blob/fa999de41273eaaa92a203efcad0c5260d0e2124/docs/django.rst?plain=1#L280 it says: 

`# E.g., get the underlying Storage instance.  storage = huey.get_storage()`

Taking a peek at the get_storage confirms that a new object is created: https://github.com/coleifer/huey/blob/fa999de41273eaaa92a203efcad0c5260d0e2124/huey/api.py#L140

I understand that this may seem like a very small and irrelevant thing however it bite me because I called `huey.get_storage()` from a django (instead of calling `huey.storage`) view and that returned a redis connection *with default settings* (localhost/6379) ; I use different settings instead) so it threw error that it couldn't connect. 

I'm really not sure why it didn't initialize the redis connection properly using the django settings.

**Comment by coleifer** [comment]
That snippet was probably ill-chosen on my part because the intent of that section was to merely show how you can access methods and properties on the `huey` instance that are not exposed directly through `djhuey`. I've updated the doc.

At any rate, yes you should use `huey.storage` if you need it.
