### ISSUE TITLE
Using Huey in Django

### ISSUE THREAD

**Issue by edmundrotimi** [coleifer/huey#739]
I am using the Huey package for task queues in Django. To use Greenlet as a worker, the documentation says, "the only way is to apply Gevent monkey-patch to create a custom bootstrap script that mimics the functionality of manage.py".

    #!/usr/bin/env python
    import os
    import sys

    # Apply monkey-patch if we are running the huey consumer.
    if 'run_huey' in sys.argv:
        from gevent import monkey
        monkey.patch_all()

    if __name__ == "__main__":
        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "conf")
        from django.core.management import execute_from_command_line
        execute_from_command_line(sys.argv)

How can I apply this patch in Django.

**Comment by coleifer** [comment]
Just copy it into a file in your project named `gevent_manage.py` or something and use it.
