### ISSUE TITLE
task priorities, sqlite, and immediate mode

### ISSUE THREAD

**Issue by ChrisJefferson** [coleifer/huey#741]
There are a couple of sentences in the docs about sqlite and priorities, namely:

"Task prioritization is fully supported by [SqliteHuey](https://huey.readthedocs.io/en/latest/api.html#SqliteHuey) and the in-memory storage layer used when [Immediate mode](https://huey.readthedocs.io/en/latest/guide.html#immediate) is enabled"

"[SqliteHuey](https://huey.readthedocs.io/en/latest/api.html#SqliteHuey) and the in-memory storage used when immediate-mode is enabled have full support for task priorities."

I wasn't sure if this meant

(Sqlite and the in-memory stoage) with immediate mode, or:

Sqlite and (the in-memory storage with immediate mode)

I now believe (and I might be wrong!) that sqlite always supports priority. In the case perhaps change to something like the following, to clarify? (there is possibly shorter things which are clear, but seeing as redis is already always discussed seperately, seems clearest to me to just also seperate out sqlite and the in-memory storage?)

"Task prioritization is fully supported by [SqliteHuey](https://huey.readthedocs.io/en/latest/api.html#SqliteHuey). Task priorization is also fully supported by the in-memory storage layer used when [Immediate mode](https://huey.readthedocs.io/en/latest/guide.html#immediate) is enabled"

and:

"* [SqliteHuey](https://huey.readthedocs.io/en/latest/api.html#SqliteHuey) supports task priorities.
* The in-memory storage supports task priorities when immediate-mode is enabled."

**Comment by coleifer** [comment]
Sqlite always supports priorities under all circumstances.

As does the built-in in-memory mode used for testing.

I will fix the wording thanks for your question.

**Comment by ChrisJefferson** [comment]
Thank you, this completely clarifies the text for me.
