### ISSUE TITLE
About SIGINT, SIGTERM and SIGKILL

### ISSUE THREAD

**Issue by abannura** [coleifer/huey#743]
Hi, not really an issue, but rather a question/doubt about how these signals work in the context of Huey.

I've been reading the docs and other issues, and my current understanding is:
1. Outside of Huey:
  * SIGINT/SIGTERM are used to request a process termination, thus they are mechanisms through which one can implement a graceful shutdown.
  * SIGKILL on the other hand, terminates it on the spot, leaving no space for cleanup.
2. Within Huey:
  * SIGINT is used to request process termination, which allows for extra graceful shutdown (i.e. workers are allowed to finish the tasks they are working on, but no new tasks will be started).
  * SIGTERM is used to "force" the termination of the workers (i.e tasks that are currently executing will end abruptly, and of course, no new tasks will be started). I say "force" (between quotes) because it's not as brute as the SIGKILL signal, because there is some sort of "graceful" shutdown. More concretely, you can execute some cleanup actions, like requeuing the task in order to retry it later. One would do this by adding a handler to the `SIGNAL_INTERRUPTED` Huey signal (do not confuse with OS signals).
  * SIGKILL is not handled by Huey (and can't be by definition of that signal). Usually one would expect a SIGKILL coming after a SIGTERM, therefore, whatever cleanup task you do within your `SIGNAL_INTERRUPTED` handler, you better make sure it's fast.

Note: I only mentioned what happens with the worker processes/threads, and left aside the main process and the scheduler process (which are also part of the Huey consumer), because for now I'm only concerned about the workers.

Having said that, my question is: is my understanding correct? Particularly around using a `SIGNAL_INTERRUPTED` handler to requeue a task that was abruptly ended.

Note: I'm concerned about what would happend in the context of a deployment, where the cloud provider I use sends first a SIGTERM and then a SIGKILL (30 seconds later). I don't mind that the running tasks aren't able to finish in that same execution, so I don't really need to capture the SIGTERM sent by the OS, and transform it into a SIGINT before passing it down to Huey. For me, ending the tasks abruptly, but requeuing them for a later retry is enough.

Let me know what you think, and thanks for building such a great product!

**Comment by coleifer** [comment]
Huey:

* SIGINT (e.g. Ctrl+C) performs graceful shutdown. Any currently-executing tasks will finish before the consumer stops.
* SIGTERM will shutdown immediately and send the huey `SIGNAL_INTERRUPTED` for any tasks that were interrupted.
* SIGKILL immediately kills the process.

SIGKILL may be sent by a process manager if the process does not exit quickly enough after receiving a SIGTERM - depends on how you have it configured.

>Having said that, my question is: is my understanding correct? Particularly around using a SIGNAL_INTERRUPTED handler to requeue a task that was abruptly ended.

Yes, that's pretty much the main use-case for the huey signal SIGNAL_INTERRUPTED.

It's probably ideal to have your process manager instead send a `SIGINT` if you want to avoid losing tasks that are running, but with 30s you should have tons of time to re-enqueue any tasks that are interrupted after a `SIGTERM` is sent.

**Comment by abannura** [comment]
> Yes, that's pretty much the main use-case for the huey signal SIGNAL_INTERRUPTED.

Awesome! And thank you very much for the quick reply.

> It's probably ideal to have your process manager instead send a SIGINT if you want to avoid losing tasks that are running, but with 30s you should have tons of time to re-enqueue any tasks that are interrupted after a SIGTERM is sent.

In my case, these are long running tasks (~5 minutes each). So, even if I changed the `SIGTERM` signal sent by the OS to a `SIGINT`, the task may not have enough time to finish before the OS sends the deadly `SIGKILL`.

Additionally, its worth mentioning that I have no control over those 30 seconds I mentioned previously, as that timeout is managed by the cloud provider. This means that increasing that timeout to a certain value where any task can finish within it, is not feasible for me.

Anyhow, thanks again for your response!

**Comment by abannura** [comment]
Hi @coleifer, sorry for bringing this up again, but I have additional questions that I'd hope you could help me with.

I looked into the code and realized what you meant when you said that the scheduler thread and the worker thread were "shutdown immediately" upon receiving a SIGTERM, and that "to avoid losing tasks that are running" I should change the SIGTERM signal for a SIGINT signal.

My main issue with changing the SIGTERM for a SIGINT, is that workers that are running a task will not be stopped. As I mentioned before, my tasks are long running tasks that take ~5 minutes to execute.

Having said that, is there an alternative that mixes both approaches? More concretely, one that doesn't "shutdown immediately" the threads, allowing them to perform cleaning actions such as those added through the `on_shutdown` hook, but also abruptly stops the execution of the tasks (and emits the corresponding `SIGNAL_INTERRUPTED` for each task).

What do you think about that behavior? 

------------------------------------------
Notes for other people that may read this:
- The "immediate shut down" of the scheduler thread can occur after the thread has removed tasks from the schedule, but before it has enqueued them. Therefore, you may lose these scheduled tasks.
- The "immediate shut down" of the worker threads can occur after the thread has dequeued a task, but before it has added it to the `huey._tasks_in_flight` set. Therefore, you will not receive a `SIGNAL_INTERRUPTED` for these tasks.

This behavior is consistent with the fact that Huey is an "at most once" queue, not an "at least once" queue ([relevant issue](https://github.com/coleifer/huey/issues/733#issuecomment-1525932810)).

**Comment by coleifer** [comment]
The `on_shutdown` hooks are called by the worker processes themselves and are intended for clean-up actions within the worker during a graceful shutdown, [see doc](https://huey.readthedocs.io/en/latest/api.html#Huey.on_shutdown). An example might be a connection pool within the context of the worker process, to be used by tasks executed on that worker. These hooks are not called or used when a shutdown via `SIGTERM` is requested.

If you wish to re-enqueue a task that is interrupted, it should be done with the huey `SIGNAL_INTERRUPTED`. Yes there is a possibility that a task could be lost in the brief window between schedule -> queue or queue -> in flight (executing), and yes this is a consequence of the at-most-once design.

This is why I recommend that people use the graceful shutdown.

I don't believe there's much to suggest other than:

1. Use huey's `SIGNAL_INTERRUPTED` to re-enqueue interrupted tasks
2. Break your tasks into smaller pieces.
3. Wrap your consumer with a parent/wrapper script that traps `SIGTERM` and, when it is received, send the wrapped consumer a SIGINT and allows up to (say) 25s for it to terminate before sending a SIGTERM.
4. Add your own storage engine/layer that provides better guarantees.
5. Switch to an at-least-once tool.

Are these 5 minute tasks triggered by an external event of some kind, or do they run on a predictable schedule? You may be better off using a different tool if the latter.

**Comment by abannura** [comment]
> Are these 5 minute tasks triggered by an external event of some kind, or do they run on a predictable schedule?
The former, basically an HTTP request from a UI.

And, thanks for your input! I was actually thinking of a very similar approach to what you suggest. It's always nice to have some sort of validation that what one is thinking makes sense to others, so I really appreciate it.

-----------------------------------------
Summary of the suggested approach (in case someone else reads this):
1. Wrap consumer with a parent script that traps `SIGTERM`, sends the consumer a `SIGINT` and waits `X` seconds for it to terminate before sending a `SIGTERM`. `X` should leave enough time for the consumer to shutdown after it receives the `SIGTERM`, considering that in 30s the container will receive a `SIGKILL` (from the cloud provider). That's why `@coleifer` used 25s as an example, which would leave 5s to the consumer to shutdown after the `SIGTERM`.
2. If all tasks were able to finish within the interval defined by `X`, then we are all good. Otherwise some tasks will be terminated abruptly. In order to avoid losing those jobs, it's necessary to setup a handler for Huey `SIGNAL_INTERRUPTED`. This signal will be called for every task that gets interrupted, and inside the handler we should re-schedule/re-enqueue the task.
3. When the Huey consumer is forced to stopped (vía SIGTERM), it will not perform shutdown hooks. This will happen when a running task didn't finish within the interval defined by `X`. This means that, if you are using shutdown hooks to perform cleaning operations, such as closing db connections, these connections will be left unclosed (on the db server side). One way to handle this is to have the db server reap inactive connections after some time.
4. Note that by giving some time to the Huey consumer to shutdown gracefully, we are eliminating the risk of it shutting down during critical windows such as the mentioned before (i.e. scheduler pops tasks, but didn't have time to enqueue them, or worker dequeues tasks but didn't have time to add it to the `_tasks_in_flight` set). Therefore, there shouldn't be any lost of tasks due to the reasons aforementioned.

Having said that, Huey implements an "at most once" approach, so it's always possible that something out of what's controllable fails, and that tasks are lost.

**Comment by MattExact** [comment]
@abannura one way to handle this is to alter the behaviour of `_handle_stop_signal` and `stop` to stop gracefully with a timeout on a `SIGTERM`.
See the snippet below for an example.
Note that you'd still need a `SIGNAL_INTERRUPTED` handler for re-queuing tasks that don't complete.

```python
class GracefulTerminationConsumer(Consumer):
    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self._graceful_timeout = None

    def _handle_stop_signal(
        self,
        sig_num: Any,
        frame: Any,
    ):
        """
        Handles SIGTERM gracefully.
        The consumer blocks until the workers finish executing their tasks,
        for at most `SIG_TERM_TIMEOUT` seconds.
        If the workers are not finished, the workers are forcefully stopped.
        """
        self._graceful_timeout = SIG_TERM_TIMEOUT
        super()._handle_stop_signal(sig_num, frame)

    def stop(self, graceful: bool = False):
        if self._graceful_timeout is None:
            super().stop(graceful)
        else:
            self._stop_gracefully_with_timeout(self._graceful_timeout)

    def _stop_gracefully_with_timeout(self, timeout_delay: int):
        """
        Blocks the consumer while shutting down workers for at most `timeout_delay` seconds.
        """
        self.stop_flag.set()
        self._logger.info(
            f"Shutting down gracefully with {timeout_delay} second timeout..."
        )
        processes = [
            self.scheduler,
            *(worker_process for _, worker_process in self.worker_threads),
        ]

        # Non-blocking shut down of all processes.
        for process in processes:
            process.join(timeout=0)

        elapsed_seconds = 0
        start_time = time.monotonic()
        while elapsed_seconds < timeout_delay:
            if all(not self.environment.is_alive(p) for p in processes):
                # Exit loop if all processes have successfully shut down.
                self._logger.info("All workers have stopped gracefully.")
                break
            time.sleep(0.1)
            elapsed_seconds = time.monotonic() - start_time
        else:
            self._logger.info("Graceful termination timed out!")
```

@coleifer not sure how open you are to changing how `SIGTERM` is handled to something similar to this?

PS: If you're running your consumers as part of something like an autoscaling group, another thing that could help is tracking the running tasks on your instances and creating a custom termination policy to only terminate instances not running any tasks.
