### ISSUE TITLE
About "extra" threads within the huey_consumer.py process

### ISSUE THREAD

**Issue by abannura** [coleifer/huey#744]
Hi! Again, not an issue, but a question/doubt. In order to understand better what is Huey doing in the back, I ran `pstree` and got the following output:
```
huey_consumer.py───6*[{huey_consumer.py}]
```
What I don't understand is where do the 6 threads come from?

I'm running only one worker (of type "thread"), and I know that there should be one thread for the "main consumer thread" and another for the scheduler. So 3 in total. Where do the other 3 come from?

I looked in the code but couldn't find an answer :/

**Comment by coleifer** [comment]
I'm sure those are coming from your application or something else. Running the barebones consumer from the "examples/simple" directory with 1 worker thread, I get the following:

```
$ ps -o pid,nlwp,args -p $(pgrep -f huey)
  PID NLWP COMMAND
10163    3 python ../../huey/bin/huey_consumer.py main.huey --workers=1 -k thread -C -S
```

Number LightWeight Processes (threads): 3 (main, scheduler, worker).

When I switch the number of workers to 4 threads I see 6 (main, scheduler, 4x worker)
```

**Comment by abannura** [comment]
OK, I'll keep looking into it. Thanks for the quick reply.
