### ISSUE TITLE
djhuey: move autodiscovery into AppConfig

### ISSUE THREAD

**Issue by adamchainz** [coleifer/huey#747]
I'm working on a Django project that has a custom web view for inspecting the status of the Huey queue. It sometimes triggers the `HueyException: ... not found in TaskRegistry` exception deserializing tasks with the `pending()` method.

It seems this is because the Django app's `tasks` submodule hasn't been imported in the web process. The task is only triggered by management commands, so a normal web startup doesn't import the tasks module, nor does it trigger djhuey's autodiscovery in `run_huey`.

I propose we move the autodiscovery into a `huey.contrib.djhuey.apps` module, inside a Django [`AppConfig.ready()`](https://docs.djangoproject.com/en/4.2/ref/applications/#django.apps.AppConfig.ready). This way the autodiscovery will be run every time Django starts, and all processes should have a consistent task registry.

**Comment by coleifer** [comment]
Going to pass on this for now, but may reconsider in the future. For now I suggest running the task discovery or importing them explicitly for the task registration.

**Comment by adamchainz** [comment]
Can I ask your reasoning? I was just preparing a patch. This seems like a bit of a sharp corner that could be smoothed out.

**Comment by coleifer** [comment]
The method we have used for many years is `django.utils.module_loading.autodiscover_modules` (or the equivalent). I'm not interested or inclined in fundamentally changing this to use an app ready hook, and debugging edge-cases where this change breaks people's apps which had been working all this time.

**Comment by adamchainz** [comment]
I'm not suggesting changing that call, only moving it into an app ready hook. Let me show you in a draft PR.
