### ISSUE TITLE
Job Scheduling and Restarts

### ISSUE THREAD

**Issue by grinchios** [coleifer/huey#751]
Hey! I've read the docs [here](https://huey.readthedocs.io/en/latest/guide.html#scheduling-tasks) and have a question about if I was to use the eta parameter when scheduling. If my consumers were to be down during when a task is supposed to run what happens? 

For example, if I have an eta of 12 o'clock and the consumers are down 11:30-12:30, what happens, do the consumers pick up where they left off or skip over the job! Thanks

**Comment by coleifer** [comment]
If it is a scheduled job then it will run as soon as they start back up, seeing as it is considered "overdue".

If it is a periodic task that is supposed to run (say) daily at noon, however, it will *not* run.

**Comment by wedens** [comment]
I have a related question, so I hope it's ok if I ask it here.

Is there a way to make sure that a periodic task gets executed daily? For example, if a consumer was down during the scheduled time, the task gets executed as soon as the consumer is up. Basically, I don't really care if a task gets executed at the exact specified time, I just want it to be executed every day.

**Comment by coleifer** [comment]
@wedens - I'd invoke the task multiple times during the day, and just drop a record in your persistent storage to check when it last ran:

```python
@huey.periodic_task(crontab(hour='*/6'))
def run_reports():
    if time_since_last_run < 24h:
        return
    run reports
    store current time as last run
```

**Comment by wedens** [comment]
Thanks for the reply!  Yeah, that looks like a feasible solution.

You mentioned earlier that a scheduled job will run on startup if it's overdue. So, I though that maybe another way to do what I want is to schedule a job on app startup to execute at a specific time and at the end of that scheduled job schedule another job 1 day later. Having date/time of the last run would still be useful to calculate the initial schedule on startup.

**Comment by coleifer** [comment]
A scheduled job will run when it's overdue, but that refers more to "I scheduled this singular task to run at X". For a task that is supposed to run at particular intervals 1/day, 1/hour, whatever, you should definitely be using periodic tasks.

>So, I though that maybe another way to do what I want is to schedule a job on app startup to execute at a specific time and at the end of that scheduled job schedule another job 1 day later.

If it fails once w/a traceback you lose the job for good until you re-invoke it, though. So this is not robust.
