### ISSUE TITLE
How to share a redis connection pool between threads?

### ISSUE THREAD

**Issue by a3rosol** [coleifer/huey#756]
Hello,

in the docs you write about how to share resources amongst workers: https://huey.readthedocs.io/en/latest/shared_resources.html#startup-hooks
However, I have a hard time figuring out how to do this with redis and before I completely refactor my application I wanted to ask you for a sanity check.
Setup: PriorityHuey with Threads

assume I have a config.py where I define a redis instance with a connection pool:

```
pool = ConnectionPool(host=RHOST, port=RPORT, max_connections=RCONNS, password=RPW)
red = Redis(connection_pool=pool)

# Huey
huey = PriorityRedisHuey(connection_pool=pool)
```

following your example, I would create a startup hook like this:

```
from somewhere import make_api_call
from config import red

@huey.on_startup()
def share_redis():
    red.ping()

@huey.task()
def do_something():
    # call a function that uses redis internally
    make_api_call()
```

```
# somewhere.py
from config import red

def make_api_call():
    red.ping()
```
    

Now when the task is executed and `make_api_call()` is called it and any other called function in this thread will have their own access to `red` and that connection pool or is a new connection pool created for each thread? And to use the the redis instance, all I have to do is to import if from config.py?
Will I have to use a context manager to manage the pool or should I avoid it because it might destroy the instance?

**Comment by coleifer** [comment]
It's sufficient to simply do this:

```python
pool = ConnectionPool(host=RHOST, port=RPORT, max_connections=RCONNS, password=RPW)
red = Redis(connection_pool=pool)

# Huey
huey = PriorityRedisHuey(connection_pool=pool)
```

You can use `red` in your application normally. There's no need to ping it on startup. The redis client (`red` in your example) only leases a connection from the pool while executing a command and the connection is immediately returned.

**Comment by a3rosol** [comment]
Thanks @coleifer !
And how do you recommend dealing with resources that need a more active handling like a requests session or something like the influxdb-client?

**Comment by coleifer** [comment]
Depends entirely on the client implementation.

**Comment by a3rosol** [comment]
simplest case:

```python
influx = InfluxDBClient(url=f"http://{IHOST}:{IPORT}", token=ITOKEN, org=IORG, connection_pool_maxsize=10000)
write_api = influx.write_api(write_options=SYNCHRONOUS)
_point1 = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3)
_point2 = Point("my_measurement").tag("location", "New York").field("temperature", 24.3)

write_api.write(bucket="my-bucket", record=[_point1, _point2])

client.close()
```

**Comment by coleifer** [comment]
As I said, it depends completely on the client implementation. Does the client maintain its own pool internally, or not? What is the client's level of thread-safety? How are connections obtained and released to the pool, if one exists? All those things depend on how the client was implemented, so you'll need to consult the docs.
