### ISSUE TITLE
Externally create scheduled tasks

### ISSUE THREAD

**Issue by Mimicvat** [coleifer/huey#760]
Hi, would it be possible to create scheduled tasks in an externaly? For example, I have a website and I would like the user to be able to create, edit and delete scheduled and periodic tasks from the interface with customizable parameters. One way I imagine would be to create an API, since my website runs on another machine, that interacts with the Huey database, directly adding these scheduled tasks to that database, would that be possible and recommended?

**Comment by coleifer** [comment]
Here is the section of the guide on dynamic periodic tasks: https://huey.readthedocs.io/en/latest/guide.html#dynamic-periodic-tasks

There are some gotcha's, of course.

There's also a section on loading and running arbitrary code in tasks: https://huey.readthedocs.io/en/latest/guide.html#run-arbitrary-functions-as-tasks

I don't know that I would do it the way you've described. I'd rather probably have a single task that runs at the minimum interval, then queries the database for matching user-scheduled stuff, and dispatches them as sub-tasks.

**Comment by Mimicvat** [comment]
Thats perfect! 
One question that remained was how to cancel a scheduled periodic task using this method. I tried to use the revoke_by_id, but I think the id generated is the one of the first execution, would it be possible to cancel the execution of one of these instances permanently by the unique name of the task, for example?

**Comment by coleifer** [comment]
I didn't suggest doing dynamic tasks, I suggested having a single master task that reads your user configs and then spawns subtasks. There should be no need to revoke them.
