### ISSUE TITLE
Docker healthcheck

### ISSUE THREAD

**Issue by zN3utr4l** [coleifer/huey#766]
Is there a command you can call from console such as `celery -A scheduler status`, so you can add it to the healthcheck section of docker compose?

![image](https://github.com/coleifer/huey/assets/73225008/8fe63e45-2327-4190-a124-e4991d14c814)

**Comment by coleifer** [comment]
See https://github.com/coleifer/huey/issues/338#issuecomment-413582139

**Comment by coleifer** [comment]
You can just check to see that the process is up and running.
