### ISSUE TITLE
Avoid running read_schedule when self.periodic is False

### ISSUE THREAD

**Issue by pimuzzo** [coleifer/huey#768]
In `consumer.py` inside the `loop` method, the `read_schedule` function is called regardless of the value of the `self.periodic` attribute. This incurs a computational cost even when you have no periodic tasks to handle, as the `read_schedule` function is executed anyway.

I would suggest, if possible, adding a condition that checks whether `self.periodic` is `False` before calling the `read_schedule` function. This way, if `self.periodic` is `False`, the call to `read_schedule` will be avoided entirely, thus reducing the computational load when there are no periodic tasks to handle.

**Comment by coleifer** [comment]
We need to call `read_schedule()` to check if there are any scheduled tasks. This would be tasks enqueued with a `delay` or an `eta`, and has nothing to do with periodic tasks.
