### ISSUE TITLE
Feature Request - Django model method task decorator

### ISSUE THREAD

**Issue by edmenendez** [coleifer/huey#769]
Is there any interest in submitting a PR to enhance Huey to support converting Django model methods into tasks by simply adding a decorator? See example of syntax below.

```
class MyModel(models.Model):

    @huey_model_task
    def update_remote_event(self):
        """ Update the event in the remote calendar. Runs as a task.
        """
```

I have this working on a local project and it's very convenient to allow the method to run as a task without the boilerplate overhead of creating a separate task. It does _not_ fit all use cases. Specifically, it only works when the work being performed doesn't depend on a unsaved state of the model instance. For example, you can't decorate a `save()` method with this. Also, the parameters need to be serializable values (i.e. no model instances for parameters).

Let me know if you find this useful and I will create a PR for it.

**Comment by coleifer** [comment]
Going to pass, but thank you.
