### ISSUE TITLE
poetry run open file instead of running huey consumer

### ISSUE THREAD

**Issue by mancioshell** [coleifer/huey#770]
Hi,
first of all, thank you for this aesome project. I'm trying to migrate from Celery to huey for a lot of reason. First of all, the feature of Dynamic Task Scheduler.

I'm in trouble to run huey consumer in a virtualenv with poetry.
If i run  `poetry run huey_consumer.py functionality.core.test.huey -w 4` huey consumer doesn't start, but the command open the editor and show me huey_consumer.py file.
If i run `poetry shell` and then inside the virtual env, run ` huey_consumer.py functionality.core.test.huey -w 4` consumer starts as expected.

I have a windows 10 OS. I have tried to run the command, in a cmd shell and also in the git bash.
I have no trouble with celery or other dependencies in python when i use poetry run.

Thank you in advance.
Alessandro.

**Comment by coleifer** [comment]
I have no idea how poetry works or why it doesn't do what you're expecting, nor do I use windows, so I can't really offer much help. I'd suggest hitting up the poetry people on their chat or whatever they use.
