### ISSUE TITLE
`result` and `revoke_by_id`  differ in their auto-conversion of task_id to str

### ISSUE THREAD

**Issue by cbm755** [coleifer/huey#778]
The [fine docs](https://huey.readthedocs.io/en/latest/api.html) tell me:

> result(task_id, ...)
>    task_id – the task’s unique identifier.

> revoke_by_id(task_id, ...)
>    task_id (str) – task instance id.

Suppose `task_id` is a `uuid.UUID`.

`revoke_by_id(task_id)` seems fine with this (thus I didn't notice `task_id` was not a `str` ;-)

But `result(task_id)` chokes:
```
sqlite3.ProgrammingError: Error binding parameter 2: type 'UUID' is not supported
```
(In retrospect, a clear enough error message but it puzzled me for a good 15 mins!)

### Workaround:

`result(str(task_id))`

### confusion

The docs say `(str)` for `revoke_by_id` which is the case that in fact works for NON-str...  Maybe the docs could be precisely the same in both cases.

- - - -

I'm quite new with Huey so my apologies if this is actually a [django-huey](https://github.com/gaiacoop/django-huey) bug, or my own misunderstanding.

**Comment by coleifer** [comment]
We never use `uuid.UUID()` objects in Huey, so I'm not sure where that would have come from? Huey itself, when creating IDs to use for tasks (and results) always uses `str(uuid.uuid4())`.

**Comment by cbm755** [comment]
Sorry if I wasn't clear: the issue I'm reporting is that one function converts the input to `str` automatically, while the other does not.

Its not relevant where the uuid came from.

**Comment by coleifer** [comment]
>Its not relevant where the uuid came from.

It is to me, since that is what Huey uses everywhere.
