### ISSUE TITLE
Question: get last execution by task name

### ISSUE THREAD

**Issue by cuthulino** [coleifer/huey#779]
Hallo, I seached hours but I didn't find a solution.

Is it possible to get a task by its name and get the last execution time?
(or timedelta or sth. similar)

I want to enqueue a delayed task (always the same one) by user action in django UI.
_User clicks button --> task is scheduled to run in 15 minutes_ (thats no problem with huey)

But I want to show the last task execution in the UI. 
Like this the user can see, when last action was performed.
_User loads page 30 minutes after clicking the button --> Text shows the task has run 15 minutes ago_
Is this somehow possible?

What i understand, I can get scheduled or pending tasks with `Huey.pending()` or `Huey.scheduled()`.
But how to get completed ones? (maybe including status. success or failure)

**Comment by coleifer** [comment]
Huey does not maintain that sort of "state" or "history". For things like this, I always suggest that you use your real database. When the task executes, it would store some record in the database regarding when it finished, so you can display that to the user.
