### ISSUE TITLE
Relation between origin task call and retry call?!?

### ISSUE THREAD

**Issue by jedie** [coleifer/huey#780]
In [Huey-Monitor](https://github.com/boxine/django-huey-monitor) i would like to store information about retries.
But i didn't see a way to get the relation between the first task call and a retry call.

Any idea how to collect the needed information?

My first thought: There is already the `SIGNAL_RETRYING` can a signal handler get the `task.id` of the origin and the new retry-`task.id` ?

EDIT: Oh! The retried task get's the same task.id as the initial call, isn't it?!?

**Comment by coleifer** [comment]
When a task is retried it uses the same task ID, correct.
