### ISSUE TITLE
TaskLockedException('unable to set lock: ...')

### ISSUE THREAD

**Issue by MichaelVoelkel** [coleifer/huey#781]
Hi,

we are having a few tasks with db_lock that are partially triggered via scheduled tasks. It's a system with quite a load and multiple workers or so. We use redis as storage.

I see in djhuey.HUEY.scheduled() many tasks going in and out, so it's not blocked in that sense. It's small tasks that take 1s or so.

The actual problem now is that I, for some reason, see one important task not being triggered. I saw for same hours (8 hours back) that it regularly failed to acquire the lock:

`TaskLockedException('unable to set lock: ...')`

And now I don't see that it is even triggered anymore. But when I try to trigger it myself from Django shell I will still get that it failed to acquire the lock. What could be the reason? If the tasks runs it spits out logs. And I see other tasks spitting out logs. So I would be (normally) quite confident that this task really does not run anymore (would be cool to double-check though).

Can it be that although the task did not finish, the lock is not released? At things like server restarts etc. we make sure to clear all locks at the beginning just to be sure.

What else could be the issue? How could I troubleshoot this? Is there a way to see running tasks to be sure or have more information about the locks being set?

`djhuey.HUEY.is_locked(...)` tells me that the lock indeed exists

Any help would be appreciated

**Comment by coleifer** [comment]
>djhuey.HUEY.is_locked(...) tells me that the lock indeed exists

Yes this is how you check. Some task must have obtained the lock and is still holding it. How that may have occurred is dependent on your code, I have no idea. Use the logs. Increase the verbosity of the logger. Check when the task executed and obtained the lock.

As you mentioned, you will want to flush locks on restart, but since you are already doing that I don't suspect that's the issue.
