### ISSUE TITLE
Inconsistent Time to Enqueue Periodic Tasks

### ISSUE THREAD

**Issue by michael-murtagh** [coleifer/huey#785]
Hello, 

I have a small script that uses Huey to run some periodic tasks which will have their results set in Redis. When I run the script, the time to enqueue the detected periodic tasks is inconsistent, sometimes taking exactly 1 minute to enqueue the periodic tasks, sometimes taking exactly 4 minutes. See below for some sample logs where it took 4 minutes to enqueue the tasks:

```
2024-02-08 14:46:29,039     INFO - Huey consumer started with 2 thread, PID 17035 at 2024-02-08 13:46:29.039593 (consumer.py:386)
2024-02-08 14:46:29,039     INFO - Scheduler runs every 1 second(s). (consumer.py:389)
2024-02-08 14:46:29,039     INFO - Periodic tasks are enabled. (consumer.py:391)
2024-02-08 14:46:29,039     INFO - The following commands are available:
+ __main__.test_task (consumer.py:398)
2024-02-08 14:50:29,040     INFO - Enqueueing periodic task __main__.test_task: a2c97a7b-ebd6-4c9e-97bd-c6bc5ca90f7b 3 retries. (consumer.py:178)
```

Without changing anything in the consumer, it varies. I would like this to happen consistently as soon as possible after the consumer has been launched as it will speed up my deployment.

Here is an example of what my script looks like:

```
# run_huey.py

from huey import SqliteHuey, crontab
from src.redis.client import RedisCache

redis_client = RedisCache() # Custom Redis client to set / pull elements from cache
huey = SqliteHuey(filename="huey_metadata.db"])

@huey.periodic_task(
    crontab(minute=f"*/5"),
    retries=3,
    retry_delay=10,
)
def test_task():
    redis_client.set_in_cache(...)

if __name__ == "__main__":
    from huey.consumer import Consumer
    consumer = Consumer(huey, workers=2)
    consumer.run()
```

And the script is being launched via the command line `python ./src/scripts/run_huey.py`. Launching the consumer via the command line as opposed to inside my script does not resolve the problem, still varying between 1 and 3 minutes.

Ideally I would like that once the Consumer has been started, that it immediately enqueues the periodic task(s) and executes them, and then continues to execute them with the scheduled period of 5 minutes.

Thanks

**Comment by coleifer** [comment]
The "*/5" means run on any minute that is a multiple of 5. So it is doing the correct thing and running at `14:50` (given that you started it at `14:46`). This is how cron works as well.

**Comment by michael-murtagh** [comment]
Thanks for the sanity check! I hadn't thought of that at all.
