### ISSUE TITLE
Not scheduled tasks

### ISSUE THREAD

**Issue by mcilfone** [coleifer/huey#786]
Hi Leifer,
I have a problem using Huey, for executing asynchronous tasks.
I have an application that, once a half hour, has to submit dozen of tasks in the same time. Obviously, I can't assure that will be enough workers free to execute all of them.
Is there a way to know if a task is succesfully scheduled to a worker, or if it is rejected because there's no enough space to work on it?
In this way, I can implement a more clever way to submit tasks to Huey.
Thanks alot

Michele Cilfone

**Comment by coleifer** [comment]
Tasks are not rejected...a task queue is literally just that -- a queue. Tasks are placed into the queue, then executed in order. This is self-evident.

**Comment by mcilfone** [comment]
Ok, thanks. So, there's a way to know if the task I'm interested in is still in queue or not. Isnt'it?
