### ISSUE TITLE
update TODO

### ISSUE THREAD

**Issue by egor-georgiev** [coleifer/huey#788]
Hello.

I have noticed that the [TODO file](https://github.com/coleifer/huey/blob/master/TODO) is 5 years old. Are there any other ideas of what could be implemented for Huey in current state? Are some of the points there stale? It would be cool to see some fresh information, perhaps, I (or other contributors) could pick something up and implement.

Many thanks!

**Comment by coleifer** [comment]
It is what it is, nothing to add at present.
