### ISSUE TITLE
Forking ?

### ISSUE THREAD

**Issue by spapas** [coleifer/huey#789]
Is there a way to run the `run_huey` management command as forking ?

**Comment by coleifer** [comment]
It automatically does if you're on MacOS and running Python 3.8 or newer. Are you on a different platform and seeing it use the `spawn` method instead? What OS/python are you running if that's the case?

**Comment by spapas** [comment]
I'm using CentOS Linux release 7.9.2009 (Core) with python 3.10.2.

**Comment by coleifer** [comment]
Then you should already be using `fork`:

```python
In [1]: import multiprocessing

In [2]: multiprocessing.get_start_method()
Out[2]: 'fork'
```

I see the above on debian w/python 3.11, for example.
