### ISSUE TITLE
How do you feel about a KeyDB implementation?

### ISSUE THREAD

**Issue by vladislavdonchev** [coleifer/huey#790]
Now that Redis has announced the transition to their new licensing, maybe it's time to also add support for another solution, like KeyDB?

I am personally vested and can help make it happen if it's something that seems like a reasonable addition to Huey.

Sorry if it's an unnecessary question, I am not familiar with the feature / PR culture here. :)

**Comment by coleifer** [comment]
It should already work out-of-the-box.

**Comment by vladislavdonchev** [comment]
OK, so it seems that it's a drop-in replacement. My bad. You can delete the issue.

**Comment by andryyy** [comment]
Offtopic: I’m a KeyDB user myself, but don’t forget it’s owned by Snap Inc. 

Just someone else’s toilette, I’d say.
