### ISSUE TITLE
Confirmation: Invoke/Enqueue a task by its string name

### ISSUE THREAD

**Issue by sgosain** [coleifer/huey#792]
I am new to Huey.  I have a requirement where a seperate API server needs to spawn / invoke Huey tasks based on certain trigger events. When those events trigger  the server  needs to call/enqueue huey tasks on the workers by their "name" (each event is mapped to one or more task names)  

I'm doing the following and wanted to ensure my appraoch is OK/as per standards because I am using protected methods in the huey object.

Going by the "simple" example in the huey examples I tried the following:

**REGISTRY METHOD**
Since as of 2.0 the Global registry is deprecated and  tasks are associated with the huey  instantiated object, I tried:
```
tsk = huey._registry._registry["tasks.add"]
result = huey.enqueue(tsk([1,2]))
print(result.get(True))
```

it works but wanted to see if there's a better way to enqueue tasks by their "name"

**Comment by coleifer** [comment]
I suppose that's OK but it is possible it may change in the future. The correct approach would be to manage the mapping yourself:

```python

@huey.task(...)
def my_task1(...):
    ...

@huey.task(...)
def my_task2(...):
    ...

# YOU manage the mapping of task name -> task callable.
TASKS = {
    't1': [my_task1],
    't2': [my_task2],
}

# Then to enqueue by name:
name = 't1'
accum = []
for task in TASKS[name]:
    accum.append(TASKS[name](...))  # Collect result handles.
```
