### ISSUE TITLE
Consumer doesn't pickup updated task

### ISSUE THREAD

**Issue by essadek** [coleifer/huey#794]
Hi,
I'm using Django extension of Huey, the issue is that when ever I update the task source code and run :
`python manage run_huey `

It doesn't pickup the update task and runs the previous task version.
Is there something I'm doing wrong, otherwise how to force Huey to pickup the update task ?

Thanks in advance for any direction.

**Comment by coleifer** [comment]
Huey doesn't come with any code to watch for "updates". You need to restart the consumer if you want it to pick up new code, or you can adapt the code Django uses and make your own management command to run the consumer.

**Comment by essadek** [comment]
@coleifer thank you for your prompt comment. 

> You need to restart the consumer if you want it to pick up new code

I know.
The issue occurs even if I stop and rerun the consumer (That's what you mean by 'restart' I guess), and that's what brings me here to ask.

**Comment by coleifer** [comment]
That doesn’t sound right at all. Something else is wrong in that case with your deployment or otherwise.

**Comment by essadek** [comment]
I've made a lot of research before coming here, I checked the redis keyspace for Huey entries but couldn't find any.

**Comment by coleifer** [comment]
I'm not sure what to tell you, though there should be at least a queue in redis. If you have a backlog of tasks in the queue then, yes, if you stop it while there are still unprocessed items they will be picked-up when the consumer starts back up. But only the task name and the task arguments are serialized -- the executable code is not and so this doesn't sound like it would match your issue.

**Comment by essadek** [comment]
This is only happening on the production server, .

>  If you have a backlog of tasks in the queue then, yes, if you stop it while there are still unprocessed items they will be picked-up when the consumer starts back up

That's good to know and it might help in narrowing my assumptions on the issue. By the way is there could we clear the backlog on consumer restart.
 


> only the task name and the task arguments are serialized -- the executable code is not
This is what bugging me why Huey execute the old code. 

As temporary workaround I had to rename the tasks to have Huey pickup the updated task's code.
Could you tell me what Redis keys are used by Huey  ?

**Comment by coleifer** [comment]
Something is clearly wrong with your deployment or environment.
