### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by edmundrotimi** [coleifer/huey#798]
I keep getting "OperationalError connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "root" connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "root". Strangely, I do not have a DB user 'root'. This does not happen in local development.

      @db_periodic_task(crontab(minute='*/1'), queue='application_expiration')
      def parcel_expiration_task():
          # current date and time
          current_timestamp = timezone.localtime(timezone.now())
      
          # get all event
          get_events = Event.objects.order_by('-creation_time').filter(
             time_ends__lt=current_timestamp
          )
  
          if get_events.exists():
              ....

I have tried to add a db. connection in the supervisor:

      [program: application]
      command='...'
      user='...'
      autostart=true
      autorestart=true
      redirect_stderr = true                                               
      stdout_logfile = '....'
      environment=DATABASE_URL="postgresql://username: password@localhost:5432/db_name"

I have also edited the pg_hba.conf file and add the following entry at the very end of the file:

      host    all             all              0.0.0.0/0                       md5
      host    all             all              ::/0                               md5

**Comment by coleifer** [comment]
`DATABASE_URL` isn't a recognized environment variable by Huey. Since it appears you are using Django, you will need to configure the appropriate connection settings in your Django settings file. This isn't a Huey issue, rather it appears you haven't properly configured your Django app to talk to your postgres database.

**Comment by edmundrotimi** [comment]
The database connection is correct only in the task where this occurs.
