### ISSUE TITLE
Redis is no longer opensource, are you going to support another option? like valkey or redict

### ISSUE THREAD

**Issue by coffeepy** [coleifer/huey#800]
just curious, seems like the code should just work with other key val dbs, havent tested myself, but wasnt sure if there might be a need to move away from 'Redis' and move more towards a a different instance, more generic ?  something like 

```
huey = KeyValHuey('my-app', host='test.myapp.com')

```
Some options as of writing this:

- Valkey: An open-source fork led by former Redis contributors from AWS and other companies, and hosted by the Linux Foundation. Valkey is backed by AWS, Google Cloud, Oracle, Ericsson, and Snap Inc., and aims to maintain the original Redis community spirit while offering improvements like better clustering and performance optimizations. Valkey plans to release annual version updates and a Rust module.

- Redict: An open-source fork led by an open-source coalition, and licensed under GPL 

Anywho just a thought, fun fact havent even used Huey yet, but not wanting use Redis made me ask this question. 

Thanks!

**Comment by coleifer** [comment]
Huey already supports all those along with keydb and anything else that speaks the redis protocol. No changes are needed.
