### ISSUE TITLE
Could we get a new release? 

### ISSUE THREAD

**Issue by patrick91** [coleifer/huey#801]
Hi there! Thanks for the package! I saw this warning:

```
/Users/patrick/github/arminiogroup/shop/backend/.venv/lib/python3.12/site-packages/huey/api.py:346: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```

And I noticed that the current version on master has a fix for it, but I don't think it has been released yet 😊

Would it be possible to get a new release out?

**Comment by coleifer** [comment]
The royal "we" or were there several of you? But yes, of course - 2.5.1 should be up on pypi now with this finger-painting I made to represent my feelings about the python leadership: 
![python](https://github.com/coleifer/huey/assets/119974/7598b0b7-ad69-428a-8d8f-25257731858b)
