### ISSUE TITLE
Forceful Termination in Huey for Already Running Tasks

### ISSUE THREAD

**Issue by davner** [coleifer/huey#803]
Thank you for your work on Huey. 

I need to terminate long-running tasks without natural checkpoints. I see `revoke` is to be used for tasks that have not started but what about already running tasks? Users should be able to cancel these running tasks forcefully by clicking a “Cancel” button on my frontend. 

Can you suggest any methods or modifications in Huey that would allow this? Thank you.

**Comment by coleifer** [comment]
Not really, no. You'll have to think outside the box for this.
