### ISSUE TITLE
Question: How do I show task status on a webpage

### ISSUE THREAD

**Issue by smseidl** [coleifer/huey#806]
Sorry for a question in the Issues section, but I'm stumped.  I've gotten my first task working with Huey, and now I want to be able to show that task status to the end user on a webpage.  I've `huey_monitor` installed and working so I can see it from the Django Admin, but I'm looking for something to implement within my site.  Google has failed in finding me any leads.  Can you help point me in a direction?

**Comment by coleifer** [comment]
Huey doesn't really provide this. You would probably need to write your own signal handlers and then push data to some storage layer that your website would regularly query. For a simple example:

```
@huey.signal(SIGNAL_EXECUTING)
def task_success(signal, task):
    storage.write('started', task.id)

@huey.signal(SIGNAL_ERROR, SIGNAL_LOCKED, SIGNAL_CANCELED, SIGNAL_REVOKED)
def task_not_executed_handler(signal, task, exc=None):
    storage.write('terminated', task.id)

@huey.signal(SIGNAL_COMPLETE)
def task_success(signal, task):
    storage.write('success', task.id)
```

Then your frontend would query the storage to display the appropriate state.
