### ISSUE TITLE
Unit testing with blocking execution for periodic_tasks hangs due to discarded result?

### ISSUE THREAD

**Issue by jgeewax** [coleifer/huey#807]
To unit test a task, I've got the following:

```python
from huey import SqliteHuey

HUEY_PATH = os.path.join(os.path.dirname(__file__), "..", "huey.db")
huey = SqliteHuey(filename=HUEY_PATH)

@huey.task()
def add(a, b) -> int:
  return a + b

@huey.task()
def do_nothing():
  return None
```

In a unit test, you can then do:

```python
from my_module import add, do_nothing

class TestHuey:
  def test_huey(self):
    run_task = add(1, 2)
    result = run_task(blocking=True, timeout=1)
    assert result == 3

  def test_that_fails_with_timeout(self):
    run_task = do_nothing()
    # This next line throws "huey.exceptions.HueyException: timed out waiting for result"
    result = run_task(blocking=True, timeout=1)
    assert result is None
```

---

Now if you want to do the same thing, but with a periodic task, I figured it'd be something like...

```python
from huey import SqliteHuey

HUEY_PATH = os.path.join(os.path.dirname(__file__), "..", "huey.db")
huey = SqliteHuey(filename=HUEY_PATH)

@huey.periodic_task(crontab(minute="*/15"))
def count_something() -> int:
  return 42
```

And in the unittest, 

```python
from datetime import datetime

from my_module import count_something

class TestHuey:
  def test_that_times_out(self):
    run_task = count_something.schedule(eta=datetime.now())
    # This next line throws "huey.exceptions.HueyException: timed out waiting for result"
    result = run_task(blocking=True, timeout=1)
    assert result == 42
```

---

I think the moral here is that if your task doesn't have a non-`None` (not `EmptyData`) return value, then it's treated as "not completed yet". This would explain why the `do_nothing` task above times out even though it's complete.

The problem here is that according to the docs, `periodic_task()` decorated functions have their return value discarded, so they will always timeout even if you provide a return value (in this example case, `42`).

I was able to get these tests passing by changing line 431 in `huey/api.py`:

```diff
-if self.results and not isinstance(task, PeriodicTask):
+if self.results:
```

But I think there's further-reaching implications of something like this.

I suspect the best way to test a periodic task instead is to split things apart (periodic task calling into a function that does the actual work, and testing that function separately):

```python
from huey import SqliteHuey

HUEY_PATH = os.path.join(os.path.dirname(__file__), "..", "huey.db")
huey = SqliteHuey(filename=HUEY_PATH)

@huey.periodic_task(crontab(minute="*/15"))
def count_something_task() -> int:
  return count_something()

def count_something() -> int:
  return 42
```

And in the unittest, 

```python
from my_module import count_something

class TestHuey:
  def test_count_something(self):
    assert count_something() == 42
```

Does that sound right?

Are there any plans to add a "here's the best way to do unit testing with Huey" to the docs? Or does it already exist and I've missed it?

**Comment by coleifer** [comment]
Periodic tasks do not have a meaningful return value. And again,

>Because periodic tasks are called independent of any user interaction, they do not accept any arguments.
>
>Similarly, the return-value for periodic tasks is discarded, rather than being put into the result store. This is because there is not an obvious way for an application to obtain a [Result](https://huey.readthedocs.io/en/latest/api.html#Result) handle to access the result of a given periodic task execution.

If you intend to test the logic of a periodic task, you would want to split it into a standalone function.

If you are doing unit tests with Huey you should be setting Huey to [immediate-mode](https://huey.readthedocs.io/en/latest/guide.html#immediate) for regular task testing. This makes it so that tasks run synchronously and you don't need to run a separate consumer. Because there is no return value for calling a periodic task, though, you will still need to split the business logic into its own function.

**Comment by jgeewax** [comment]
Sorry forgot to mention that yes, I'm using immediate mode to execute. (But the blocking call still hangs due to no return value.)

So it sounds like the moral of the story is... "Don't try to test a `@huey.periodic_task()` decorated function. Instead have that function call another that does the actual work and test that."

Just want to ask also:

> Are there any plans to add a "here's the best way to do unit testing with Huey" to the docs? Or does it already exist and I've missed it?

If not, I can try to carve out some time to throw in a PR for that... If you have something in flight I don't want to duplicate the work.
