### ISSUE TITLE
[Question]: Set a customized UUID for a task

### ISSUE THREAD

**Issue by hck007** [coleifer/huey#808]
I'm working with Huey 2.5.1 in a Flask application and have a question regarding as setting a customized uuid for a task. 

I have a task with three states Pending, In Progress, Completed. The task transitions to In Progress as soon as a worker processes the task. I want to set the task's state to Pending before the worker even processes the task. The reason is that we may have multiple long running task request but limited worker threads. Sometimes, the number of requests is bigger than that of worker threads. Any task that is not processed by a worker (enqueued) is Pending state. Having Pending state logic in the task function doesn't work since the state is considered to be In Progress if the task is processed by a worker. I'm considering passing a custom UUID that is generated prior to the invocation of task function. The `Task` instance in Huey has an id parameter https://huey.readthedocs.io/en/latest/api.html#Task, and I think this might allow some flexibility to set a custom ID?
```
@huey.task(context=True)
def long_running_task(a, b, task=None):
    task_id = task.id

    #update the state of task to be In Progress
    update_state(task_id, "In Progress")

    #run the long time blocking function
    res = long_running_process(a, b)

    #update the state of task to be Completed
    update_state(task_id, "Completed")
    
    return res

#below is a view function of a Flask app
def run_task():
    a = 1
    b = 2

    #generate customized uuid. we can assume uuid is system wide unique
    customized_id = generate_id()

    #update state to Pending
    update_state(customized_id, "Pending")

    #I want to use customized_id as task id
    task_result = long_running_task(a, b)

    #return the result, the rest of code can be ignored
    return ........
```

**Comment by coleifer** [comment]
Don't use the opaque identifiers used by Huey for this.

I suggest you use your database - this is the standard practice:

1. Create a record in your db to represent whatever job you're running.
2. Set record state to pending.
3. Call your first task, along with the record ID for the job
4. Update the record inside the task(s) as many times as needed
5. When all done, you can optionally remove the record from your database

**Comment by coleifer** [comment]
```python
@huey.task(context=True)
def long_running_task(job_id, ...):
    #update the state of task to be In Progress
    Job.update(status='in progress').where(id=job_id).execute()

    #run the long time blocking function
    res = long_running_process(a, b)

    #update the state of task to be Completed
    Job.update(status='complete').where(id=job_id).execute()
    
    return res

#below is a view function of a Flask app
def run_task():
    a = 1
    b = 2

    #generate customized uuid. we can assume uuid is system wide unique
    job = Job.create(status='pending')

    #I want to use customized_id as task id
    task_result = long_running_task(job.id, a, b)

    #return the result, the rest of code can be ignored
    return ........
```

**Comment by hck007** [comment]
Thanks for the help. There is one more thing. I also have a view function that allows users to cancel (revoke) a task if the task is in Pending state. There is `revoke_by_id` API in huey. If we use id generated by database, `revoke_by_id` will not work since this API uses task id. Maybe we should add one more field in database to record the identifier used by huey?
```
def run_task():
    a = 1
    b = 2

    #generate customized uuid. we can assume uuid is system wide unique
    job = Job.create(status='pending')

    #I want to use customized_id as task id
    task_result = long_running_task(job.id, a, b)

    #add task id used by huey to database
    job = job.update(task_result.id).where(id=job.id)

    #return the result, the rest of code can be ignored
    return ........

def revoke_pending_task():
    huey.revoke_by_id()
```

**Comment by coleifer** [comment]
For those I wouldn't worry about revoking it, necessarily, but just check if it was canceled inside the task.

If you really did want to you could update the job record w/the task id (which is obtainable via the result-handle returned when you run the task, or via the object returned by task_function.s()).
