### ISSUE TITLE
Could we have a specific exception for task timeout?

### ISSUE THREAD

**Issue by danielbprice** [coleifer/huey#810]
Today, if you pass `timeout=<whatever>` to a task, a timeout results in a `HueyException`.  It would be a lot nicer for consumers who want to know if the timeout was reached if there was a specific `HueyTimeoutException` subclass.  Then you could write:

```
try:
    r(blocking=True, timeout=5)
except HueyTimeoutException as exc:
    # handle timeout
except HueyException as exc:
    # something else
```

It seems like I can get at this information today by looking at the message of the HueyException, but that feels like a hack.

**Comment by coleifer** [comment]
Well technically I think you would catch a `TaskException` in the event of "something else", e.g. something went wrong with the task, but the point is still valid.

I've added a `ResultTimeout` subclass of `HueyException` that works as you suggest.

**Comment by danielbprice** [comment]
Thanks so much, I really appreciate it!
