### ISSUE TITLE
Switching from multiprocessing to multiprocess

### ISSUE THREAD

**Issue by wKollendorf** [coleifer/huey#811]
With multiprocessing worker-type=process is not possible on Windows systems. Unfortunately, Windows is unavoidable in my case. multiprocess is s fork of multiprocessing and makes use of dill rather than pickle for serializing objects. My knowlege in the details is limited, but a test replacing multiprocessing in consumer.py seems to work. Starting huey with worker-type=process works on a Windows machine. 
What do you think about it? What downsides do you see? Maybe you already commented on such a request, which I missed while searching this repo. Thanks!

**Comment by coleifer** [comment]
I don't know enough about `dill` or `multiprocess` to offer any meaningful opinion. Tread carefully, I guess.
