### ISSUE TITLE
Garnet support / lua use in RedisStorage

### ISSUE THREAD

**Issue by hho6643** [coleifer/huey#812]
First, thanks for making such a useful bit of software.

I'm working on a project that uses Garnet (https://github.com/microsoft/garnet) as a (mostly) drop-in replacement for Redis as a backend cache store.  I would like to use Huey in this project, specifically the RedisHuey backend.  Unfortunately, Garnet doesn't support Lua scripting, and RedisStorage uses in what looks like just 1 place a tiny little lua script to pop scheduled tasks.  

I've made a workaround for this, so my immediate problem is solved.  I'm wondering if you'd be interested in a pull request, and if so, what form you'd like it to take from the options below:

Option 1: 
Make a custom "GarnetStorage" class, "GarnetHuey" class, etc.  They'd be subclasses of the equivalent Redis classes with just an updated read_schedule function:
```
    def read_schedule(self, ts):
        unix_ts = self.convert_ts(ts)
        tasks = self.conn.zrange(self.schedule_key, "-inf", unix_ts, byscore=True)
        if tasks:
            rmtask = self.conn.zremrangebyscore(self.schedule_key, "-inf", unix_ts)
            if rmtask != len(tasks):
                tasks = []
        return [] if tasks is None else tasks
```

Option 2:
Update the current RedisStorage backend to use the new 'read_schedule' function as above.  I'm guessing you had a good reason to do it as a lua script instead of direct redis calls, so this might not be as preferable.  

Option 3:
It's too small a use case for you, don't bother with a pull request.

**Comment by coleifer** [comment]
The reason we do it with Lua is to ensure atomicity. There is a possible race condition in your option 2.
