### ISSUE TITLE
revoke_all for classes of pending tasks?

### ISSUE THREAD

**Issue by p-j-l** [coleifer/huey#814]
Hey, I'm wondering if anyone has run into this before:

I'm trying to do some automated pending-queue management, and I'd like to be able to get the pending tasks, find the top occurring ones, and then revoke them to prevent any of that type from running.

I'm trying to do something like this (pseudocode):

```
pending_tasks = huey.pending()
top_ten_pending_tasks = ...  # Exercise for the reader

for top_task in top_ten_pending_tasks:
    top_task.revoke_all()
```

But it looks like the pending() call returns Task objects, rather than TaskWrapper or Result objects, and so I'm struggling to call revoke_all() on them.  Any suggestions?

**Comment by coleifer** [comment]
You have the class, just call `type(task_instance)` to get it:

```python
counter = Counter(type(t) for t in huey.pending())
for task_class, ct in counter.most_common(10):
    huey.revoke_all(task_class)
```
