### ISSUE TITLE
How to create a dead-letter-queue for tasks that can't be executed?

### ISSUE THREAD

**Issue by p-j-l** [coleifer/huey#815]
Hey, I've been having fun where sometime we run into a task that's scheduled but which can't be run.

As an example of how this can happen, suppose that you schedule a task to persistent storage but then delete the code that would actually run it and restart the Huey workers.  Now there's a scheduled task that can't run and which will throw an exception when it gets to here.  It'll also stay on the queue, which means the scheduler will keep trying to rerun it. 
https://github.com/coleifer/huey/blob/master/huey/registry.py#L49

(Other ways this could happen include things like a bad custom serializer/deserializer, etc.)

What's the right way to catch errors such as this and make sure that tasks which're in that state don't stay queued?

If it's of any use, I'm happy to send a patch for [api.py:deserialize_task()](https://github.com/coleifer/huey/blob/master/huey/api.py#L299) to add a callback for if a task can't be deserialized?  That way people could decide what to do with it themselves?

**Comment by coleifer** [comment]
>Now there's a scheduled task that can't run and which will throw an exception when it gets to here. It'll also stay on the queue, which means the scheduler will keep trying to rerun it.

What do you mean the scheduler will keep trying to rerun it? If the task was not found, then the scheduler just throws it out. It's easy to demonstrate this and verify for yourself. When the scheduler attempts to run the task that no longer exists/can't be executed, it will throw something like `huey.exceptions.HueyException: tasks.will_be_gone not found in TaskRegistry` and the task is discarded. It no longer remains in the schedule or the queue at that point.

If you want to catch these yourself you can just subclass `RedisHuey` or whatever and implement your own `deserialize_task()` that does what you want with the message.

**Comment by p-j-l** [comment]
Thanks for the incredibly fast response!  My apologies, I was wrong there in thinking that the scheduler kept those on the queue.

Just to make sure that I understand: if I subclass RedisHuey I'll be able to catch errors in deserialization but not if the task doesn't exist in the registry?  Oh, I suppose I could add a custom check in the deserialize_task() call to see if the task name is in the registry before create_task() is called?

**Comment by coleifer** [comment]
No that's incorrect - you *will* be able to catch those errors inside `deserialize_task()`.

**Comment by p-j-l** [comment]
Sorry, one last quick question - when the scheduler gets the next batch of tasks to work though, what happens if just one of those were to have the sort of problems mentioned above?  Would just that task be thrown out?  Or would the entire batch be removed?

**Comment by coleifer** [comment]
You were absolutely right -- if a bad task was mixed in a batch of tasks that were ready to transition from the schedule -> main queue, then that whole batch of tasks would be lost! This is now fixed - the tasks are deserialized individually when reading the schedule and an exception is logged if one or more of them fails.

**Comment by p-j-l** [comment]
Much appreciated, thank you!

**Comment by coleifer** [comment]
2.5.2 should be on pypi now.
