### ISSUE TITLE
Default implementation of Serializer vulnerable to arbitrary code execution

### ISSUE THREAD

**Issue by WilliamRoyNelson** [coleifer/huey#818]
The default implementation of the Serializer class uses the `pickle` library, and uses pickle.loads with no restrictions.
https://github.com/coleifer/huey/blob/2.5.2/huey/serializer.py#L72-L73

This is vulnerable to arbitrary code execution:
https://docs.python.org/3/library/pickle.html#restricting-globals

```python
from huey import serializer

if __name__ == '__main__':
    serializer.Serializer._deserialize("", b"cos\nsystem\n(S'calc'\ntR.")
```
The above opens the calculator app on my windows PC.

Would it be possible to replace the default deserializer function with a restricted unpickler that limits classes and functions to a reasonable subset?

Example from python documentation:

```python
import builtins
import io
import pickle

safe_builtins = {
    'range',
    'complex',
    'set',
    'frozenset',
    'slice',
}

class RestrictedUnpickler(pickle.Unpickler):

    def find_class(self, module, name):
        # Only allow safe classes from builtins.
        if module == "builtins" and name in safe_builtins:
            return getattr(builtins, name)
        # Forbid everything else.
        raise pickle.UnpicklingError("global '%s.%s' is forbidden" %
                                     (module, name))

def restricted_loads(s):
    """Helper function analogous to pickle.loads()."""
    return RestrictedUnpickler(io.BytesIO(s)).load()
```

reference:
https://huntr.com/bounties/1-pypi-huey

**Comment by coleifer** [comment]
Don't expose stuff to untrusted input, but I have no patience for security theatre. If you are truly worried about it you can use the signed serializer implementation, ensuring only trusted messages come through. You are also welcome to use your own custom serializer or open-source one as a 3rd-party library.
