### ISSUE TITLE
Help needed to test huey signal handler

### ISSUE THREAD

**Issue by ariane762** [coleifer/huey#823]
Hello,

I've been struggling to unit test huey's signal handler.

I have the following bit of code that gets the task statuts through the signal decorator to update a django model that persists its status. I'm using pytest to perform unit tests and I don't understand how to factor a task fixture with its own id and kwargs attributes. Do you have any idea?

```
@signal()
def all_signal_handler(huey_signal, task, exc=None):
    '''Global huey signals handler'''
    logger.info(msg={
        "message": f"Task {task.id} now in state {huey_signal}",
        "task": task.id
    })
    try:
        django_task = models.Task.objects.get(id=task.kwargs['task_id'])
        django_task.task_id = task.id
        django_task.update_status(huey_signal)
        django_task.updated = timezone.now()
        django_task.routine = task.name
        django_task.args = task.data

        django_task.save()
    except KeyError:
        pass
```

**Comment by coleifer** [comment]
Sorry I’m not sure what you’re asking.

**Comment by ariane762** [comment]
Hello,
Okay, I'll give you more information on what I want. 
I want to test the all_signal_handler function.
```
@signal()
def all_signal_handler(huey_signal, task, exc=None):
...
```
This function takes a huey signal and a task object as arguments. But I can't simulate this task object.
For example we have the following huey task "test_task" :
```
@db_task()
def test_task(task_id):
    '''Test task'''
    sleep(10)
    return True
```
And when we want to test the all_signal_handler function using the test_task task as an argument, huey doesn't consider it as a task but as a TaskWrapper Object or a Result Object. How can I make huey understand that test_task is indeed a task in our tests? Or simply how to simulate a task object in our tests?

You will find below the two test we tried to launch and you will find the error messages obtained:

Test attempt 1:
```
#Test the all_signal_handler function 
@pytest.mark.django_db
def test_signal_huey():
    all_signal_handler(huey_signal="executing", task=test_task(task_id="dd3f7105-6376-4ed7-9389-85001a1cd4c2"), exc=None)
    assert ...
```	
I get the following error message:
```
task = <Result: task 64c41740-d89a-4146-a0eb-fc6629d6aab2>, exc = None

>           django_task = models.Task.objects.get(id=task.kwargs['task_id'])
E           AttributeError: 'Result' object has no attribute 'kwargs'
```
Test attempt 2:
```
#Test the all_signal_handler function 
@pytest.mark.django_db
def test_signal_queued():
    all_signal_handler(huey_signal="executing", task=test_task, exc=None) 
	assert ...
```

I get the following error message:
```
task = <huey.api.TaskWrapper object at 0x7efffdc8a290>, exc = None

>           "message": f"Task {task.id} now in state {huey_signal}",
            "task": task.id
        })
E       AttributeError: 'TaskWrapper' object has no attribute 'id'
```

**Comment by coleifer** [comment]
Oh, I have no idea how this pytest stuff works, sorry. You can see the huey unit-tests for an idea of how signal testing works, though: https://github.com/coleifer/huey/blob/master/huey/tests/test_signals.py

**Comment by ariane762** [comment]
Hello,
Thank you. 
I would like to inform you that we found the solution in the Huey documentation. 
To instantiate a task and be able to use it as an argument for our tests, we used the **TaskWrapper.s()** function. 
Below is our code : 

```
@pytest.mark.django_db
def test_signals():
    django_task = models.Task(name="my mock task")
    django_task.save()
    task_instance=test_task.s(task_id=str(django_task.id))
    all_signal_handler(huey_signal=SIGNAL_EXECUTING, task=task_instance)
    django_task.refresh_from_db() 
    assert django_task.status == SIGNAL_EXECUTING
```
