### ISSUE TITLE
Auto Discover Broken in Django 1.8

### ISSUE THREAD

**Issue by pizzapanther** [coleifer/huey#86]
Auto discover no longer works in Django 1.8. If you force the old method (1.6 <=) it works fine. The newer appears to function without error but tasks never get registered.

**Comment by coleifer** [comment]
Oh no, is this with the very newest release, 0.4.4?

**Comment by pizzapanther** [comment]
Yes looking at this further I think auto discovery is just broken for 1.7 and 1.8a.

**Comment by coleifer** [comment]
OK I believe i've fixed this. I'm going to blow away the current 0.4.4 and push a new release.

**Comment by coleifer** [comment]
Just created 0.4.5 release and push to pypi. Thank you for the quick bug report, really appreciate it!

**Comment by pizzapanther** [comment]
Think your fix is going to still break stuff it needs:

```
module_args = imp.find_module(module_name, app_path)
imp.load_module('{}.{}'.format(config.name, module_name), *module_args)
```

If you just do `module_name` it conflicts with other imports

**Comment by coleifer** [comment]
I tried it out locally with 1.8 and the fix I merged seems to have worked. Can you explain? Did you try it and it broke?

**Comment by pizzapanther** [comment]
It probably has to do with relative imports, I'm using relative imports in my `tasks.py` and get `ValueError: Attempted relative import in non-package` with Huey 0.4.5.  If I change `load_module` to use the name `'{}.{}'.format(config.name, module_name)` it works.

**Comment by coleifer** [comment]
Alright, hopefully we're good to go. Pushed 0.4.6 with your suggested change.

**Comment by coleifer** [comment]
And thanks again for your help with this!

**Comment by pizzapanther** [comment]
Just tested, it works great.

Thanks for the great library.
