### ISSUE TITLE
how works multi-threaded task execution with the python GIL?

### ISSUE THREAD

**Issue by nicchub** [coleifer/huey#89]
Hi, I have a question, how works multi-threaded task execution in huey with the python GIL?, I know is hard working with threads on python.. and a little slow, so is huey fast?

thanks.

**Comment by coleifer** [comment]
With Huey, because of the GIL, only one thread will ever be running at a time. For CPUbound tasks this will be slower than a single thread. For IO bound tasks, huey will be faster.

**Comment by nicchub** [comment]
Understood, I'll try Huey. thanks.
