### ISSUE TITLE
Huey taking very long 

### ISSUE THREAD

**Issue by vladlep** [coleifer/huey#92]
Hello,

Sorry for writing here but i did not find a group or other place to ask for support. It might not be a bug, might be that i am just using huey wrong. 

We were using huey and it was working well, but i had to change the database structure and adapt the task and now it takes hours to execute tasks that would take 30 secs if they would not be inside a task. The CPU on the server is running at 100%. Are there any constraints that I am missing? 

I tried to simplify the code (it is not production ready anymore, just a test), got to this level and it still does not work:

    @db_periodic_task(crontab(minute="*/10"))
    def find_recurring_subscriptions_about_to_end():
        """Renew subscriptions that are running out soon.
        """
        logger.error("find_recurring_subscriptions_about_to_end START: %s", timezone.now())
        TOMORROW = date.today() + relativedelta(days=+1)
        up_for_renewal = Subscription.objects.filter(cancelled=None)   
        for subscription in up_for_renewal:
            end_date = subscription.get_end_date()
            if end_date and end_date <= TOMORROW:
                logger.error("+1")
                #should have here the real code that renews a subscription
       logger.error("find_recurring_subscriptions_about_to_end STOP : %s", timezone.now())

Are there any memory limitations? On the testing server, where the code runs, there are only 26 subscriptions, which does not seem that much. In production there are thousands, so i would not move the code until i am sure it can work with more subscriptions.

Thanks,
Vlad

**Comment by coleifer** [comment]
> We were using huey and it was working well, but i had to change the database structure and adapt the task and now it takes hours to execute tasks that would take 30 secs if they would not be inside a task. 

I'm not sure I understand. So you were using huey in the past and it worked fine. You changed your database and now huey is taking hours, *but* if you run the code outside of huey it takes only 30 seconds?

**Comment by vladlep** [comment]
Yes.
 In the past the Django query - Subscription.objects.filter(cancelled=None) - was returning less elements and now it returns more but max 26. And if i call the same code from a simple django view (not a  huey task) it takes 30 millisecond (i wrote it wrong). 

I am trying different things and surprisingly i can not make it work. That is why i thought to ask, maybe i missed some constraints

**Comment by coleifer** [comment]
That's incredibly bizarre. Perhaps the issue is with the use of `db_periodic_task()`. Does anything happen if you use `periodic_task()` instead?

**Comment by vladlep** [comment]
Puff...I found the problem, it was on my side. The server was running out of memory at some point. For the test server i assigned fewer ram and it got consumed exactly when starting that task.

Upgraded the server and now i see it runs much faster. 

Thank you for your  patience,
Vlad
