### ISSUE TITLE
Question about revoking a task

### ISSUE THREAD

**Issue by birdsarah** [coleifer/huey#98]
Hi,

I'm new to Huey and task queues in general, so apologies if this question doesn't quite make sense or is poorly worded.

Here's the workflow I want to support:

1 - schedule a task for the future (https://huey.readthedocs.org/en/latest/getting-started.html#executing-tasks-in-the-future)
2 - user decides they want to change the execution time
3 - grab the task back from the task queue (** this is where I'm stuck **)
4 - revoke the task (https://huey.readthedocs.org/en/latest/getting-started.html#canceling-a-normal-task-or-one-scheduled-in-the-future)
5 - schedule the task for a new time in the future.

I'm stuck on how to retrieve the task so that I can revoke it. Sorry if this is documented and I've missed it.

Of course, there are other ways I can structure my workflow so the retrieval isn't necessary, but I wanted to check in on this.

Many thanks for your help,

Sarah Bird

**Comment by coleifer** [comment]
You'll need to store a reference to the task's ID somewhere. When you schedule a Task, you'll get back an `AsyncData` object that can be used to retrieve the task's return value. This object also provides you the task object:

```python
data = some_task.schedule(args=('foo', 'bar'), delay=3600)
task = data.task
```

To revoke it:

```python
huey.revoke(task)
```

Then rather than re-scheduling the task, just spin up a new task instance:

```python
# Create a new task instance.
new_task = some_task.schedule(args=('foo', 'bar'), delay=3600)
```

**Comment by birdsarah** [comment]
Thanks!
