### ISSUE TITLE
Error logging to Sentry

### ISSUE THREAD

**Issue by camilonova** [coleifer/huey#99]
I'm getting some errors on a task, and I can see them at the logfile, but they are not reported to Sentry.

I'm running the django management command, using this settings:

```
HUEY = {
    'backend': 'huey.backends.sqlite_backend',
    'name': 'broname',
    'connection': {'location': DATABASES['default']['NAME']},
    'always_eager': False,
    'consumer_options': {'workers': 1},
}
```

Sentry is installed and configured according to: https://raven.readthedocs.org/en/latest/integrations/django.html

Can you tell if there is some extra configuration needed?

**Comment by deathowl** [comment]
They are caught by huey and reported back via the redis pubsub if you use huey with redis.

**Comment by deathowl** [comment]
A pluggable error handler would be handy also.

**Comment by camilonova** [comment]
I'm not using Redis, seems it only needs some extra configuration at the logger, I'm right? @coleifer

**Comment by g-cassie** [comment]
I have huey working with Sentry.  You need to add some config to the `LOGGING['loggers']` in `settings.py`

```python
LOGGING['loggers']['huey.consumer'] = {
  'handlers': ['sentry', 'console'],   # assuming you have a `sentry` handler defined in LOGGING['handlers']
  'level': 'INFO'
}
```

**Comment by coleifer** [comment]
I believe @g-cassie is correct. I'm not sure the exact logging settings you need, but it should be easy since huey logs to `huey.consumer`.
